### PR TITLE
Add shoot CP prometheus overload rules

### PR DESCRIPTION
**Pull request by jfortin-sap**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Prometheus shoot CP overload rules to alert on high risk scenarios before the point of failure is reached.

**Which issue(s) this PR fixes**:
Fixes landscape-stability-backlog/issues/65

**Special notes for your reviewer**:

**Release note**:

```other operator
Prometheus shoot CP overload rules to alert on high risk scenarios before the point of failure is reached.
```

### CODE REVIEW

**Review by vicwicker — COMMENTED** [review]
I didn't go through the queries in detail yet, but I would prefer if we remove the `OL` prefix in the alert name to make it consistent with the other alerts in this file. It is also IMHO not very clear what it means.

Also, as a side note, [this](https://github.com/gardener/gardener/pull/9941) other PR will break this because the VPA metrics are getting reworked. We should make sure the former is not in by the time this one is merged or the queries here will need a small adaptation.

**Comment by timuthy** [comment]
@jfortin-sap could you please coordinate this with @vicwicker and decide what to do with this PR, i.e. continuing with this one or closing and creating a new one based on https://github.com/gardener/gardener/pull/9941.

**Comment by timuthy** [comment]
/hold
Until https://github.com/gardener/gardener/pull/9977#pullrequestreview-2123152413 is clarified.

**Comment by vicwicker** [comment]
After discussing with @istvanballok, the monitoring team will take over this topic and provide a new PR revisiting the alert queries.

/close

**Pull request closed without merging**
