### PR TITLE
[release-v1.7] Generate mocks for the controlplane Actuator interface

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**
/area testing
/kind test
/priority normal

**What this PR does / why we need it**:
Adds generated mocks for the `Actuator` interface from `extensions/pkg/controller/controlplane` to be used in extension unit tests.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Same as #2644, but for version 1.7

**Release note**:
```improvement operator
NONE
```

### CODE REVIEW

**Comment by vpnachev** [comment]
In the `release-*` branches usually only fixes are cherry-picked, but not features.
I do not see anything critical that this PR will resolve, thus I prefer not to be merged.

/needs second-opinion

**Comment by ialidzhikov** [comment]
@vpnachev is currently revendoring the provider extension to g/g@master (here is the provider-aws PR https://github.com/gardener/gardener-extension-provider-aws/pull/151). So I guess the revendoring of provider extensions will happen much faster than potential v1.7.4 g/g release.

**Comment by rfranzke** [comment]
@vpnachev can you please open a PR for Azure as well so that we can continue with @stoyanr's PR?

**Comment by vpnachev** [comment]
Done https://github.com/gardener/gardener-extension-provider-azure/pull/141
I will open same vendor PR on the other providers.

**Comment by stoyanr** [comment]
@vpnachev @ialidzhikov Thanks. I opened this PR since I wasn't sure how long a revendor to master would take, and I realized I can't just do it as part of https://github.com/gardener/gardener-extension-provider-azure/pull/138. After https://github.com/gardener/gardener-extension-provider-azure/pull/141, I could just rebase my PR on top of it and it should work. This PR could be closed then.

**Pull request closed without merging**
