### PR TITLE
Data Compression Support for ManagedResources (Phase II)

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/area cost
/area storage
/kind enhancement

**What this PR does / why we need it**:
See #9868 which was split into #9955 and this PR for a smooth rollout.

**Special notes for your reviewer**:
/cc @ScheererJ @rfranzke

To keep the context of previous reviews, most commits from #9868 were taken over, except for the following ones:
- ecb2f71e6e185780e96357bd8d9bd58ae30e0429 for ~0df3533ed2f28be7e0f1f4b9204b72b8479a5c66~: Only changes the `registry` utility, controller was changes in #9955
- 6e535a38233a3c96ccb4f926e85c644258e219be for ~a38d3b9396f7578005e618898f446a5422af4a5c~: Removes the update code for GRMs, instead of adding it.

**Release note**:

```other operator
The data in `ManagedResource` secrets is now compressed with [Brotli](https://github.com/google/brotli) and stored under a single data key `data.yaml.br`.
```
```breaking dependency
The `Registry` in `pkg/utils/managedresources/registry.go` was changed to return all objects as a compressed data chunk.
As soon as you update the `github.com/gardener/gardener` dependency to this version, `ManagedResource` secrets will be rewritten in a [Brotli](https://github.com/google/brotli) compressed format (combined under data key `data.yaml.br`).
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
Thanks a lot for the effort of splitting the original pull request and ensuring a smooth transition.

/lgtm

**Comment by timuthy** [comment]
Many thanks for all the reviews @ScheererJ! 😅

**Pull request merged**
