### PR TITLE
exit cloud config downloader script if the reload command has failed

### LINKED ISSUE #4556: Cloud config downloader script does not catch cloud config reload error
**How to categorize this issue?**

/area quality
/kind bug
/priority 3

**What happened**:

Observed an outdated cloud config

image

The kubelet binary version was the old 1.18.16.

However, the checksum on the Node was already updated indicating that the cloud config was successfully applied.

```
Annotations:        checksum/cloud-config-data: d93f7f2ea278ac7d3e18e88176cda0f76d4e2e1b8a6b021b497c433878e28cb3
```

You can also see it in the logs for the cloud-config-downloader
- the cloud init failed
- the node was updated nonetheless

image

**What you expected to happen**:

That the checksum `checksum/cloud-config-data` on the node is not updated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area os
/kind bug

**What this PR does / why we need it**:

Please see the mentioned issue.
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/4556

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
Couldn't we just move the `kubectl annotate` command, etc. into the `if`-block? It'd be a bit more straight-forward to understand what's going on.

**Comment by danielfoehrKn** [comment]
> Couldn't we just move the kubectl annotate command, etc. into the if-block? It'd be a bit more straight-forward to understand what's going on.

Sure can do that.
Though I would still like to output the message that applying the config failed. It was not immediately obvious to me when reading the logs.

**Comment by rfranzke** [comment]
Please fix the tests.
/author-action

**Comment by rfranzke** [comment]
ping @danielfoehrKn

**Comment by danielfoehrKn** [comment]
> Couldn't we just move the kubectl annotate command, etc. into the if-block? It'd be a bit more straight-forward to understand what's going on.

I tested it again and noticed on problem with doing that.
When the cloud config is already up-to-date the annotation is not set again assuming that the annotation is already up-to-date.
However, in my local setup the annotation was outdated, but the recent cloud config applied. 

Idk how that could happen, but by always updating the annotation we make sure the annotation is up to date when the cloud config is up to date. 
If applying the cloud config fails, the annotation is not updated.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
