### PR TITLE
Update envoyproxy to v1.26.4

### PR DESCRIPTION
**Pull request by axel7born**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Update envoyproxy to v1.26.4
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ScheererJ — CHANGES_REQUESTED** [review]
@axel7born Please first upload the image via https://github.com/gardener/ci-infra/blob/master/config/images/images.yaml.

**Comment by axel7born** [comment]
> @axel7born Please first upload the image via https://github.com/gardener/ci-infra/blob/master/config/images/images.yaml.

Ah, that's the configuration I was looking for. 
I was hoping it would happen somehow automatically. :smile:

**Review by timebertt — APPROVED** [review]
/retest

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
