### PR TITLE
Persist additional disk storage metrics in Prometheus

### PR DESCRIPTION
**Pull request by bd3lage**
**How to categorize this PR?**

/area monitoring
/kind enhancement 

**What this PR does / why we need it**:
Persist additional metrics to monitor disk device performance contention/saturation
See https://github.tools.sap/kubernetes/landscape-issues/issues/56

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Persist additional metrics to monitor disk device performance contention/saturation
```

### CODE REVIEW

**Review by istvanballok — APPROVED** [review]
/lgtm
Regarding the wording: instead of "scraping" please consider using "allow list".
Reason: these metrics are already scraped by prometheus, they are just dropped right away because they are not allow listed. This PR extends the allow list so that these metrics can be persisted in the database.

**Review by timebertt — COMMENTED** [review]
/approve
/lgtm
/ok-to-test
ref https://github.com/gardener/gardener/issues/3667

**Comment by timebertt** [comment]
/hold
to not block tide's merge pool

**Pull request merged**
