### PR TITLE
Add cleanup of shoot leftover resources

### LINKED ISSUE #5173: Cleanup of shoot leftover resources
**How to categorize this issue?**

/area control-plane-migration
/kind enhancement

**What would you like to be added**:
We should introduce a cleanup mechanism for leftover resources in a Seed cluster that once contained the control plane of a Shoot cluster that are no longer needed since the Shoot cluster has been meanwhile force restored to a different seed (see #5123), or force deleted. Such resources include the shoot namespace (and all resources in it), the shoot `BackupEntry` resource, and the `Cluster` resource.

**Why is this needed**:
Without such a mechanism, leftover resources would remain in the seed cluster indefinitely and consume CPU and memory resources until manually removed.

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Adds a mechanism for cleaning up shoot leftover resources in a seed cluster that once contained the control plane
of a shoot cluster that are no longer needed and should be cleaned up, either because the shoot was force restored in a different seed, or because it was force deleted.
* Adds a new core resource `ShootLeftover` to represent such leftover resources.
* Adds a few helper functions and refactors existing code to use these functions.
* Adds seed authorizer logic for `ShootLeftover` resources.
* Adds a controller for `ShootLeftover` resources to `gardenlet`.

**Which issue(s) this PR fixes**:
Fixes #5173

**Special notes for your reviewer**:
* The following missing parts could be addressed in future PRs:
  - An admission plugin should be added to fill-in default values for missing `spec.technicalID` and `spec.uid` fields and check certain conditions when deleting a `ShootLeftover` resource, e.g. such a resource should not be deleted if the `Shoot` still exists and is scheduled on the same seed.
  - A "grace period" for actually deleting the shoot leftover resources after the `ShootLeftover` has been deleted should be introduced, perhaps as a new spec field, see https://github.com/gardener/gardener/issues/5173#issuecomment-997218476 for the motivation.

**Release note**:

```other operator
It is now possible to cleanup shoot leftover resources in a seed cluster that once contained the control plane
of a shoot cluster that are no longer needed and should be cleaned up, either because the shoot was force restored in a different seed, or because it was force deleted.
```

### CODE REVIEW

**Comment by timebertt** [comment]
Had a rough scan through the PR and have mainly one question right now:

Who will actually delete the `ShootLeftover` resource to trigger the cleanup? Tell me if I missed some part for that in the PR.

**Comment by stoyanr** [comment]
@timebertt You didn't miss anything, this is intentionally missing from this PR. It's concerned with the cleanup mechanism itself. The actual creation (and immediate deletion) of `ShootLeftover` resources for the "bad case" fallback should be added to the reconcilers introduced with #5123. For other cases, this could be done by e.g. the dashboard (a user wants to get rid of a failing half-created, half-reconciled, or half-deleted shoot), or by other controllers if they happen to detect a situation that requires a cleanup.

**Comment by stoyanr** [comment]
I tested the cleanup with fully reconciled shoots under the following conditions:

* Awake as well as hibernated shoots.
* Shoots created with `UseDNSRecords` enabled as well as disabled

I also tested with "half-migrated" shoots by artificially making `gardenlet` to panic after the following tasks in the migration flow, and then cleaning up the leftover resources:

* (beginning)
* `annotateExtensionCRs...`
* `deleteAllExtensionCRs`
* `deleteAllManagedResources...`
* `prepareKubeAPIServer...`
* `destoryEtcd`

**Comment by stoyanr** [comment]
I refactored the logging to use `logr.Logger` and added unit tests for the new controller and the seed authorizer enhancements (in new commits).

**Comment by stoyanr** [comment]
I consider this PR as ready for review now.
/invite @timebertt @plkokanov

**Comment by rfranzke** [comment]
Given that @stoyanr is on a longer vacation, it doesn't make sense to keep this PR open. @plkokanov, in case you take over, please reopen a new PR.
/close

**Pull request closed without merging**
