### PR TITLE
Don't remediate webhook if timeoutSecond is not set

### LINKED ISSUE #6726: Webhook remediator feature too aggressive
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
With https://github.com/gardener/gardener/pull/6090 Gardener has introduced a webhook remediator feature which should trigger once users are using Webhook which are too costly. Unfortunately, the current implementation will also remediate Webhook definitions which are simply lacking a "timeoutSeconds" property. 

```
func mustRemediateTimeoutSeconds(timeoutSeconds *int32) bool {
	return timeoutSeconds == nil || *timeoutSeconds > WebhookMaximumTimeoutSecondsNotProblematic
}
```
https://github.com/gardener/gardener/pull/6090/files#diff-baa858cea1e1a35989cd4be79657eefdceb915139fb4380a2fbc38bfc622ad06

Usually, such Webhook definitions would then get the default timeoutSeconds of 10s by API-Server which would be fine. Now using Webhook definition will mark shoots as "problematic" even if they are actually not problematic.

**What you expected to happen**:
No warning/interaction by Gardener components if no harming behavior is followed.

**How to reproduce it (as minimally and precisely as possible)**:
Use a Webhook without timeoutSeconds property

**Anything else we need to know?**:

**Environment**: all

- Gardener version: landscape-canary-garden 0.584.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: all
- Others:

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
If timeoutSeconds is not set in webhhok then don't remediate it cause it will default to `10s`.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6726

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Hm, the API server only defaults the `timeoutSeconds` to `10` when using the `admissionregistration.k8s.io/v1` API: https://github.com/kubernetes/kubernetes/blob/91a9ce28ac2486c50222aeeec1f76e664155d769/pkg/apis/admissionregistration/v1/defaults.go#L48-L51

However, when using older APIs it defaults to `30`: https://github.com/kubernetes/kubernetes/blob/91a9ce28ac2486c50222aeeec1f76e664155d769/pkg/apis/admissionregistration/v1beta1/defaults.go#L53-L56

Gardener still supports shoots from 1.17: https://github.com/gardener/gardener/blob/master/docs/usage/supported_k8s_versions.md#shoot-cluster-versions

Given that `v1beta1` API is still not removed in `master` branch of k/k, we would need to know with which version the user created the `*WebhookConfiguration` object. Otherwise, we cannot confidently remove this check.

**Comment by acumino** [comment]
> Hm, the API server only defaults the `timeoutSeconds` to `10` when using the `admissionregistration.k8s.io/v1` API: https://github.com/kubernetes/kubernetes/blob/91a9ce28ac2486c50222aeeec1f76e664155d769/pkg/apis/admissionregistration/v1/defaults.go#L48-L51
> 
> However, when using older APIs it defaults to `30`: https://github.com/kubernetes/kubernetes/blob/91a9ce28ac2486c50222aeeec1f76e664155d769/pkg/apis/admissionregistration/v1beta1/defaults.go#L53-L56
> 
> Gardener still supports shoots from 1.17: https://github.com/gardener/gardener/blob/master/docs/usage/supported_k8s_versions.md#shoot-cluster-versions
> 
> Given that `v1beta1` API is still not removed in `master` branch of k/k, we would need to know with which version the user created the `*WebhookConfiguration` object. Otherwise, we cannot confidently remove this check.

We only remediate  `admissionregistration.k8s.io/v1` webhook https://github.com/gardener/gardener/blob/147f7b8b5dfd2fc875ef977609e07c61f56d8a05/pkg/operation/care/webhook_remediation.go#L74-L77

**Comment by rfranzke** [comment]
I'm still a bit confused about the original issue. I tried creating a webhook with `v1beta1` version (without specifying `timeoutSeconds` explicitly). It was defaulted to `30s` as expected, so when I now get it with `v1` version then this is what I see:

```
$ kubectl get validatingwebhookconfigurations.v1.admissionregistration.k8s.io example.com -o jsonpath={.webhooks[0].timeoutSeconds}
30
```

If I had created it with `v1` then I'd have seen `10`, so far so good.

However, now #6726 talks about "Webhook definitions which are simply lacking a 'timeoutSeconds' property."
How would this work? IIUC, the kube-apiserver always defaults the `timeoutSeconds` to something, so how can this field ever not be present? @dimakow maybe you have some input here as well?

**Comment by dimakow** [comment]
@rfranzke you are right. I was not 100% sure how we got into the situation we are in with our production clusters but think I have now figured it out.

We were never specifying a timeout in our `ValidationWebhook` definitions. This was true for api versions `v1beta` as well as `v1` . Since we have in production only long-living clusters we were first using `v1beta` api version - as you pointed out we got the K8S default of 30s back then. In preparation for v1.22 we adjusted our helm charts to v1 api version. 

Internally, the K8S API-Server must have migrated the storageversion of the existing `ValidationWebhook` to `v1` with those 30s when upgrading to v1.22.

If you are activating the Webhook remediator feature now it rightfully catches our `v1` `ValidationWebhooks` and adjusts them.

Conceptually I would claim the Webhook remediator works as designed and I would suggest to close https://github.com/gardener/gardener/issues/6726 .

Fine for you @rfranzke  ?

**Comment by rfranzke** [comment]
Thanks for checking @dimakow, this makes sense. Yes, it seems we can close this PR as well as the backing issue #6726 then. cc @acumino

**Pull request closed without merging**
