### PR TITLE
Add additionalAllowedMetrics for prometheus and additionalArgs for node-exporter

### PR DESCRIPTION
**Pull request by dergeberl**
**How to categorize this PR?**
/area monitoring
/kind enhancement

**What this PR does / why we need it**:
- Add `additionalAllowedMetrics` for Shoot Prometheus in GardenletConfiguration to be able to add metrics which should be scraped by the Shoot Prometheus without changing the helm charts
- Add `additionalArgs` for node-exporter in GardenletConfiguration to be able to add collectors which should be added to the node-exporter without changing the helm charts

**Release note**:

```feature operator
Add option to append additional metrics for Shoot Prometheus in GardenletConfiguration.
```
```feature operator
Add option to append additional collectors for node-exporter in GardenletConfiguration.
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @dergeberl for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by rfranzke** [comment]
Same comment like in https://github.com/gardener/gardener/pull/5561#pullrequestreview-919837503

**Review by ialidzhikov — COMMENTED** [review]
> Same comment like in [#5561 (review)](https://github.com/gardener/gardener/pull/5561#pullrequestreview-919837503)

+1. I think in the past we recommended end users to deploy their own node-exporter if they need customizations - ref https://github.com/gardener/gardener/pull/5396#pullrequestreview-874473369 (@wyb1 correct me if I am wrong).
I agree that it is getting too much to allow configuring similar things in the gardenlet component config. I could image that this easily explodes if we start allowing configurations for each and every chart gardenlet is deploying.

**Comment by dergeberl** [comment]
I will close this PR as discussed in #5650

**Pull request closed without merging**
