### PR TITLE
Reduce the number of parallel running e2e tests

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
We run lots of e2e tests in parallel. Thus, many kubelets, pods etc. using use the same cgroup filesystem which could lead to very high loads (~750). 
This could cause inaccessible nodes in our prow cluster and flaking tests.

This PR reduces the number of parallel running e2e tests to reduce the load on the prow nodes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I'm not sure about the best value for the number of parallel tests yet, so I'm planning to test it with this PR.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Comment by oliver-goetz** [comment]
/retitle Reduce the number of parallel running e2e tests

As discussed, the effect of this setting would be visible only when we apply it for all the tests. Thus, let us test this setting for two weeks and see how it affects the stability of the prow nodes.

**Pull request merged**
