### PR TITLE
Fix Dynamic Host Regex

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**How to categorize this PR?**

/area logging
/kind bug
/priority normal

**What this PR does / why we need it**:
Current regex matches logs for `extension-extension-shoot-cert-service-x9hw6` and `extension-extension-shoot-dns-service-ztx52` but it cannot create client for them and skips their logs.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@vlvasilev

**Release note**:

```improvement operator
An issue has been fixed which caused the logging stack to skip logs for certain extension pods.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

Shall this be cherry-picked to `release-v1.12` hotfix branch as well? cc @timuthy

**Comment by Kristian-ZH** [comment]
> /lgtm
> 
> Shall this be cherry-picked to `release-v1.12` hotfix branch as well? cc @timuthy

Yes, this issue also exists there

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Pull request merged**
