### PR TITLE
Make machine image optional

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Currently trying to apply a Shoot without a machine image:
```
$ k apply -f shoot.yaml
error: error validating "shoot.yaml": error validating data: ValidationError(Shoot.spec.provider.workers[0].machine.image): missing required field "version" in com.github.gardener.gardener.pkg.apis.core.v1beta1.ShootMachineImage; if you choose to ignore these errors, turn validation off with --validate=false
```

It looks like kubectl is using the openapi schema to validate the resources.

**Which issue(s) this PR fixes**:
Ref #1960

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by vpnachev — DISMISSED** [review]
/lgtm

nice catch

**Comment by rfranzke** [comment]
Should the type be changed to pointer? Should we add omitempty tags?

**Comment by ialidzhikov** [comment]
> Should the type be changed to pointer? Should we add omitempty tags?

It is now changed to `*string`, `omitempty` also added.

**Comment by ialidzhikov** [comment]
@rfranzke , @mvladev , I changed the Version field in the external type to `*string` and the respective field in the internal type is `string`. 
If you have any objections/comments from api-conventions side, please share.
My goal is to have the Version field optional (and to be omitted, if needed, on POST) and to be defaulted in an admission plugin.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]

**Comment by rfranzke** [comment]
FYI @danielfoehrKn

**Review by danielfoehrKn — APPROVED** [review]

**Pull request merged**
