### PR TITLE
Classify quota issue as configuration problem

### PR DESCRIPTION
**Pull request by BeckerMax**
Error message: 
`Error while creating machine <>: machine codes error: code = [Internal] message = [error waiting for server [ID=""] to reach target status: server [ID=""] reached unexpected status "ERROR", fault: {Code:500 Created:<> Details: Message:Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance <>. Last exception: Maximum number of ports exceeded}]`

Classify quota issue as configuration problem

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by BeckerMax** [comment]
cc @kon-angelo can you confirm that it is correct to label the above as a user configuration error?

**Comment by rfranzke** [comment]
Shouldn't it rather be in the `quotaExceededRegexp` regexp?

**Comment by kon-angelo** [comment]
@BeckerMax I agree with @rfranzke 's suggestion and would go for the quotaExceeded option.

**Comment by BeckerMax** [comment]
yes, thanks. PTAL.
/merge squash

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
