### PR TITLE
Fix `ReconcileContainerdRegistries` race condition

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:
This PR fixes a race condition while waiting for the containerd registries to be configured, [ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10093/pull-gardener-integration/1815720313019699200).

**Special notes for your reviewer**:
The error happens if `nil` is sent to the `errChan` and consequently, the `ReconcileContainerdRegistries` function returns `nil` as the waiting function.

The issue was introduced with https://github.com/gardener/gardener/pull/10050, no backports required.

Thanks a lot @shafeeqes for spotting and analyzing this issue 🙏.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm
/retest

**Comment by shafeeqes** [comment]
In this approach, if the error is nil, `cleanupUnusedContainerdRegistries` will not get called. Is this fine?

**Comment by timuthy** [comment]
> In this approach, if the error is nil, `cleanupUnusedContainerdRegistries` will not get called. Is this fine?

Nice catch, thank you 😊

**Comment by shafeeqes** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
