### PR TITLE
Remove pointer to LabelSelector in SeedSelector

### LINKED ISSUE #4295: Observed a panic: reflect: Field of non-struct type *v1.LabelSelector
**How to categorize this issue?**

/kind bug
/priority 3

**What happened**:

```
E0701 09:50:25.280474       1 runtime.go:76] Observed a panic: reflect: Field of non-struct type *v1.LabelSelector
goroutine 1843 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x21ab1a0, 0xc00a2ed450)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x21ab1a0, 0xc00a2ed450)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.(*rtype).Field(0x24ec920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:920 +0x177
k8s.io/apimachinery/third_party/forked/golang/json.LookupPatchMetadataForStruct(0x291f368, 0x2389ba0, 0xc009cc9cb0, 0xb, 0x8, 0x10, 0x7f3342477d28, 0x10, 0xc00a2ed420, 0x2259239, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go:60 +0x2ca
k8s.io/apimachinery/pkg/util/strategicpatch.PatchMetaFromStruct.LookupPatchMetadataForStruct(0x291f368, 0x24bfe20, 0xc009cc9cb0, 0xb, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go:74 +0x86
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff(0xc009cc9cb0, 0xb, 0xc0061159b0, 0xc008585dd0, 0xc0025d63c0, 0x28ed870, 0xc00a2ed430, 0xc000000001, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:263 +0x82
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc006115980, 0xc008585da0, 0x28ed870, 0xc00a2ed430, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:212 +0x50d
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff(0xc009cc9ca0, 0xc, 0xc006115980, 0xc008585da0, 0xc0025d60f0, 0x28ed870, 0xc00a2ed1a0, 0xc000000001, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:286 +0x2b2
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc0061154a0, 0xc0085856e0, 0x28ed870, 0xc00a2ed1a0, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:212 +0x50d
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff(0xc009cc9c8c, 0x4, 0xc0061154a0, 0xc0085856e0, 0xc0025d6090, 0x28ed870, 0xc0099b3e40, 0x1, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:286 +0x2b2
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc00adfe210, 0xc006115c20, 0x28ed870, 0xc0099b3e40, 0xc000000001, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:212 +0x50d
k8s.io/apimachinery/pkg/util/strategicpatch.CreateTwoWayMergeMapPatchUsingLookupPatchMeta(0xc00adfe210, 0xc006115c20, 0x28ed870, 0xc0099b3e40, 0x0, 0x0, 0x0, 0xc0099b3e40, 0xc008de5408, 0xc0099b3e40)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:143 +0x5b
k8s.io/apimachinery/pkg/util/strategicpatch.CreateTwoWayMergePatchUsingLookupPatchMeta(0xc009780000, 0x2289, 0x2500, 0xc009782500, 0x227c, 0x2500, 0x28ed870, 0xc0099b3e40, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:119 +0x10f
k8s.io/apimachinery/pkg/util/strategicpatch.CreateTwoWayMergePatch(0xc009780000, 0x2289, 0x2500, 0xc009782500, 0x227c, 0x2500, 0x258a340, 0xc006ca4e00, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:100 +0x15b
sigs.k8s.io/controller-runtime/pkg/client.createStrategicMergePatch(0xc009780000, 0x2289, 0x2500, 0xc009782500, 0x227c, 0x2500, 0x258a340, 0xc006ca4e00, 0x0, 0xc008de5530, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go:140 +0xac
sigs.k8s.io/controller-runtime/pkg/client.(*mergeFromPatch).Data(0xc00a10fe00, 0x2921e18, 0xc006ca4e00, 0xc0087fe048, 0x0, 0x0, 0xffffffffffffffff, 0x0)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go:127 +0x170
sigs.k8s.io/controller-runtime/pkg/client.(*typedClient).PatchStatus(0xc00045c0e0, 0x28f3758, 0xc000136000, 0x2921e18, 0xc006ca4e00, 0x28ba670, 0xc00a10fe00, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go:190 +0xeb
sigs.k8s.io/controller-runtime/pkg/client.(*statusWriter).Patch(0xc0002fc408, 0x28f3758, 0xc000136000, 0x2921e18, 0xc006ca4e00, 0x28ba670, 0xc00a10fe00, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go:326 +0x331
github.com/gardener/gardener/pkg/operation.(*Operation).ReportShootProgress.func1(0xc006ca4e00, 0xc02f81d850a7d30f, 0x4545913f7, 0x3a43b60, 0xc009797f20, 0x25, 0xc000000000, 0xc0053f38c0, 0x28f3758, 0xc000136000, ...)
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:440 +0x21d
github.com/gardener/gardener/pkg/operation.(*Operation).ReportShootProgress(0xc0053f38c0, 0x28f3758, 0xc000136000, 0xc008c1b980)
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:441 +0x137
github.com/gardener/gardener/pkg/utils/flow.(*progressReporterDelaying).Report(0xc009c38000, 0x28f3758, 0xc000136000, 0xc008c1b980)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_delaying.go:90 +0xcf
github.com/gardener/gardener/pkg/utils/flow.(*execution).reportProgress(0xc00c20bea0, 0x28f3758, 0xc000136000)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:267 +0x7a
github.com/gardener/gardener/pkg/utils/flow.(*execution).run(0xc00c20bea0, 0x28f3758, 0xc000136000, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:282 +0x11b
github.com/gardener/gardener/pkg/utils/flow.(*Flow).Run(0xc00aadb590, 0x291e010, 0xc008aeefc0, 0x28ddf10, 0xc009c38000, 0xc009b39dc0, 0xc00bd2cd50, 0x0, 0x0, 0xc00bd57760, ...)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:120 +0xb9
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*Controller).runReconcileShootFlow(0xc000caa6c0, 0x28f3720, 0xc000cf9600, 0xc0053f38c0, 0xc0078e36c0)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go:529 +0x82a5
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*Controller).reconcileShoot(0xc000caa6c0, 0x28f3720, 0xc000cf9600, 0xc008aeefc0, 0x291c5b8, 0xc000b73200, 0xc006ca4e00, 0xc0078e36c0, 0xc004c22c40, 0xc0049e5d40, ...)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_control.go:506 +0xbfd
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*Controller).reconcileShootRequest(0xc000caa6c0, 0x28f3720, 0xc000cf9600, 0xc000f0dec0, 0xe, 0xc000f0decf, 0x7, 0x2, 0x2, 0xc000fb7b78, ...)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_control.go:243 +0xcb2
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc0017833e0, 0x28f3720, 0xc000cf9600, 0xc000f0dec0, 0xe, 0xc000f0decf, 0x7, 0x0, 0xc001b55468, 0x44ec8c, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:102 +0x6f
github.com/gardener/gardener/pkg/controllerutils.worker.func1(0x290f180, 0xc000277140, 0x28a0c80, 0xc0017833e0, 0x28f3720, 0xc000cf9600, 0x25b8fa6, 0x5, 0x0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:114 +0x142
github.com/gardener/gardener/pkg/controllerutils.worker(0x28f3720, 0xc000cf9600, 0x290f180, 0xc000277140, 0x25b8fa6, 0x5, 0x28a0c80, 0xc0017833e0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:131 +0x7a
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2.1(0x28f3720, 0xc000cf9600)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:72 +0x6b
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001b556e8)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc008de7ee8, 0x289e5a0, 0xc00157d3b0, 0xc000cf9601, 0xc000cbe3c0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001b556e8, 0x3b9aca00, 0x0, 0xc001c18701, 0xc000cbe3c0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x28f3720, 0xc000cf9600, 0xc001b55748, 0x3b9aca00, 0x0, 0xc000bfa901)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2(0x28f3720, 0xc000cf9600, 0x290f180, 0xc000277140, 0x25b8fa6, 0x5, 0x28a0c80, 0xc0017833e0, 0xc00084da40, 0xc0012085f0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:71 +0xd2
created by github.com/gardener/gardener/pkg/controllerutils.CreateWorker
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:70 +0x276
panic: reflect: Field of non-struct type *v1.LabelSelector [recovered]
	panic: reflect: Field of non-struct type *v1.LabelSelector

goroutine 1843 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x21ab1a0, 0xc00a2ed450)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.(*rtype).Field(0x24ec920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:920 +0x177
k8s.io/apimachinery/third_party/forked/golang/json.LookupPatchMetadataForStruct(0x291f368, 0x2389ba0, 0xc009cc9cb0, 0xb, 0x8, 0x10, 0x7f3342477d28, 0x10, 0xc00a2ed420, 0x2259239, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go:60 +0x2ca
k8s.io/apimachinery/pkg/util/strategicpatch.PatchMetaFromStruct.LookupPatchMetadataForStruct(0x291f368, 0x24bfe20, 0xc009cc9cb0, 0xb, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go:74 +0x86
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff(0xc009cc9cb0, 0xb, 0xc0061159b0, 0xc008585dd0, 0xc0025d63c0, 0x28ed870, 0xc00a2ed430, 0xc000000001, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:263 +0x82
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc006115980, 0xc008585da0, 0x28ed870, 0xc00a2ed430, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:212 +0x50d
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff(0xc009cc9ca0, 0xc, 0xc006115980, 0xc008585da0, 0xc0025d60f0, 0x28ed870, 0xc00a2ed1a0, 0xc000000001, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:286 +0x2b2
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc0061154a0, 0xc0085856e0, 0x28ed870, 0xc00a2ed1a0, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:212 +0x50d
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff(0xc009cc9c8c, 0x4, 0xc0061154a0, 0xc0085856e0, 0xc0025d6090, 0x28ed870, 0xc0099b3e40, 0x1, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:286 +0x2b2
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc00adfe210, 0xc006115c20, 0x28ed870, 0xc0099b3e40, 0xc000000001, 0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:212 +0x50d
k8s.io/apimachinery/pkg/util/strategicpatch.CreateTwoWayMergeMapPatchUsingLookupPatchMeta(0xc00adfe210, 0xc006115c20, 0x28ed870, 0xc0099b3e40, 0x0, 0x0, 0x0, 0xc0099b3e40, 0xc008de5408, 0xc0099b3e40)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:143 +0x5b
k8s.io/apimachinery/pkg/util/strategicpatch.CreateTwoWayMergePatchUsingLookupPatchMeta(0xc009780000, 0x2289, 0x2500, 0xc009782500, 0x227c, 0x2500, 0x28ed870, 0xc0099b3e40, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:119 +0x10f
k8s.io/apimachinery/pkg/util/strategicpatch.CreateTwoWayMergePatch(0xc009780000, 0x2289, 0x2500, 0xc009782500, 0x227c, 0x2500, 0x258a340, 0xc006ca4e00, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:100 +0x15b
sigs.k8s.io/controller-runtime/pkg/client.createStrategicMergePatch(0xc009780000, 0x2289, 0x2500, 0xc009782500, 0x227c, 0x2500, 0x258a340, 0xc006ca4e00, 0x0, 0xc008de5530, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go:140 +0xac
sigs.k8s.io/controller-runtime/pkg/client.(*mergeFromPatch).Data(0xc00a10fe00, 0x2921e18, 0xc006ca4e00, 0xc0087fe048, 0x0, 0x0, 0xffffffffffffffff, 0x0)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go:127 +0x170
sigs.k8s.io/controller-runtime/pkg/client.(*typedClient).PatchStatus(0xc00045c0e0, 0x28f3758, 0xc000136000, 0x2921e18, 0xc006ca4e00, 0x28ba670, 0xc00a10fe00, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go:190 +0xeb
sigs.k8s.io/controller-runtime/pkg/client.(*statusWriter).Patch(0xc0002fc408, 0x28f3758, 0xc000136000, 0x2921e18, 0xc006ca4e00, 0x28ba670, 0xc00a10fe00, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go:326 +0x331
github.com/gardener/gardener/pkg/operation.(*Operation).ReportShootProgress.func1(0xc006ca4e00, 0xc02f81d850a7d30f, 0x4545913f7, 0x3a43b60, 0xc009797f20, 0x25, 0xc000000000, 0xc0053f38c0, 0x28f3758, 0xc000136000, ...)
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:440 +0x21d
github.com/gardener/gardener/pkg/operation.(*Operation).ReportShootProgress(0xc0053f38c0, 0x28f3758, 0xc000136000, 0xc008c1b980)
	/go/src/github.com/gardener/gardener/pkg/operation/operation.go:441 +0x137
github.com/gardener/gardener/pkg/utils/flow.(*progressReporterDelaying).Report(0xc009c38000, 0x28f3758, 0xc000136000, 0xc008c1b980)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_delaying.go:90 +0xcf
github.com/gardener/gardener/pkg/utils/flow.(*execution).reportProgress(0xc00c20bea0, 0x28f3758, 0xc000136000)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:267 +0x7a
github.com/gardener/gardener/pkg/utils/flow.(*execution).run(0xc00c20bea0, 0x28f3758, 0xc000136000, 0x0, 0x0)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:282 +0x11b
github.com/gardener/gardener/pkg/utils/flow.(*Flow).Run(0xc00aadb590, 0x291e010, 0xc008aeefc0, 0x28ddf10, 0xc009c38000, 0xc009b39dc0, 0xc00bd2cd50, 0x0, 0x0, 0xc00bd57760, ...)
	/go/src/github.com/gardener/gardener/pkg/utils/flow/flow.go:120 +0xb9
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*Controller).runReconcileShootFlow(0xc000caa6c0, 0x28f3720, 0xc000cf9600, 0xc0053f38c0, 0xc0078e36c0)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go:529 +0x82a5
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*Controller).reconcileShoot(0xc000caa6c0, 0x28f3720, 0xc000cf9600, 0xc008aeefc0, 0x291c5b8, 0xc000b73200, 0xc006ca4e00, 0xc0078e36c0, 0xc004c22c40, 0xc0049e5d40, ...)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_control.go:506 +0xbfd
github.com/gardener/gardener/pkg/gardenlet/controller/shoot.(*Controller).reconcileShootRequest(0xc000caa6c0, 0x28f3720, 0xc000cf9600, 0xc000f0dec0, 0xe, 0xc000f0decf, 0x7, 0x2, 0x2, 0xc000fb7b78, ...)
	/go/src/github.com/gardener/gardener/pkg/gardenlet/controller/shoot/shoot_control.go:243 +0xcb2
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc0017833e0, 0x28f3720, 0xc000cf9600, 0xc000f0dec0, 0xe, 0xc000f0decf, 0x7, 0x0, 0xc001b55468, 0x44ec8c, ...)
	/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:102 +0x6f
github.com/gardener/gardener/pkg/controllerutils.worker.func1(0x290f180, 0xc000277140, 0x28a0c80, 0xc0017833e0, 0x28f3720, 0xc000cf9600, 0x25b8fa6, 0x5, 0x0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:114 +0x142
github.com/gardener/gardener/pkg/controllerutils.worker(0x28f3720, 0xc000cf9600, 0x290f180, 0xc000277140, 0x25b8fa6, 0x5, 0x28a0c80, 0xc0017833e0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:131 +0x7a
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2.1(0x28f3720, 0xc000cf9600)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:72 +0x6b
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001b556e8)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc008de7ee8, 0x289e5a0, 0xc00157d3b0, 0xc000cf9601, 0xc000cbe3c0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001b556e8, 0x3b9aca00, 0x0, 0xc001c18701, 0xc000cbe3c0)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x28f3720, 0xc000cf9600, 0xc001b55748, 0x3b9aca00, 0x0, 0xc000bfa901)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
github.com/gardener/gardener/pkg/controllerutils.CreateWorker.func2(0x28f3720, 0xc000cf9600, 0x290f180, 0xc000277140, 0x25b8fa6, 0x5, 0x28a0c80, 0xc0017833e0, 0xc00084da40, 0xc0012085f0)
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:71 +0xd2
created by github.com/gardener/gardener/pkg/controllerutils.CreateWorker
	/go/src/github.com/gardener/gardener/pkg/controllerutils/worker.go:70 +0x276
```

**What you expected to happen**:

No panic

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot with .spec.seedSelector

```yaml
spec:
  seedSelector:
    matchLabels:
      foo: bar
```

2. `make start-gardenlet` and observe the panic above

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.26.0-dev-7c267382926289513fc11d62c2247b986ef68c92
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area dev-productivity
/kind bug

**What this PR does / why we need it**:

This switches from `*metav1.LabelSelector` to `metav1.LabelSelector` in the `SeedSelector` type in our APIs.
The embedded pointer struct has already caused us a lot of headaches, as most code-generators and libraries don't support it.

From an API-perspective, having a pointer vs. not having a pointer in this embedded field doesn't make a difference (JSON and YAML behave exactly the same) as long as the `json` tag still contains `inline,omitempty`.
So this should be backwards- and forwards-compatible.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/4295

**Special notes for your reviewer**:

**Release note**:

```other developer
Switch from `*metav1.LabelSelector` to `metav1.LabelSelector` in the `gardenercore.SeedSelector` type in our APIs. This doesn't impose a breaking change for users of the API, however users of the golang types, will have to adapt accordingly.
```

### CODE REVIEW

**Comment by timebertt** [comment]
@mandelsoft mentioned, that the reason for using a pointer in https://github.com/gardener/gardener/pull/2169 was that there is a semantical difference between an empty and nil `LabelSelector` which needs to be distinguished in our case.
So until we have clarified this, the RP is in draft.

Side-note: while removing the pointer and adapting the scheduler and validation code, I did not encounter any failing unit test. If there is an important semantical difference that needs to be considered here, I expect that there is a unit test verifying that behavior to prevent others (like me) breaking this behavior in the future.
So either, there is no semantical difference (as I currently expect) or this is simply no unit test and we were sloppy on this one.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by timebertt** [comment]
> @mandelsoft mentioned, that the reason for using a pointer in #2169 was that there is a semantical difference between an empty and nil `LabelSelector` which needs to be distinguished in our case.
> So until we have clarified this, the RP is in draft.

I clarified this with @rfranzke and @ialidzhikov and we came to the following conclusion:
We don't have to differentiate between unset and empty `LabelSelector` in our `SeedSelector` use case, because the `LabelSelector` and `ProviderTypes` are basically additive scheduling predicates (they're ANDed). 

The scheduler first filters available seeds by labels (or selects all when no label selector is given) and then selects seed of matching provider types (or selects all when no provider types is given):
https://github.com/gardener/gardener/blob/3b49e8ae1e7d52d40b3d8266f695dd2fea79e413/pkg/scheduler/controller/shoot/scheduler_control.go#L172-L183

There will probably never be the need for a match-nothing label selector in the seed selector, because it doesn't make sense to select no seeds (where would you schedule shoots then?).
Even if there will be a use case for distinguishing, this should definitely be done in a different API type and not use embedded pointer fields.

/ready

**Review by ialidzhikov — APPROVED** [review]
/lgtm

You could also add a release note that describes the change in the golang API.

**Comment by timebertt** [comment]
Good point, done.

**Pull request merged**
