### PR TITLE
Fix `UnauthenticatedHTTP2DOSMitigation` feature gate

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area security
/kind bug

**What this PR does / why we need it**:
🙈 

**Release note**:

```bugfix operator
An issue has been fixed that prevented setting the `UnauthenticatedHTTP2DOSMitigation` feature gate.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
🤐

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
