### PR TITLE
Deploy vpa-exporter for shooted seeds

### PR DESCRIPTION
**Pull request by wyb1**
**How to categorize this PR?**

/area monitoring
/kind bug
/priority normal

**What this PR does / why we need it**:
The vpa exporter should be deployed in the garden ns of seeds.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @amshuman-kr @rfranzke 
**Release note**:

```noteworthy operator
The `vpa-exporter` is now deployed again into the `garden` namespace of seed clusters (also for shooted seeds).
```

### CODE REVIEW

**Comment by rfranzke** [comment]
This will deploy the vpa-exporter into the shoot namespace in the seed, not in the `garden` namespace.
Did you test the change?

**Comment by wyb1** [comment]
vpa-exporter got deployed into the `garden` ns of my seed. 

Edit: Probably because my seed is not shoot...

**Comment by wyb1** [comment]
@rfranzke I've updated the PR PTAL

**Review by rfranzke — APPROVED** [review]
Thanks, it
/lgtm
now. We should definitely work on refactoring the whole VPA deployment, it gets a lot more scattered now and it's anyways already hard to maintain (just a note to @gardener/gardener-maintainers, it's not particularly related to this PR).

I guess the PR is
/ready
now, but I want to have a
/needs second-opinion
before merging it.
/invite @timebertt @ggaurav10 @amshuman-kr

**Review by amshuman-kr — APPROVED** [review]

**Pull request merged**
