### PR TITLE
Make applier order aware

### PR DESCRIPTION
**Pull request by timuthy**
**What this PR does / why we need it**:
This PR makes the `Applier` order manifests before they get applied on the k8s cluster. Ordering mainly happens by the `Kind` of each resource which allows the applier to follow a logical sequence, e.g. a `CRD` is applied before referencing `CRs`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Gardener now applies Kubernetes resources in a predefined order (e.g., `Namespace`s before any other resource inside that namespace).
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Nice, but why don't we convert the unstructured manifest data into Helm's [`Manifest`](https://github.com/helm/helm/blob/release-2.13/pkg/tiller/hooks.go#L57:6) type and simply call their [`SortByKind`](https://github.com/helm/helm/blob/release-2.13/pkg/tiller/kind_sorter.go#L153) function (instead of duplicating their code here)?

**Comment by timuthy** [comment]
@rfranzke I thought about that option, too. The downside of this is that we cannot add our own `Kinds` as well as have another dependency to `Helm`  which we tried to avoid in the past. WDYT?

**Comment by rfranzke** [comment]
OK, understood. The dependency we have anyways because we use it's chart rendering functionality. For the kinds argument: I don't see anything from us right now. Is it needed at all? What could be a use-case for this? If we really need it, shouldn't we talk to the Helm maintainers and file a PR that allows to pass a desired kind list?

**Comment by timuthy** [comment]
Fair enough, it's rather a theoretical issue at the moment.
@rfranzke I changed it in a separate commit. Once you agree, I'll discard the previous one.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
