### PR TITLE
Add plutono dashboard for image pull duration

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
The motivation for this PR is the following: wrt to the registry-cache we received questions of type "does it improve/regress image pull times?". However, currently there are no kubelet metrics or plutono dashboard for the image pull durations.
This PR:
- allowlists the new kubelet image pull duration metrics in K8s 1.30 (ref https://github.com/kubernetes/kubernetes/pull/121719) to be scraped by prometheus
- adds a new panel for container images that currently only shows 2 panels about image pull durations

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener-extension-registry-cache/issues/3

**Special notes for your reviewer**:
A screenshot from the dashboard:
Screenshot 2024-03-18 at 17 41 53

The panels won't show any data for K8s clusters < 1.30.

**Release note**:

```other operator
There is a new plutono dashboard named `Container Images` that currently contains 2 panels for image pull durations.
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
Thanks for providing this very relevant improvement.

/lgtm

**Review by istvanballok — COMMENTED** [review]
/lgtm

**Review by istvanballok — APPROVED** [review]
/lgtm

**Review by ScheererJ — APPROVED** [review]

**Pull request merged**
