### PR TITLE
Increased default reconciliation timeout to 3 minutes.

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:
Increased default reconciliation timeout to 3 minutes.

The default reconciliation timeout is used as a safety net to prevent reconciliation operations to hang forever. Therefore, it should be long enough that all usual operations succeed, but short enough so that the waiting time is not endless in case of issues/hanging operations.
With larger amount of resources being applied for example as managed resources the default reconciliation timeout needs to be increased. An example for such a resource is the istio ingress gateway in case the seed uses multiple availability zones as the managed resource will then include all entities for all availability zones. Another contributing factor may be if the control plane of a seed is latency-wise fairly distant to its data plane causing operations such as applying resources to be rather slow.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
The reconciliation time limit for the controller resource reconciliation, e.g. for `ManagedResource`, has been increased from `1m` to `3m`.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
I think the concrete timeout for `ManagedResource` reconciliation is overwritten, e.g. in https://github.com/gardener/gardener/blob/150da5fdc804520f6b567948c6640570da911928/pkg/resourcemanager/controller/managedresource/reconciler.go#L161-L162

**Comment by ScheererJ** [comment]
> I think the concrete timeout for `ManagedResource` reconciliation is overwritten, e.g. in
> 
> https://github.com/gardener/gardener/blob/150da5fdc804520f6b567948c6640570da911928/pkg/resourcemanager/controller/managedresource/reconciler.go#L161-L162

You are absolutely right that it is possible to reduce the timeout to a lower value, but it is not possible to overwrite it to a higher value as it is being limited by the default timeout:

https://github.com/gardener/gardener/blob/150da5fdc804520f6b567948c6640570da911928/pkg/controllerutils/miscellaneous.go#L134-L141

This is the reason why it may be required to change the timeout at all.

**Comment by rfranzke** [comment]
OK, and this works because we configure the `ManagedResource` controller's sync period with `1h` for runtime clusters. Got it, thank you.

/lgtm
/approve

**Comment by timuthy** [comment]
Can you adjust the release notes? I think it's not only the reconciliation timeout for `managedresource`s that is affected by this change.

**Comment by ScheererJ** [comment]
> Can you adjust the release notes? I think it's not only the reconciliation timeout for `managedresource`s that is affected by this change.

Indeed, this timeout is used all over the place. I adapted the release note accordingly.

@timuthy Does it work for you?

**Pull request merged**
