### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.4.0->v0.4.1]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**How to categorize this PR?**

/area TODO
/kind TODO
/priority normal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by amshuman-kr — APPROVED** [review]
Thanks for the hotfix @shreyas-s-rao. LGTM

Local dev-setup test worked with this PR branch.
```sh
# local dev-setup garden cluster
$ k -n garden-dev get shoots
NAME        CLOUDPROFILE   VERSION   SEED   DOMAIN                                          HIBERNATION   OPERATION   PROGRESS   APISERVER   CONTROL       NODES   SYSTEM        AGE
akr-aws-1   aws            1.19.1    aws    akr-aws-1.dev.shoot.dev.k8s-hana.ondemand.com   Awake         Succeeded   100        True        Progressing   True    Progressing   167m

# shoot control-plane in the seed
$ g k -- -n shoot--dev--akr-aws-1 get pods
NAME                                          READY   STATUS    RESTARTS   AGE
aws-lb-readvertiser-564dc58fc5-mz9tq          1/1     Running   0          8m40s
cert-controller-manager-fdd5c4d54-qfvjp       1/1     Running   0          8m25s
cloud-controller-manager-c77c6dfc-tzn4c       1/1     Running   0          9m13s
cluster-autoscaler-585954cdf9-x9rp8           1/1     Running   0          116s
csi-driver-controller-f899bf4c7-wtmcc         6/6     Running   32         162m
csi-snapshot-controller-77b65656c-thpxc       1/1     Running   0          162m
etcd-events-0                                 2/2     Running   0          10m
etcd-main-0                                   2/2     Running   0          10m
gardener-resource-manager-764c9bdd7f-j2qlq    1/1     Running   0          8m26s
grafana-operators-67d46786fb-jh5p5            1/1     Running   0          2m3s
grafana-users-579cb4547d-bwk2c                1/1     Running   0          119s
kube-apiserver-7dc8c8595d-7mppf               2/2     Running   0          9m41s
kube-controller-manager-7657bcc8b8-crdj5      1/1     Running   0          8m41s
kube-scheduler-545c7c945c-v2xln               1/1     Running   0          7m43s
kube-state-metrics-5d657d794b-6qkvn           1/1     Running   0          2m9s
machine-controller-manager-5976f69fbc-h4xwp   1/1     Running   0          7m21s
prometheus-0                                  3/3     Running   0          2m11s
shoot-dns-service-7fc4948fd7-cs4l9            1/1     Running   0          8m25s
```

I had to delete the etcd pods which were struck in unhealthy state due to the previous issue with etcd-druid `v0.4.0`. Not sure if this would have automatically reconciled by statefulset controller.
```sh
$ g k -- -n shoot--dev--akr-aws-1 get pod | grep etcd
etcd-events-0                             1/2     Running            0          124m
etcd-main-0                               1/2     Running            0          151m

$ g k -- -n shoot--dev--akr-aws-1 delete pod etcd-main-0 etcd-events-0
pod "etcd-main-0" deleted
pod "etcd-events-0" deleted

$ g k -- -n shoot--dev--akr-aws-1 get pod | grep etcd
etcd-events-0                             2/2     Running            0          48s
etcd-main-0                               2/2     Running            0          51s
```

**Review by shreyas-s-rao — APPROVED** [review]

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
