### PR TITLE
Adjust the regex of compaction job in alerting rule and dashboard.

### LINKED ISSUE #8576: Adjust the alert definition and compaction job dashboard based on new format of name of compaction job
**How to categorize this issue?**

/area monitoring
/kind enhancement

**What would you like to be added**:

Once this [PR](https://github.com/gardener/etcd-druid/pull/672)  is merged and released with a new version of etcd druid, we should adjust the alert definition here:

https://github.com/gardener/gardener/pull/8361/files#diff-e5831943a4ab78c34cc948a519ab72334ec2d651c7621b2cd4f897488a4d9c4dR38

and in the compaction dashboard here:
https://github.com/gardener/gardener/blob/f0d1bf5d2b52e9de3e39bdf6d3c7c6c5364c249a/pkg/component/plutono/dashboards/shoot/owners/etcd-compaction-job-dashboard.json#L467

We could remove the regex prefix (.+) . Then the new regex will become pod!~"etcd*compactor".

**Why is this needed**:
This is needed because we are changing the name of compaction job in the PR https://github.com/gardener/etcd-druid/pull/672

### PR DESCRIPTION
**Pull request by abdasgupta**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
This PR adjust the regex in alerting rule and compaction dashboard based on the modified name of compaction job.

**Which issue(s) this PR fixes**:
Fixes #8576 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by abdasgupta** [comment]
cc @rickardsjp @istvanballok

**Review by ScheererJ — COMMENTED** [review]
/approve

**Pull request merged**
