### PR TITLE
Use vanity domain after VDF

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area open-source
/kind task
/priority normal

**What this PR does / why we need it**:
As the [vanity domain flip](https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md) is now completed, we can again use the vanity domain.

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
