### PR TITLE
Gardener API server now uses dedicated folder for the audit logs

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area audit-logging
/kind cleanup enhancement 

**What this PR does / why we need it**:
Gardener API server now uses dedicated folder for the audit logs.
This also reverts #6204 

The K8s dependencies are updated to v0.24.4 to adopt the following upstream fix - https://github.com/kubernetes/kubernetes/pull/110813.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The default value for the `--audit-log-path` flag of Gardener API Server was changed from `/tmp/audit.log` to `/tmp/audit/audit.log`.
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
Can you properly explain in the PR description why update of the k8s modules to v0.24.4 is required (that you have a fix upstream and you adopt it in this way, etc)?

**Comment by vpnachev** [comment]
Done.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
