### PR TITLE
Cleanup leader election clients/recorders

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area quality
/kind cleanup
/priority normal
/size xs

**What this PR does / why we need it**:
This PR cleans up two thing related to leader election in our components:
- gcm uses a separate client for leader election again according to best practice
- gardenlet reports leader election events to the Seed cluster instead of the garden cluster (which is confusing/incorrect IMO)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
The gardenlet now reports leader election events to the Seed cluster instead of the Garden cluster.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
What's the motivation for 

> g-scheduler doesn't create an additional client for leader election

**Comment by timebertt** [comment]
> What's the motivation for
> 
> > g-scheduler doesn't create an additional client for leader election

No specific motivation. I just saw, that we also use the same client in gcm, so I changed it along the way.

**Comment by rfranzke** [comment]
Interesting, I missed that during the client map refactoring. Earlier, we already had dedicated clients (that's why it's also the same for the kube-scheduler), see https://github.com/gardener/gardener/blob/v1.6.6/cmd/gardener-controller-manager/app/gardener_controller_manager.go#L256-L259

AFAIK that's a best practice in Kubernetes controllers to prevent the leader election contributing to the client-go's client-side rate limiting settings.

**Comment by timebertt** [comment]
> AFAIK that's a best practice in Kubernetes controllers to prevent the leader election contributing to the client-go's client-side rate limiting settings.

Makes sense to me. Then I would suggest to revert this change and have separate clients in all components

**Comment by rfranzke** [comment]
👍 Thank you

**Comment by timebertt** [comment]
> Then I would suggest to revert this change and have separate clients in all components

Done. Added back a separate client for leader election in the gcm.
PTAL :)

**Review by rfranzke — APPROVED** [review]
/lgtm

Thank you!

**Pull request merged**
