### PR TITLE
Update to alpine 3.15.8

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Update to alpine 3.15.8.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
You have to add the new tag [here](https://github.com/gardener/ci-infra/blob/74a3735877c00e3cf2810de150d48769e181689a/config/images/images.yaml#L21-L24) first and get that PR merged that the image is copied to GCR before the e2e will succeed again.

**Comment by ScheererJ** [comment]
> You have to add the new tag [here](https://github.com/gardener/ci-infra/blob/74a3735877c00e3cf2810de150d48769e181689a/config/images/images.yaml#L21-L24) first and get that PR merged that the image is copied to GCR before the e2e will succeed again.

Good point. Thanks.

Why did `pull-gardener-e2e-kind-ha-multi-zone-upgrade` and `pull-gardener-e2e-kind-ha-single-zone-upgrade` succeed? Was the failure to pull the new image just not noticed?

**Comment by ScheererJ** [comment]
https://github.com/gardener/ci-infra/pull/665

**Comment by oliver-goetz** [comment]
> > You have to add the new tag [here](https://github.com/gardener/ci-infra/blob/74a3735877c00e3cf2810de150d48769e181689a/config/images/images.yaml#L21-L24) first and get that PR merged that the image is copied to GCR before the e2e will succeed again.
> 
> Good point. Thanks.
> 
> Why did `pull-gardener-e2e-kind-ha-multi-zone-upgrade` and `pull-gardener-e2e-kind-ha-single-zone-upgrade` succeed? Was the failure to pull the new image just not noticed?

Tbh, I don't know. I just assumed that this was the issue, because the exactly the same tests failed twice and there is a reference to new 3rd party image on gcr.io 😅

**Pull request merged**
