### PR TITLE
Improve package structure

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
- Move monitoring-related components to `pkg/component/monitoring/*`
- Move Gardener components to `pkg/component/gardener/*`
- Move autoscaling-related components to `pkg/component/autoscaling/*`
- Move networking-related components to `pkg/component/networking/*`
- Move Garden cluster-related components to `pkg/component/garden/*`
- Move Seed cluster-related components to `pkg/component/seed/*`
- Move Shoot cluster-related components to `pkg/component/shoot/*`
- Move node mgmt-related components to `pkg/component/nodemanagement/*`
- Move observability-related components to `pkg/component/observability/*`
- Move etcd-related components to `pkg/component/etcd/*`
- Move Kubernetes components to `pkg/component/kubernetes/*`
- Move `pkg/envtest` to `test/envtest`
- Move `pkg/mock` to `third_party/mock `
- Move `pkg/{openapi,registry}` packages to `pkg/apiserver/*`
- Move `pkg/operation` to `pkg/gardenlet/operation`

**Release note**:

```breaking developer
The `pkg/envtest` package has been moved to `test/envtest`. Most component packages in `pkg/component` have been moved. The `pkg/openapi` and `pkg/registry` packages have been moved to `pkg/apiserver/*`.
```

### CODE REVIEW

**Comment by plkokanov** [comment]
I managed to go through most of the commits, and plan to try out the PR locally as well.

I just have one question for now - is the `nodemanagement/*` location ok for the `dependency-watchdog`? It seems to fit the `prober` component of the `dependency-watchdog`, but not the `weeder`.
As an alternative, I could suggest using the `seed/*` directory, but don't really have too strong of an opinion.

**Comment by rfranzke** [comment]
> I managed to go through most of the commits, and plan to try out the PR locally as well.
> 
> I just have one question for now - is the `nodemanagement/*` location ok for the `dependency-watchdog`? It seems to fit the `prober` component of the `dependency-watchdog`, but not the `weeder`. As an alternative, I could suggest using the `seed/*` directory, but don't really have too strong of an opinion.

I think it shouldn't matter much - I'd prefer to keep it as is since DWD's main task is preventing massive node terminations when getting unavailable.

**Review by acumino — COMMENTED** [review]
Look good in general only two things - 
- Shouldn't `/pkg/component/observability/monitoring/logging.go` be in `/pkg/component/observability/logging/logging.go`
- Plutono can be kept inside monitoring?

**Comment by rfranzke** [comment]
> * Shouldn't `/pkg/component/observability/monitoring/logging.go` be in `/pkg/component/observability/logging/logging.go`

This `/pkg/component/observability/monitoring/logging.go` file is used for providing logging configuration for the monitoring components. Hence, it should be "correct" there. But I anyways expect this file to disappear eventually as part of https://github.com/gardener/gardener/issues/9065.

> * Plutono can be kept inside monitoring?

Since Plutono is used for both monitoring and logging, I decided to put it into `pkg/component/observability`. Doesn't this make sense to you?

**Comment by plkokanov** [comment]
> I think it shouldn't matter much - I'd prefer to keep it as is since DWD's main task is preventing massive node terminations when getting unavailable.

Alrighty
/approve

**Review by acumino — COMMENTED** [review]
/lgtm

**Pull request merged**
