### PR TITLE
Store coordination.k8s.io/leases in the etcd-events

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area control-plane performance storage
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Store coordination.k8s.io/leases in the etcd-events to reduce load on etcd-main. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
The `coordination.k8s.io/leases` resources are now stored in the `etcd-events`. With this change, the db of `etcd-main` will be less often updated, hence less snapshots will be taken.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/second-opinion
/invite @mvladev

**Comment by timebertt** [comment]
What will happen to leases that are already stored in etcd-main? I guess, they won't get cleaned up, right?

**Comment by vpnachev** [comment]
> What will happen to leases that are already stored in etcd-main? I guess, they won't get cleaned up, right?

Yes, they will be orphaned there. One option that comes into my mind is to run a clean-up command against etcd-main
```bash
ETCDCTL_API=3 etcdctl --endpoints=etcd-main-client:2379 del --prefix /registry/leases
```

However, this cannot be done from this repository now, at least not so easy.

**Comment by rfranzke** [comment]
Well, what about simply keeping them orphaned for existing clusters? They are small anyways, and they don't cause any trouble.

**Comment by ialidzhikov** [comment]
One minor nit - the name etcd-events will be misleading as the etcd will be no longer used only for events.

**Review by timebertt — APPROVED** [review]
Thanks!
/lgtm

**Comment by mvladev** [comment]
The problem is that it causes perceived data-loss. It might cause problems for end-users using the lease objects for some reasons other than healtchecks.

**Comment by rfranzke** [comment]
Hm, that's a valid point (although, I'm not sure how likely this is). I can image three ways to proceed now:
1. Only store the `Lease`s in etcd-events for shooted seeds
1. Do it for all shoots, but put it behind a feature gate
1. Make it configurable per shoot

Opinions?

**Comment by rfranzke** [comment]
Shall we close this PR for now until we clarified how to proceed?

**Comment by vpnachev** [comment]
Yes.
/close

**Pull request closed without merging**
