### PR TITLE
Revert "Add Generic resource"

### PR DESCRIPTION
**Pull request by mvladev**
Reverts gardener/gardener#800

It's not clear which path we need to take in my honest opinion.

https://github.com/gardener/gardener-extensions/issues/21
https://github.com/gardener/gardener-extensions/issues/20

### CODE REVIEW

**Comment by rfranzke** [comment]
This thing is pretty clear. For things like the cert-service we will use the `Generic` resource. You are right, the control plane part is not clear yet. But the `Generic` resource we need anyways. OK?

**Comment by mvladev** [comment]
> For things like the cert-service we will use the Generic resource. 

It's like saying that `Deployment` controller should know about the existence of `HorisonalAutoScaller` or `VertialPodAutoScaller` or `FoooBaz` resource.
It's the other way around - `HPA` report using events to the `Deployment` resource without touching its status. It makes lots more sense to have the cert-service handle it's `Cert` resource (or whatever it's called).

> But the Generic resource we need anyways. OK?

As mentioned above it's better to have solid API contract as `Generic` is too _generic_ and it does not handle all the lifecycle flow of various resources.

**Comment by rfranzke** [comment]
I don't get it. You are outlining general paradigms, but I don't see a concrete proposal how to enable generic extensions like the cert-service.

Why are we talking about this in the first place? The ext. proposal is out since half a year now, and we are in the process of implementing it. You didn't give any feedback on that point earlier, and you didn't propose proper and working alternatives. Tim's PR was open for five days and you didn't comment on it. Now that it's merged you want to revert it but without an alternative.

**Comment by rfranzke** [comment]
Same for the issue #730: Created one month ago, no feedback from nobody, but now in the process of implementation you raise doubts.

**Comment by timuthy** [comment]
To me it also occurs you are addressing a general design doubt @mvladev.

For example, `OperatingSystemConfig` which is already released basically follows the same pattern: Gardener writes `OperatingSystemConfig` to Seed --> Controller acts upon it in the Seed cluster & updates `status` --> `Gardener` reads `status` and proceeds with that information.

 The `Generic` resource is solely a commonly shared resource which serves as an implementation hook for (generic) extensions, i.e. extensions Gardener does not know about.

> No operation is depending on the status of these resources, however, the entire reconciliation flow is.

https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md#generic-resources

Imho, we can definitely think about naming the `Generic` resource differently but I can't imagine any other way to handle use cases with generic extensions at the moment.

**Comment by rfranzke** [comment]
How do we proceed here now?
@mvladev can you please outline your alternative approach for the cert-service (or likewise) extensions?

**Comment by mvladev** [comment]
A simple approach would be for the `cert-service` to listen for resources defined in
gardener/gardener-extensions#21 or gardener/gardener-extensions#20 (as it needs a working APIServer in order to work) and then to deploy the `cert-manager`.

If it needs some specific `Shoot` information it can talk to the Gardener APIserver with the help of #677

**Comment by adracus** [comment]
I think the design of every extension controller in a seed watching the Gardener API server doesn't really scale: If you have e.g. 10 extensions and 30 Seeds, then you have 300 controllers that are not in the same network as the Gardener API server constantly polling (yes, I know they're `WATCH`ing but this is nothing more but a bit more optimized polling).

An even bigger issue is that if we followed this design, every extension controller would have to be aware of two Kubernetes clusters which complicates code + resource version handling + testing.

No, I think a concept like the one we're using right now allows for way more scalability and re-use potential. I agree with @timuthy that the naming of the `Generic` resource isn't right, I'd have actually preferred sth. like `AddonInstallation` or similar but that's _really_ only a minor issue.

**Comment by rfranzke** [comment]
How does the cert-service report back status information? How does it report back that it's done?

**Comment by mvladev** [comment]
> I think the design of every extension controller in a seed watching the Gardener API server doesn't really scale: If you have e.g. 10 extensions and 30 Seeds, then you have 300 controllers that are not in the same network as the Gardener API server constantly polling (yes, I know they're WATCHing but this is nothing more but a bit more optimized polling).

@adracus A single poorly written controller can already nuke the API server with requests anyway (no server-side request limit yet). K8S already does that - you can have clusters with up to 5000 Nodes and normally on each of them you have `kubelet` and `kube-proxy` each opening connections to the APIserver.

> An even bigger issue is that if we followed this design, every extension controller would have to be aware of two Kubernetes clusters.

Only those which require fetching something from the Garden API server.  

> which complicates code + resource version handling + testing

It's an additional `kubeconfig` pointing to the server you want to use. Testing, yest it'll be more difficult. Can you elaborate on `resource version handling`?

-----

>  How does the cert-service report back status information? How does it report back that it's done?

@rfranzke why it should report? it's completely optional and it can already use events to report status.

**Comment by rfranzke** [comment]
> @rfranzke why it should report? it's completely optional and it can already use events to report status.

You can not generalize this statement. For some extensions, e.g. the cert-service extension, the Gardener provider wants all clusters to have a running cert-broker next to the control plane. So, here it's not optional. If there is no dedicated resource in the seed then how should status be reported? Events are not evaluated by Gardener currently and it's not planned (there is no easy way to fetch the events for a resource).

**Comment by mvladev** [comment]
> For some extensions, e.g. the cert-service extension, the Gardener provider wants all clusters to have a running cert-broker next to the control plane. So, here it's not optional. If there is no dedicated resource in the seed then how should status be reported?

The real question is _should the reconciliation flow be canceled, because optional component X is failing?_. For Gardener this component is completely optional. For the provider, I would argue that it's optional and not on the same level as for example `kube-controller-manager`.

If we look at the `Pod` - it's creation fails when `CSI` or `CNI` is not ready, but succeeds even if `kube-proxy` is not working on that Node (as there might be other implementation providing the same behavior). It'll also produce warning events in case there are more search domains in `/etc/resolv.conf`, but your `Pod` will not fail.

I would expect to do `kubectl describe shoot cluster` and there in events section to see that cert-service is not in a working state.

> there is no easy way to fetch the events for a resource

`v1.Event` has fieldSelectors for this:

https://my-apiserver/api/v1/events?fieldSelector=involvedObject.name=my-foo-resource&involvedObject.namespace=some-namespace&involvedObject.kind=Foo&involvedObject.uid=some-uiid

See https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/apis/core/field_constants.go#L28-L37 

You can do quite detailed filtering based on those fields: 

- `action`
- `reportingComponent`
- `type`
- `involvedObject.kind`
- `involvedObject.namespace`
- `involvedObject.name`
- `involvedObject.uid`
- `involvedObject.apiVersion`
- `involvedObject.resourceVersion`
- `involvedObject.fieldPath`

**Comment by mvladev** [comment]
To put it more simply: we define `Generic` as an abstraction to fit many use cases, but end up with this abstraction being too abstract (it violates Liskov substitution principle from OOP).

**Comment by rfranzke** [comment]
> The real question is should the reconciliation flow be canceled, because optional component X is failing?. For Gardener this component is completely optional. For the provider, I would argue that it's optional and not on the same level as for example kube-controller-manager.

That's another question you are opening up. Some extensions might want to cause the flow to fail, other don't. Anyways, how is this related to the `Generic` resource? For those extensions that need some further configuration out of the shoot manifest, and that maybe are relevant/important and want the shoot flow to fail if something goes wrong, and those that want to report status back or contribute to the conditions - for all of these use-cases we need the `Generic` resource.

Events are nice but so far our contract is to get information out of the status, and for now we should keep it homogenous.

**Comment by mvladev** [comment]
> Anyways, how is this related to the Generic resource? 

I don't see how failing or not failing behavior can be described in the `Generic` specification.

> For those extensions that need some further configuration out of the shoot manifest.

Putting everything (or random arbitrary data) in 1 resource (Shoot) specification can only de-gradate the behavior of our controllers and makes reasoning about complex behavior really hard. I'm looking from history - `v1.ReplicatationController` was trying to 2 different jobs - handle replication of `Pods` and roll-out of versions - the logic was really complex and hard to add new functionality.

> Events are nice but so far our contract is to get information out of the status, and for now we should keep it homogenous.

I don't think that this behavior have can scale. If we copy everything from the `Generic` status into `Shoot` status we might hit also `etcd` problems where we constantly update the same resource (which at this moment is not bound and can grow - I'm looking at the conditions). So every `Shoot` status update is going to store the same resource in `JSON` and those `runtime.RawExtension` blobs in there it can lead to severe `etcd` degradation.

Even `cert-broker` does not modify the status of the `Ingress` resource - it writes events.

**Comment by rfranzke** [comment]
> I don't see how failing or not failing behavior can be described in the Generic specification.

We can extend the `ControllerRegistration` to describe this behaviour as soon as we need it. We can't make 100 steps at the same time. Let's first implement what is possible today and then extend it to support even more use-cases.

> Putting everything (or random arbitrary data) in 1 resource (Shoot) specification can only de-gradate the behavior of our controllers and makes reasoning about complex behavior really hard. I'm looking from history - v1.ReplicatationController was trying to 2 different jobs - handle replication of Pods and roll-out of versions - the logic was really complex and hard to add new functionality.

The Shoot resource is the only and the central API for our users. We certainly don't want them to create multiple "sub" resources to describe their shoot. Already today we have different sections there (`networks`, `dns`, `maintenance`, ...). Out of this API Gardener creates a resource in the seed that is acted up-on by another controller. So no complexity here. It's the same principle like for all other extension resources that we have (`Infrastructure`, `Worker`, ...). Gardener is just creating them and others do the work, that's it. We want to keep Gardener's opinion on how the shoot creation flow looks like, which step is executed when etc.

> I don't think that this behavior have can scale. If we copy everything from the Generic status into Shoot status we might hit also etcd problems where we constantly update the same resource (which at this moment is not bound and can grow - I'm looking at the conditions). So every Shoot status update is going to store the same resource in JSON and those runtime.RawExtension blobs in there it can lead to severe etcd degradation.

We don't copy everything. The shoot care controller will collect certain conditions from the extension resource (not only `Generic`, but also others) and merge them into one in the `Shoot`. Nothing is growing unbound and we won't do that too often. Compared to how it works today nothing changes reg. frequency, etc., only the way how the conditions content is computed (collected from extension resource instead of letting Gardener doing everything on its own).

> Even cert-broker does not modify the status of the Ingress resource - it writes events.

Yes, but why is it doing it that way? Because we don't control the `Ingress` resource, but another dedicated ingress controller. The cert-broker is just an extension. For the `Generic` resource we have dedicated controllers that are responsible for reconciling them and writing the status.

**Comment by mvladev** [comment]
Okay to make it 100% clear:

1. Are those `Generics` going to be configurable in the Shoot specification?
1. Is this `Generics` resource required by Gardener only for the `status` copying by `shoot-care` controller?

**Comment by rfranzke** [comment]
> Are those Generics going to be configurable in the Shoot specification?

Depends. I guess there will be generics that are mandatory for all shoots. The administrator would configure that in the respective `ControllerRegistration`. In this case probably no configuration needs to happen in the `Shoot` resource. The cert-service is such an example, right @timuthy?
Others could be entirely optional, and those might need to be enabled explicitly:

```yaml
spec:
  ...
  generics:
  - type: foo-bar
    providerConfig: |
      some-optional-configuration-if-needed
```

Both scenarios exist I guess.

> Is this Generics resource required by Gardener only for the status copying by shoot-care controller?

It is needed for several things:

a) If the extension requires specific configuration (see above), then Gardener moves this configuration out of the `Shoot` resource to the `Generic` resource.
b) For those extensions that are mandatory we want the shoot flow to fail if something went wrong -> this information is reported via the `Generic`'s status.
c) For those extensions that want to contribute to the shoot conditions the `shoot-care` controller merges the `.status.conditions[]` written to the `Generic` resource into the `Shoot`'s `conditions`.

**Comment by rfranzke** [comment]
ping. How to continue?

**Comment by rfranzke** [comment]
Just had a call with @mvladev about this issue.

Martin is *strongly against* the `Generic` approach. His arguments/thoughts were:
- The `providerConfig` inside the `Shoot` resource may contain arbitrary data that cannot be validated during creation because the extension controller is running in the seed cluster. (The same is true for all the other extension CRDs like `Infrastructure`, `Worker`, etc.)
- Instead of putting the "declaration" of "generic" extensions into the `Shoot` resource he suggested to have a CRD per extension that is loosely connected to the shoot (maybe via reference). This CRD shall contain the configuration (`providerConfig`) and can be "better validated" (still, some validating webhook must be installed into the garden cluster, so for validation the extra CRD does not help at all, "it's just a better approach to have small building blocks").
- Gardener must not know about any of these "generic" extensions. That means that the extensions would still be deployed in the seed cluster, however, there is no extension CRD there. The consequence is that the extensions must identify themselves *when* and *what* to do.
    - The extensions must talk to the garden cluster to get their configuration (be it from the `Shoot` resource or (preferred) some other CRD, because Gardener will not replicate that information into the seed) --> "generic" extensions require a kubeconfig+RBAC for the garden cluster.
    - In order to report their status back they again talk to the garden cluster and (preferred) send events to their CRD.
    - In case they want to contribute to `Shoot` conditions (not preferred at all) then they would directly modify the `Shoot` resource in the garden cluster.
    - There is no way to let the shoot reconcile/delete flow fail if something with the generic extension goes wrong. That means that end-users would have to retrieve the events for all the extension CRDs in order to get information about the status. (Same applies for the Gardener dashboard.)
    - Extensions must talk to three clusters (garden,seed,shoot) which (in @mvladev's opinion) does not increase complexity but is a better approach.

**Comment by rfranzke** [comment]
We discussed the topic again with @adracus, @timuthy, @zanetworker. The summary is:

> The providerConfig inside the Shoot resource may contain arbitrary data that cannot be validated during creation because the extension controller is running in the seed cluster. (The same is true for all the other extension CRDs like Infrastructure, Worker, etc.)

That's independent of the `Generic` resource itself but also applies to the other extension resources. Basically, this is the approach followed by the community (cluster-api), we are adapting it. Irrelevant for the discussion about the `Generic` resource.

> Instead of putting the "declaration" of "generic" extensions into the Shoot resource he suggested to have a CRD per extension that is loosely connected to the shoot (maybe via reference). This CRD shall contain the configuration (providerConfig) and can be "better validated" (still, some validating webhook must be installed into the garden cluster, so for validation the extra CRD does not help at all, "it's just a better approach to have small building blocks").

This approach might look nicer because smaller building blocks will be used, but it also increases the complexity regarding usability and implementation. In the end, it doesn't matter whether the configuration for the "generic" extension resides in its own resource or in the shoot resource itself. For validating there is a controller required that lives inside the garden cluster, be it the validation for a CRD or for the `Shoot`.

> The extensions must talk to the garden cluster to get their configuration (be it from the Shoot resource or (preferred) some other CRD, because Gardener will not replicate that information into the seed) --> "generic" extensions require a kubeconfig+RBAC for the garden cluster.

This is currently not part of the extensibility concept. The extensions live in the seed and talking to the Garden cluster is does increase complexity (extensions might need to three clusters in parallel). Moreover, from the current architectural point of view there is not necessarily a network connectivity from seed->garden, only from garden->seed. Sure, we might change this in the future when we introduce the gardenlet, but it's not yet there. 

> In order to report their status back they again talk to the garden cluster and (preferred) send events to their CRD.

We would need to build a mechanism to read events which does not exist yet. Event's are nice, but also unstructured compared to what we have with the `lastOperation` status.

> In case they want to contribute to Shoot conditions (not preferred at all) then they would directly modify the Shoot resource in the garden cluster.

Apart from needed connectivity to the garden cluster we would like to avoid that arbitrary extensions modify the `Shoot` status themselves.
Generally, let's keep the control with Gardener, at least at the beginning. We can't do too much at the same time risking the stability and robustness of the systems.

> There is no way to let the shoot reconcile/delete flow fail if something with the generic extension goes wrong. That means that end-users would have to retrieve the events for all the extension CRDs in order to get information about the status. (Same applies for the Gardener dashboard.)

For certain extensions we want that the shoot reconcile/delete flow fails which is not covered with the CRD and loosely coupled approach. Also, it's too complex for end-users to manually retrieve events for (the potentially many) extension CRDs, likewise it's effort for the dashboard team to implement the same.


Overall, having separate CRDs inside the Garden cluster is kind of contradicting the current extensibility proposal. A dedicated extension resource (like `Generic`) fits into the model. There was the change to shape the extensibility approach back last year in September, but it didn't happen. The CRD approach might be another way to achieve what we need, but let's start with something that is aligned to how extensibility works for other places. We can rename `Generic` to `Extension` or `Custom` or anything else that sounds better and is not misleading, but we decided that we want such a resource - at least now at the beginning. We plan to proceed with the cert-service extension (#730) to get experience how it works out. If it's not sufficient then we can certainly revisit this topic. However, let's now start progressing to get this experience that we don't have today.

@adracus @timuthy @zanetworker Do you have additional thoughts? Do you want to add something?

**Pull request closed without merging**
