### PR TITLE
Add CVE categorisation labels for the node-problem-detector image

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
This PR adds CVE categorisation labels for easier triaging of vulnerabilities. It also adds responsibles so that it is clear who should triage vulnerabilities for this image.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ashwani2k — COMMENTED** [review]
Thanks for this @ialidzhikov 
Looks good to me.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
