### PR TITLE
topology-aware routing: Adapt to the upstream annotation change in K8s 1.27

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area high-availability
/area networking
/kind enhancement

**What this PR does / why we need it**:
In Kubernetes 1.27 the `service.kubernetes.io/topology-aware-hints=auto` annotation is deprecated in favor of the newly introduced `service.kubernetes.io/topology-mode=auto`. This PR adapts the usages of the old annotation so that when the runtime cluster's K8s version is >= 1.27, the new annotation is used.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6718

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
The gardenlet and the gardener-operator will now use the new `service.kubernetes.io/topology-mode=auto` annotation when enabling topology-aware routing for a Service when the Kubernetes version of the runtime cluster is >= 1.27. In Kubernetes 1.27, the `service.kubernetes.io/topology-aware-hints=auto` annotation is deprecated in favor of the newly introduced `service.kubernetes.io/topology-mode=auto`
```

### CODE REVIEW

**Review by timuthy — COMMENTED** [review]
Thank you 👏 
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve

**Pull request merged**
