### PR TITLE
Cluster autoscaler metrics to be scraped by prometheus

### LINKED ISSUE #254: Prometheus/Plutono should scrape important CA metrics
**What would you like to be added**:

Currently CA exposes many metrics , but we still don't utilize them in Prometheus/Plutono. 
Scraping of the key metrics should be enabled

**Why is this needed**:
To increase dev productivity and ops productivity. Further the customer could also investigate their issue better with such metrics.

### PR DESCRIPTION
**Pull request by aaronfern**
**How to categorize this PR?**

/area monitoring ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR adds `cluster autoscaler` metrics to the scrape config so that it can be scraped by `prometheus`

**Which issue(s) this PR fixes**:
Fixes gardener/autoscaler#254

**Special notes for your reviewer**:
ref: https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/proposals/metrics.md

**Release note**:

```other operator
metrics exposed by `cluster autoscaler` now scraped by `prometheus`
```

### CODE REVIEW

**Review by himanshu-kun — COMMENTED** [review]
/lgtm

**Review by acumino — COMMENTED** [review]
/approve

**Pull request merged**
