### PR TITLE
Network policy for KubeApiserver on Alicloud

### LINKED ISSUE #722: Block meta-data IP access to seed cluster in Alicloud
The metadata IP of Alicloud is 100.100.100.200. If the seed cluster is deployed in Alicloud, we should prohibit Shoot control plane to access 100.100.100.200.  

Please assign it to me.

### PR DESCRIPTION
**Pull request by jia-jerry**
**Which issue(s) this PR fixes**:
Fixes #722

### CODE REVIEW

**Comment by rfranzke** [comment]
Looks good.
Can you explain why https://github.com/gardener/gardener/blob/9a133170a92dd80934e84e8bd01a99e3d159709d/test/integration/shoots/applications/shoot_app_test.go#L402-L408 did not fail yet?

**Comment by schrodit** [comment]
The tests fail on all landscapes.
@jia-jerry do you know why the network policy isn't applied correctly?

**Comment by rfranzke** [comment]
ping @jia-jerry

**Comment by rfranzke** [comment]
@jia-jerry can you please outline how you plan to proceed here? If you don't work on it actively anymore then I would close the PR

**Comment by jia-jerry** [comment]
> The tests fail on all landscapes.
> @jia-jerry do you know why the network policy isn't applied correctly?

Sorry for late response. The original implementaion has some issues.
1. Alicloud enable CSI, so cloudProvider is not set value. https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/controlplane.go#L401-L417. This is why the test case failed.
2. The API Server runs on Seed cluster nodes. We should pass Cloudl provider name of Seed cluster. So this why I used another variable **seedCloudProvider**. For example, in soild cluster, we should forbid Seed API Servers to access GCP nodes.

**Review by schrodit — APPROVED** [review]

**Comment by mvladev** [comment]
@jia-jerry I've just updated my #904 PR.
More specifically
https://github.com/gardener/gardener/blob/e1dc88ff9eea65f29da2f0fbafaeb4eb85fdb6fa/pkg/operation/hybridbotanist/controlplane.go#L184

**Comment by jia-jerry** [comment]
> @jia-jerry I've just updated my #904 PR.
> More specifically
> https://github.com/gardener/gardener/blob/e1dc88ff9eea65f29da2f0fbafaeb4eb85fdb6fa/pkg/operation/hybridbotanist/controlplane.go#L184



> @jia-jerry I've just updated my #904 PR.
> More specifically
> https://github.com/gardener/gardener/blob/e1dc88ff9eea65f29da2f0fbafaeb4eb85fdb6fa/pkg/operation/hybridbotanist/controlplane.go#L184

This is  a huge change. When will it be merged? With your PR, it seems current PR is not used.

**Comment by rfranzke** [comment]
@jia-jerry this one will be merged before #904 I guess. Martin needs to rebase then.

**Pull request merged**
