### PR TITLE
Removes owner checks from extension controller reconciliations

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind cleanup

**What this PR does / why we need it**:
This PR removes the owner checks from the reconciliation of the extension controllers. As part of #6302 it was decided that it is not worth it to keep this complex code as bad case migration is most likely not going to be necessary with the introduction of the HA gardener set up.

**Which issue(s) this PR fixes**:
Part of #6302 

**Special notes for your reviewer**:

**Release note**:

```other operator
Extension controllers no longer perform owner checks based on the owner `DNSRecord` at the start of their reconciliations.
```
```breaking developer
The RBAC for `DNSRecords` is no longer required by extension controllers (other than `DNSRecords`) and should be removed where applicable.
```

### CODE REVIEW

**Comment by plkokanov** [comment]
/hold
I noticed a few more lines of code that can be removed.

**Review by rfranzke — COMMENTED** [review]
/approve
/cc @timebertt

**Review by timebertt — APPROVED** [review]
Nice, thank you!
/lgtm

**Comment by timebertt** [comment]
@plkokanov you could add a sentence to the release note saying that RBAC for `DNSRecords` is not required by extension controllers (other than `DNSRecords`) any more.
It was added before because of this feature and should not be required any more now.
You could add a corresponding task to https://github.com/gardener/gardener/issues/6302 to cleanup these RBAC rules when upgrading to g/g@1.60 in extensions. :)

**Comment by plkokanov** [comment]
Nice catch @timebertt! I added the release note and also the task in the issue.

**Comment by shafeeqes** [comment]
Failure due to https://github.com/gardener/gardener/issues/6923
/test pull-gardener-integration

**Pull request merged**
