### PR TITLE
Kubernetes Version Configurability per Worker Pool

### LINKED ISSUE #3501: Kubernetes Version Configurability per Worker Pool
**What would you like to be added**:
Today, end users can define the OS version per worker pool, but not the Kubernetes version. I.e., while they can create themselves a new worker pool with a new OS and orchestrate a careful migration of workload (brownfield/legacy apps that have individual "planned maintenance time window" where the cluster-global maintenance time window won't help), they cannot do that for a Kubernetes minor version update (patch updates are executed in-place, but due to effort/risk this is not supported for minor versions, yet).

Therefore, it would be great to support "pinning" the Kubernetes version also per worker pool:
- A skew of 2 versions is permitted (see https://kubernetes.io/docs/setup/release/version-skew-policy)
- We want to flag this feature, as also others do, as supported only during upgrades and not in general (which would speak for a skew of only one minor version for a limited amount of time)
- We should validate the shoot spec and allow a skew only if there is a specific `kubelet` configuration for that worker pool or none at all for the cluster in general (otherwise end users may forget to copy it to the old worker pool when they adapt the global `kubelet` configuration to the new Kubernetes version that wouldn't fit the old Kubernetes version anymore)

**Why is this needed**:
To allow end users to execute "gentle" Kubernetes version minor version upgrades where they can much better control the transition of workload from old to new worker nodes.

/cc @amshuman-kr @rfranzke @vpnachev @dguendisch

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
To allow end users to execute "gentle" Kubernetes version minor version upgrades where they can much better control the transition of workload from old to new worker nodes it is now possible to specify the Kubernetes version per worker pool for `Shoot`s by setting `.spec.provider.workers[].kubernetes.version`.

A version skew by two minor versions is allowed as described in https://kubernetes.io/releases/version-skew-policy/#kubelet-1.

The feature is hidden behind the newly introduced `WorkerPoolKubernetesVersion` feature gate since provider extensions must be revendored to properly handle such shoot clusters.

**Which issue(s) this PR fixes**:
Fixes #3501

**Special notes for your reviewer**:
✅ Based on #4969 which needs to be merged first

**Release note**:

```feature user
If the `WorkerPoolKubernetesVersion` feature gate is enabled then it is possible to specify the Kubernetes version per worker pool for `Shoot`s by setting `.spec.provider.workers[].kubernetes.version`. Please consult [this document](https://github.com/gardener/gardener/tree/master/docs/usage/worker_pool_k8s_versions.md) for more information.
```
```feature operator
The `WorkerPoolKubernetesVersion` feature gate must only be enabled when all provider extensions explicitly announce in their release notes that they support specific Kubernetes versions per worker pool. Otherwise, worker nodes of shoot clusters might be misconfigured or rolled out unexpectedly.
```
```noteworthy developer
In order to make provider extensions ready for properly handling `Shoot` clusters with overridden Kubernetes versions per worker pool, you need to revendor the extensions library.
```

### CODE REVIEW

**Review by danielfoehrKn — COMMENTED** [review]
/assign By looking at the commits I can already say that it is easily understandable and well structured. I'll have a test run tomorrow.

**Comment by danielfoehrKn** [comment]
There is a problem for kubelet feature gates that are added by the [provider-extension based on the Kubernetes version.](https://github.com/gardener/gardener-extension-provider-aws/blob/a752b0306605e98cb6c4297e38c6503591c077fb/pkg/webhook/controlplane/ensurer.go#L67)
For example for the kubelet flag  `InTreePluginAWSUnregister`.

Example:
 - Worker Pool 1 with K8s 1.21
 - Worker Pool 2 with K8s 1.20


The kubelet for kubernetes 1.20 of worker pool 2  has the feature flag `InTreePluginAWSUnregister` added leading to:

> Nov 10 15:02:54 ip-10-250-31-182.eu-north-1.compute.internal kubelet[5142]: F1110 15:02:54.798061    5142 server.go:208] unrecognized feature gate: InTreePluginAWSUnregister

The erroneous check is performed in the provider extension [here](https://github.com/gardener/gardener-extension-provider-aws/blob/a752b0306605e98cb6c4297e38c6503591c077fb/pkg/webhook/controlplane/ensurer.go#L61) (on the global Kubernetes version)

**Comment by majst01** [comment]
> There is a problem for kubelet feature gates that are added by the [provider-extension based on the Kubernetes version.](https://github.com/gardener/gardener-extension-provider-aws/blob/a752b0306605e98cb6c4297e38c6503591c077fb/pkg/webhook/controlplane/ensurer.go#L67) For example for the kubelet flag `InTreePluginAWSUnregister`.
> 
> Example:
> 
> * Worker Pool 1 with K8s 1.21
> * Worker Pool 2 with K8s 1.20
> 
> The kubelet for kubernetes 1.20 of worker pool 2 has the feature flag `InTreePluginAWSUnregister` added leading to:
> 
> > Nov 10 15:02:54 ip-10-250-31-182.eu-north-1.compute.internal kubelet[5142]: F1110 15:02:54.798061    5142 server.go:208] unrecognized feature gate: InTreePluginAWSUnregister
> 
> The erroneous check is performed in the provider extension [here](https://github.com/gardener/gardener-extension-provider-aws/blob/a752b0306605e98cb6c4297e38c6503591c077fb/pkg/webhook/controlplane/ensurer.go#L61) (on the global Kubernetes version)

So does this mean that for csi drivers, aws specifc in this case, we must ensure the same version skew policy as we already implemented for kube-proxy? 

But if this is the case this must obviously done in the extension of the concrete provider, we only can give a hint for the extension developers.

**Comment by rfranzke** [comment]
Thanks @danielfoehrKn, that's a good catch. Still, as @majst01 explained, this is unrelated to this concrete PR in g/g and must be covered in the provider extensions. I've added it to my list and will work on it when I'm free.
For now, we have the feature gate which is disabled by default. I have refined the release note such that it should only be enabled when the provider extensions announce that they support having specific Kubernetes versions per pool.
I guess we can proceed with this PR.

**Review by danielfoehrKn — DISMISSED** [review]
Another thing to think about would be auto-updates for worker pools. 

Other than that, the functionality worked just fine for me. Thanks!

**Comment by majst01** [comment]
> Another thing to think about would be auto-updates for worker pools.

This is already covered !

> 
> Other than that, the functionality worked just fine for me. Thanks!

Thanks for reviewing

**Comment by danielfoehrKn** [comment]
> Another thing to think about would be auto-updates for worker pools.

Sorry, to be more precise: Having individual k8s auto-update settings per worker pool.
So worker pool 1 would use auto-updates, while pool 2 does not.
Currently, there is only the global `shoot.Spec.Maintenance.AutoUpdate.KubernetesVersion`.
Just an idea. Probably not worth implementing before there is a concrete demand. And not relevant for this PR.
Thanks for the great work :)

**Comment by rfranzke** [comment]
@danielfoehrKn Yes, good point, we also discussed this last week and came to the same conclusion like you: For now, the global auto-update is good enough. If there is demand for configuring this per worker pool then we can easily add it later.

**Comment by rfranzke** [comment]
I rebased and resolved the conflicts. @danielfoehrKn can you please approve again so that we can get it merged? Thank you!

**Review by danielfoehrKn — APPROVED** [review]

**Comment by majst01** [comment]
Thanks all for pushing this !

**Comment by rfranzke** [comment]
Thanks again for the great collaboration @majst01 @mwennrich. We should do this again :)

**Pull request merged**
