### PR TITLE
Promote `ShootMaxTokenExpirationOverwrite` feature gate to beta

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Promote `ShootMaxTokenExpirationOverwrite` feature gate to beta.

**Release note**:

```other operator
The `ShootMaxTokenExpirationOverwrite` feature gate has been promoted to beta and is now enabled by default.
```

### CODE REVIEW

**Review by acumino — CHANGES_REQUESTED** [review]
Please update changes here also https://github.com/gardener/gardener/blob/256b46794f44b193a40e58f8035a8905b202ff7a/pkg/features/features.go#L143-L150

**Comment by rfranzke** [comment]
@acumino What do you mean? What needs to be changed?

**Comment by acumino** [comment]
> alpha: v1.43.0

We also need to update when the feature was updated to beta in features.go.

**Comment by rfranzke** [comment]
Isn't this covered by https://github.com/gardener/gardener/pull/5726/files#diff-4914632202b9c7ee5d0ba5f8d143ba5a91887e66c02f35e1456e912092a9346dR150?

**Comment by acumino** [comment]
> Isn't this covered by https://github.com/gardener/gardener/pull/5726/files#diff-4914632202b9c7ee5d0ba5f8d143ba5a91887e66c02f35e1456e912092a9346dR150?

Ah missed it.

**Review by acumino — APPROVED** [review]
/lgtm

**Pull request merged**
