### PR TITLE
Allow Shoot to be created when Seed .spec.backup=nil

### LINKED ISSUE #2366: cannot change seed name, because seed backup is not configured
**How to categorize this issue?**

/kind bug
/priority critical

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Try to create a new Shoot.

2. Ensure that the apply fails with

```
$ k apply -f shoot.yaml
Error from server (Forbidden): error when creating "shoot.yaml": shoots.core.gardener.cloud "foo" is forbidden: cannot change seed name, because seed backup is not configured, for shoot "foo"
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality
/kind bug
/priority critical

**What this PR does / why we need it**:
Allow Shoot to be created when Seed .spec.backup=nil.

**Which issue(s) this PR fixes**:
Fixes #2366

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by swilen-iwanow — APPROVED** [review]
/lgtm

**Comment by ghost** [comment]
@swilen-iwanow Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Review by vpnachev — APPROVED** [review]

**Pull request merged**
