### PR TITLE
Move `extensions/test` files to test package

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area testing
/kind cleanup

**What this PR does / why we need it**:
This PR moves files from extensions/test to the dedicated test package.

ie;
github.com/gardener/gardener/extensions/test/testmachinery goes into github.com/gardener/gardener/test/testmachinery/extensions

github.com/gardener/gardener/extensions/test/integration goes into github.com/gardener/gardener/test/integration/extensions/controller

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @rfranzke 

**Release note**:

```breaking dependency
Files in `./extensions/test` have been moved to `./test` package, Please adapt the import paths accordingly:
- `github.com/gardener/gardener/extensions/test/testmachinery` has been moved to `github.com/gardener/gardener/test/testmachinery/extensions`
- `github.com/gardener/gardener/extensions/test/integration` has been moved to `github.com/gardener/gardener/test/integration/extensions/controller`
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
Sorry, fixing the failing tests.

**Comment by rfranzke** [comment]
You should add a breaking release note for dependencies since they have to adapt their import paths (e.g., extensions)

**Comment by shafeeqes** [comment]
> You should add a breaking release note for dependencies since they have to adapt their import paths (e.g., extensions)

Done.

**Pull request merged**
