### PR TITLE
Release responsible schedule for v1.103 until v1.115

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
Extends the docs with a proposal for the release responsible schedule for v1.103 until v1.115

/assign @plkokanov @oliver-goetz @ialidzhikov @acumino @timuthy @LucaBernstein @ScheererJ @ary1992 @shafeeqes @tobschli 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by timuthy — COMMENTED** [review]
/lgtm
/unassign

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Pull request merged**
