### PR TITLE
Configure prometheus to scrape metrics for the central logging stack

### PR DESCRIPTION
**Pull request by KristianZH**
**What this PR does / why we need it**:

Prometheus will scape metrics for fluent-bit, fluentd and elasticsearch in `garden` namespace

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@ialidzhikov @vpnachev @mvladev 

**Release note**:

```improvement operator
Prometheus will now scrape metrics for `fluent-bit`, `fluentd`, and `elasticsearch` in the `garden` namespace.
```

### CODE REVIEW

**Review by wyb1 — COMMENTED** [review]
What do you plan on doing with these metrics? Currently, the prometheus you configured only retains its data for 2 hours max and is more or less used as a cache for our other Prometheus instances (to get CPU and memory metrics via federation). 

I see why its configured here since fluentbit and fluentd only exist in the garden namespace (correct me if I'm wrong). As is I don't think that we have a proper place for these metrics because AFAIK fluentbit and fluentd don't "belong" to a specific control plane so they don't belong in the `seed-monitoring` prometheus. They don't belong in this Prometheus either since it is only a federation endpoint for the `seed-monitoring` Prometheus. We also have no dashboards that directly use this Prometheus as a data source. The metrics could be useful but I'm not sure where they belong. Maybe I also don't know enough about fluentbit/fluentd. Any thoughts @dkistner @vlerenc ?

**Comment by KristianZH** [comment]
The Idea here was to fetch metrics for the logging components. 
```I see why its configured here since fluentbit and fluentd only exist in the garden namespace``` - Correct, fluent-bit and fluentd live only in the garden namespace and for that reason i use this prometheus.

**Comment by wyb1** [comment]
So the problem with this prometheus is that it only has a retention of 2 hours and no dashboards use the data from this prometheus directly.

**Comment by KristianZH** [comment]
In my opinion 2 hours retention is better than the current state.
I do not think that the lack of Grafana in the `garden` namespace is a problem. We can access the metrics directly from the Prometheus, or can use its `web` Service

**Comment by KristianZH** [comment]
Okay, then let put this PR on hold till we have a monitoring for the `seed` components like: gardener-extensions, logging, monitoring, etc.

**Comment by wyb1** [comment]
If this is useful for you then I'm ok with this for now, but I would like to get a second opinion before merging. If we change/extend the monitoring stack in the future, then we should move these metrics too.

**Comment by KristianZH** [comment]
We still do not have use case for this. Just wanted to monitor our logging stack, because till this moment, we do not monitor any of our logging components. It is okay to freeze this PR for now. Soon i will create a new one, where i will expose metrics from our `elasticsearch` which lives in each shoot-namespace.

**Comment by rfranzke** [comment]
If you decided that it's not useful now then let's close the PR and reopen it as soon as we see fit. OK?

**Comment by dkistner** [comment]
I agree with @wyb1. The prometheus in the `garden` namespace is not the right place to integrate these metrics, due to the retention and for scaling reasons. We have the requirement to add a Prometheus to monitor Seed components like extensions controller etc. already in mind, but we did not yet have the time to tackle this topic.

**Comment by KristianZH** [comment]
Okay, I understand. Then I will close the PR for now.

**Comment by KristianZH** [comment]
@wyb1 @dkistner  Can you review the PR now, please :)

**Review by wyb1 — APPROVED** [review]
/lgtm
FYI the `aggregate-prometheus` is not configured to send alerts to the alertmanager, so these alerts will not be sent out.

**Comment by dkistner** [comment]
Then we should configure the Prometheus to push these alerts to the central Alertmanager otherwise these alerts are useless...

**Comment by KristianZH** [comment]
I will create a PR with the configuration :)

**Pull request merged**
