### PR TITLE
Promote `ShootMaxTokenExpirationValidation` feature gate to beta

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Similar to #5726: Promote `ShootMaxTokenExpirationValidation` feature gate to beta.

**Release note**:

```other operator
The `ShootMaxTokenExpirationValidation` feature gate has been promoted to beta and is now enabled by default.
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
https://github.com/gardener/gardener/blob/e0654f04e0c87e87f2f5af7639ebc00e4b24704d/hack/local-development/start-apiserver#L63
Is this flag still needed here?

**Comment by rfranzke** [comment]
> https://github.com/gardener/gardener/blob/e0654f04e0c87e87f2f5af7639ebc00e4b24704d/hack/local-development/start-apiserver#L63
> 
> 
> Is this flag still needed here?

Not necessarily, I will clean this up after GA promotion.

**Pull request merged**
