### PR TITLE
Add API server conversion webhook duration metric

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area monitoring ops-productivity
/kind enhancement

**What this PR does / why we need it**:

Add API server conversion webhook duration metric.

**Which issue(s) this PR fixes**:
Ref https://github.com/gardener/gardener/issues/4794

**Special notes for your reviewer**:

**Release note**:

```feature operator
The `apiserver_crd_webhook_conversion_duration_seconds` metric is now kept in the shoot monitoring stack.
```

### CODE REVIEW

**Review by stoyanr — COMMENTED** [review]
@timebertt Where is `apiserver_crd_webhook_conversion_duration_seconds` coming from? I couldn't find any references in https://github.com/kubernetes/kubernetes.

**Comment by timuthy** [comment]
> @timebertt Where is `apiserver_crd_webhook_conversion_duration_seconds` coming from? I couldn't find any references in https://github.com/kubernetes/kubernetes.

@stoyanr I think this is what you have looked for: https://github.com/kubernetes/kubernetes/blob/b0eac84937f7f587d738c41a98ac36f7449c9afe/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/conversion/metrics.go#L62

**Review by timuthy — DISMISSED** [review]
/lgtm

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timebertt** [comment]
Rebased to fix grm image build

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
