### PR TITLE
[ci:component:github.com/gardener/ext-authz-server:0.8.0->0.9.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
```feature user github.com/gardener/ext-authz-server #23 @axel7born
Update golang 1.20.4 -> 1.21.3
```

### CODE REVIEW

**Comment by rfranzke** [comment]
ping @axel7born @DockToFuture @ScheererJ

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
