### PR TITLE
Increase CoreDNS memory limits to avoid OOMKill.

### PR DESCRIPTION
**Pull request by amshuman-kr**
**How to categorize this PR?**

/area control-plane scalability
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Increase CoreDNS memory limits to avoid OOMKill.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Addresses the following part of https://github.tools.sap/kubernetes-canary/issues-canary/issues/605#issuecomment-184664.
> 4. If VPA is not enabled for the shoot cluster, use only HPA for CoreDNS with statically increased requests/limits.

I will raise a separate PR to address the VPA part.
> 3. If VPA is enabled for the shoot cluster, remove HPA for CoreDNS but still retain some fixed replicas (2 or 3?) and then scale only vertically.

cc @mvladev @rfranzke 

**Release note**:

```bugfix operator
Increase CoreDNS memory limits to avoid OOMKill.
```

### CODE REVIEW

**Review by vpnachev — APPROVED** [review]
/lgtm

Why is this bug?

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by amshuman-kr** [comment]
> Why is this bug?

Wasn't sure how to categorize it. There was a issue raised for it. Please suggest if it is inappropriate. enhancement or post-mortem, then?

**Comment by vpnachev** [comment]
> > Why is this bug?
> 
> Wasn't sure how to categorize it. There was a issue raised for it. Please suggest if it is inappropriate. enhancement or post-mortem, then?

For sure enhancement sounds more appropriate. If it was a bug, I would expect it is easily reproducible and affecting all or almost all shoot clusters.

**Comment by amshuman-kr** [comment]
The build seems to have failed due to resource issues on the machine. How do I re-trigger the build?

**Pull request merged**
