### PR TITLE
Cleanup more stuff related to local kind setup

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
After #8075, we only have the skaffold based local setup.
This PR cleans up more stuff related to the local kind setup.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @oliver-goetz @acumino 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Nice, thanks!
/lgtm

**Review by acumino — COMMENTED** [review]
/lgtm

**Pull request merged**
