### PR TITLE
Use cached client for generic health check reconciler

### PR DESCRIPTION
**Pull request by timebertt**
**What this PR does / why we need it**:
This PR replaces the unstructured `GET` call in the generic health check reconciler by a typed `GET` call, which can leverage the client's cache. This will help us, reduce some unnecessary direct API calls to the Seed API (which will result in external network traffic). 

**Which issue(s) this PR fixes**:
Part of #1953 

**Special notes for your reviewer**:
Ref https://github.com/gardener/gardener/pull/2249#discussion_r417915941

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]

**Comment by rfranzke** [comment]
Can we merge this PR?

**Comment by timebertt** [comment]
From my POV, yes.

**Comment by rfranzke** [comment]
cc @gardener/gardener-maintainers

**Review by danielfoehrKn — APPROVED** [review]
lgtm

**Pull request merged**
