### PR TITLE
Add serviceaccountmanager permissions to administratos

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
Add serviceaccountmanager permissions to administratos

cc @donistz @dimityrmirchev 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Gardener landscape administrators are now provided with `serviceaccountmanager` permissions, i.e. they can manage service accounts and issue tokens for them.
```

### CODE REVIEW

**Review by Kristian-ZH — APPROVED** [review]
/lgtm

**Review by dimityrmirchev — APPROVED** [review]

**Pull request merged**
