### PR TITLE
[ci:component:github.com/gardener/vpn:0.20.0->0.21.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-2**
**Release Notes**:
``` noteworthy operator github.com/gardener/vpn #60 @ScheererJ
Updated base container image of old vpn seed and vpn shoot to alpine 3.16.2
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Comment by rfranzke** [comment]
/approve cancel
since we saw VPN-related issues in `master` branch which should be clarified first

**Comment by rfranzke** [comment]
/close

@ScheererJ @DockToFuture Kindly open new PRs with image bumps once you are ready

**Pull request closed without merging**
