### PR TITLE
Allow changing container runtime on existing workers

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
Allow changing container runtime on existing workers.

Changing the container runtime on an existing worker will result in a node rollout and is therefore unproblematic and a use-case we want to support. We're not sure why this was specifically forbidden before.

**Which issue(s) this PR fixes**:
Related to #4110 

**Release note**:

```feature user
Allow changing container runtime on existing workers. This triggers a graceful recreation of the workers.
```

/cc @BeckerMax

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Looks good, can you please adapt the documentation (https://github.com/gardener/gardener/blob/master/docs/usage/shoot_updates.md#rolling-update-triggers)?

**Comment by voelzmo** [comment]
> Looks good, can you please adapt the documentation (https://github.com/gardener/gardener/blob/master/docs/usage/shoot_updates.md#rolling-update-triggers)?

done.

**Review by rfranzke — DISMISSED** [review]
Thanks!
/lgtm

**Review by vpnachev — APPROVED** [review]
Thanks!
/lgtm

**Pull request merged**
