### PR TITLE
Remove preStop hook for >= 1.16 clusters

### LINKED ISSUE #3278: kube-apiserver v1.19 fails to exec the preStop lifecycle hook
**How to categorize this issue?**

/kind bug
/priority normal

**What happened**:
https://github.com/gardener/gardener/pull/1275/files adds a prestop hook that relies on presence of `sh` in the apiserver image.
`sh` seems to be missing in `k8s.gcr.io/kube-apiserver:v1.19.4`:
```
$ docker run -ti k8s.gcr.io/kube-apiserver:v1.19.4 sh
2020/12/08 15:34:45 Running command:
Command env: (log-file=, also-stdout=false, redirect-stderr=true)
Run from directory:
Executable path: sh
Args (comma-delimited): sh
2020/12/08 15:34:45 starting command: exec: "sh": executable file not found in $PATH
```

And hence on each rollout we have events that report failure of the prestop hook:

```
53m         Warning   FailedPreStopHook                 pod/kube-apiserver-59d8cbdf5b-9cfkd                          Exec lifecycle hook ([sh -c sleep 5]) for Container "kube-apiserver" in Pod "kube-apiserver-59d8cbdf5b-9cfkd_shoot--foo--bar(01fa2ddb-8156-4e62-aba0-716343bba136)" failed - error: command 'sh -c sleep 5' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"sh\": executable file not found in $PATH: unknown\r\n"
```

`sh` seems to be present on v1.18 and below.

**What you expected to happen**:
The apiserver preStop hook to do not fail for v1.19.

- Gardener version: v1.13.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area usability
/kind bug
/priority normal

**What this PR does / why we need it**:
Because of the streamlining of KAS 1.19.x images and the `shutdown-delay-duration`, we can remove the `preStop` hook for the API server deployment (see linked issue). `shutdown-delay-duration` has been increased to `15s` to circumvent kubernetes/kubernetes#88293.

**Which issue(s) this PR fixes**:
Fixes #3278

**Release note**:

```bugfix operator
An issue has been fixed that prevented the execution of the Kube-API-Server's configured `preStop` hooks for `>=1.19.x` clusters.
```

### CODE REVIEW

**Comment by timuthy** [comment]
PR remains in draft state until I've run some tests.

**Comment by timuthy** [comment]
I ran a view tests:
- Single/Multiple API server replicas
- Observed endpoints while randomly deleting KAS Pods
- Monitored logs of terminating KAS Pods and ensured that new traffic isn't hit by connection issues

Looks good FMPOV.

**Review by rfranzke — APPROVED** [review]
/lgtm
/invite @amshuman-kr

**Review by ialidzhikov — APPROVED** [review]
/lgtm

Thank you @timuthy !

**Review by amshuman-kr — APPROVED** [review]
LGTM

**Pull request merged**
