### PR TITLE
kube-dns now uses .spec.DNS.Domain as domain

### LINKED ISSUE #90: Use dnsmasq to cache Shoot's DNS in the Seed cluster
In our setup end-users should be able to use an extension apiserver, `ExternalAdmissionHookConfiguration`, `ValidatingWebhookConfiguration` ...

Imagine the following configuration that the user adds to it's Shoot cluster via `kubectl`:

```yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: example-config
externalAdmissionHooks:
- name: pod-image.k8s.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    caBundle: <pem encoded ca cert that signs the server cert used by the webhook>
    service:
      name: foo
      namespace: bar
```

This will fail, because the API server is in the Seed cluster and it'll try to do a call against `https://foo.bar` and when trying to resolve `foo.bar` the Seed's DNS will not find this record.
Even worse - this can be used to call some existing services in the Seed cluster.

# Solution 1

To solve this issue and to smooth Seed -> Shoot NS lookups the following should be added to the Shoot cluster for every Shoot namespace:

- `kube-dnsmasq` pod with `kube-dnsmasq` and `vpn-seed` as containers. `kube-dnsmasq` will be configured with:
    
    ```
    [...]
    --server=/<SHOOT-CLUSTER-DOMAIN>/<SHOOT-KUBE-DNS-SERVICE>-#53
    --server=/<SEED-CLUSTER-DOMAIN>/<SEED-KUBE-DNS-SERVICE>-#53
    [...]
   ```

- Kubernetes service for `kube-dnsmasq` called `kube-dnsmasq` it's ClusterIP we call `<KUBE-DNSMASQ-CLUSTER-IP>`
- `kube-apiserver` should have the following [dns configuration](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-dns-config) (alpha in 1.9):

    ```yaml
    [....]
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - <KUBE-DNSMASQ-CLUSTER-IP>
      searches:
        - kube-system.svc.<SHOOT-CLUSTER-DOMAIN>
        - svc.<SHOOT-CLUSTER-DOMAIN>
        - <SHOOT-CLUSTER-DOMAIN>
        - <SEED-NAMESPACE>.svc.<SEED-CLUSTER-DOMAIN>
      options:
        - name: ndots
          value: "5"
        - name: edns0
    [....]
    ```

This requires 2 things - both Shoot and Seed to have different DNS domains - not `cluster.local`. 

# Solution 2

This also can be simplified by simply putting the `kube-dnsmasq` container in the `kube-apiserver` pod, but if multiple pods in the Seed cluster needs to have the same DNS resolve, then they should add it to theirs as well.

### PR DESCRIPTION
**Pull request by mvladev**
This will allow end-users to expose their kube-dns and use dnsmasq to connect
multiple clusters easily.

closes #90

### CODE REVIEW

**Comment by rfranzke** [comment]
You need to handle the case where `.spec.dns.domain` is not set (e.g., when `.spec.dns.provider=unmanaged`).

**Comment by mvladev** [comment]
Shouldn't the `.spec.dns.domain` be `cluster.local` be in that case?

**Comment by rfranzke** [comment]
Not sure, actually the `.spec.dns` section was only meant to configure the cluster's external domain.
Do you suggest to default it with `cluster.local` ?

**Comment by mvladev** [comment]
Yes

**Comment by rfranzke** [comment]
Hmm, okay, we can do that in case `.spec.dns.provider=umanaged` (and only in that case). The DNS section is later anyhow immutable, thus when somebody decided not to have an external domain it should be fine seeing there `cluster.local`. Then let's do that and adapt the code paths where the `spec.dns.domain` value or the `ExternalDomain` attribute of the `shoot.Shoot` structure (`pkg/shoot/types.go`) is used.

**Comment by mvladev** [comment]
Something like this, right:
- defaulting `.spec.dns.domain` to `cluster.local` only if  `.spec.dns.provider==umanaged`
- validation: require `.spec.dns.domain` to be set in any case

**Comment by rfranzke** [comment]
Yes, sounds good. Will ease some code paths probably.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
