### PR TITLE
Move all components into ./pkg/operation/botanist/component/

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PRs moves all the component packages which were scattered across several directories into the `./pkg/operation/botanist/component` directory. Earlier, we tried to come up with an "artificial" dir structure (`controlplane`, `systemcomponents`, `seedsystemcomponents`, etc., but this cannot be done consistently anyways because some components might be reused in multiple places (most prominent example is the `resourcemanager` component).
For easier navigation throughout the project it's easier to maintain them in one place.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Any feedback to this PR @gardener/gardener-maintainers?

**Comment by ialidzhikov** [comment]
Sorry for the delay. Can you rebase?

**Comment by ialidzhikov** [comment]
Can you check `make verify`?

**Comment by rfranzke** [comment]
@ialidzhikov done

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
