### PR TITLE
Add configuration to expose network extension metrics / dashboards

### PR DESCRIPTION
**Pull request by zanetworker**
**How to categorize this PR?**

/area monitoring
/area networking
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PR adds `monitoringConfig` to the `spec.networking` in the shoot. This is to expose charts and configure Prometheus to fetch monitoring specific metrics. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
related to https://github.com/gardener/gardener-extension-networking-calico/pull/45 

**Release note**:

```improvement operator
Network monitoring dashboards for network extensions can now be enabled and configured. 
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Why do we hard-code calico-specific things into g/g?

**Comment by rfranzke** [comment]
Is https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#monitoring not flexible enough? If yes, why? I guess we should then rather improve the contract.

**Comment by zanetworker** [comment]
> Why do we hard-code calico-specific things into g/g?

where are the calico specific things :)? this is to enable monotring for networking. This is respecting the extension contract still.

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/2712#diff-b8d9b2efb9ea9963b32ff225084bc196R625 e.g.

**Comment by zanetworker** [comment]
> Is https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#monitoring not flexible enough? If yes, why? I guess we should then rather improve the contract.

Currently we don't have monitoring for extensions at all, we don't do that ourselves (expose metrics for the extensions we implement), or the things they deploy. If you have suggestions on how to improve I am more than happy to discuss.

**Comment by zanetworker** [comment]
I have discussed with @rfranzke, and I was not aware of https://github.com/gardener/gardener/pull/1466. This should decouple things a bit, so I will try this out and modify this PR accordingly.

**Comment by rfranzke** [comment]
Thanks, looking forward!

**Comment by zanetworker** [comment]
Closing in favor of https://github.com/gardener/gardener-extension-networking-calico/pull/45.

**Pull request closed without merging**
