### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by majst01**
**How to categorize this PR?**

/area documentation
/kind cleanup

**What this PR does / why we need it**:

Let [typos](https://github.com/crate-ci/typos) scan the codebase, fix all of them.

With a proper `_typos.toml`, this check can even be performed in the CI.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
> Let [typos](https://github.com/crate-ci/typos) scan the codebase, fix all of them.
> 
> With a proper `_typos.toml`, this check can even be performed in the CI.

What about integrating this tool into our `make check` rule?

**Comment by marc1404** [comment]
ℹ️ @majst01 The typo fixes require `make generate` to be run :)

**Comment by majst01** [comment]
> ℹ️ @majst01 The typo fixes require `make generate` to be run :)

Thanks, should be fixed now

**Review by ScheererJ — COMMENTED** [review]
Thanks for fixing a few typos ;-) .

Do you mind sharing how you performed the check or even better as @rfranzke add it to the automation?

/lgtm

**Comment by majst01** [comment]
> Thanks for fixing a few typos ;-) .
> 
> Do you mind sharing how you performed the check or even better as @rfranzke add it to the automation?
> 
> /lgtm

I simply executed the `typos` binary locally which can be downloaded from here: https://github.com/crate-ci/typos

This produces a lot of false positives, which can be disabled by creating a `_typos.toml` configuration in this repository. But this is the hard work to make it pass.

I would try to create one as a followup and add it to `make check` as @rfranzke suggested.

**Review by marc1404 — APPROVED** [review]
Thanks for going after the typos! 🙇 
Let's get this merged so that it'll be easier to create the `_typos.toml` next.
Looking forward to the follow-up! 👀 

/approve

**Pull request merged**
