### PR TITLE
Remove Go Module for forked code

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area open-source
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR removes the Go Module of the forked K8s sources in `third_party/forked/kubernetes` because it caused vendor issues in repositories depending on Gardener (https://github.com/gardener/gardener/pull/2627#issuecomment-716804575).

**Special notes for your reviewer**:
/cc @timebertt @rfranzke 

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]

**Review by timebertt — DISMISSED** [review]
Thanks, @timuthy!
Vendoring is fixed :)
/lgtm

**Comment by timebertt** [comment]
@timuthy 
Can you check the build failure?
```
> Install
pkg/apiserver/admission/initializer/initializer.go:22:2: cannot find package "." in:
	/go/src/github.com/gardener/gardener/third_party/forked/kubernetes/pkg/quota/v1
cmd/gardener-apiserver/app/gardener_apiserver.go:54:2: cannot find package "." in:
	/go/src/github.com/gardener/gardener/third_party/forked/kubernetes/pkg/quota/v1/generic
cmd/gardener-apiserver/app/gardener_apiserver.go:55:2: cannot find package "." in:
	/go/src/github.com/gardener/gardener/third_party/forked/kubernetes/plugin/pkg/admission/resourcequota
make: *** [Makefile:100: install] Error 1
```

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
Thanks!
/lgtm

**Pull request merged**
