### PR TITLE
Fix bugs in CPM introduced by latest refactorings

### LINKED ISSUE #4180: CPM Is failing on step "Deleting all extension CRs from the Shoot namespace"
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
Control Plane Migration fails with the following error:
```
Flow "Shoot's control plane preparation for migration" encountered task errors: [task "Deleting all extension CRs from the Shoot namespace" failed: 5 errors occurred:
	* resource name may not be empty
	* resource name may not be empty
	* resource name may not be empty
	* resource name may not be empty
	* resource name may not be empty
] Operation will be retried.
```

With the current changes on the master branch the object that is passed to the [DeleteExtensionObject()](https://github.com/gardener/gardener/blob/080adaec429c75d7525b45b6d48d6f8d774355f4/pkg/extensions/customresources.go#L158) function contains almost no data. Example:
```
&{{ } {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[confirmation.gardener.cloud/deletion:true gardener.cloud/timestamp:2021-06-07 14:01:18.207702 +0000 UTC] [] []  []} {{ nil}  { } []} {{nil [] nil nil 0 nil []} <nil>}
```
This cause the function [ConfirmDeletion()](https://github.com/gardener/gardener/blob/080adaec429c75d7525b45b6d48d6f8d774355f4/pkg/utils/gardener/deletion_confirmation.go#L58) to return error `resource name may not be empty`

This happens in the following components when the `Destory()` function is called:
```
1. /gardener/gardener/pkg/operation/botanist/component/extensions/infrastructure/infrastructure.go:181
1. /gardener/gardener/pkg/operation/botanist/component/extensions/worker/worker.go:269
1. /gardener/gardener/pkg/operation/botanist/component/extensions/network/network.go:140
1. /gardener/gardener/pkg/operation/botanist/component/extensions/controlplane/controlplane.go:177
```
**What you expected to happen**:
The control plane migration should finish successfully. 
**How to reproduce it (as minimally and precisely as possible)**:
Run CPM as described [here](https://github.com/gardener/gardener/blob/080adaec429c75d7525b45b6d48d6f8d774355f4/docs/usage/control_plane_migration.md) The issue is reproducible every time.
**Anything else we need to know?**:

**Environment**:

- Gardener version: tested with 1.25.0-dev, but should be reproducible with 1.24.0 as well
- Kubernetes version (use `kubectl version`): tested with 1.19.2 and 1.20.6 but should be irrelevant
- Cloud provider or hardware configuration: tested with GCP and AWS
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/kind bug

**What this PR does / why we need it**:

This PR fixes three bugs in the Control Plane Migration flow introduced by latests refactorings:

- Don't reset ObjectKey in `extensions.WaitUntil*` funcs. Callers might want to reuse the passed in object afterwards, even if it was not found. Thus, we have to ensure, that the ObjectKey is not reset in the helper funcs (described in #4180, introduced by #4027)
- Return faster when waiting for `DNS{Provider,Entry}` (behavior was changed in #4161, brings back old behavior) to detect the `Invalid` state of `DNSEntries` faster when restoring them. The behavioral change added an extra ~minute to the restoration flow, because it waited longer until the overall timeout has elapsed (cc @timuthy).
- Fix detecting the `Invalid` state of `DNSEntries` when restoring them (error message was changed in #4161, which broke the string matching)

You can find more details in the respective commit messages.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/4180

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by timebertt** [comment]
/hold
There is another bug, that prevents the restoration to succeed because the error message in the DNS entry component was changed in https://github.com/gardener/gardener/pull/4141.
That's why [this check here](https://github.com/gardener/gardener/blob/2c003f3d8590e05f38969f572fe8442fffba7d44/pkg/operation/botanist/dns.go#L455) can't catch the `Invalid` state because of missing `DNSOwner` anymore.

**Comment by timebertt** [comment]
/unhold

Added more commits to fix the other problems, I discovered. See PR description and commit messages.
With this, I was now able to migrate a Shoot multiple times without issues anymore in my local setup.

/cc @rfranzke

**Review by timuthy — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm

Tested successfully on a development landscape

**Pull request merged**
