### PR TITLE
Upgrade grafana to 7.0.3 and update dashboards

### PR DESCRIPTION
**Pull request by wyb1**
**How to categorize this PR?**

/area monitoring
/kind enhancement
/kind cleanup
/priority normal

**What this PR does / why we need it**:
Upgraded grafana to the newest version to prevent grafana [vulnerability](https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/). Some dashboards were also updated.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Upgrade grafana to `7.0.3`
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by dkistner — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
