### PR TITLE
[ci:component:github.com/gardener/alpine-iptables:3.15.4->3.16.0]

### PR DESCRIPTION
**Pull request by ghost**
**How to categorize this PR?**

/area TODO
/kind TODO

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Comment by oliver-goetz** [comment]
Shouldn't the alpine-iptables image be tagged with `3.16.2` because it is based on this alpine version?

**Comment by ScheererJ** [comment]
> Shouldn't the alpine-iptables image be tagged with `3.16.2` because it is based on this alpine version?

The version is bound to diverge, but if you prefer I can create two hotfixes so that it is in line again.

@oliver-goetz Is this what you want?

**Comment by oliver-goetz** [comment]
I checked the previous release and there the versions have been in line, so I thought this might have been a typo.

**Comment by ScheererJ** [comment]
No typo, but just the first release of the 3.16 code line. As mentioned, it is possible to move to 3.16.2. I saw it only as a minor benefit to have a somewhat similar version, but if you insist I can update the alpine-iptables version to 3.16.2 to be in line with the alpine version.

**Comment by oliver-goetz** [comment]
That would be nice 😄

**Comment by ScheererJ** [comment]
Closed in favour of https://github.com/gardener/gardener/pull/6713.
/close

**Pull request closed without merging**
