### PR TITLE
Support for Kubernetes v1.16

### LINKED ISSUE #1376: Support new API resources in core.gardener.cloud/v1alpha1 group
Part of #308.

As we have proposed in [GEP-1](https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md) and [GEP-4](https://github.com/gardener/gardener/blob/master/docs/proposals/04-new-core-gardener-cloud-apis.md) we want to new API resources in the `core.gardener.cloud/v1alpha1` group.

# Definition of Done

- **Backwards-compatible resource migrations (+ example manifest in `example/` directory)**
  - [x] New `core.gardener.cloud/v1alpha1.Seed` resource [#1308, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.SecretBinding` resource [#1377, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.Quota` resource [#1377, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.Project` resource [#1382, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.CloudProfile` resource [#1403, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.Shoot` resource [#1430, ✅]

- **Code adaptations**
  - [x] The admission plugins inside `gardener-apiserver` have been adapted to work with potential changes in the internal versions of the resources. [*implicitly done by the above PRs*, ✅]
  - [x] The `gardener-controller-manager` has been adapted to work with `core.gardener.cloud/v1alpha1` [#1453, ✅]
  - [x] The `gardener-scheduler` has been adapted to work with `core.gardener.cloud/v1alpha1` [#1435, ✅].
  - [x] The extensions need to work with `core.gardener.cloud/v1alpha1` [gardener/gardener-extensions#319, ✅].
  - [ ] The integration tests and test definitions have been adapted to work with `core.gardener.cloud/v1alpha1`.

### LINKED ISSUE #1434: Support for Kubernetes v1.16
Ref to the Changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
Support for Kubernetes v1.16

**Which issue(s) this PR fixes**:
Fixes #1434 

**Special notes for your reviewer**:
I didn't vendor the `kubernetes-1.16` sources yet because the controller-runtime is still using `kubenretes-1.14`.

⚠️ Also, using 1.16 requires a newer version of the provider extensions (not yet released, you can use `0.13.0-dev3-kubernetes-1.16` tag for testing, if you want.)

I have successfully validated the functionality for all cloud providers and all older versions:
- :white_check_mark: Create new clusters with versions < 1.16
- :white_check_mark: Create new clusters with version  = 1.16
- :white_check_mark: Upgrade old clusters from version 1.15 to version 1.16
- :white_check_mark: Delete clusters with versions < 1.16
- :white_check_mark: Delete clusters with version  = 1.16

**Release note**:

```action operator
In order to support Kubernetes 1.16 you must use at least v[`0.13.0`](https://github.com/gardener/gardener-extensions/releases/tag/0.13.0) of the provider extension controllers.
```
```noteworthy user
Gardener does now support shoot clusters with Kubernetes version 1.16. You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md) before upgrading to 1.16.
```
```noteworthy user
The CoreDNS version for all shoots has been upgraded from `1.4.0` to `1.6.3`.
```
```action user
As the Kubernetes community is in the process of deprecating basic authentication for the kube-apiserver newly created 1.16 shoot clusters don't enable it by default anymore. Similarly, the default authentication mode for the `kubernetes-dashboard` addon is `token` instead of `basic`. You can still enable it manually, but you should consider migrating away from it. We will drop basic authentication support in a future release when Kubernetes doesn't support it anymore.
```

### CODE REVIEW

**Comment by zanetworker** [comment]
where is `--maximum-startup-sequence-duration` set to 2m?

**Comment by rfranzke** [comment]
Nowhere, this flag was renamed to `--livez-grace-period` and appeared (with a wrong name) in the Kubernetes release notes. I'll fix the commit msg after rebasing.

**Review by zanetworker — DISMISSED** [review]

**Comment by timuthy** [comment]
Is there any reason you haven't implemented the basic authentication defaulting for `core.gardener.cloud/v1alpha1`?

**Comment by rfranzke** [comment]
No, the PR was opened before #1430 was merged. Will rebase and do.

**Review by timuthy — APPROVED** [review]
/lgtm

**Pull request merged**
