### PR TITLE
Upgrade gardener/autoscaler for k8s 1.22

### PR DESCRIPTION
**Pull request by rishabh-11**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Updates the CA image in the charts for v1.22.3

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following image is updated:
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler`: `v1.22.2` -> `v1.22.3` (for Kubernetes `1.22`)
```

### CODE REVIEW

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
Don't you plan to cut new patch releases for 1.21 and 1.20? Why only 1.22 has a new patch release (containing base image change)?

**Comment by rishabh-11** [comment]
> Don't you plan to cut new patch releases for 1.21 and 1.20? Why only 1.22 has a new patch release (containing base image change)?

The canary seeds run on K8S 1.23 and live on 1.22, so we decided to do it only for 1.22, not 1.21 and 1.20. 
cc @ashwani2k

**Comment by ialidzhikov** [comment]
> The canary seeds run on K8S 1.23 and live on 1.22, so we decided to do it only for 1.22, not 1.21 and 1.20.

Gardener supports Seed clusters with K8s >= 1.20 - ref https://github.com/gardener/gardener/blob/v1.52.1/docs/usage/supported_k8s_versions.md. IMO, it is not okay to do it only for CA 1.22 just because we internally use a concrete version in our environment. If it is not a major effort can I ask you do consider doing the change for CA 1.21 and 1.20? Thanks in advance!

**Comment by rishabh-11** [comment]
> > The canary seeds run on K8S 1.23 and live on 1.22, so we decided to do it only for 1.22, not 1.21 and 1.20.
> 
> Gardener supports Seed clusters with K8s >= 1.20 - ref https://github.com/gardener/gardener/blob/v1.52.1/docs/usage/supported_k8s_versions.md. IMO, it is not okay to do it only for CA 1.22 just because we internally use a concrete version in our environment. If it is not a major effort can I ask you do consider doing the change for CA 1.21 and 1.20? Thanks in advance!

Ok, I understand. I'll update here once it is done.

**Comment by ashwani2k** [comment]
My bad @ialidzhikov, I didn't think it through, as I didn't look into supported usage. I just considered current usage and thought 1.22 / 1.23 should suffice. 
@rishabh-11  and I agree we will make it for 1.21/1.20 as well.

**Comment by rishabh-11** [comment]
I'll raise a new PR with the change, sorry for the error in this one.

**Comment by rishabh-11** [comment]
Opened this PR. [https://github.com/gardener/gardener/pull/6449](url)

**Pull request closed without merging**
