### PR TITLE
Change Alicloud EIP type PayByTraffic

### PR DESCRIPTION
**Pull request by jia-jerry**
**What this PR does / why we need it**:
Change Alicloud EIP type PayByTraffic. It will save a lot of money. Origin setup was charged more than 1/2 of VM instances!!!
 
```improvement user
Gardener does now create Alicloud EIPs with `PayByTraffic` policy for new clusters to save costs.
```

### CODE REVIEW

**Review by rfranzke — CHANGES_REQUESTED** [review]
As discussed via Slack: It won't work that way. You can only do that for new shoots. Check in the Alicloud Botanist whether the Terraform config already exists (if yes, then preserve old logic (`PayByBandWidth`). Otherwise, go ahead with `PayByTraffic`.

**Comment by rfranzke** [comment]
/cc @adracus 

This should be taken over into the Alicloud extension infrastructure controller ⚠️

**Comment by jia-jerry** [comment]
> As discussed via Slack: It won't work that way. You can only do that for new shoots. Check in the Alicloud Botanist whether the Terraform config already exists (if yes, then preserve old logic (`PayByBandWidth`). Otherwise, go ahead with `PayByTraffic`.

Hi @rfranzke , Now we will keep old pay type for exsiting shoot. The new shoot will use PayByTraffic.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
