### PR TITLE
PVC migration: Remove `.spec.claimRef` only after new PVC got created

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area storage monitoring
/kind bug

**What this PR does / why we need it**:
With the old algorithm for the PVC migration, we have
- deleted the old PVC
- removed `.spec.claimRef` from the PV (this set the PV status to `Available`)
- wait until PV is `Available`
- create the new PVC (with `.spec.volumeName=<pv-name>`)
- this binds the PV to the new PVC.

Unfortunately, until the new PVC is created, there is a time window when the PV is "available to be claimed by any matching PVC" (even PVCs that are not related to it). Concretely, we have seen `etcd-events` of unrelated shoot namespaces to claim Prometheus PVs in migration.

This behaviour is intentional in Kubernetes. From https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding:

> A control loop in the control plane watches for new PVCs, finds a matching PV (if possible), and binds them together.
> [...]
> Otherwise, the user will always get at least what they asked for, but the volume may be in excess of what was requested.
> [...]
> Claims will be bound as matching volumes become available. For example, a cluster provisioned with many 50Gi PVs would not match a PVC requesting 100Gi. The PVC can be bound when a 100Gi PV is added to the cluster.

This PR adapts the algorithm to

- delete the old PVC
- wait until PV is `Released` (important: not `Available`, i.e., PV controller does not consider it for any PVCs) since `.spec.claimRef` is still set.
- create the new PVC (with `.spec.volumeName=<pv-name>`)
- this cannot bind the PV to the new PVC yet since it still references the old PVC in `.spec.claimRef`.
- removed `.spec.claimRef` from the PV (this set the PV status to `Available`)
- wait until new PVC gets bound to the PV

This way, the race condition can be avoided, ensuring that only the expected PVCs can claim the respective PVs.

**Which issue(s) this PR fixes**:
Related to https://github.com/gardener/gardener/issues/9065

**Special notes for your reviewer**:
/cc @ialidzhikov 

**Release note**:

```bugfix operator
A race condition has been fixed which could cause unrelated `Pod`s to claim the `PersistentVolume` of a Prometheus or Alertmanager deployment during migration to the management of `prometheus-operator`.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
FYI @acumino

**Review by ScheererJ — COMMENTED** [review]
Thanks for the fix. Looks good overall.

Does this really remove the race condition or just reduces the probability as it shortens the timeframe when the persistent volume is unbound? Could the persistent volume not still be bound to another claim if the claim was created just before the new observability claim?

**Comment by rfranzke** [comment]
> Does this really remove the race condition or just reduces the probability as it shortens the timeframe when the persistent volume is unbound? Could the persistent volume not still be bound to another claim if the claim was created just before the new observability claim?

Not sure, the only scenario where the PV could be bound to a PVC different from the new PVC for Prometheus is if this other PVC also sets `.spec.volumeName=<pv-name>`. Then there are two PVCs (this other one, and the new PVC for Prometheus) with `.spec.volumeName=<pv-name>`. Not sure what happens then, but assuming only one can "win", this other different PVC could. However, this is a quite artificial case (there will be no other PVC with this `.spec.volumeName` field set). Hence, I think the race condition is fully avoided now.

**Pull request merged**
