### PR TITLE
Clean up Grafana Unification helper functions

### PR DESCRIPTION
**Pull request by rickardsjp**
**How to categorize this PR?**

/area monitoring
/kind cleanup

**What this PR does / why we need it**:
For the Grafana Unification PR (#7007) we required some logic to handle the transition from two Grafana deployments (operators and users) to a single, unified Grafana instance. This PR removes that transition logic, which had to be executed only once for a shoot cluster's transition from Gardener v1.63 to v1.64. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @istvanballok, @rfranzke 
We assume that Gardener upgrades do not skip versions. However, this still might be problematic because a shoot that was hibernated for long enough (i.e. hibernated on v1.63, and then woken up in the release that this change makes it into), would be leaking resources: The new unified Grafana deployment would be created and the health check would succeed, but the two pre-unification Grafana deployments would not be deleted and would continue to use resources. Or are long-term hibernated clusters also woken up for reconciliation automatically? We checked the Gardener version of old, hibernated shoots and those seemed to be updated.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by istvanballok — COMMENTED** [review]
/lgtm

**Comment by istvanballok** [comment]
> a shoot that was hibernated for long enough...

I could confirm by checking the control planes of some long-term hibernated clusters that the Grafana migration was indeed executed during the reconciliation to Gardener v1.64.0. So it seems to be safe to remove the migration specific functions.

@rickardsjp:
> pull-gardener-unit — Job failed.
```
make generate needs to be run:
M pkg/operation/common/utils.go
```

>  pull-gardener-apidiff — Job failed.

is expected, `DeploymentNameGrafanaOperators` and `DeploymentNameGrafanaUsers` are removed

**Review by istvanballok — APPROVED** [review]
/lgtm

**Review by istvanballok — APPROVED** [review]
/lgtm

**Review by acumino — COMMENTED** [review]
/approve

**Pull request merged**
