### PR TITLE
Adapt monitoring to new certificate files

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area monitoring
/kind bug

**What this PR does / why we need it**:
Adapt monitoring to new certificate files.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator

```

/cc @wyb1

### CODE REVIEW

**Review by wyb1 — APPROVED** [review]

**Comment by rfranzke** [comment]
For backwards-compatibility, I think we should rather map the `bundle.crt` key to the `ca.crt` file in https://github.com/gardener/gardener/blob/a1b5eb6b2fb011857a7f9a8f35fb5cc872b07bd3/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml#L217-L219 via a projected volume.

**Comment by rfranzke** [comment]
Actually, we probably should map it to both `ca.crt` and `bundle.crt` by specifying two `items` in the `projected` volume (is this possible)?

**Comment by ScheererJ** [comment]
@rfranzke Ok, I will try it.

**Comment by ScheererJ** [comment]
@rfranzke It worked and the change just got significantly smaller :-) .

**Review by rfranzke — COMMENTED** [review]
Awesome!
This looks great, thanks!

/lgtm
/approve

**Comment by rfranzke** [comment]
cc @ialidzhikov for milestone

**Pull request merged**
