### PR TITLE
fixing scheduler minimal distance

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**What this PR does / why we need it**:

The Minimal distance Scheduler Strategy contains problems
- Seed Selector needs to be executed before the Strategy to filter the list of possible seed candidates
- Minimal Distance Strategy had a bug leading to wrong scheduling decisions, when the shoot specified region is shorter than the seed regions

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Scheduler: Fixing MinimalDistance Strategy to correctly apply the seed selector from the CloudProfile and fixing a bug in the distance logic
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Could you please add a description about why we need this PR?

**Comment by danielfoehrKn** [comment]
> Could you please add a description about why we need this PR?

Was still in the process of writing it - opened it too early :)

**Comment by rfranzke** [comment]
Thanks for the PR! It looks good, I like the dedicated functions - it's way better readable now. I'll give it a try tomorrow and come back. 💯

**Review by rfranzke — APPROVED** [review]
/lgtm, works perfectly!

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
