### PR TITLE
Upgrade envoy image to distroless 1.18.3

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Envoy used apiserver-proxy and sidecar are upgraded to distroless `1.18.3` version.
```

### CODE REVIEW

**Comment by timebertt** [comment]
```
>> make generate
make generate needs to be run:
 D landscaper/pkg/gardenlet/apis/imports/v1alpha1/zz_generated.deepcopy.go
 D landscaper/pkg/gardenlet/apis/imports/v1alpha1/zz_generated.defaults.go
```

**Comment by mvladev** [comment]
> ```
> >> make generate
> make generate needs to be run:
>  D landscaper/pkg/gardenlet/apis/imports/v1alpha1/zz_generated.deepcopy.go
>  D landscaper/pkg/gardenlet/apis/imports/v1alpha1/zz_generated.defaults.go
> ```

How's that related to my PR?

**Comment by vpnachev** [comment]
I guess landscaper is building something on top of the charts.

**Comment by mvladev** [comment]
> I guess landscaper is building something on top of the charts.

This is not the case. For example https://github.com/gardener/gardener/pull/4301 had exact same changes but the build was successful. Something must be broken in the CI/CD

**Comment by mvladev** [comment]
Okay the build is passing. Can you have another look?

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
