### PR TITLE
Move `vpa-exporter` monitoring config into component package

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
Move `vpa-exporter` monitoring config into component package.

**Which issue(s) this PR fixes**:
Part of #2754
Left-over of #5745 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by vlvasilev — COMMENTED** [review]
/uncc

**Review by timebertt — COMMENTED** [review]
/approve

**Pull request merged**
