### PR TITLE
make push :latest configurable

### PR DESCRIPTION
**Pull request by adracus**
**What this PR does / why we need it**:
make push :latest configurable

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
Thank you!

**Comment by bergerx** [comment]
Does this mean we now have a latest tag for the gardener (https://github.com/gardener/gardener/pull/198#issuecomment-395775255)?

Will the draft (https://github.com/gardener/gardener/pull/309) releases pushed with the latest tag?

**Comment by rfranzke** [comment]
Yes, because of that: https://github.com/gardener/gardener/blob/master/.ci/pipeline_definitions#L17-L23. However, I recommend to only use actual releases for non-dev scenarios.

What do you mean regarding the draft release notes? Can you explain again?

**Comment by bergerx** [comment]
From @rfranzke:
> What do you mean regarding the draft release notes? Can you explain again?

I thought draft releases could also be tagging with latest, but reading the `.ci/pipeline_definitions` I saw that's not the case.

**Comment by vlerenc** [comment]
The draft release notes are giving an overview about the features that were merged since the last release and do not refer to "a" `latest` release. We basically use a similar means like Kubernetes itself to get to release notes by scanning for certain formalised release note comments in the PRs.

Independent of that, we could use `tag_as_latest: True` in the pipeline definition to tag the latest (built) image as `latest`.

**Pull request merged**
