### PR TITLE
[ci:component:github.com/gardener/dependency-watchdog:v0.5.0->v0.6.0]

### LINKED ISSUE #2833: kube-controller-manager is often not scaled down on hibernation
**How to categorize this issue?**

/area dev-productivity ops-productivity
/kind bug
/priority normal

**What happened**:
kube-controller-manager is often not scaled on hibernation. There might be something wrong with `Scale` on upstream side or dependency-watchdog can scale up kube-controller-manager again.

**What you expected to happen**:
kube-controller-manager to be scaled down.

**How to reproduce it (as minimally and precisely as possible)**:
1. Hibernate a Shoot

2. Ensure that kube-controller-manager is not scaled down

```
$ k -n shoot--foo--bar get po
NAME                                       READY   STATUS             RESTARTS   AGE
kube-controller-manager-85489f686b-sgt4c   0/1     CrashLoopBackOff   5          4m6s

$ k -n shoot--foo--bar get deploy
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
aws-lb-readvertiser          0/0     0            0           45h
cloud-controller-manager     0/0     0            0           45h
gardener-resource-manager    0/0     0            0           45h
kube-apiserver               0/0     0            0           45h
kube-controller-manager      0/1     1            0           45h
kube-scheduler               0/0     0            0           45h
machine-controller-manager   0/0     0            0           45h
```

```
$ k -n garden-foo get shoot bar -o jsonpath='{.status.hibernated}'
true
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.10
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by gardener-robot-ci-2**
*Release Notes*:
``` improvement operator github.com/gardener/dependency-watchdog #24 @amshuman-kr
Improve logging while scaling.
```

``` improvement operator github.com/gardener/dependency-watchdog #23 @ggaurav10
Probe is stopped for clusters that are hibernating, or in hibernation or are still waking up from hibernation
```

Fixes #2833

### CODE REVIEW

**Comment by amshuman-kr** [comment]
close I will raise a separate PR to include a necessary RBAC change in the chart.

**Comment by vpnachev** [comment]
@amshuman-kr do not worry, I have pushed the required RBAC change to this PR.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by amshuman-kr — COMMENTED** [review]
/lgtm

**Pull request merged**
