### PR TITLE
Vendor kubernetes-1.16.0

### LINKED ISSUE #1556: Update k8s.io/client-go version
As I was implementing #1552 I discovered, that we are currently using the outdated version `k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a`, which has no support for the new `events.k8s.io` API (see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/events-redesign.md)

k8s.io/client-go version v12.0.0 is the one used in k8s 1.15 and includes support for the new events API, which has better deduplication logic to not impact cluster performance in the case of many similar events.

Can we upgrade to the latest version of client-go?

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Vendor kubernetes-1.16.0.

**Which issue(s) this PR fixes**:
Fixes #1556 
Ref gardener/gardener#1206

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Kubernetes dependencies are updated to `kubernetes-1.16.0`.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm, very nice PR, thank you very much!!!

**Comment by ialidzhikov** [comment]
I found an issue with the admission plugins. Let me check it.

/hold

**Review by rfranzke — APPROVED** [review]
Thanks @ialidzhikov for checking and driving the fix.

**Comment by vpnachev** [comment]
you can also check
* https://github.com/kubernetes/apimachinery/releases/tag/v0.16.4
* https://github.com/kubernetes/client-go/releases/tag/v0.16.4

they are using now go-mod friendly version name( `v` prefix).

**Comment by ialidzhikov** [comment]
I opened kubernetes-sigs/controller-runtime#732 but there are some test failures. So I would suggest for now to use the same versions used by controller-runtime@v0.4.0.

**Pull request merged**
