### PR TITLE
Improve prevention of removing the gardener finalizer on Shoots

### PR DESCRIPTION
**Pull request by timebertt**
**What this PR does / why we need it**:
The Shoot admission plugin now only allows removing the gardener finalizer when the Shoot deletion has completed successfully. It therefore checks `Shoot.status.lastOperation` instead of checking if the Shoot namespace in the Seed still exists.
This is done to remove communication from the Garden cluster to the Seed cluster (prerequisite for #1601)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```improvement operator
`gardener-apiserver` now prevents the removal of the `gardener` finalizer for existing shoots if the shoot deletion has not yet finished successfully.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm, nice PR!

**Review by timuthy — COMMENTED** [review]
I think you can also remove the `RuntimeClientFactory` interface and implementation since it's not used any more.

**Comment by timebertt** [comment]
Indeed. I removed the `RuntimeClientFactory` and all related code.
PTAL

**Review by rfranzke — DISMISSED** [review]

**Review by timuthy — DISMISSED** [review]

**Comment by timuthy** [comment]
@tim-ebert can you resolve the conflicts?

**Comment by timebertt** [comment]
Sure, done :)
Should be good now

**Review by timuthy — APPROVED** [review]

**Pull request merged**
