### PR TITLE
Increase the readiness probe timeout for the `gardener-metrics-exporter`

### PR DESCRIPTION
**Pull request by vicwicker**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

The performance of the `/metrics` endpoint from the `gardener-metrics-exporter` depends on the number of metrics that need to be exported. The higher the number of shoots and metrics to be generated, the longer it takes to respond. In consequence, the default probe timeout of 1 second is not enough when using this endpoint for the readiness probe.

**Special notes for your reviewer**:

/cc @rickardsjp @istvanballok @hendrikKahl 

**Release note**:

```other operator
Increase the readiness probe timeout for the `gardener-metrics-exporter` from 1s to 10s.
```

### CODE REVIEW

**Review by istvanballok — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
