### PR TITLE
Classify missing CloudNAT IPs as configuration error

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area ops-productivity
/area quality
/kind enhancement

**What this PR does / why we need it**:
If a user adds names of nonexisting nat IPs in the `shoot.spec.provider.infrastructureConfig.networks.cloudNAT.natIPNames` field for a GCP shoot the following error will appear:
```
 * Null value found in list
on tf/main.tf line 42, in resource "google_compute_router_nat" "nat":
42:   nat_ips                = [data.google_compute_address.<address_name>.self_link]
Null values are not allowed for this attribute value. 
```
This PR classifies the error as a configuration error.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Error from terraform indicating nonexistent GCP CloudNAT IPs that can appear if a user has specified CloudNAT settings in the Shoot spec, is now classified as a configuration error.
```

### CODE REVIEW

**Review by timuthy — COMMENTED** [review]
I'm wondering if the message you posted contains newlines. Because with that the regex does not match. Can you double check?

**Comment by plkokanov** [comment]
@timuthy yeah it does contain new lines, for some reason the `s` flag didn't get added in the PR. I can add it and update the PR.

**Comment by ialidzhikov** [comment]
I guess the better option would be to add a prerequisite check to the Infrastructure reconciliation for provider-gcp whether the corresponding resource exists. We have similar prerequisite checks on Infrastructure reconciliation for provider-aws that check - whether the manually created VPC has the required attributes set; whether the manually created VPC has an internet gatewat attached.

**Comment by ialidzhikov** [comment]
I created https://github.com/gardener/gardener-extension-provider-gcp/issues/309. Let's close this PR in favour of https://github.com/gardener/gardener-extension-provider-gcp/issues/309.

/close

**Pull request closed without merging**
