### PR TITLE
Switched from DockerHub to Gardener GCR

### PR DESCRIPTION
**Pull request by robinschneider**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
This PR is needed to support IPv6 single stack and avoid DockerHub pull limits as it uses copied images from Gardener GCR instead.
Part of https://github.com/gardener/ci-infra/issues/619
Part of https://github.com/gardener/gardener/issues/7051

**Release note**:

```other operator
Switched images from DockerHub to copies in Gardener GCR
```

### CODE REVIEW

**Review by timebertt — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
The upgrade tests fail expectedly these days.

**Pull request merged**
