### PR TITLE
Add pctp vulnerability test

### PR DESCRIPTION
**Pull request by schrodit**
**What this PR does / why we need it**:
This PR adds an integration test for the pctp vulnerability.

**Special notes for your reviewer**:
@marwinski 

**Release note**:

```improvement user
Add integration test for pctp vulnerability
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

Can this be merged or do we have to wait for something?

**Comment by marwinski** [comment]
Please merge - we want to see it fail. The code change for the fix is ready and tested - just need to port it to the alicloud coreos controller.

**Comment by rfranzke** [comment]
As discussed with @schrodit and @dguendisch we don't merge it yet. Please reopen the PR once the fix actually has been arrived and released.

**Comment by dguendisch** [comment]
We can test manually, but for sure we don't want to have failing shoot app tests if this test is merged and the pctp fix is not, hence: not to be merged yet

**Comment by marwinski** [comment]
ok, understand. Can you test manually - should fail.

**Comment by schrodit** [comment]
@marwinski Already tested manually. The test fails for shoots on dev.

**Pull request closed without merging**
