### PR TITLE
Create alert for certificate expiration date

### PR DESCRIPTION
**Pull request by cathyzhang05**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Create alert for certificate when the expiration date is closed. 

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
/ok-to-test
/cc @istvanballok @rickardsjp 
@cathyzhang05 Can you please add a release note?

**Review by timuthy — COMMENTED** [review]
I wonder if this approach is appropriate for multiple reasons:
- It is strongly related to the ingress hostName of Prometheus.
- In a productive setup, all Ingresses usually share the same wildcard certificate (more [info](https://github.com/gardener/gardener/blob/4b9e0f456023c5c9acbf891f4fd24e8624e37bdf/docs/usage/trusted-tls-for-control-planes.md)). If such a certificate is about to expire, many alerts will be triggered for the same underlying problem.
- Other certificates are not covered.

Ideally, such an alerting is contributed by the Certificate Service Extension (see [here](https://github.com/gardener/gardener-extension-shoot-cert-service/blob/master/charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml)).
WDYT @MartinWeindel?

**Comment by MartinWeindel** [comment]
> Ideally, such an alerting is contributed by the Certificate Service Extension (see [here](https://github.com/gardener/gardener-extension-shoot-cert-service/blob/master/charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml)). WDYT @MartinWeindel?

I agree, an alerting on the level of the shoot-cert-service would cover also certificates created by our users.
The corresponding metric would be `cert_management_overdue_renewal_certificates` of the cert-management, see [here](https://github.com/gardener/cert-management#metrics).

**Comment by cathyzhang05** [comment]
> > Ideally, such an alerting is contributed by the Certificate Service Extension (see [here](https://github.com/gardener/gardener-extension-shoot-cert-service/blob/master/charts/internal/shoot-cert-management-seed/templates/configmap-observability.yaml)). WDYT @MartinWeindel?
> 
> I agree, an alerting on the level of the shoot-cert-service would cover also certificates created by our users. The corresponding metric would be `cert_management_overdue_renewal_certificates` of the cert-management, see [here](https://github.com/gardener/cert-management#metrics).

Hi @MartinWeindel ,
I considered using the metrics from cert-manager, but these metrics could be used to define an alert when a certificate expired or is about to expire soon.

**Comment by MartinWeindel** [comment]
> Hi @MartinWeindel ,
> I considered using the metrics from cert-manager, but these metrics could be used to define an alert when a certificate expired or is about to expire soon.

@cathyzhang05 
If you think, it is useful I don't want to stop you. I just wanted to make the point, that checking for certificates whose renewals are overdue may be preferable, as you get the alerting about 30 days before the certificate is actual expiring.

**Comment by timuthy** [comment]
@cathyzhang05 
> I considered using the metrics from cert-manager, but these metrics could be used to define an alert when a certificate expired or is about to expire soon.

Do you have any use case in mind where this is particularly important and where the metrics/alerts from cert-manager won't help? At the moment I have the impression that the alert configuration would be redundant.

**Comment by cathyzhang05** [comment]
> @cathyzhang05
> 
> > I considered using the metrics from cert-manager, but these metrics could be used to define an alert when a certificate expired or is about to expire soon.
> 
> Do you have any use case in mind where this is particularly important and where the metrics/alerts from cert-manager won't help? At the moment I have the impression that the alert configuration would be redundant.

Hi @timuthy ,
The metric/alert such as cert_management_overdue_renewal_certificates is only returned the number of the overdue certificates instead of the instance or expiration date.

**Comment by timuthy** [comment]
> The metric/alert such as cert_management_overdue_renewal_certificates is only returned the number of the overdue certificates instead of the instance or expiration date.

How about enhancing the metrics? 😃

**Comment by cathyzhang05** [comment]
> > The metric/alert such as cert_management_overdue_renewal_certificates is only returned the number of the overdue certificates instead of the instance or expiration date.
> 
> How about enhancing the metrics? 😃
  
It's a good idea, we can monitor all the certificates managed by cert manager.

**Comment by cathyzhang05** [comment]
Hi @istvanballok,
We have discussed using blackbox exporter approach to probe the HTTPS endpoints and monitor the certificates by the metrics I am using in the PR. 
Any suggestion from your side?  Enhance the cert-manager metrics OR keep this pr's approach? Thank you.

**Comment by timuthy** [comment]
For the mentioned reasons in https://github.com/gardener/gardener/pull/7895#pullrequestreview-1424650974 and https://github.com/gardener/gardener/pull/7895#issuecomment-1547415820, I suggest to rather enhance the [Cert-Management](https://github.com/gardener/cert-management/) component.

**Comment by cathyzhang05** [comment]
One issue raised in cert-manager https://github.com/gardener/cert-management/pull/130. And Martin fixed it in issue https://github.com/gardener/cert-management/pull/131. Close this pr and will develop the function based on new cert metrics. 

/close

**Pull request closed without merging**
