### PR TITLE
update alpine image to v3.13.5

### PR DESCRIPTION
**Pull request by DockToFuture**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
Update alpine image to v3.13.5.

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
From @vpnachev , I know:
>  Please, avoid upgrading OCI images to use alpine 3.14 as there are breaking syscal [changes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2) that requires runc >=v1.0.0-rc93 , but we still have a lot of nodes that are on older versions.

**Comment by DockToFuture** [comment]
> From @vpnachev , I know:
> 
> > Please, avoid upgrading OCI images to use alpine 3.14 as there are breaking syscal [changes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2) that requires runc >=v1.0.0-rc93 , but we still have a lot of nodes that are on older versions.

If you rely on `v3.13.5`, I will upload the image as well and update the PR.

**Comment by ialidzhikov** [comment]
> If you rely on v3.13.5, I will upload the image as well and update the PR.

Yes, let's prefer 3.13.5.

**Comment by DockToFuture** [comment]
Updated the PR.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
