### PR TITLE
Add NoExists and NoSchedule tolerations to system components

### LINKED ISSUE #656: Missing tolerations on kube_proxy and node_exprorter daemonsets
We are using node taints to separate our pods from the system ones.
There are missing tolerations on the kube_proxy and node_exporter daemonsets definitions in Gardener. As a result, the pods for kube_proxy and node_exporter are not created in all nodes.

*Remark - The Calico daemonset is define correctly.
 

The missing part is:
 
tolerations:
  # Make sure this pod gets scheduled on all nodes.
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
 
It is crucial for our solution, could you please fix that?

Thanks,
Saggi Raiter, WebIDE, DevX

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**: Add missing tolerations to system components deployed by Gardener.

**Which issue(s) this PR fixes**:
Fixes #656 

**Special notes for your reviewer**:

**Release note**:

```improvement user
All system components deployed by Gardener do now tolerate the `NoSchedule`, `CriticalAddonsOnly`, and `NoExecute` taints on nodes.
```

### CODE REVIEW

**Review by saggir — CHANGES_REQUESTED** [review]
Coredns, vpn shoot and metrics deployments should not include the tolerations, only the daemonsets.
Otherwise we cannot have a dedicated node for applicative use and another one for system/k8s pods.
Adding the tolreations to the vpn shoot, coredns and metrics can cause them to be deployed in the application nodes

**Comment by rfranzke** [comment]
What happens if a user taints all nodes with e.g. `NoSchedule`? These system components would not be schedulable and the cluster would end up broken.
What is the rationale behind having these kind of dedicated nodes? Btw., are you aware that the machine-controller-manager can replace nodes at any time, i.e. you would need some kind of automation for tainting new nodes properly again?

**Comment by saggir** [comment]
> What happens if a user taints all nodes with e.g. `NoSchedule`? These system components would not be schedulable and the cluster would end up broken.
> What is the rationale behind having these kind of dedicated nodes? Btw., are you aware that the machine-controller-manager can replace nodes at any time, i.e. you would need some kind of automation for tainting new nodes properly again?

Yes, you are correct, this is a problematic use case, this is a the reason we are waiting for your backlog item to add taints on the worker tab. for now, we'll have a cronjob task that redefine the taint on nodes every x minutes. 
The rational behind the dedicated nodes is to seperate the resources per applicative use and adding an operator node for logging and monitoring. using taints we can define different machines per uses (e.g. allocate more memory for our workspace pods and bigger disk size for logging)

**Comment by rfranzke** [comment]
OK, well, I am good with removing the `NoSchedule`/`NoExecute` tolerations from the system deployments for now (users can anyway easily break the cluster by other means).
But, without a real controller that is watching the `Node` objects you cannot guarantee the separation of application/system nodes anyway.

@mvladev any input from your side?

**Comment by saggir** [comment]
> OK, well, I am okay with removing the `NoSchedule`/`NoExecute` tolerations from the system deployments for now (users can anyway easily break the cluster by other means).
> But, without a real controller that is watching the `Node` objects you cannot guarantee the separation of application/system nodes anyway.
> 
> @mvladev any input from your side?

Thanks, 
Hope you priorities the taints task too...
Saggi.

**Comment by rfranzke** [comment]
Well, from Gardener PoV we have to wait until this feature is supported by the machine-controller-manager (see gardener/machine-controller-manager#174) - I guess the colleagues are working with the community to find a common way of enabling that.

**Comment by timuthy** [comment]
I think having pure application nodes can still be handled by `PreferNoSchedule` which sounds quite reasonable to me -> You tell it to prefer not to schedule a system component on a Node but it will do it as a last resort which prevents the cluster breakage. WDYT?

**Review by timuthy — DISMISSED** [review]

**Comment by vlerenc** [comment]
Interesting discussion (cc @hardikdr @prashanth26 @ggaurav10 @amshuman-kr). Please note, we plan to optimise the MCM rolling update (https://github.com/gardener/machine-controller-manager/issues/120):
MCM will taint all existing/old nodes when initiating a rolling update with `PreferNoSchedule` before being rolled, so that when a node gets drained, the pods get rescheduled only to the new nodes (that do not have this taint), so that each pod gets redeployed (ideally, because it's "only" a `prefer` taint) only once.

**Comment by mvladev** [comment]
> OK, well, I am good with removing the NoSchedule/NoExecute tolerations from the system deployments for now (users can anyway easily break the cluster by other means).
But, without a real controller that is watching the Node objects you cannot guarantee the separation of application/system nodes anyway.
@mvladev any input from your side?

Yes, that would be the same way `kubeadm` https://github.com/kubernetes/kubernetes/blob/6d479af411333c8f1bba2c1edac76ec929caf1f7/cmd/kubeadm/app/phases/addons/dns/manifests.go#L173-L174 does it

```yaml
tolerations:
- key: CriticalAddonsOnly
  operator: Exists
```

**Comment by rfranzke** [comment]
OK, will do and merge afterwards. Thanks.

**Comment by saggir** [comment]
When can we expect the release?

tnx,
Saggi

**Comment by rfranzke** [comment]
Hi Saggi, probably end of this week/beginning of next week.

**Comment by saggir** [comment]
Hi,
You have a bug in the fix, in the node-exporter.yaml file.
You have 2 "tolerations" sections in the file. the active one is the second one and we need the first definition...

Saggi.

**Comment by rfranzke** [comment]
Thanks for reporting, fixed in 0fb3aefb6c0e433a4d65f8b1e7226fe219beedd1.

**Comment by saggir** [comment]
Thanks, when can I get this fix in Canary?

**Pull request merged**
