### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.20.3->v0.21.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
```improvement user github.com/gardener/etcd-backup-restore #675 @abdasgupta
The snapshots are fetched from the actual backend store when queried for latest snapshots on `/snapshot/latest` endpoint.
```
```noteworthy operator github.com/gardener/etcd-druid #711 @abdasgupta
Compaction job now reconciles on Job Status changes along with the holder identity changes in snapshot leases.
```
```improvement operator github.com/gardener/etcd-backup-restore #673 @anveshreddy18
Enhanced Garbage Collector to garbage collect the chunks for cloud providers like GCP and OpenStack which does not automatically delete snapshot chunks after the formation of a composite object.
```
```doc operator github.com/gardener/etcd-druid #697 @ishan16696
Updated the recovery from permanent quorum loss ops guide.
```
```noteworthy operator github.com/gardener/etcd-backup-restore #668 @ishan16696
Fix a restoration failure which can occurs due to an etcd database space exceeds during restoration.
```
```noteworthy operator github.com/gardener/etcd-backup-restore #661 @ishan16696
Making etcd-backup-restore restart tolerant while scaling-up an etcd cluster.
```
```noteworthy developer github.com/gardener/etcd-druid #723 @abdasgupta
Added e2e test for compaction.
```
```bugfix operator github.com/gardener/etcd-druid #682 @abdasgupta
Local storage provider for backups is now supported for snapshot compaction jobs.
```
```feature developer github.com/gardener/etcd-druid #713 @seshachalam-yv
Added documentation and sample configurations for simplifying Localstack setup, making it easier for developers to create a local testing environment using a Kind cluster.
```
```other operator github.com/gardener/etcd-druid #724 @shreyas-s-rao
Update alpine image version to `3.18.4`.
```

### CODE REVIEW

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by ishan16696** [comment]
cc @plkokanov

**Comment by ialidzhikov** [comment]
@seshachalam-yv, @ishan16696 can you also raise a PR to update the etcd-druid dependency version in go.mod so that CRDs and dependency version match the etcd-druid version?

**Pull request merged**
