### PR TITLE
Nit: Update to golang@1.14.7

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind task
/priority normal

**What this PR does / why we need it**:
Ref https://groups.google.com/d/msg/golang-announce/NyPIaucMgXo/GdsyQP6QAAAJ

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm
Should we cherry-pick this to 1.7 (and maybe even 1.6)?

**Comment by rfranzke** [comment]
@timebertt are we vulnerable against the fixed CVEs?

**Comment by timebertt** [comment]
I don't know and I also can't tell only from the list mail / commit.

**Pull request merged**
