### PR TITLE
Expose `enforceNodeAllocatable` in the `Shoot` resource

### LINKED ISSUE #2590: Resource reservation for kube and system daemons
This issue tracks activities related  to resource reservation for kube and system daemons started in this [Issue](https://github.com/gardener/gardener/issues/2559). 

**How to categorize this issue?**

/area robustness
/kind enhancement
/priority normal

Following up on the discussion made in [this PR](https://github.com/gardener/gardener/pull/2574).
There are multiple open points / activities to be done (not restricted to @guydaichs only).

- [X]  Expose [kube-reserved](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved) and [system-reserved](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved) configuration in the Shoot resource: https://github.com/gardener/gardener/pull/2574
  - As a first step in [this PR](https://github.com/gardener/gardener/pull/2574) only allow configuration of the system-reserved and kube-reserved  quantities. This will be taken into consideration when the kubelet calculates the [Node Allocatable](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable) and is enforced on pods per default.
- [x] Configure sensible default values for kube-reserved based on the worker pool's machine size, similar to GKE's [formula for resource reservation](https://cloud.google.com/kubernetes-engine/docs/concepts/plan-node-sizes#resource_reservations) (discussed in https://github.com/gardener/gardener/issues/9105): https://github.com/gardener/gardener/pull/9449
  - Remove static defaults for `v1beta1.Shoot` fields `shoot.spec.kubernetes.kubelet.kubeReserved`.
  - Add an optional admission plugin (disabled by default for now) that for each `Worker` in a `Shoot` object injects `shoot.spec.provider.workers[].kubernetes.kubelet.kubeReserved` by using the GKE formula based on the `MachineType` from the `CloudProfile`. 
  - If the admission plugin is not enabled, apply the current defaults.
  - The value is only injected if the user sets no explicit values on the shoot level or the particular worker.
    - With this, existing shoots are not modified when enabling the plugin.
    - This also avoids the problem of unexpectedly changing the resource reservation if the `CloudProfile` is modified.
    - Special case: if the user only changes the machine type of a worker pool, the resource reservations become out-of-sync. The admission plugin cannot tell whether the user has knowingly set the resource reservations, so it will not change them according to the new machine type. This case must be documented properly.
- [x] ~~Expose [`enforceNodeAllocatable`](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#enforcing-node-allocatable) in the Shoot resource: https://github.com/gardener/gardener/pull/7395~~ EDIT: not recommended by official documentation (https://github.com/gardener/gardener/issues/9105#issuecomment-1959666703)
- [x] ~~Align with the [Kubernetes recommended cGroup setup](https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md#recommended-cgroups-setup).~~ EDIT: doesn't make a difference without `enforceNodeAllocatable` (see above)
- [ ] Drop `systemReserved` configuration in `Shoot` API. Doesn't make a difference without `enforceNodeAllocatable` (see above).
- [ ] Rolling update of the worker pool when critical kubelet configuration changed: https://github.com/gardener/gardener/pull/9465
  - Restricted to:  [kube-reserved](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved) and [eviction thresholds](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy) 
  - Requires changes to the [MachineClass calculation in the extension library](https://github.com/gardener/gardener/blob/3c39cff6a0d14e621b377eae22417118c70014b2/extensions/pkg/controller/worker/machines.go#L119) + revendoring in the extensions. 
- [ ] Documentation
  - Explaining the cGroup setup on Gardner nodes with reference to the Kubernetes recommended setup
  -  User documentation explaining which fields in the [kubelet configuration](https://github.com/gardener/gardener/blob/c0c5a694ae28d90f06c080008f5464d161fb30d3/pkg/apis/core/types_shoot.go#L510) in the Shoot lead to a rolling update and which are updated in place. This is to ensure there is no unexpected behaviour.  
 In general we should document this better also for other configurations of the worker.

### PR DESCRIPTION
**Pull request by nschad**
**How to categorize this PR?**

/area robustness
/kind api-change

**What this PR does / why we need it**:

Partial implementation of #2590. 
Expose [`enforceNodeAllocatable`](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#enforcing-node-allocatable) in the Shoot resource.

**Which issue(s) this PR fixes**:
Part of #2590

**Special notes for your reviewer**:

:x: in draft because it requires the task "Align with the [Kubernetes recommended cGroup setup](https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md#recommended-cgroups-setup)" to be completed first, otherwise kubelet will fail to start up.

**Release note**:

```feature operator
allow configuration of enforceNodeAllocatable via Shoot resource
```

### CODE REVIEW

**Comment by timebertt** [comment]
Thanks, @nschad!
Can you add a note to the PR description why it is in draft and what it takes to make it ready?

From https://github.com/gardener/gardener/issues/2590:

> Prerequisite: Align with the Kubernetes recommended cGroup setup.

Is this still a strict prerequisite for exposing this configuration option in the `Shoot` API?

**Comment by rfranzke** [comment]
@nschad Do you plan to continue with this PR in the next days? Otherwise, perhaps we should close it and reopen later when there is capacity again?

**Comment by nschad** [comment]
> @nschad Do you plan to continue with this PR in the next days? Otherwise, perhaps we should close it and reopen later when there is capacity again?

Hi,

This PR is ready for review technically but it doesn't really make any sense merging it before you implement the cgroup setup.
I'm currently on vacation however another team member should pick that up very soon.
```
❌ in draft because it requires the task "Align with the [Kubernetes recommended cGroup setup](https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md#recommended-cgroups-setup)" to be completed first, otherwise kubelet will fail to start up.
```

**Comment by rfranzke** [comment]
> This PR is ready for review technically but it doesn't really make any sense merging it before you implement the cgroup setup.

In this case, I still vote for closing this PR and reopening it later when the prerequisites have been done. It doesn't make sense to keep it open and "pollute" the overview of such important (and potentially expensive) prerequisites need to be tackled first :)

**Comment by rfranzke** [comment]
/close

Kindly reopen when the prerequisites were completed, please.

**Pull request closed without merging**
