### PR TITLE
Stop patching new secretRefs on MR reconciliaition

### LINKED ISSUE #8549: [Cleanup] Managed resource package is making unnecessary calls causing transient errors
**How to categorize this issue?**

/area quality
/kind cleanup

Together with @rfranzke we had a private discussion about the logic residing in the managed resource builder package and more concretely we discussed the [mr.Reconcile](https://github.com/gardener/gardener/blob/fbbd16a1aefdc4aaac295162fa4a692cd1d4b7de/pkg/utils/managedresources/builder/managedresources.go#L121) function. It is not ideal that we currently patch the referenced secrets to make them garbage collectable. This results in transient errors when reconciling a managed resource because some client's caches may not be populated with the newly created secret. See [an example log from a test run](https://gcsweb.gardener.cloud/gcs/gardener-prow/pr-logs/pull/gardener_gardener/8509/pull-gardener-e2e-kind-operator/1704409810713186304/artifacts/gardener-operator-local/gardener-operator-local-worker/pods/garden_gardener-operator-775bcf7488-g2pg4_5eb8618d-6a8c-4ac5-8ca1-9805461264fa/gardener-operator/0.log) and search for "marking new secrets as garbage collectable". Ideally we would not see such errors.

We can remove this piece of code (the one that marks the secrets as garbage collectable) if we ensure that:
 - old secrets are deleted/marked for garbage collection
 - it is ensured that all extensions now work with the immutable secrets approach

A [quick search](https://sourcegraph.com/search?q=context:global+repo:github.com/gardener+-file:vendor+WithSecretRef&patternType=standard&sm=1&groupBy=repo) shows that only a couple of extensions are using the `WithSecretRef` function which is one of the fewer possible ways to use managed resources with a mutable secrets, i.e. you create a mutable secret and then reference it via the said function.

Initlially the plan was not to modify any extension code. This would mean that every extension should be released with vendored g/g >= [v1.77](https://github.com/gardener/gardener/releases/tag/v1.77.0) and managed resources should be reconciled at least once.

Another more involved (and probably safer) approach would be to include migration step in extensions's code. This approach may also unblock the removal of the discussed code since the cleanup will happen explicitly.
1. Deploy managed resource with immutable secrets
2. Clean the old secret (temporary step which can be removed anytime by the extension owner after a (few) release(s))

@timuthy @shafeeqes since you reviewed https://github.com/gardener/gardener/pull/8116 do you have any inputs on this?

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area robustness
/kind cleanup

**What this PR does / why we need it**:
New managed resource secret references will no longer be ensured to be garbage collectable.

**Which issue(s) this PR fixes**:
Fixes #8549

**Special notes for your reviewer**:

**Release note**:

```breaking developer
New `Secret`s referenced in `ManagedResource`s will no longer be patched with the label `resources.gardener.cloud/garbage-collectable-reference` when the `ManagedResource` is reconciled. `Secret`s which already exist in the `ManagedResource` specification will still be patched if necessary.
```

### CODE REVIEW

**Review by timuthy — COMMENTED** [review]
Thank you!
/lgtm

**Review by shafeeqes — APPROVED** [review]
Thanks!
/approve

**Pull request merged**
