### PR TITLE
Set dnsPolicy to Deault for Shoot system components

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/area networking
/kind enhancement
/priority normal

**What this PR does / why we need it**:

The following components only talk to their respective API server and do not need any DNS resolution other than the API server:

- metrics-server
- node-problem-detector
- vpn-shoot

**Which issue(s) this PR fixes**:

n/a

**Special notes for your reviewer**:

**Release note**:

```improvement operator
`metrics-server`, `node-problem-detector` and `vpn-shoot` now have `dnsPolicy: Default` set to them to remove dependency to `coredns`.
```

/cc @DockToFuture

### CODE REVIEW

**Review by DockToFuture — DISMISSED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
Can you check the failing test?
/hold until v1.13 is released

**Comment by mvladev** [comment]
The tests are fixed.

**Review by rfranzke — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
