### PR TITLE
Upgrade node-problem-detector to `v0.8.15`

### PR DESCRIPTION
**Pull request by rishabh-11**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
Upgrade NPD version to https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.15

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Works on both AMD and ARM ( cc @acumino )

**Release note**:

```other operator
The `node-problem-detector` version has been updated from `v0.8.13` to `v0.8.15`.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve
/retest

**Comment by rfranzke** [comment]
@rishabh-11 It seems this NPD image doesn't work well:

```
  {"level":"info","ts":"2024-02-12T15:21:39.351Z","logger":"shoot-test.test","msg":"Shoot not yet created","shoot":{"name":"e2e-migrate","namespace":"garden-local"},"reason":"condition type SystemComponentsHealthy is not true yet, had message DaemonSet \"kube-system/node-problem-detector\" is unhealthy: too many unavailable pods found (1/1) with reason DaemonSetUnhealthy"}
```

Any insights?

**Comment by rishabh-11** [comment]
Open issue on NPD - https://github.com/kubernetes/node-problem-detector/issues/851. It affects us as well. I guess we can't change the version until this is fixed.

**Comment by rfranzke** [comment]
Then let's
/close
this PR until there is a new image which fixes the problems. This tag seems to not be usable anyways.

**Pull request closed without merging**
