### PR TITLE
Add `class` field to `extensions.gardener.cloud` APIs

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area delivery
/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR adds a new optional field `class` to various objects in the `extensions.gardener.cloud` API. As described in #9635, some extension controller will in the future not only be responsible to reconcile extension resource for `Shoot`s, but also for the `Garden` cluster, e.g. managing `BackupBucket` and `DNSRecord`s.

The `class` field is required when the Runtime-Garden is registered as a Seed cluster. There might be two provider extensions of the same type running in the same cluster. One is responsible for reconciling extension resources belonging to the `garden` class, while the other one takes care about extensions for the `<nil>`(backwards compatibility) or `shoot` class.

**Which issue(s) this PR fixes**:
Part of #9635

**Special notes for your reviewer**:
- Please see description in 91e8b88e9644d27fce96890463ed7792f91e23f1 about how the future class configuration is envisioned:

>  Generally, to follow the example of `ManagedResource` handling, the `class` field is planned to be only set in the `garden` use-case. Gardener won't set the `class` for extensions belonging to shoot clusters.

- Documentation is not part of this PR. This is planned for a future PR, when we generally add support for developing and deploying `Extension`s via `gardener-operator`.

- Today, a `class` would be sufficient for resources of type `BackupBucket` and `DNSRecord`. For the sake of completeness and future use-cases, the field was added to other resources as well.

**Release note**:

```noteworthy dependency
A new field `class` was added to resources of the `extensions.gardener.cloud` API group. Together with the newly introduced predicate [HasClass](https://github.com/gardener/gardener/blob/master/extensions/pkg/predicate/predicate.go), it serves as a mean to split responsibilities of extension controllers for extensions belonging to different type of targets, i.e. `shoot` (default) or `garden`. Handling is backwards compatible, so that extensions are still responsible for `shoot` extension resources without any adjustments. If you intend to already support the reconciliation of extensions belonging to the `garden` class (cluster), please consider adding the `ExtensionClass` parameter (see [here](https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/cmd/reconciler_options.go) for more information). 
```

### CODE REVIEW

**Review by LucaBernstein — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve

**Pull request merged**
