### PR TITLE
Add vpa for hvpa-controller

### PR DESCRIPTION
**Pull request by ggaurav10**
**How to categorize this PR?**

/area auto-scaling
/kind impediment
/priority normal

**What this PR does / why we need it**:
Added vpa for hvpa-controller so that it can autoscale as per load

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Added vpa for hvpa-controller 
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

nice :D

**Review by amshuman-kr — APPROVED** [review]
/lgtm

**Pull request merged**
