### PR TITLE
Remove deprecated seed-terraformer chart

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Remove deprecated  `<provider>-infra` charts as they are no longer used.

Ref https://github.com/gardener/gardener/pull/1453#issuecomment-537687649.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement developer
`TerraformerChartPath` and `ChartInitializer` func are now removed from `pkg/operation`.
```

### CODE REVIEW

**Comment by swapnilgm** [comment]
You can actually remove seed-terraformer chart entirely right?. Also, function ChartInitializer from https://github.com/gardener/gardener/blob/master/pkg/operation/operation.go#L377

**Comment by ialidzhikov** [comment]
> You can actually remove seed-terraformer chart entirely right?

Yep.

**Review by swapnilgm — COMMENTED** [review]
Thanks you for the PR. Just couple of cleanups more: 
1. Remove const `TerraformerChartPath` from https://github.com/gardener/gardener/blob/master/pkg/operation/common/types.go#L470
2. Remove function `ChartInitializer` from https://github.com/gardener/gardener/blob/master/pkg/operation/operation.go#L377

**Comment by ialidzhikov** [comment]
Done.

**Review by swapnilgm — APPROVED** [review]
LGTM

**Review by vpnachev — CHANGES_REQUESTED** [review]
Add a release note `action developer` that the variable `TerraformerChartPath` and the method `ChartInitializer` have been removed, because they are exported and maybe somebody is using them.

**Review by vpnachev — APPROVED** [review]
/approve

**Review by zanetworker — APPROVED** [review]

**Pull request merged**
