### PR TITLE
[ci:component:github.com/gardener/logging:0.9.0->0.10.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**

### CODE REVIEW

**Comment by rfranzke** [comment]
@vlpanov what do we get with logging 0.10.0?

**Comment by vlpanov** [comment]
@rfranzke
Flexible setting of the maximum heap size for EalsticSearch.
Before 0.10.0, this size was hard-coded in the container image itself (in jvm.options). Using 0.10.0, it can be passed to the container dynamically using an environment variable.
See:
https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
We will use ${ES_JAVA_OPTS} in the future.

**Comment by rfranzke** [comment]
Thank you. Do we need any change in the logging manifests in Gardener or can we merge this PR as it is?

**Comment by vlpanov** [comment]
@rfranzke
The Gardener will use 0.9.0 for the time being. We are not ready with the changes in the Gardener that will use the new images.

**Comment by rfranzke** [comment]
Thank you.

**Comment by rfranzke** [comment]
@vlvasilev and colleagues: Please reopen this one once you want to bump the logging version.

**Pull request closed without merging**
