### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.19.0->v0.19.1]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
```bugfix operator github.com/gardener/etcd-druid #662 @aaronfern
A bug causing incorrect volume mount path for `Etcd`s and `EtcdCopyBackupsTask`s using `Local` snapshot storage provider while using distroless etcd-backup-restore image `v0.25.x` has been resolved.
```
```bugfix operator github.com/gardener/etcd-druid #662 @aaronfern
A bug causing `EtcdCopyBackupsTask` jobs to fail to create temp snapshot directory while using distroless etcd-backup-restore image `v0.25.x` has been resolved.
```

### CODE REVIEW

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Review by aaronfern — APPROVED** [review]
/lgtm

**Pull request merged**
