### PR TITLE
[ReversedVPN] Add dashboard for connection overflows of envoy proxy to reversed-vpn dashboard

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/area monitoring
/kind enhancement

**What this PR does / why we need it**:
Add dashboard for connection overflows of envoy proxy to reversed-vpn dashboard.
We have seen that for some clusters the configured maximum connection limit in the envoy proxy side car is not big enough. This change visualizes the corresponding metric in the dashboard of the reversed-vpn.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/second-opinion
/cc @wyb1 @istvanballok

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by istvanballok — APPROVED** [review]
/lgtm

**Pull request merged**
