### PR TITLE
Make additional vpa-recommender flags configurable via the Shoot spec

### LINKED ISSUE #10141: Make VPA more configurable to improve utilisation of VPA-dependent workload
**What would you like to be added**:
https://github.com/gardener/gardener/pull/9279 made VPA's `--target-cpu-percentile` configurable. Now, let's please also add:
- `--recommendation-lower-bound-cpu-percentile`
- `--recommendation-upper-bound-cpu-percentile`
- `--target-memory-percentile` <-- most important
- `--recommendation-lower-bound-memory-percentile`
- `--recommendation-upper-bound-memory-percentile`

**Why is this needed**:
This is needed to improve utilisation of VPA-dependent workload.

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Exposes additional vpa-recommender flags as suggested in https://github.com/gardener/gardener/issues/10141.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/10141

**Special notes for your reviewer**:
N/A

**Release note**:

```feature user
The following `vpa-recommender` flags are now configurable via the `Shoot` specification:
- `--recommendation-lower-bound-cpu-percentile`: `.spec.kubernetes.verticalPodAutoscaler.recommendationLowerBoundCPUPercentile`
- `--recommendation-upper-bound-cpu-percentile`: `.spec.kubernetes.verticalPodAutoscaler.recommendationUpperBoundCPUPercentile`
- `--target-memory-percentile`: `.spec.kubernetes.verticalPodAutoscaler.targetMemoryPercentile`
- `--recommendation-lower-bound-memory-percentile`: `.spec.kubernetes.verticalPodAutoscaler.recommendationLowerBoundMemoryPercentile`
- `--recommendation-upper-bound-memory-percentile`: `.spec.kubernetes.verticalPodAutoscaler.recommendationUpperBoundMemoryPercentile`
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/hold
due to https://github.com/gardener/gardener/issues/10141#issuecomment-2256047396

**Comment by ialidzhikov** [comment]
/hold cancel
due to https://github.com/gardener/gardener/issues/10141#issuecomment-2273381309

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
