### PR TITLE
Redraw gardener-architecture-detailed.png with a cleaner look

### PR DESCRIPTION
**Pull request by lotharbach**
and we hope easier to follow lines. This was also done as the
basis for future contentual enhancement proposals, and our
designer refused to work in PowerPoint :)

Co-authored-by: Jonathan Schweppe <schweppe@23technologies.cloud>

**How to categorize this PR?**

/area documentation
/kind enhancement

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @gesslein for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by rfranzke** [comment]
Thanks for your efforts, really appreciating!
How was this drawn/with which tool? I'm asking because I'm wondering how other contributors would be able to change it in the future.

**Comment by lotharbach** [comment]
Adobe Illustrator, and I could also add the source file here or in gardener/documentation (as was done for the pptx source). Of course we also offer some ongoing stewardship of this work and are happy to be assigned related issues etc.

**Comment by rfranzke** [comment]
Hm, I don't know this tool, but from a quick googling it seems it's paid software?

Maybe we should use something that is open-source and easy-to-use, e.g. [Excalidraw](https://excalidraw.com/).
We have already started to use it for some diagrams, e.g. https://github.com/gardener/gardener/blob/master/docs/deployment/gardenlet_api_access_flow.png or https://github.com/gardener/gardener/blob/master/docs/deployment/gardenlet_api_access_graph.png.
The scene/"source" is embedded into the `png` itself, enabling a quick and easy workflow.

WDYT?

**Comment by berendt** [comment]
> WDYT?

In my experience, all open source tools for creating graphics are not at one point like the commercial tools. I'm with you and prefer to use open source tools where possible and appropriate. With graphics, that's not the case in my opinion.

What do you think about specifying the export format in general, i.e. SVG. Then the graphics are editable for all. And are not dependent on any particular tool.

**Comment by istvanballok** [comment]
I think excalidraw (its [blog](https://blog.excalidraw.com/) gives a good overview of the open source project's history) is gaining popularity (see e.g. the illustrations of the [operator whitepaper](https://github.com/cncf/tag-app-delivery/blob/public-comment/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md)) and it is fairly easy to use: as @rfranzke mentioned, the exported `png` images can also embed the scene (the abstract model of the drawing, more abstract than svg, with an opinionated sketchy look&feel) so that the `png` image can be "loaded" into excalidraw for further editing.
Try to download e.g. https://raw.githubusercontent.com/gardener/gardener/master/docs/deployment/gardenlet_api_access_graph.png and load it into https://excalidraw.com/. 😊

**Comment by berendt** [comment]
@istvanballok There is no point in committing to a particular tool. You never know where they're going to go. With the argumentation about popularity, draw.io would probably be the better choice. Or Libreoffice. Or Gimp. Or Inkscape. Therefore IMO it is better to specify only the file format (SVG) and leave the tool open.

**Comment by lotharbach** [comment]
I added the SVG to this PR, which edits fine (maybe a bit slow) in Inkscape. If the gardener projects in the future standardizes on a tool like Excalidraw, or some format we can't convert to, it might need to be redrawn from scratch again. But right now I hope you agree this is an overall improvement over the previous version, which was not available in any "open" format.

**Comment by vlerenc** [comment]
@gesslein And it is helping with the lines how? Isn't it still very complex/didn't really changed significantly?

@rfranzke Besides, since the VPN is about to be reversed and the shoot LBs were bundled by means of SNI/Istio gateways, this images will be obsolete soon.

**Comment by berendt** [comment]
@vlerenc The goal of this step was not to improve the graphics from the point of view of complexity etc. We wanted the graphics to look better for our internal documents and not have to use PowerPoint for editing. This is the result of what we would like to provide.

**Comment by rfranzke** [comment]
We discussed this PR internally and while we highly appreciate your efforts and investments to improve the picture, we came to the conclusion that we would rather not merge it at this point. Yes, it's an improvement compared to today's PowerPoint-based solution, though, as @vlerenc mentioned, the graphic will be obsolete (actually, it already is) and needs to be re-drawn soon anyways (also due to its complexity).
We figured that this will most likely be done with Excalidraw (some newer diagrams already use it, and the tool itself is lightweight, open-source, and portable (it can even be ran locally in a Docker container)). It also supports exports to the SVG file format, so even if they are going somewhere we don't want to follow (unlikely), it won't be lost.

Obviously, you can still use the picture for your internal documentation (which was the initial trigger) if you want, just be aware of the upcoming changes to it (that you might potentially need to duplicate if you don't want to use the upstream image).

/close

**Pull request closed without merging**
