### PR TITLE
[ci:component:github.com/gardener/vpn2:0.17.0->0.18.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/kind enhancement
according to https://github.com/gardener/vpn2/compare/0.17.0..0.18.0

**Review by ialidzhikov — COMMENTED** [review]
/approve

**Comment by timuthy** [comment]
@DockToFuture please feel free to lgtm, so the PR can be merged.

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
