### PR TITLE
Drop `nodeSelector` and `tolerations` from Shoot System Components

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area scalability
/kind cleanup

**What this PR does / why we need it**:
After the integration of #7204, this PR cleans up relevant deployments of Shoot System Components:
- removes `nodeSelector`
- removes general `tolerations`
- removes all `CriticalAddonsOnly` tolerations (not related to #7204 but removed along the way)

Please see the individual commit messages for more information.

**Which issue(s) this PR fixes**:
Part of #7103

**Release note**:

```other operator
None
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Nice, thanks for cleaning this up!
/approve

**Review by acumino — COMMENTED** [review]
/lgtm

**Comment by timebertt** [comment]
Great work! 🎉

**Pull request merged**
