### PR TITLE
change the shoot namespace matching regex to 'shoot-'

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind bug
/priority normal

**What this PR does / why we need it**:
When shoot namespace start with `shoot-`  and there is no consecutive dash the logs are send to the central garden Loki instance.
By changing the shoot namespace matching regex to `shoot-` now the logs are send to the right namespace.

Also we increase the promtail batch wait to 30 seconds in order to lower the number of send requests.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
Change the shoot namespace matching regex of fluent-bit to `shoot-`
```
```noteworthy operator
Change the promtail batch wait to 30 seconds
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Can you fix the typo in the commit message (maching -> matching) and typo in the PR title (maтching -> matching)?

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Review by rfranzke — DISMISSED** [review]

**Comment by Kristian-ZH** [comment]
backlog for -> https://github.com/gardener/logging/issues/72

**Review by Kristian-ZH — DISMISSED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
