### PR TITLE
Eliminate client certificate for `dependency-watchdog-probe`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
Similar to #4931, this PR eliminates the client certificate for the `dependency-watchdog-probe` in favor of a token managed by the `TokenRequestor` controller in `gardener-resource-manager`.

**Which issue(s) this PR fixes**:
Part of #4661
Part of #4878

**Special notes for your reviewer**:
/invite @BeckerMax
/cc @ashwani2k  

**Release note**:

```noteworthy operator
`dependency-watchdog-probe` does no longer use a client certificate but an auto-rotated `ServiceAccount` token which is only valid for `12h`.
```

### CODE REVIEW

**Review by BeckerMax — DISMISSED** [review]

**Comment by rfranzke** [comment]
I had to rebase, @BeckerMax please check it again.

**Review by BeckerMax — APPROVED** [review]
/lgtm

**Pull request merged**
