### PR TITLE
Cleanup deprecated `install-requirements.sh`

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:

Cleanup deprecated `install-requirements.sh`.

**Special notes for your reviewer**:

The only place where the script was still used was `hack/.ci/prepare_release`. We now install `jq` via `apk`, the other tools installed by `install-requirements.sh` are covered by `hack/tools.mk`.

**Release note**:

```breaking dependency
`hack/install-requirements.sh` is removed. You can use `hack/tools.mk` to install tools needed for development and CI.
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
Are all extensions adapted to no longer rely on `install-requirements.sh`?

**Comment by timebertt** [comment]
> Are all extensions adapted to no longer rely on `install-requirements.sh`?

Good point. I cross-checked this with the provider extensions in our organization.
They have been adapted already with my revendoring PRs for g/g@v1.44 (https://github.com/gardener/gardener-extension-provider-aws/pull/529 and similar).
I haven't checked the other extensions. However, the script has been deprecated for quite some time and there was a breaking release note in https://github.com/gardener/gardener/releases/tag/v1.36.0.

Hence, I think we can go ahead with this PR.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Pull request merged**
