### PR TITLE
Increase timeout of delete test

### PR DESCRIPTION
**Pull request by schrodit**
**What this PR does / why we need it**:
Increase the timeout for deleting a shoot to 1 hour.
cc @dguendisch 

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by dguendisch — CHANGES_REQUESTED** [review]
How about removing the timeouts from go altogether? We already have timeouts in the testdefs (e.g. https://github.com/gardener/gardener/pull/1619/files). Would be helpful to avoid double maintenance. WDYT?

**Comment by schrodit** [comment]
I would not remove it from the test. For the future I would try to make it configurable so that we can specify different timeouts per flavor to not just set a timeout of 4h just that all tests will pass.

I want to see the tm timeout more like the concourse timeout, as a stopper for too long running tests.
The downside is that we do not know about timeouts in tests. They will then look like failures but I think this is ok?

**Comment by dguendisch** [comment]
> I would not remove it from the test.

What's the rationale of having a timeout in the code at all? Don't we run the tests without testmachinery only during development & debugging? There I actually don't want any timeout to not be kicked out of me checking this or of the debug session.

> I want to see the tm timeout more like the concourse timeout, as a stopper for too long running tests.

Agreed. Analogous to this, what you execute in concourse typically doesn't have a timeout itself, e.g. a deploy script doesn't have one on its one, just concourse has it.

**Comment by schrodit** [comment]
> What's the rationale of having a timeout in the code at all? Don't we run the tests without testmachinery only during development & debugging? There I actually don't want any timeout to not be kicked out of me checking this or of the debug session.

Most of the test will only run during development locally and 99% of time in the testmachinery.
But with our vision of moving to a real test suite we need these timeouts as multiple tests will be executed in one testmachinery step. 
We would also have more benefits like real cleanup of tests. If the testmachinery deletes the pod some test resources may leak and state dumping, cleanup, etc would not be possible.

Currently the timeout of a testdefs is hardcoded and cannot be overwritten by the testrun.
How would we want to do dynamic timeouts? Overwriting it in the testrun step may be possible.

**Comment by dguendisch** [comment]
Ok, the testsuite is a good argument. So let's go with this.

**Review by dguendisch — APPROVED** [review]

**Review by timuthy — APPROVED** [review]

**Pull request merged**
