### PR TITLE
Add fine-grained RBAC resources for gardenlet in the seed cluster

### LINKED ISSUE #1724: Harden Gardenlet RBAC privileges in the seed cluster
With #1601 we have introduced the gardenlet, a component comparable with the kubelet in Kubernetes.

However, in this first introduction we have not hardened the `ClusterRole`s we bind the gardenlet to in the seed ([ref](https://github.com/gardener/gardener/blob/1e591cc942e3c968407ace20f3e9cc0f183f7438/charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml#L5-L22)).

This is true for both the garden and the seed cluster.
For the garden cluster, we plan to address this with a special authorization plugin, see #1724.
For the seed cluster, we should harden these RBAC roles in order to only allow access to those resources it needs to access.

### PR DESCRIPTION
**Pull request by ialidzhikov**
/area security
/kind enhancement

Fixes #1724

This PR is based on https://github.com/gardener/gardener/pull/3763 with the following adaptations:
- It switches from Role to ClusterRole the ManagedIstio RBAC resources to prevent a chicken-or-egg problem - #3763 tries to install Role and RoleBinding in istio-system and istio-ingress Namespaces which are actually created by gardenlet in a much later point - during Seed bootstrap.
- It adapts few RBAC rules required due to recent changes in the master branch.

**Release note**:

```noteworthy operator
The gardenlet chart now defines fine-grained RBAC resources for the gardenlet in the Seed cluster. Previously the gardenlet's ServiceAccount was granted with all privileges. With this change the gardenlet's `ServiceAccount` privileges are limited as much as possible.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Thanks @ialidzhikov! I think after #4005 this PR might need adaptation, is it?

**Comment by ialidzhikov** [comment]
> Thanks @ialidzhikov! I think after #4005 this PR might need adaptation, is it?

Adaptation was required after #4006. I updated the PR now.

**Comment by rfranzke** [comment]
It lgtm, I cannot judge if we caught each and every RBAC rule that is required, but we can learn and improve as we go and you explained that you have already heavily tested many use-cases, so I'm confident that we can start as is.

Do you think we should merge this already without support for the local environment (though, not as part of v1.25)?
Independent of your opinion here, I'll setup a sync for next week to discuss the subject matter. :)

**Comment by ialidzhikov** [comment]
> Do you think we should merge this already without support for the local environment (though, not as part of v1.25)?
Independent of your opinion here, I'll setup a sync for next week to discuss the subject matter. :)

The PR looks good from my point of view. I would also wait for a second opinion from @vpnachev as the PR is similar to the initial one and it shouldn't be too much effort to go over it.

**Review by rfranzke — APPROVED** [review]
/lgtm
/second-opinion

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
