### PR TITLE
[GEP-18] Credentials rotation e2e test

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area security testing
/kind test

**What this PR does / why we need it**:

Co-Authored-By: @rfranzke 

Augments the current CA rotation e2e test with more assertions for all credentials rotated by `rotate-credentials-{start,complete}`.

Also
- allow reusing existing shoot in e2e tests
- enhance the precision of CA rotation assertions

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3292

**Special notes for your reviewer**:

As part of https://github.com/gardener/gardener/issues/3292, we plan to add some advanced checks to the e2e test. E.g.: check that the kubeconfig works in all phases of the rotation, etc. This will help us to gain even more confidence.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Very nice, thanks again for pairing on this!

/lgtm
/approve

**Comment by timebertt** [comment]
Fixed a few things. Let's hope the test passes now.

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Pull request merged**
