### PR TITLE
Do not validate `Shoot` DNS domain uniqueness for `DELETE` operations

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:
Earlier, `Shoot`s whose DNS domains weren't unique could not be deleted:

```
shoots.core.gardener.cloud "foo" is forbidden: [spec.dns.domain: Forbidden: the domain is already used by another shoot or it is a subdomain of an already used domain]
```

This PR fixes this.

Getting into such situation in the first place is only possible when two `Shoot`s are created at roughly the same time with the same domains. While the `gardener-scheduler` cannot schedule them (they at least never get really created), the objects could also not be deleted from the API.

**Release note**:

```bugfix user
A bug has been fixed which prevented deleting `Shoot`s whose domains were not unique in the system.
```

### CODE REVIEW

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve

**Comment by shafeeqes** [comment]
#7064 again
/test pull-gardener-e2e-kind-migration

**Comment by rfranzke** [comment]
🥱

**Pull request merged**
