### PR TITLE
Adds build file for Gogradle as a possible replacement for dep

### PR DESCRIPTION
**Pull request by Tarkleigh**
**What this PR does / why we need it**:
Dep is overcomplicated and unreliable (and no longer the Go tool of choice). EPS has switched to Gogradle and this might be a good idea for Gardener as well. The build.gradle in this pull request, replaces the Gopkg.toml in dep and should contain all necessary dependencies for Gardener. 

Currently, it is possible to build Gardener with the attached build.gradle file. However, I am not an expert for the Gardener build request so more tests might be required. As with Dep, one file has to be removed from the vendor folder which is currently done with the makefile.

### CODE REVIEW

**Comment by rfranzke** [comment]
Thank you for the PR. However, as said, I doubt that we want to spend time **now** on switching from dep to gogradle. Nobody of us knows gogradle (but dep) right now, and we rather aim to work on extensibility beginning next year which is much more important.
@mvladev, @adracus, @timuthy, @zanetworker thoughts?

**Comment by zanetworker** [comment]
@Tarkleigh Thank you so much for the contribution :). 

Looks interesting, I would put this PR on hold till we are through with the tasks of extensibility, only then  we can properly evaluate it. 

Looking forward to your talk on it as  well ;)

**Comment by timuthy** [comment]
I agree with @rfranzke. Additionally our dependencies will probably change when it comes to **extensibility**, i.e. moved from Gardener to other components. So we can maybe think of switching to Gogradle then, especially if we'd experience some severe issues with golang/dep.

**Comment by adracus** [comment]
I don't see any benefits from switching to gogradle. In the community `dep` is the de-facto standard, switching away from this might also scare away newbies from the project.

**Comment by mvladev** [comment]
I'd rather go for [golang modules](https://github.com/golang/go/wiki/Modules). As they come as a standard way to manage dependencies in go 1.11 ++

**Comment by Tarkleigh** [comment]
I wanted to hold off comments until after my talk but I want to make a few points now. First of all, I based the build.gradle on release 0.13.2 of Gardener, if the dependencies have changed since then, you might have to update them. Also, if you want to learn more about Gogradle, please have a look the Github [repo](https://github.com/gogradle/gogradle) and at this [talk](https://www.youtube.com/watch?v=Mvf3gY1MopE) on Gradle Summit where Gogradle was named Plugin of the Year 2017.

@rfranzke 
I never said anything about switching to Gogradle now. In fact, I am not even adding a requirement to Gardener at all. I opened this pull request because EPS switched to Gogradle and to me it was a vast improvement to Dep. This pull request is here to help you guys, not to create more work or mess up your schedule.
 
If you want to switch later - for instance when extensibility is done - this is perfectly fine with me. I personally don't need Gardener to switch at all, as Gogradle can also import it with the current dependency management.

@adracus 
The main benefit would be that Gogradle is much more reliable than Dep and needs less manual intervention (just compare the attached build.gradle to the .toml file of Gardener, I guess it is obvious which tool needs more special configuration). Also, it simply not true that Dep is a standard. It was very late to the party and the vast majority of Go projects do not use it. It had some fame as "official" tool for maybe a year but it has lost this status to golang modules now. 

Also, Gogradle is a plugin for Gradle which is more famous than Dep ever was and ever will be. A new developer is far more likely to be familiar with Gradle than with Dep, especially if he has a Java or C++ or Android background.

@mvladev 
This is a valid point and indeed golang modules offer some of the same benefits as Gogradle does (for instance, working outside of Gopath). I considered using them as well but they are still in beta until Go 1.12 and it is too early to really see how well they perform. Interaction with the many other dependency management tools will be key as it is very unlikely that the majority of existing projects switch to modules.

**Comment by rfranzke** [comment]
OK, understood, thank you very much for your efforts/time. Let's then take this PR as a reference/base in case we decide to switch at a later point in time and close it until then. We can't merge it as we don't want to maintain two places at the same time.

**Pull request closed without merging**
