### PR TITLE
[Workerless Shoots] Adapt monitoring and logging components

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane open-source
/kind enhancement

**What this PR does / why we need it**:
This PR adapts monitoring and logging components for workerless shoot. Key points - 
 - Disable shoot node logging  for workerless shoot
 - Adapt grafana dashboard to show only workerless relevant tiles in the dashboard.
 - Drop not required alerting rules for workerless shoots.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7635

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
lgtm FMPOV

**Comment by shafeeqes** [comment]
lgtm 
/approve

**Comment by ary1992** [comment]
lgtm

**Review by istvanballok — COMMENTED** [review]
/lgtm
Should be merged before #7318 to avoid conflicts in this PR.

**Pull request merged**
