### PR TITLE
[ci:component:github.com/gardener/gardener-metrics-exporter:0.28.0->0.29.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
```improvement operator github.com/gardener/gardener-metrics-exporter #96 @rickardsjp
Upgrade dependencies
Upgrade golang to 1.22
```
```improvement operator github.com/gardener/gardener-metrics-exporter #97 @rickardsjp
Upgrade go to 1.22, update base image to distroless based on Debian 12, and exchange the linter.
```
```bugfix operator github.com/gardener/gardener-metrics-exporter #94 @timebertt
Helm chart upgrades no longer fail due to the immutable `Deployment.spec.selector` field. In order to upgrade to this version, the `gardener-metrics-exporter` Deployment needs to be deleted first.
```
```breaking operator github.com/gardener/gardener-metrics-exporter #92 @ccwienk
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.

```
```improvement operator github.com/gardener/gardener-metrics-exporter #95 @Sinscerly
Adds: garden_shoot_worker_node_max_total and garden_shoot_worker_node_min_total. Also gives insight into the worker type (for example for OpenStack the Flavor name).
```

### CODE REVIEW

**Comment by rfranzke** [comment]
ping @rickardsjp @istvanballok

**Comment by rickardsjp** [comment]
thanks for the reminder.
/lgtm

**Pull request merged**
