### PR TITLE
Introduce persona-based docs

### PR DESCRIPTION
**Pull request by vlerenc**
**What this PR does / why we need it**:
We would like to introduce persona-based docs focussing on the already known release notes personas:
- users
- operators
- developers

**Special notes for your reviewer**:
@n-boshnakov Can you please share your thoughts while the PR is still a draft?
@rfranzke We tried (low-touch, but because of the cross-references more files had to be updated) to focus in the `usage` folder only on end-user relevant content and moved the content that wasn't suitable for end-users to a new folder `operations` that we have also introduced elsewhere for operators (Dashboard, ETCD, MCM, soon extensions, etc. as discussed in the out-of-band sync on improving the docs where you couldn't participate). We also tagged a few other documents (in `concepts` and `monitoring`) as end-user relevant (even if it wasn't a 100% fit, if the information in the document was important enough). We hope that's an acceptable starting point. Whether or not you restructure more content is up to you (e.g. move more content to the new `operations` folder or split up individual documents to cater to the 3 different personas better).

**Release note**:
None as ~30 PRs have/will be opened and the message would be the same everywhere.

### CODE REVIEW

**Comment by n-boshnakov** [comment]
I checked the documentation and in regards to profiling and links everything looks great!

Regarding the new structure, we had previously removed the Proposals section, as it stands mostly as an archive and is not something that should be actively maintained. 

If we want to place it on the website once more, we should go through all the GEPs and make sure that they are all standardized (the final two proposals do not include a number in their title) and also make changes to the the "GEP Title" - rename it to a more descriptive "GEP Template" and give it weight to make sure it isn't place haphazardly in the actual proposals.

**Comment by vlerenc** [comment]
@n-boshnakov Sure, I removed the proposals again (didn't know this was deliberate, although the GEPs are actually legit content for the external docs page).

I also changed the `categories` as @Kostov6 suggested/explained is implemented today (plural in the frontmatter headers of the individual files).

**Comment by vlerenc** [comment]
PR now ready for review from Gardener maintainers.

**Comment by vlerenc** [comment]
Well, the failed test looks very unrelated.

**Comment by rfranzke** [comment]
> Well, the failed test looks very unrelated.

I don't think they are unrelated 👀 It seems you manually changed generated files whose changes are reverted on regeneration.

**Comment by vlerenc** [comment]
Well, that's bad then @rfranzke, is it? I shall take a look then. :-)

**Comment by vlerenc** [comment]
OK now? My dev setup wasn't working anymore and since I will replace my notebook and have 25 similar cleanup PRs open, I didn't invest. At least the majority of the docs should now be better categorised, if you agree.

**Comment by rfranzke** [comment]
But now the link in https://github.com/gardener/gardener/blob/3a78b1c6f6e96e690c1003665cde6868b7ebe2cf/example/operator/10-crd-operator.gardener.cloud_gardens.yaml#L157 is broken. What about fixing it here https://github.com/gardener/gardener/blob/3a78b1c6f6e96e690c1003665cde6868b7ebe2cf/pkg/apis/operator/v1alpha1/types.go#L115 and running `make generate`?

**Comment by vlerenc** [comment]
See above. My dev setup wasn't working anymore and since I will replace my notebook and have 25 similar cleanup PRs open, I didn't invest (I started, but then this was missing, that was missing, so I stopped).

I can move the file back to where it was (but doesn't belong -> usage), if you want @rfranzke? But I cannot run `make generate` as of now. Apart from the comment that I couldn't update in the generated content, has this PR improved the placement of the docs that wasn't optimal/right before (the main goal here) or did I make a mistake?

The outcome we want to reach the most is to present end users with "their" docs (the other personas as well, but developers and operators can manage better), so that we confuse them less about stuff that is not relevant/accessible to them.

**Comment by vlerenc** [comment]
Thank you @rfranzke for https://github.com/gardener/gardener/pull/8202/commits/2d202e422ff850601f7488cebe68ec9a543cf9ba / running the `make generate`.

**Pull request merged**
