### PR TITLE
Fixed broken relative links

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

**What this PR does / why we need it**:
This PR fixes broken relative links

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @n-boshnakov for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by vpnachev — CHANGES_REQUESTED** [review]
Please, see the last line of the file
> Generated with <a href="https://github.com/ahmetb/gen-crd-api-reference-docs">gen-crd-api-reference-docs</a>

This PR will not even succeed the validations checks.

**Comment by n-boshnakov** [comment]
This PR is not needed, since the file is autogenerated. I will be closing it.

**Comment by vpnachev** [comment]
Please, do the following 
- fix the reference here https://github.com/gardener/gardener/blob/f7e980d9e5a34524ffb305806e13cf4b2bc6b692/hack/api-reference/extensions-config.json#L20
  You need to apply the following patch
  ```diff
  --- a/hack/api-reference/extensions-config.json
  +++ b/hack/api-reference/extensions-config.json
  @@ -17,7 +17,7 @@
           },
           {
               "typeMatchPrefix": "^github\\.com/gardener/gardener/pkg/apis/core/",
  -            "docsURLTemplate": "../core#core.gardener.cloud/v1alpha1.{{.TypeIdentifier}}"
  +            "docsURLTemplate": "../core.md#core.gardener.cloud/v1alpha1.{{.TypeIdentifier}}"
           },
           {
               "typeMatchPrefix": "^k8s\\.io/(api|apimachinery/pkg/apis)/",
  
  ```
- run `make generate` to re-generate https://github.com/gardener/gardener/blob/master/hack/api-reference/extensions.md (and other automatically generated files).
- commit and push the changes again to your `relative-links-fix` branch
- re-open this PR

**Review by vpnachev — APPROVED** [review]
/lgtm
/ok-to-test
/milestone v1.32

**Pull request merged**
