### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.20.1->v0.20.2]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
```improvement operator github.com/gardener/etcd-backup-restore #666 @shreyas-s-rao
Update alpine base image version to 3.18.4.
```
```improvement operator github.com/gardener/etcd-backup-restore #669 @seshachalam-yv
Introduced `delta-snapshot-retention-period` CLI flag to extend the configurable retention period for delta snapshots in `etcd-backup-restore`, enhancing flexibility for backup retention.
```
```improvement operator github.com/gardener/etcd-custom-image #41 @shreyas-s-rao 
Update alpine base image version to 3.18.4.
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
/kind enhancement
/approve

/cc @seshachalam-yv @aaronfern 
for lgtm

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Pull request merged**
