### PR TITLE
Upgrade NPD to v0.8.5

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Upgrade node-problem-detector to `v0.8.5` to fix `OOMKilling` detection for newer Linux kernels v5.1+, ref https://github.com/kubernetes/node-problem-detector/pull/481 and https://github.com/kubernetes/kubernetes/issues/96746.

**Special notes for your reviewer(s):**
/cc @ialidzhikov @vpnachev @hardikdr @prashanth26 

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Thank you for the PR. Can you also update the versions in `charts/shoot-core/components/charts/node-problem-detector/values.yaml` and `charts/shoot-core/components/charts/node-problem-detector/README.md`?

**Comment by rfranzke** [comment]
@ialidzhikov I've deleted those things, ptal.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by prashanth26 — APPROVED** [review]
Thanks for this upgrade.
/lgtm

**Pull request merged**
