### PR TITLE
Replace all occurences of interface{} whith any

### PR DESCRIPTION
**Pull request by majst01**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:

With go-1.18 `interface{}` was replaced with a type-alias to `any` to enhance readability see https://pkg.go.dev/builtin#any

With this all occurrences in the codebase, except the generated and third-party code was modified to use `any` now.

This was done with:

```
gofmt -r 'interface{} -> any' -w *.go
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by Kostov6** [comment]
If we are going to stick with this approach what about adding an automated script that checks for any occurrence of `interface{}` in any of the Make targets (example format) that ensures there are no `interface{}` added in future PR's? On the other side is it worth the effort for just a little bit of bonus code consistency?

**Comment by majst01** [comment]
> If we are going to stick with this alias what about adding a script in a Make target (example `format`) that checks for/replaces `interface{}` so that there are no `interface{}` added in future PR's? On the other side is it worth the effort for just a little bit of bonus code consistency?

Can easily be done with golangci-lint, see [Examplee](https://golangci-lint.run/usage/linters/#gofmt)

**Comment by rfranzke** [comment]
@majst01 Do you want to augment https://github.com/gardener/gardener/blob/master/.golangci.yaml.in accordingly?

**Comment by majst01** [comment]
> @majst01 Do you want to augment https://github.com/gardener/gardener/blob/master/.golangci.yaml.in accordingly?

done

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
