### PR TITLE
Deploy namespace during shoot deletion

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area high-availability
/area control-plane
/kind enhancement

**What this PR does / why we need it**:
The control-plane namespace in the seed should be redeployed during shoot deletion, mainly to update the zone information in the namespace. Earlier, clusters were stuck in deletion because the zones regarding the persistent volumes in use were not up-to-date.

**Special notes for your reviewer**:
/cc @shreyas-s-rao @unmarshall @dguendisch 

**Release note**:

```other operator
The shoot namespace in seeds is redeployed during shoot deletion to update the zones in use.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Review by shreyas-s-rao — APPROVED** [review]
@timuthy thanks a lot for fixing this!
/lgtm

**Pull request merged**
