### PR TITLE
Update Golang to 1.16.2

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR updates the Golang version to v1.16.2 and eliminates both the `packr` and `go-bindata` libraries in favor of the native `go:embed`.

**Special notes for your reviewer**:
/cc @ialidzhikov @timuthy 
/squash

**Release note**:

```noteworthy developer
The Golang version has been updated to `v1.16.2`. Support of `packr` and `go-bindata` has been dropped in favor of the native `go:embed`.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
I assume the `verify` step will fail because the pipeline is still using the `1.15` images of Golang which we only can change after merging this PR.

**Comment by vpnachev** [comment]
Seems that https://github.com/golang/go/issues/43985 is fixed in 1.16.1 (ref https://github.com/gardener/terraformer/pull/82).

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
image
Nice!
/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Thanks for the reviews, I'll force-merge this PR and adapt the pipeline definition to properly reflect the 1.16 version.

**Pull request merged**
