### PR TITLE
Gardenlet syncs Shoot certificate authorities in the Garden cluster

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
Gardenlet syncs Shoot certificate authorities in the Garden cluster in the `gardener-system-shoot-ca` namespace. This is a prerequisite for https://github.com/gardener/gardener-discovery-server/issues/31

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
The `gardenlet` now synchronizes shoot certificate authorities in the Garden cluster in a namespace called `gardener-system-shoot-ca`.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
/assign

The `gardenlet` already syncs the CA certificates into a `ConfigMap` in the respective project namespaces. Can't we rather use those instead of duplicating the data into yet another namespace?

**Comment by dimityrmirchev** [comment]
> The `gardenlet` already syncs the CA certificates into a `ConfigMap` in the respective project namespaces. Can't we rather use those instead of duplicating the data into yet another namespace?

The main reason of copying the data to another namespace is the fact that users can modify the configmaps in their namespaces. A malicious actor can modify the certificate bundles, forcing the discovery server to serve tampered data. Similar to https://github.com/gardener/gardener/pull/9024#discussion_r1479477678

**Comment by rfranzke** [comment]
OK, almost a year, I don't remember all details 😅 Thanks for the link. Not sure why it wasn't discussed back then, but wouldn't it be much easier and straight-forward to prevent users from tampering with this `ConfigMap` by protecting this via admission (i.e., only allow `gardenlet` to manipulate)? I think this would just be a few lines of code, and if we did it also for other `gardenlet`-synced resources in their project namespaces, we would increase their reliability as well.

**Comment by dimityrmirchev** [comment]
> Not sure why it wasn't discussed back then, but wouldn't it be much easier and straight-forward to prevent users from tampering with this ConfigMap by protecting this via admission (i.e., only allow gardenlet to manipulate)?

This is a good question. The only thing that I can remember is that we wanted to limit the permissions of the `serviceaccount` that the `gardener-discovery-server` uses, because it is an internet facing component. Having said that I think this is not really a concern right now since having read access to all `configmaps` is not that critical (in comparison to having read access to secrets for example). I also found [this clarification](https://github.com/gardener/gardener/blob/master/docs/proposals/24-shoot-oidc-issuer.md#clarifications) that mentions the same reason, but does not discuss the usage of an admission. Maybe we forgot to discuss this back then 😅 

> I think this would just be a few lines of code, and if we did it also for other gardenlet-synced resources in their project namespaces, we would increase their reliability as well.

This is a good idea that I am willing to explore. Do you have in mind a separate admission plugin that is dedicated for that sole purpose or something else?

**Comment by rfranzke** [comment]
> This is a good question. The only thing that I can remember is that we wanted to limit the permissions of the `serviceaccount` that the `gardener-discovery-server` uses, because it is an internet facing component. Having said that I think this is not really a concern right now since having read access to all `configmaps` is not that critical (in comparison to having read access to secrets for example).

Agree 👍🏻 

> I also found [this clarification](https://github.com/gardener/gardener/blob/master/docs/proposals/24-shoot-oidc-issuer.md#clarifications) that mentions the same reason, but does not discuss the usage of an admission. Maybe we forgot to discuss this back then 😅
>
> This is a good idea that I am willing to explore. Do you have in mind a separate admission plugin that is dedicated for that sole purpose or something else?

Thank you, appreciated. I think we would need a new handler in the `gardener-admission-controller` to cover the `Secret`s and `ConfigMap`s. WDYT?

**Comment by dimityrmirchev** [comment]
> Thank you, appreciated. I think we would need a new handler in the gardener-admission-controller to cover the Secrets and ConfigMaps. WDYT?

Yes. This aligns with what I thought.

I will close this PR for now and explore the other approach (eventually propose an implementation) when I finish with my current assignments 

/close

**Pull request closed without merging**
