### PR TITLE
Update apiserver-proxy sidecar image version

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Similar to https://github.com/gardener/gardener/pull/6828 - this PR updates the apiserver-proxy sidecar image. Around my changes in the apiserver-proxy, I executed the release tests and the default tests in my local setup against apiserver-proxy images that are based on revisions after v0.7.0. During the testing there was no test failure or I was not able to notice abnormal thing.
That's why I rather assume that the reason for the flakes back then was another one. 

**Release note**:

```other operator
The following image is updated:
- eu.gcr.io/gardener-project/gardener/apiserver-proxy: v0.6.0 -> v0.7.0
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Do we need this intermediate update? Isn't the plan to anyways cut v0.8.0 to fix #6818?

**Comment by ialidzhikov** [comment]
> Do we need this intermediate update? Isn't the plan to anyways cut v0.8.0 to fix #6818?

Yes, that's the plan. If you want, I can close this PR and we then directly go with v0.6.0 -> v0.8.0 update.

**Comment by rfranzke** [comment]
OK, I don't have any preference, I was just curious whether this is prerequisite. I assume we don't want to ship this with v1.58, do we? In this case, we can probably wait for v0.8.0 - otherwise, let's assign the milestone and merge this PR.

**Comment by ialidzhikov** [comment]
The PR is not urgent, so no need to rush for the v1.58 milestone. Then, I will close this PR and let the automation open PR when the v0.8.0 release is cut. 👍 

/close

**Comment by ialidzhikov** [comment]
I actually changed my mind. It won’t hurt if we do the v0.7.0 update first - just to prove that there is nothing wrong with it. No need to add to the v1.58 milestone.

/reopen

**Comment by ialidzhikov** [comment]
/close
in favour of https://github.com/gardener/gardener/pull/6869

**Pull request closed without merging**
