### PR TITLE
Let the metrics-server tolerate the NoSchedule/NoExecute taints

### PR DESCRIPTION
**Pull request by istvanballok**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Let the metrics-server tolerate the NoSchedule/NoExecute taints

Motivation: Shoot owners can taint their nodes to control scheduling and execution of the workload. If the system components did not tolerate these taints, it can happen that they can not be scheduled at all.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @rickardsjp @hendrikKahl 

**Release note**:

```other operator
The metrics-server tolerates the NoSchedule/NoExecute taints
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Let's go ahead with this for now until we have a better solution for explicitly tolerating the taints of the worker pools allowing system components to run.

/approve
/lgtm

**Review by rickardsjp — APPROVED** [review]
/lgtm

**Comment by istvanballok** [comment]
/unhold
Note that there was an issue that we caught while verifying the PR in the remote local-setup: we used the key "Key" instead of the key "Effect". [Diff](https://github.com/gardener/gardener/compare/7ad5c499842a5d10f9d92f340aba6529f85b1906..f26012487b1ba8377f8b99fcbef95e84c1cb79f3)

**Pull request merged**
