### PR TITLE
Add an overview image to illustrate the purpose of extensions and managers

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
**How to categorize this PR?**
/area documentation
/kind enhancement

**What this PR does / why we need it**:
The image added to the extensions overview page of the documentation illustrates the purpose and communication flow of Gardener Extensions and Machine Controller Managers. It should help to better understand and differentiate when which code path is relevant.

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @NotTheEvilOne for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by rfranzke — CHANGES_REQUESTED** [review]
Thanks for the PR!

Though, I guess a few things aren't fully accurate:

1. It's confusing that there's an arrow from `Gardener Admin` to `Seed Namespace ` with label `Requests new Shoot Cluster`. First of all, it could by any user, it is not needed to be an admin. Secondly, there is the garden cluster (with the Gardener API server) which hosts the only API to "request" (I'd actually call it "create") a shoot cluster, see https://github.com/gardener/gardener/blob/master/docs/concepts/architecture.md. Thirdly, what is the `Seed Namespace` (especially in comparison to the `Shoot Control Plane Namespace`)? The component which creates the `Shoot Control Plane Namespace` is the gardenlet running in the seed cluster (after it has observed the `Shoot` resource in the garden cluster).
2. I think the `Shoot workers` and `Shoot Cluster` connection is confusing.

There are probably more. What do you think about rather enhancing the existing architecture image (https://github.com/gardener/gardener/raw/master/docs/concepts/gardener-architecture-detailed.png) with the extension controllers (I think that's the only thing that is missing currently) instead of creating an entirely new image?

**Comment by berendt** [comment]
> There are probably more. What do you think about rather enhancing the existing architecture image (https://github.com/gardener/gardener/raw/master/docs/concepts/gardener-architecture-detailed.png) with the extension controllers (I think that's the only thing that is missing currently) instead of creating an entirely new image?

@rfranzke We are revising this graphic as well. I think it is already full and should not be filled with more details.

**Comment by rfranzke** [comment]
Hm, ok, fair enough, still, it's only the extension controllers that are missing from the "overall architecture" picture (at least from what you are contributing here). Yes, it's already "full" and very detailed, but is it really worth to create an entire new diagram instead of creating an additional box in the seed?
Anyways, I'm not against it, so if you rather want a smaller, less detailed, more scoped diagram focusing only on extensions then I'm fine. Though, the current picture is still somewhat confusing and a little inaccurate and should be corrected.

**Comment by rfranzke** [comment]
We discussed this PR internally and given the many inaccuracies in the proposed picture, we would rather
/close
it for now. Also, see https://github.com/gardener/gardener/pull/4157#issuecomment-859310002, we figured that we rather tend towards the "Excalidraw" style (and working model) for newer diagrams. Your points that today's architecture picture is quite complex already are still perfectly valid. As outlined in https://github.com/gardener/gardener/pull/4157#issuecomment-859310002, we will have to re-draw it soon with a cleaner, less complex look. Most likely, this "v2" will incorporate what's missing today and what you are contributing here, i.e., the extension controllers.

**Pull request closed without merging**
