### PR TITLE
Introduce `rotate-credentials-{start,complete}` operation annotations

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
This PR introduces new `rotate-credentials-{start,complete}` operation annotations for `Shoot`s which can be used to start or complete the rotation of all Gardener-provided/Gardener-generated credentials.

**Which issue(s) this PR fixes**:
Related to #3292

**Release note**:

```feature user
There are two new `rotate-credentials-{start,complete}` operation annotations for `Shoot`s which can be used to start or complete the rotation of all Gardener-provided/Gardener-generated credentials.
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by krgostev — APPROVED** [review]
/lgtm

**Pull request merged**
