### PR TITLE
Fix cluster sync after retry operation

### LINKED ISSUE #2452: v1alpha1.Cluster Shoot lastOperation is not updated after retry operation
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:
v1alpha1.Cluster Shoot lastOperation is not updated after retry operation is applied on Shoot.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with wrong credentials

2. Ensure that after given period of time, the Shoot will be marked as `Failed` and the Infrastructure in the Seed will be in `Error` state

3. Update the Shoot credentials and annotate the Shoot with `gardener.cloud/operation=retry`

4. Ensure that the `v1alpha1.Cluster` Shoot lastOperation will stay in `Failed` state even after the retry and this will prevent the extension controllers to retry.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.5.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR replicates the correct shoot status through the `cluster` resource to the seed after the shoot was triggered for a retry (`gardener.cloud/operation:retry`).

**Which issue(s) this PR fixes**:
Fixes #2452

**Special notes for your reviewer**:

**Release note**:

```improvement operator
An issue has been fixed which prevented the `retry` operation for shoots from working reliably in case of a reconciliation.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
... nice catch :)
/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
@timuthy when this is merged can you please open a cherry-pick PR against `release-1.6` (and `release-1.5`, potentially?)? Do you also have time to drive a hotfix?

**Comment by timuthy** [comment]
> @timuthy when this is merged can you please open a cherry-pick PR against `release-1.6` (and `release-1.5`, potentially?)? Do you also have time to drive a hotfix?

Yes @rfranzke, I'll take care of this

**Pull request merged**
