### PR TITLE
Fix LICENSE and NOTICE

### PR DESCRIPTION
**Pull request by msohn**
- move legal information about subcomponents from NOTICE to LICENSE
- include verbatim copy of subcomponent licenses in LICENSE
- add disclaimer regarding third party APIs

### CODE REVIEW

**Comment by msohn** [comment]
do not yet merge this PR

**Comment by rfranzke** [comment]
@msohn , what's the status of that PR?

**Comment by msohn** [comment]
I am still waiting for feedback from the legal team :-(
I pinged them yesterday

**Review by msohn — COMMENTED** [review]
looks now good to me

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
