### PR TITLE
Make sure secret manager's clean up is executed at the end of the flow

### PR DESCRIPTION
**Pull request by ialidzhikov**
/area control-plane
/kind bug

After https://github.com/gardener/gardener/issues/5865 got resolved, we noticed the following issue as well. We see that the vpn-seed-server was failing requests with logs:
```
2022-04-28 08:41:53 TCP connection established with [AF_INET]10.32.1.166:46454
2022-04-28 08:41:55 10.32.1.166:46454 Authenticate/Decrypt packet error: packet HMAC authentication failed
2022-04-28 08:41:55 10.32.1.166:46454 TLS Error: incoming packet authentication failed from [AF_INET]10.32.1.166:46454
2022-04-28 08:41:55 10.32.1.166:46454 Fatal TLS error (check_tls_errors_co), restarting
```

We see that the vpn-seed-server Secrets were recreated (notice that the Secret is newer than the Pod) and the vpn-seed-server Pod was mounting the old Secret.
```
$ k -n shoot-foo-bar get secret vpn-seed-server-tlsauth-a1d0aa00
NAME                               TYPE     DATA   AGE
vpn-seed-server-tlsauth-a1d0aa00   Opaque   1      25h

$ k -n shoot-foo-bar get po vpn-seed-server-68bd4454d4-gqdtb
NAME                               READY   STATUS    RESTARTS   AGE
vpn-seed-server-68bd4454d4-gqdtb   2/2     Running   0          34h
```

We see that it was actually gardenlet who deleted the vpn-seed-server Secrets as part of the `Cleaning no longer required secrets` (currently executed "at the end" of the flow).

https://github.com/gardener/gardener/blob/c72255a52840f824a7afd469ff2479d217c88c1a/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L634-L641

```
{"log":"2022-04-28T02:35:51.96788104Z stderr F {\"level\":\"info\",\"ts\":\"2022-04-28T02:35:51.967Z\",\"logger\":\"secretsmanager\",\"msg\":\"Deleting stale secret\",\"namespace\":\"shoot-garden-az\",\"namespace\":\"shoot-foo-bar\",\"name\":\"vpn-seed-server-tlsauth-a1d0aa00\"}"
```

`Cleaning no longer required secrets` is supposed to be executed after all steps. But our graph does not have a single leaf(terminal vertex) and `Cleaning no longer required secrets` can be executed before a step that requires the secretManager. Such executing leads to a Secret to be deleted as a step that requires the secretManager failed early (or was not executed) and the Secret is not present in the internal store of the secretManager.

To fix this issue, this PR moves the `Cleaning no longer required secrets` step to be executed after the flow execution.

Special thanks to @rfranzke for helping with this issue.

**Release note**:

```bugfix operator
A potential issue causing control plane Secrets to be wrongly deleted due to a failed (or not yet executed) task is now fixed.
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
Nice, thank you!

/lgtm
/approve

**Pull request merged**
