### PR TITLE
Update istio to 1.15.3

### PR DESCRIPTION
**Pull request by axel7born**
How to categorize this PR?

/area networking
/kind enhancement

What this PR does / why we need it:
Update istio to v1.15.3.

Which issue(s) this PR fixes:
None

Special notes for your reviewer:

Release note:

```other operator
Update istio to v1.15.3
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Review by rfranzke — COMMENTED** [review]
/approve

**Pull request merged**
