### PR TITLE
Reapply "Drop deprecated .spec.pools[].userData from `extensions.gardener.cloud/v1alpha1.Worker` API"

### LINKED ISSUE #9545: Gardener fails to create shoots with > ~80 worker pools
**How to categorize this issue?**

/area scalability
/kind bug

**What happened**:
When attempting to create a shoot with over approximately 80 nodepools, the shoot becomes stuck in the `Create Processing` state. The shoot generates an error message stating: `Flow "Shoot cluster reconciliation" encountered task errors: [task "Configuring shoot worker pools" failed: retry failed with context deadline exceeded, last error: etcdserver: request is too large] Operation will be retried.`

Upon investigation, it was discovered that the `Worker` resource, which is created for the shoot, becomes excessively large due to each `WorkerPool` containing userData necessary for machine bootstrap. This exceeds the etcd's max-request-bytes limit of 1.5MiB for the worker resource.

**What you expected to happen**:
The shoot should be successfully created.

**How to reproduce it (as minimally and precisely as possible)**:
Create shoots with a large number (80-90+) of nodepools.

**Proposed Solution:**
Suggest replacing the [userData field in the WorkerPool type](https://github.com/gardener/gardener/blob/f6e3efa6fbaafb42025e14b6af8ee4b03d6a5cb4/pkg/apis/extensions/v1alpha1/types_worker.go#L145) with a secretReference. This approach aligns with the OperatingSystemConfig resource, which already stores its cloud_config in a secret. Refer to the [OperatingSystemConfig documentation](https://github.com/gardener/gardener/blob/master/docs/extensions/operatingsystemconfig.md?plain=1#L268-L308) for more details.

**Tasks**:

- [x] https://github.com/gardener/gardener/pull/9722
- Adapt `Worker` extensions (after `v1.95` has been released)
  - [x] [`provider-alicloud`](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/727
  - [x] [`provider-aws`](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/961
  - [x] [`provider-azure`](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/868
  - [x] [`provider-gcp`](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/767
  - [x] [`provider-openstack`](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/776
  - [x] [`provider-equinix-metal`](https://github.com/gardener/gardener-extension-provider-equinix-metal): https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/314
- [x] ~~After `gardener/gardener@v1.100` has been released~~: Drop deprecated `UserData` field from `extensions.gardener.cloud/v1alpha1.Worker` resource (originally done after `v1.100` release with https://github.com/gardener/gardener/pull/10220, but reverted with https://github.com/gardener/gardener/pull/10285), now planned after `gardener/gardener@v1.104`): https://github.com/gardener/gardener/pull/10542

**Environment**:

- Gardener version: v1.82.3
- Kubernetes version (use `kubectl version`): v1.26.14
- Cloud provider or hardware configuration: 
  - openstack-provider v1.39.2
  - coreos extension v1.21
- Others:
  - etcd-druid v0.20.0

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
This commit reverts https://github.com/gardener/gardener/pull/10285 and cleans up two more small TODOs.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/9545

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
The limitation of having at maximum ~80 worker pools in `Shoot`s has been lifted. Much higher numbers should be possible now (concrete limit depends on the amount of configuration within the pools (e.g., labels, taints, annotations, etc.)).
```

### CODE REVIEW

**Comment by rfranzke** [comment]
/hold
until https://github.com/gardener/gardener/pull/10539 is merged

**Comment by ialidzhikov** [comment]
/hold cancel
https://github.com/gardener/gardener/pull/10539 is merged

**Review by ScheererJ — APPROVED** [review]
Thanks a lot for removing the limit. Let's see how far we can scale now ;-) .

/lgtm
/approve

**Comment by hown3d** [comment]
I'm excited to see this being released 🥳

**Pull request merged**
