### PR TITLE
Fix the guestbook integration test for alicloud Shoots

### PR DESCRIPTION
**Pull request by ialidzhikov**
/area testing
/kind bug
/kind regression

**What this PR does / why we need it**:
After https://github.com/gardener/gardener/pull/6446, the guestbook integration against an alicloud Shoot fails with:
```
$ k -n gardener-e2e-6x25v get po
NAME             READY   STATUS             RESTARTS        AGE
redis-master-0   0/1     CrashLoopBackOff   9 (3m10s ago)   24m

$ k -n gardener-e2e-6x25v logs redis-master-0
/bin/bash: line 15: /run.sh: No such file or directory
```

The reason is that the `master.command` value in https://github.com/gardener/gardener/blob/2a7155d5a73c6c36c2161f4374bee96790327689/test/framework/applications/guestbooktest.go#L149-L151 gets overwritten in https://github.com/gardener/gardener/blob/2a7155d5a73c6c36c2161f4374bee96790327689/test/framework/applications/guestbooktest.go#L153-L159

**Release note**:

```bugfix developer
An issue causing the guestbook integration test to fail against alicloud Shoot clusters is now fixed.
```

### CODE REVIEW

**Comment by dguendisch** [comment]
So this means the old redis image could even run without specifying the command on alicloud (as there it would have been overwritten)?
Anyway, looks good.
/lgtm

**Review by acumino — APPROVED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
