### PR TITLE
Adds generation of password for the monitoring stack

### PR DESCRIPTION
**Pull request by plkokanov**
This change makes it so that a different password for the
monitoring stack is generated and the kubeconfig
basic authentication credentials aren't reused.

Also disables grafana login form so that the default grafana
admin user cannot be used

### CODE REVIEW

**Review by dkistner — CHANGES_REQUESTED** [review]
You still access the ``grafana-secret.yaml`` in ``charts/seed-monitoring/charts/grafana/templates/grafana-deployment.yaml`` line 21. 

Error:
```
time="2018-07-16T14:52:19+02:00" level=error msg="Failed to reconcile Shoot cluster state: Errors occurred during flow execution: '(*Botanist).DeploySeedMonitoring' returned 'render error in \"seed-monitoring/charts/grafana/templates/grafana-deployment.yaml\": template: seed-monitoring/charts/grafana/templates/grafana-deployment.yaml:21:33: executing \"seed-monitoring/charts/grafana/templates/grafana-deployment.yaml\" at <include (print $.Tem...>: error calling include: template: no template \"seed-monitoring/charts/grafana/templates/grafana-secret.yaml\" associated with template \"gotpl\"', '(*Botanist).EnsureIngressDNSRecord' returned 'services \"addons-nginx-ingress-controller\" not found' Operation will be retried." opid=<redacted> shoot=<redacted>
```

**Comment by plkokanov** [comment]
@dkistner didn't throw an error on my local landscape so I must've forgot to remove it. Will fix it asap.

**Comment by dkistner** [comment]
:warning: Also one TODO for the dashboard regarding this PR: https://github.com/gardener/dashboard/issues/135

**Comment by plkokanov** [comment]
Actually now that I look at it, it might be better to rename the secret containing the username and password to `monitoring-ingress-credentials`. Here's why: 
 - secrets that end with '-basic-auth' actually contain the base64 encoded username + password for ingress resources in a single auth field. E.g. `grafana-basic-auth`, `alertmanager-basic-auth` and so on. Whereas `monitoring-ingress-credentials` will contain the  username and the base64 encoded password in two separate fields.
 - in the logging stack for the kibana inside the seed garden namespace I think that we will be using `kibana-ingress-credentials` for the same reason as above (so as to differentiate it from the eventual `kibana-basic-auth` used for the ingress resource).

**Comment by dkistner** [comment]
Yes right, think nginx ingress controller relies on the structure of basic-auth secrets, with credentials stored at ``.data.auth`` in format ``b64(<username>:<password>)``. But you are not using the monitoring secret directly to configure basic auth for ingress, therefore it would maybe just a naming convention clash. I would appreciate if you rename the secret, then it will be clear that this secret is not used to configure ingress directly.

If you decide to do that. Could you please also update the referenced issue for the dashboard?

**Comment by plkokanov** [comment]
@dkistner @mvladev Changed the secret name and squashed the commits. Could you guys have another look?

**Review by dkistner — APPROVED** [review]
Lgtm now. Thanks also for updating the Dashboard issue.
@mvladev Could you also have a look?

**Review by mvladev — APPROVED** [review]

**Comment by dkistner** [comment]
@plkokanov Could you please rebase the PR?

**Comment by plkokanov** [comment]
@dkistner should be rebased now

**Pull request merged**
