### PR TITLE
Increase per node resources for metrics-server.

### PR DESCRIPTION
**Pull request by amshuman-kr**
**How to categorize this PR?**

/area control-plane auto-scaling
/kind impediment

**What this PR does / why we need it**:
Increase per node resources for metrics-server to better support nodes with lots of pods in them.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
While the increased base memory in #4386 proved enough while testing with varying number of nodes, nodes that have a lot of pods like those in shooted seeds seem to need more memory per node.

The shooted seeds in the landscape seem to need anything from `5Mi` to `8Mi` per node. But I have configured `14Mi` per node erring on the side of caution because the `requests` and `limits` are the same.

cc @vpnachev @ialidzhikov  

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — DISMISSED** [review]
/lgtm

**Review by vpnachev — DISMISSED** [review]
/lgtm

**Comment by vpnachev** [comment]
/needs rebase

to get #4403

**Comment by amshuman-kr** [comment]
I have rebased and the image builds have now passed.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
