### PR TITLE
Remove bird as a calico backend for Azure

### PR DESCRIPTION
**Pull request by zanetworker**
**What this PR does / why we need it**:
Azure does not support **IPinIP** and as a result **Calico's Bird** can not be used, this PR removes bird as a calico backend for Azure. 

For more information: https://docs.projectcalico.org/v3.5/reference/public-cloud/azure

```noteworthy user
Calico is now only used for policies on Azure, Bird backend is removed.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by mvladev** [comment]
What about 

```
On Kubernetes, also complete the following.

    Ensure that the selected pod’s subnet is a part of your Azure virtual network IP range.

    Include the name of your routing table in the configuration file of your Kubernetes Azure cloud provider.
```

https://docs.projectcalico.org/v3.5/reference/public-cloud/azure#azure-user-defined-routes

**Comment by dkistner** [comment]
@mvladev This seems to be a revert to the old networking solution which we had before we have switched to Calico for Azure. The route table is still part of the terraform infra job for Azure and even the cloud provider still config contains the reference. https://github.com/gardener/gardener/blob/74e0c8d9ce71101841e247eeca0d649703fad49b/pkg/operation/cloudbotanist/azurebotanist/controlplane.go#L24-L47

**Review by dkistner — APPROVED** [review]
/lgtm

**Comment by marwinski** [comment]
Thanks a lot for reacting to this so quickly.

**Pull request merged**
