### PR TITLE
Fix race condition in WaitCleanup

### LINKED ISSUE #4648: gardenlet is not waiting for Extension resources to be deleted
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:

I observed some clusters that cannot be deleted due to a redeployed shoot-dns-extension. 
All other resources in the namespace are already deleted (no pods, no deployments, no services).
```
resource shoot--<shoot-name>/extension-shoot-dns-service-shoot still exists
```

According to the gardenlet logs, all clusters had the following flow:
- create shoot
- some error occurred, so the shoot did get ready (different error on the different clusters)
- shoot gets deleted
- shoot was mostly successfully deleted and in state `Waiting until the namespace .. has been deleted` (see the logs at `2021-09-06T20:36:45Z`).
- Then after the next reconcile (`2021-09-06T20:51:40Z`) the gardenlet noticed the extension resource and was since then in `Error deleting Extension resource`

See the attached redacted logs for one of the concrete gardenlet logs.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

I was unable to reproduce on a dev cluster. so it seems like a timing issue.

**Anything else we need to know?**:

I observed that behavior for multiple shoots on different cloudproviders.

**Environment**:

- Gardener version: 1.30.1
- Kubernetes version (use `kubectl version`): 1.19.10
- Cloud provider or hardware configuration: os and aws

[leaked-dns-ext.gardenlet.log](https://github.com/gardener/gardener/files/7144207/leaked-dns-ext.gardenlet.log)

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:

This PR fixes a race in the `WaitCleanup` logic of Extension, OSC and ContainerRuntime components, that can occur if the `CachedRuntimeClients` feature gate is enabled.
`WaitCleanup` is now split into `WaitCleanup` (waits for all resources to be deleted, e.g. in delete flow) and `WaitCleanupStaleResources` (only waits for unwanted resources to be deleted, i.e. after a call to `DeleteStaleResources` in the reconcile flow).
See the linked issue and commit messages for more details. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/4648

**Special notes for your reviewer**:

Thanks @timuthy for your input on the solution.
/squash

**Release note**:

```bugfix operator
A race in gardenlet has been fixed, that caused gardenlet not to wait for `Extension` and other resources to be deleted if the `CachedRuntimeClients` feature gate is enabled.
```

### CODE REVIEW

**Comment by timebertt** [comment]
Doing some quick test runs now.
/invite @timuthy 
/priority 1
/needs cherry-pick

**Comment by timuthy** [comment]
/assign
Thanks @timebertt for helping out on this.

**Comment by timebertt** [comment]
My quick tests (create, hibernate, delete shoot) looked good.

**Comment by vpnachev** [comment]
> that can occur if the CachedRuntimeClients feature gate is enabled

`CachedRuntimeClients` is still in alpha state, therefore:
/unmilestone v1.32
/remove needs/cherry-pick
/priority 3

**Comment by timebertt** [comment]
I simplified this PR and removed the last commit (back and forth with the fake retry ops in unit tests).
Originally, I wanted to fake `retry.UntilTimeout` to speed up unit tests (both the container runtime and extension component suite take about 2s) and make them time-insensitive.
The problem is, that the tested functions (e.g. `Wait`) use `flow.ParallelExitOnError` to execute `extensions.WaitUntilExtensionObjectReady` in parallel (i.e., in multiple goroutines). These goroutines then read the alias variable `retry.UntilTimeout`, which was overwritten by the testing goroutine moments earlier. Thus, the race detector might be complaining about this.

The proper way to improve the tests would be to pass a `retry.Waiter` on creation of the component, not overwrite any global variable and pass the waiter down to `WaitUntilExtensionObjectReady`. This will speed up and stabilize the tests, while still making the race detector happy.
This will require some more work, so it should be done in a separate PR.

**Comment by timebertt** [comment]
> /remove needs/cherry-pick

This bug can cause significant manual ops effort, see https://github.com/gardener/gardener/issues/4648.
I think, it is definitely worthy of being cherry picked and delivered with a patch release, even though the feature gate is in alpha state.

> /unmilestone v1.32

Even if you don't want to cherry-pick it (which I could maybe see a point in it), I don't understand why you would consciously not include a very minor fix like this (with a rather big impact) in the upcoming release, which is only planned for next week.
Please reconsider this and get in touch with me, if you have good reasons not to include it in v1.32.
Same applies to https://github.com/gardener/gardener/pull/4666 FMPOV.

**Comment by vpnachev** [comment]
Let me share how I see the urgency of this change: If somebody was really taking care about the ops effort caused by the bug fixed with this PR, the cached runtime feature gate would have been disabled immediately, but not - it is still enabled and operators have to live with it. No matter how simple is the fix, single line of configuration change is much easier and faster then implementing a fix, testing it, verifying it, release it and deliver it to the affected users. 


I have no time to review and test the change, therefore I cannot approve and merge it, but have added it to the v1.32 milestone. If it is merged by Monday next week, it will be included in v1.32.0.

**Comment by stoyanr** [comment]
/rebase
It should be rebased and the new generation of OSC names from #4666 properly included (otherwise it's a compiler error).

**Comment by timebertt** [comment]
> /rebase
> It should be rebased and the new generation of OSC names from #4666 properly included (otherwise it's a compiler error).

Yes, done. Rebased and adapted to #4666

**Comment by stoyanr** [comment]
Tested successfully the following scenarios:
* Creating / reconciling / deleting a shoot (with the `shoot-dns-service` extension).
* Hibernating / waking-up a shoot 
* Migrating a shoot to a different seed and back to the original seed
* Adding / removing the `shoot-dns-service` extension to / from a shoot
* Changing the OS of a shoot's worker and back (with #4666 included)
* Changing the CRI of a shoot's worker and back
* Changing the seed, the CRI, the OS, and adding the `shoot-dns-service` extension all at the same time (to cause the new extension resources to be reconciled during a restore)

**Review by stoyanr — APPROVED** [review]
I tested multiple interesting scenarios successfully. I wasn't able to reproduce the original issue though (I think it's rather hard in general), so I can't be 100% sure it's fixed by the tests I performed (although the code certainly looks good).
/lgtm

**Comment by timebertt** [comment]
Thank you very much @stoyanr for your review and extensive testing. Much appreciated!

**Pull request merged**
