### PR TITLE
Release responsible schedule for v1.57 until v1.63

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
Extends the docs with a proposal for the release responsible schedule for v1.57 until v1.63.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by timebertt — COMMENTED** [review]
/lgtm
🙊

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
Feedback received from everybody, so

/approve
/unhold

**Pull request merged**
