### PR TITLE
Clean up the hvpa component and its usages

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area auto-scaling
/kind cleanup

**What this PR does / why we need it**:
This PR is the 3rd PR related to the HVPA removal. The first 2 PRs were:
1. https://github.com/gardener/gardener/pull/10796
2. https://github.com/gardener/gardener/pull/10800

Context: With https://github.com/gardener/gardener/pull/10659 in Gardener v1.106 the HVPA feature gate was deprecated and locked to its default value - `false`. As described in https://github.com/gardener/gardener/pull/10796#discussion_r1838236028, in this way we ensure that the gardenlet/operator will destroy the HVPA component and its CRD on Seed/Garden reconciliation. After the HVPA component and its CRD are already destroyed since v1.106, we can clean up the associated code paths which are no longer used.

This PR in particular cleans up the hvpa component usages in the seed/garden controllers, then it cleans up the hvpa component itself.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
The HVPA component is removed. Before updating to this version of Gardener, make sure that you upgraded to v1.106.0 and all Seed and Garden resources reconciled with that version. This is required to ensure that the HVPA component and its CRD were properly cleaned up.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
`pull-gardener-e2e-kind-migration` failed with:

```
Error: bad file 'hack/../example/gardener-local/gardenlet/operator/patch-imagevector-overwrite.yaml': yaml: line 13: could not find expected ':'
Build [local-skaffold/gardenlet] failed: exit status 1
```

/test pull-gardener-e2e-kind-migration

**Comment by ialidzhikov** [comment]
```
  [FAILED] Timed out after 33.122s.
  The function passed to Eventually failed at /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_update_delete.go:78 with:
  Unexpected error:
      <*fmt.wrapError | 0xc000887800>: 
      error discovering kubernetes version: Get "https://api.e2e-default-wl.local.external.local.gardener.cloud/version": read tcp 172.18.255.1:59134->172.18.255.1:443: read: connection reset by peer - error from a previous attempt: read tcp 172.18.255.1:59118->172.18.255.1:443: read: connection reset by peer
      {
          msg: "error discovering kubernetes version: Get \"https://api.e2e-default-wl.local.external.local.gardener.cloud/version\": read tcp 172.18.255.1:59134->172.18.255.1:443: read: connection reset by peer - error from a previous attempt: read tcp 172.18.255.1:59118->172.18.255.1:443: read: connection reset by peer",
          err: <*rest.wrapPreviousError | 0xc0008877a0>{
              currentErr: <*url.Error | 0xc000e26000>{
                  Op: "Get",
                  URL: "https://api.e2e-default-wl.local.external.local.gardener.cloud/version",
                  Err: <*net.OpError | 0xc0003e82d0>{
                      Op: "read",
                      Net: "tcp",
                      Source: <*net.TCPAddr | 0xc000807e90>{
                          IP: [172, 18, 255, 1],
                          Port: 59134,
                          Zone: "",
                      },
                      Addr: <*net.TCPAddr | 0xc000807ec0>{
                          IP: [172, 18, 255, 1],
                          Port: 443,
                          Zone: "",
                      },
                      Err: <*os.SyscallError | 0xc000887760>{
                          Syscall: "read",
                          Err: <syscall.Errno>0x68,
                      },
                  },
              },
              previousError: <*net.OpError | 0xc00059a9b0>{
                  Op: "read",
                  Net: "tcp",
                  Source: <*net.TCPAddr | 0xc000c7a420>{
                      IP: [172, 18, 255, 1],
                      Port: 59118,
                      Zone: "",
                  },
                  Addr: <*net.TCPAddr | 0xc000c7a450>{
                      IP: [172, 18, 255, 1],
                      Port: 443,
                      Zone: "",
                  },
                  Err: <*os.SyscallError | 0xc000a45ec0>{
                      Syscall: "read",
                      Err: <syscall.Errno>0x68,
                  },
              },
          },
      }
  occurred
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/shoot/create_update_delete.go:88 @ 11/15/24 14:13:54.65
```

/test pull-gardener-e2e-kind

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Pull request merged**
