### PR TITLE
set_dependency_version script: Add tune2fs as logging image as well

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area dev-productivity
/area logging
/kind enhancement

**What this PR does / why we need it**:
The tune2fs image was added with https://github.com/gardener/gardener/pull/7650. With this PR, the upgrade PRs generated by ci/cd should also bump the tune2fs image. Example where currently it does not bump it - ref https://github.com/gardener/gardener/pull/7874.

**Which issue(s) this PR fixes**:
See above

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by Kristian-ZH — APPROVED** [review]
/lgtm

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Pull request merged**
