### PR TITLE
[ci:component:github.com/gardener/logging:v0.55.1->v0.55.2]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` bugfix operator github.com/gardener/logging #197 @vlvasilev
Remove lastOperation check in fluent-bit-to-vali plugin.
```

### CODE REVIEW

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Review by istvanballok — COMMENTED** [review]
lgtm

**Pull request merged**
