### PR TITLE
Cleans up HVPA usages from `Roles` and `Clusterroles` and removes HVPA CRDs

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area auto-scaling
/kind cleanup

**What this PR does / why we need it**:
This PR is the 6th PR related to the HVPA removal. The first 5 PRs were:
1. https://github.com/gardener/gardener/pull/10796
2. https://github.com/gardener/gardener/pull/10800
3. https://github.com/gardener/gardener/pull/10851
4. https://github.com/gardener/gardener/pull/10853
5. https://github.com/gardener/gardener/pull/10860

This PR cleans up remaining HVPA usages:
- Removes HVPA from the clusterroles and roles used by `gardenlet` and `gardener-operator`
- Removes HVPA from the seed and operator client schemes
- Removes the HVPA CRD
- Cleans up go imports

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
This pr is rebased on top of https://github.com/gardener/gardener/pull/10860 so I will keep it in draft until that one gets merged.

**Release note**:

```breaking developer
The `autoscaling.k8s.io/v1alpha1.Hvpa` and `autoscaling.k8s.io/v1alpha1.HvpaList` resources were removed from the `pkg/client/kubernetes.SeedScheme` and `pkg/operator/client.RuntimeScheme`   
```
```other developer
The `HVPA` CRD has been removed from the codebase and is no longer generated.
```
```other operator
RBAC rules related to `HVPA` resources have been removed from `gardenlet` and `gardener-operator` - they are no longer necessary.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
```
Error: bad file 'hack/../example/gardener-local/gardenlet/operator/patch-imagevector-overwrite.yaml': yaml: line 13: could not find expected ':'
Build [local-skaffold/gardenlet] failed: exit status 1
```

/test pull-gardener-e2e-kind-ha-multi-zone

**Comment by ialidzhikov** [comment]
```
  [FAILED] Timed out after 30.001s.
  The function passed to Eventually failed at /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/seed/renew_garden_access_secrets.go:131 with:
  Expected
      <map[string]string | len:2>: {
          "provider-local-e2e-test-garden-access": "2024-11-28T14:30:48Z",
          "gardener.cloud/operation": "renew-garden-access-secrets",
      }
  not to have key
      <string>: gardener.cloud/operation
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/seed/renew_garden_access_secrets.go:132 @ 11/28/24 14:31:03.903
```

/test pull-gardener-e2e-kind

**Pull request merged**
