### PR TITLE
Update node local dns to v1.22.5

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Update node local dns to v1.22.5

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
Update node local dns to v1.22.5
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/approve

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
