### PR TITLE
Adapt network policies to reversed vpn.

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Adapt network policies to reversed vpn.

With reversed vpn only the vpn-seed-server pod in the cluster control plane has layer 3 routing
access to the shoot cluster. The kube-apiserver uses the vpn-seed-server as http proxy. Monitoring
utilizes kube-apiserver as another level of indirection.
This is why this change removes the annotations from kube-apiserver and prometheus in case reversed
vpn is active.
As there is basically no longer connectivity to the shoot networks it is also no longer necessary
to exclude the shoot networks from the private network range (allow-to-private-networks). This
allows additional scenarios where private IPv4 addresses are used in the shoot cluster as well as
for other services.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
`NetworkPolicy/allow-to-private-networks` now allows access to networks overlapping the shoot networks in case reversed VPN is active.
```
```other operator
`kube-apiserver` and `prometheus` pods are no longer allowed to access shoot networks in case reversed VPN is active.
```

/cc @DockToFuture @MartinWeindel

### CODE REVIEW

**Comment by rfranzke** [comment]
Does it make sense to have a release note?

**Comment by ScheererJ** [comment]
> Does it make sense to have a release note?

Added a release note.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Pull request merged**
