### PR TITLE
Auto-restart scheduler in shoot maintenance

### LINKED ISSUE #2722: Auto-restart kube-scheduler in maintenance time window
**How to categorize this issue?**

/area robustness quality
/kind enhancement
/priority normal
/topology seed
/exp beginner
/platform all

**What would you like to be added**:
With #2098 we have added the auto-restarts of the KCM (and other components with the respective labels) in the shoot's maintenance time windows. The rationale behind it was to circumvent stale cache/stuck controller behaviours. However, we have not enabled this for the `kube-scheduler` which is no different than KCM and could have the same problems.
Hence, let's also do the same for the `kube-scheduler` as we have seen the mentioned issues with it meanwhile as well.

/cc @hardikdr who might have more inputs/comments.

**Why is this needed**:
Robustness, less ops effort, better user experience.

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity robustness
/kind enhancement
/priority normal

**What this PR does / why we need it**:
The `kube-scheduler` is now auto-restarted in the shoot maintenance time window, similar to other controllers.

**Which issue(s) this PR fixes**:
Fixes #2722

**Special notes for your reviewer**:
As #2731 is still in discussion, I'm making this change now separately and rebase the PR later if necessary.

**Release note**:

```improvement operator
The `kube-scheduler` is now auto-restarted in the shoot maintenance time window, similar to other controllers.
```

### CODE REVIEW

**Review by timuthy — APPROVED** [review]
/lgtm

**Review by danielfoehrKn — APPROVED** [review]

**Comment by ialidzhikov** [comment]
We initially stared with restart for cloud-controller-manager, then we did the same for kcm and mcm, now we do it also the kube-scheduler in this PR. This sounds like we bury/workaround issues? Are there occurrences of kube-scheduler Pod which "hangs" for some reason? If yes, shouldn't we rather try to understand the root cause?

**Comment by rfranzke** [comment]
@ialidzhikov I don't think there are clear steps to reproduce the problems that we see (luckily very rarely). If you can help here it's highly appreciated to tackle the root cause in the first place, sure, but until then this one-time auto-restart in the maintenance time window is a simply thing to improve the ops experience.

**Pull request merged**
