### PR TITLE
Update `k8s.io/*`, `sigs.k8s.io/controller-runtime` dependencies

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
Update `k8s.io/*`, `sigs.k8s.io/controller-runtime` dependencies to their latest patch versions.
With this, GAPI also gets the new generic feature gate `UnauthenticatedHTTP2DOSMitigation` like KAPI, see #8665.

**Special notes for your reviewer**:
/cc @timuthy 

**Release note**:

```other operator
The following Golang dependencies have been updated:
- `k8s.io/*` from `v0.28.2` to `v0.28.3`
- `sigs.k8s.io/controller-runtime` from `v0.16.2` to `v0.16.3`
```

### CODE REVIEW

**Review by acumino — CHANGES_REQUESTED** [review]
You can now also remove TODO - https://github.com/gardener/gardener/blob/743cc3e49e3d41a2368d784951ac1341a23605dd/pkg/operation/botanist/kubeapiserver_test.go#L556-L570
Issue was fixed with - https://github.com/kubernetes-sigs/controller-runtime/pull/2508

**Review by acumino — COMMENTED** [review]
Thanks
/lgtm

**Comment by rfranzke** [comment]
Running the integration tests locally on my machine succeeds without any issues... not sure why it repeatedly fails in Prow/CI.

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
