### PR TITLE
Add `skip-health-check` annotation for managed resources

### LINKED ISSUE #6275: pending reserve-excess-capacity pods cause seed as notReady
**How to categorize this issue?**
/area ops-productivity
/kind bug

**What happened**:
When there is no enough capacity in seed cluster which enables excessCapacityReservation feature,  reserve-excess-capacity pod can't be scheduled and in pending state,  in this case,  the status of seed is notReady and all shoots created in this seed can't be reconciled anymore

**What you expected to happen**:
Status of reserve-excess-capacity shouldn't affect seed's status
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area usability 
/kind enhancement

**What this PR does / why we need it**:
This PR introduces an annotation `resources.gardener.cloud/skip-health-check`. If this annotation is set to true, then `resource-manager` will skip health check for this resource, and `ResourcesHealthy` for the MR would be `True` even if this resource is unhealthy. Also the `ResourcesProgressing` condition will be set to `False` even if the resource hasn't been fully rolled out yet (In case of statefulsets, deployments and daemonsets).

This annotation has been set to true for `reserve-excess-capacity` deployment by default, so that the seed can get `Ready` even if this pod is stuck in pending.

**Which issue(s) this PR fixes**:
Fixes #6275 

**Special notes for your reviewer**:

**Release note**:

```feature developer
If a resource in the `ManagedResource` is annotated with `resources.gardener.cloud/skip-health-check=true` then the resource will be skipped during health checks by the health controller. The ManagedResource conditions will not reflect the health condition of this resource anymore. The `ResourcesProgressing` condition will also be set to `False`.
```

### CODE REVIEW

**Comment by ary1992** [comment]
Thanks for the PR :)
/lgtm

**Review by rfranzke — COMMENTED** [review]
Nice PR, well structured!
/lgtm

**Pull request merged**
