### PR TITLE
Minor improvements for the metering dashboards

### PR DESCRIPTION
**Pull request by istvanballok**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Minor improvements for the metering dashboards that were introduced in

- #6944

Improvements:

- avoid using dashed lines: they look similar as if data was missing
- fix promql query for the average network usage
- for the overview, don't consider the unhealthy clusters: consider only cluster that have been running for at least 5 minutes and are not stuck in creation, i.e. use at least some resources

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @rickardsjp 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rickardsjp — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
