### PR TITLE
Adds OverconstrainedZonalAllocationRequest to config problem regex

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Classify errors from Azure that have the code `OverconstrainedZonalAllocationRequest` as configuration problems.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Azure errors with OverconstrainedZonalAllocationRequest error code are now classified as configuration problems.
```

### CODE REVIEW

**Review by vpnachev — DISMISSED** [review]
/lgtm
/reviewed/ok-to-test

**Comment by vpnachev** [comment]
I don't know why, but the `verify` step for this PR now fails for third time. Please, check if it is related to your change.

**Comment by plkokanov** [comment]
Seems that it was fixed in #4483. I've rebased the PR.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
