### PR TITLE
Update versions of various tools

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area open-source security
/kind enhancement

**What this PR does / why we need it**:
Updates versions of various tools used.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
Thanks.
/lgtm
/approve

**Comment by shafeeqes** [comment]
Checking the failing tests.

**Comment by shafeeqes** [comment]
> @shafeeqes: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-e2e-kind-upgrade	[8975e52](https://github.com/gardener/gardener/commit/8975e520804a5864e0e5a0178416774dd044eb36)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8388/pull-gardener-e2e-kind-upgrade/1694590404957048832)	true	`/test pull-gardener-e2e-kind-upgrade`
> pull-gardener-e2e-kind-ha-single-zone-upgrade	[8975e52](https://github.com/gardener/gardener/commit/8975e520804a5864e0e5a0178416774dd044eb36)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8388/pull-gardener-e2e-kind-ha-single-zone-upgrade/1694590404902522880)	true	`/test pull-gardener-e2e-kind-ha-single-zone-upgrade`
> pull-gardener-e2e-kind-ha-multi-zone-upgrade	[8975e52](https://github.com/gardener/gardener/commit/8975e520804a5864e0e5a0178416774dd044eb36)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8388/pull-gardener-e2e-kind-ha-multi-zone-upgrade/1694590404856385536)	true	`/test pull-gardener-e2e-kind-ha-multi-zone-upgrade`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=8388). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

The failure is due to upgrading skaffold to v2.6.0, 
```
 - garden:deployment/gardener-apiserver failed. Error: Liveness probe failed: HTTP probe failed with statuscode: 500.
 - garden:deployment/gardener-admission-controller: Failed to create Pod for Deployment gardener-admission-controller: Error creating: pods "gardener-admission-controller-5fc974cb8d-" is forbidden: no PriorityClass with name gardener-controlplane was found
```
See https://github.com/GoogleContainerTools/skaffold/issues/8972, This should be fixed by https://github.com/GoogleContainerTools/skaffold/pull/9015, but it's not yet released.
For now, we can only upgrade to v2.3.0 where this issue is not present.

**Review by acumino — COMMENTED** [review]
/lgtm

**Pull request merged**
