### PR TITLE
Fix Seed bootstrap

### LINKED ISSUE #2492: Cannot bootstrap Seed when all gardenlet feature gates are false
**How to categorize this issue?**

/kind bug
/kind regression
/priority normal

**What happened**:
Cannot bootstrap Seed when all gardenlet feature gates are false.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. `make start-gardenlet` on the master branch

2. Ensure that a Seed cannot be bootstrapped.
```
$ k describe seed seed-local-aws

    Message:               failed to delete manifests: 3 errors occurred: [could not delete object of kind "EnvoyFilter" "istio-ingress/proxy-protocol": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3", could not delete object of kind "Gateway" "istio-ingress/proxy-protocol": no matches for kind "Gateway" in version "networking.istio.io/v1beta1", could not delete object of kind "VirtualService" "istio-ingress/proxy-protocol-blackhole": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"]
    Reason:                BootstrappingFailed
    Status:                False
    Type:                  Bootstrapped
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind bug
/kind regression
/priority normal

**What this PR does / why we need it**:
Fix Seed bootstrap which is failing because of the `APIServerSNI` feature gate.

**Which issue(s) this PR fixes**:
Fixes #2492 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by mvladev — APPROVED** [review]

**Comment by ialidzhikov** [comment]
We were discussing to enhance the chartApplier with configurable set of errors to ignore on deletion. Something similar would be a more elegant solution as currently all resources need to be enumerated and explicitly deleted.

/hold

**Comment by mvladev** [comment]
I'll suggest to close this in favor of https://github.com/gardener/gardener/pull/2496

**Comment by rfranzke** [comment]
@ialidzhikov do you agree?

**Pull request merged**
