### PR TITLE
Release responsible schedule for v1.94 until v1.102

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
Extends the docs with a proposal for the release responsible schedule for v1.94 until v1.102

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Review by ary1992 — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
Thanks for the schedule 📆 
/lgtm

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Pull request merged**
