### PR TITLE
Explicit labelling for well-known ManagedResources for hibernated shoots

### LINKED ISSUE #1676: Clean up DeleteManagedResources func
#1374 adds label patching for ManagedResources for compatibility reasons. 
When we fix #1675, we can clean it.

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
This PR labels well-known `ManagedResource`s even if the shoot is hibernated.
This is a preparation to remove this dedicated labelling again in the future.
/cc @ialidzhikov 

**Which issue(s) this PR fixes**:
Preparation for #1676

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — DISMISSED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
Btw we still have a small number of hibernated shoot cluster which don't have the desired labels. Their deletion will fail.

**Comment by rfranzke** [comment]
@ialidzhikov why? Hibernated shoots get reconciled as well and get the labels via https://github.com/gardener/gardener/blob/acfd206ba14d204b3b1211328ef641cf7125a6ab/pkg/operation/botanist/addons.go#L165.

**Comment by ialidzhikov** [comment]
Because this step is skipped for hibernated ones.

https://github.com/gardener/gardener/blob/f85b9461857c5e6652c2b3258d57cf5bbe1e4fd7/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L254-L258

**Comment by rfranzke** [comment]
I see.. nice catch. Then we can't delete it yet. Very unfortunate. I'll adapt the PR to add the labels even during reconciliation so that we can clean this up eventually and don't have to keep the code forever.

**Comment by ialidzhikov** [comment]
> I see.. nice catch. Then we can't delete it yet. Very unfortunate. I'll adapt the PR to add the labels even during reconciliation so that we can clean this up eventually and don't have to keep the code forever.

Great. Thank you!

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
