### PR TITLE
Fix erroneous warnings for incomplete credentials rotation of shoots

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area quality usability
/kind bug

**What this PR does / why we need it**:
This PR fixes erroneous warnings for incomplete shoot credentials rotation.
```
kubectl annotate shoot local gardener.cloud/operation=reconcile
Warning: the certificate authorities rotation initiation was finished more than 720h0m0s ago and should be completed
Warning: the ETCD encryption key rotation initiation was finished more than 720h0m0s ago and should be completed
Warning: the ServiceAccount token signing key rotation initiation was finished more than 720h0m0s ago and should be completed
shoot.core.gardener.cloud/local annotated
```
```
rotation:
  certificateAuthorities:
    lastCompletionTime: "2024-05-02T22:19:24Z"
    lastInitiationTime: "2024-05-02T21:57:43Z"
    phase: Completed
  etcdEncryptionKey:
    lastCompletionTime: "2024-05-02T22:19:24Z"
    lastInitiationTime: "2024-05-02T21:57:43Z"
    phase: Completed
  observability:
    lastCompletionTime: "2024-05-02T22:04:51Z"
    lastInitiationTime: "2024-05-02T21:57:43Z"
  serviceAccountKey:
    lastCompletionTime: "2024-05-02T22:19:24Z"
    lastInitiationTime: "2024-05-02T21:57:43Z"
    phase: Completed
  sshKeypair:
    lastCompletionTime: "2024-05-02T22:04:51Z"
    lastInitiationTime: "2024-05-02T21:57:43Z"
```

The conversion between internal and credential status was wrong (see https://github.com/gardener/gardener/pull/10059#issuecomment-2204568093), so the different dates have been mixed up. After correcting the internal data type and the conversion, the erroneous warning is gone.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other user
Erroneous warnings for incomplete shoots credentials rotation has been fixed.
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
The opposite change was introduced in #7313 😅 
However, I can reproduce the erroneous warnings. This PR needs some more investigation.

/retitle [WIP] - Fix warnings for incomplete credentials rotation of shoots

**Comment by oliver-goetz** [comment]
/retitle Fix erroneous warnings for incomplete credentials rotation of shoots

/cc @vpnachev

**Comment by vpnachev** [comment]
Can you add a test for this bug ?

**Review by ialidzhikov — COMMENTED** [review]
Can you elaborate on what is actually the fix? I only see field's place in the struct is moved and the generated conversion code moved few lines above. But I am not able to spot any behavioural change.

**Comment by oliver-goetz** [comment]
Sorry, I did not explain my findings very well.

The bug is hidden in the conversion from `v1beta1` to the internal data type ([see here](https://github.com/gardener/gardener/blob/b6b1a9ebcb7358d706c6234067121eb3acb880bf/pkg/apis/core/v1beta1/zz_generated.conversion.go#L6324)).
In the conversion the pointer of the whole `ShootCredentials` structures is converted into a pointer of its corresponding internal data type. This also includes their fields `CARotation`, `ServiceAccountKeyRotation`, `ETCDEncryptionKeyRotation` and their fields.
There is no semantic check of the variable names but both pointers just point to the same memory addresses. Thus because the order of the fields inside `CARotation`, `ServiceAccountKeyRotation`, `ETCDEncryptionKeyRotation` structs have been different, their memory addresses have been different too. 
The conversion converted the `v1beta` type into the internal type the following way.
```
v1beta1                        internal
Phase                       -> Phase
LastCompletionTime          -> LastInitiationTime
LastInitiationTime          -> LastInitiationFinishedTime
LastInitiationFinishedTime  -> LastCompletionTime
LastCompletionTriggeredTime -> LastCompletionTriggeredTime
```
The order was the same for all three rotation structs and so all of them have been mixed up the same way.
All `...Time` fields share `*metav1.Time` data type. That's why we did not see a panic, but only mixed up values.

This could be the case for other data types which are pointers too. Thus, we should compare the order of the fields across all our data types.
This is not an issue of the warning function itself, but a general conversion issue. I suggest to not write a test for this particular issue, but create a linter which is comparing all internal and external data types.

**Comment by MartinWeindel** [comment]
The root cause seems to be a bug in the code-generator. Running `make generate` with a [patched version](https://github.com/kubernetes/code-generator/compare/release-1.29...MartinWeindel:code-generator:fix/struct-reorder-v0.29.6?expand=1), the generated conversion code looks correct, but I did not run it: [Comparison](https://github.com/gardener/gardener/compare/master...MartinWeindel:gardener:patched-generation?expand=1)

**Comment by ialidzhikov** [comment]
OK, I see now. A `main.go` that demonstrates it:
```go
package main

import (
	"encoding/json"
	"fmt"
	"time"
	unsafe "unsafe"

	"github.com/gardener/gardener/pkg/apis/core"
	"github.com/gardener/gardener/pkg/apis/core/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func main() {
	time1 := metav1.NewTime(time.Date(1995, 1, 1, 0, 0, 0, 0, time.Local))
	time2 := metav1.NewTime(time.Date(1996, 1, 1, 0, 0, 0, 0, time.Local))
	time3 := metav1.NewTime(time.Date(1997, 1, 1, 0, 0, 0, 0, time.Local))
	time4 := metav1.NewTime(time.Date(1998, 1, 1, 0, 0, 0, 0, time.Local))

	in := &v1beta1.ShootStatus{
		Credentials: &v1beta1.ShootCredentials{
			Rotation: &v1beta1.ShootCredentialsRotation{
				CertificateAuthorities: &v1beta1.CARotation{
					Phase:                       v1beta1.RotationPreparing,
					LastCompletionTime:          &time1,
					LastInitiationTime:          &time2,
					LastInitiationFinishedTime:  &time3,
					LastCompletionTriggeredTime: &time4,
				},
			},
		},
	}
	out := &core.ShootStatus{}

	out.Credentials = (*core.ShootCredentials)(unsafe.Pointer(in.Credentials))

	inJSON, err := json.Marshal(in)
	if err != nil {
		panic(err)
	}
	outJSON, err := json.Marshal(out)
	if err != nil {
		panic(err)
	}

	fmt.Printf("in: %+v\n", string(inJSON))
	fmt.Printf("out: %+v\n", string(outJSON))
}
```

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
Nice finding @oliver-goetz and @MartinWeindel. Do you also want to open an issue in the generator's repo?
/lgtm

**Comment by oliver-goetz** [comment]
> The root cause seems to be a bug in the kubernetes/code-generator code. Running `make generate` with a [patched version](https://github.com/kubernetes/code-generator/compare/release-1.29...MartinWeindel:code-generator:fix/struct-reorder-v0.29.6?expand=1), the generated conversion code looks correct, but I did not run it: [Comparison](https://github.com/gardener/gardener/compare/master...MartinWeindel:gardener:patched-generation?expand=1)

Thanks for investigating the generator bug 👍 
We should contribute it to upstream.
According to your gardener code comparison, shoot credential rotation status has been the only place where we faced this bug. That's good to know too 🙂

**Comment by MartinWeindel** [comment]
Reported issue upstream: https://github.com/kubernetes/kubernetes/pull/125933

Bug fix PR: https://github.com/kubernetes/kubernetes/pull/125934

**Pull request merged**
