### PR TITLE
Use common label for all system component pods

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**: 
Use `garden.sapcloud.io/role: system-component` label for the `node-exporter` daemon set installed inside the shoot clusters. This label is used for all other system components deployed in the shoot cluster. 
 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
@Adracus, you did not use the `system-component` value for the label on the node-exporter on purpose, right?
Can you quickly elaborate here why?
Should we merge or close this one?

**Comment by vpnachev** [comment]
If the value `monitoring` is required, I propose the key to be `role` or something other, but not `garden.sapcloud.io/role`.
At the end, the labels could look like these:
```
labels:
  garden.sapcloud.io/role: system-component
  role: monitoring
```

**Comment by adracus** [comment]
@vpnachev why except for uniformity do you want to change this label?
@rfranzke yes I did this on purpose, this is required if we want to have more fine granular health check conditions (like a condition for only `monitoring`, `logging` etc.).
Btw: `system-component`s are just components which we as the Gardener itself require, I wouldn't consider the `node-exporter` to be one.

**Comment by vpnachev** [comment]
I will propose a PR fixing #565 and I will assume that all system components are labelled with `garden.sapcloud.io/role: system-component`. Also, the `node-exporter` is exactly component installed by the Gardener in the Shoot cluster. My understanding is that the label `garden.sapcloud.io/role: system-component` is used exactly for such components. The `node-exporter` is the only exception - every other component is using the label `garden.sapcloud.io/role: system-component`.

Why don't you use `health.garden.sapcloud.io/role: monitoring` for the health checks ?

**Comment by adracus** [comment]
The current label name was the first one to come to my mind back then.
But still: Status quo is that those labels are in use for the health checking, so changing them as you want in your PR breaks it. Yes, you can rename it to `health.whatever` but still, your problem will only be solved if you introduce a new label.

**Comment by rfranzke** [comment]
Either you add the `garden.sapcloud.io/role: monitoring` podSelector to your planned network policies and we close this PR, or you change the node-exporter label and fix the health check.
How do we continue?

**Comment by vpnachev** [comment]
Ok, you are right - this is a breaking change, which I have not seen.

I will think about how to amend the PR.

**Comment by vpnachev** [comment]
I close this PR.

**Pull request closed without merging**
