### PR TITLE
Add 23 technologies blogs

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR adds the [23Technologies](https://23technologies.cloud/en/blog/gardener-ext-dev) [blogs](https://23technologies.cloud/en/blog/gardener-ext-shoot-flux) to the public website.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Why do we copy the content? We should rather add links to their blogs and not duplicate it?

**Comment by n-boshnakov** [comment]
> Why do we copy the content? We should rather add links to their blogs and not duplicate it?

23Technologies have stated that they want to handover their documentation to us, so that we are responsible for maintaining it.

**Comment by rfranzke** [comment]
I don't think this makes sense given that the repositories are not part of the `gardener` organization. Let's either add links to their already existing blogs or not add this at all.
/hold

**Comment by n-boshnakov** [comment]
I will look for a suitable place to reference the blog posts. As such, I will be closing this PR.

**Pull request closed without merging**
