### PR TITLE
Node exporter: enable uname collector

### PR DESCRIPTION
**Pull request by dschmo**
**How to categorize this PR?**

/area monitoring
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Enables the uname collector of the node-exporter.
It provides the metric ```node_uname_info```

**Which issue(s) this PR fixes**:
Fixes several dashboards

**Special notes for your reviewer**:

**Release note**:

```other operator
Node exporter provides the metric node_uname_info
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @dschmo for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by wyb1 — DISMISSED** [review]
/lgtm

**Review by istvanballok — DISMISSED** [review]
/lgtm

**Comment by vpnachev** [comment]
@dschmo please sign the CLA to get this PR merged.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
