### PR TITLE
Add gen-crd-api-reference link in generated documentation

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/area documentation
/kind enhancement
/priority normal

**What this PR does / why we need it**:

Link the original `gen-crd-api-reference` project.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ahmetb** [comment]
@mvladev 🤔 the tool should be generating this string automatically, are you actively removing it somewhere?

**Review by timebertt — COMMENTED** [review]
> @mvladev 🤔 the tool should be generating this string automatically, are you actively removing it somewhere?

I guess, you mean if no custom template is specified, is that right?
https://github.com/ahmetb/gen-crd-api-reference-docs/blob/3d32c92e9f90819a89615908db8fa787288be6ff/template/pkg.tpl#L45-L46

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by mvladev** [comment]
> @mvladev 🤔 the tool should be generating this string automatically, are you actively removing it somewhere?

I removed the paragraph with commit hash info, because the documentation was previously generated for every single commit and it caused problems for us.

**Comment by ahmetb** [comment]
Ack, I forgot the templates are editable.

**Pull request merged**
