### PR TITLE
Always allow project owner to be added to member list when creating a new project

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal
/topology garden
/exp intermediate
/size s
/platform all

**What this PR does / why we need it**:
After #2611 the `Project` creation is broken as the owner is automatically added by the Gardener API server to the `.spec.members[]` list, however, this was not handled specially and thus always rejected.

**Special notes for your reviewer**:
/invite @vpnachev 
/assign @vpnachev 

**Release note**:

```improvement user
A bug showing `403 Forbidden` responses when creating new `Project`s has been fixed.
```

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
/lgtm

**Comment by rfranzke** [comment]
/unhold
/remove reviewed/lgtm
/needs review

I've updated the PR to also reflect that if the user submitting the admission request is the owner of the project then the authorization check will be bypassed as the owner has full UAM privileges anyways (i.e., it will be anyways bound to the `manage-members` custom verb by the `Project` controller later on, so we can already allow him to manage the members. Thanks @vpnachev for pointing this out!

PS: This whole project management is a very nice case for a new integration test... ref #1564.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
