### PR TITLE
Upgrade logging components to v0.44.0

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
With this PR the logging components which are supported by `Gardener` are bumped to v0.44.0 version.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix operator github.com/gardener/logging #153 @vlvasilev
Fix sending on a closed channel in the `fluent-bit's` plugin `SortedClient` when closing it before the last batch is sent. 
```
```other developer github.com/gardener/logging #154 @vlvasilev
Remove the alpine image used as a carrier for the `fluent-bit-to-loki` plugin.
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/approve

/cc @Kristian-ZH @nickytd 
for lgtm

**Comment by ialidzhikov** [comment]
/lgtm cancel
as I wanted to give chance @Kristian-ZH @nickytd to have a look and provide the lgtm

**Review by nickytd — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
The test failure is occurrence of https://github.com/gardener/gardener/issues/6766:

```
  Timed out after 300.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000162510>: {
          s: "kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-10-03 06:12:12.5284775 +0000 UTC, newClientCertificateIssuedAt: 2022-10-03 06:11:18 +0000 UTC",
      }
      kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-10-03 06:12:12.5284775 +0000 UTC, newClientCertificateIssuedAt: 2022-10-03 06:11:18 +0000 UTC
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/managedseed/create_rotate_delete.go:408
```

/retest

**Pull request merged**
