### PR TITLE
Use alpine image with iptables pre-installed for prometheus and kube-apiserver 

### PR DESCRIPTION
**Pull request by DockToFuture**
**What this PR does / why we need it**:
Use alpine image with iptables pre-installed for prometheus and kube-apiserver 

**Release note**:

```improvement operator
None
```

### CODE REVIEW

**Comment by mvladev** [comment]
/lgtm 

Just one comment on image tagging - isn't it better to have 

```
eu.gcr.io/gardener-project/alpine:3.8-iptables
```

with this I know which alpine version this image with iptables is based on.

**Comment by DockToFuture** [comment]
> based

That sounds handy, will change that to ```eu.gcr.io/gardener-project/alpine-iptables:3.8```.

**Comment by marwinski** [comment]
PS: Can you go with alpine 3.9 otherwise people will bug you to update quite soon :-)

**Comment by DockToFuture** [comment]
> PS: Can you go with alpine 3.9 otherwise people will bug you to update quite soon :-)

I've uploaded the 3.9 image as well but would wait with the update for gardener to update the alpine version and then update it together in one PR.

**Comment by rfranzke** [comment]
Why? How is gardener related? Let's directly use the 3.9 for these init containers now

**Comment by ialidzhikov** [comment]
The sts has label `networking.gardener.cloud/to-public-networks: allowed`, what is the need to have a pre-build alpine with iptables?

**Comment by rfranzke** [comment]
The reason why prometheus has this label is because it needs VPN (and thus connects to a public load balancer).
It's still better to use a prepared image for the init container to have a reproduceable behaviour and to not download the iptables each and every time.

**Review by zanetworker — APPROVED** [review]

**Pull request merged**
