### PR TITLE
update the etcd-druid dependency version in go.mod

### PR DESCRIPTION
**Pull request by ishan16696**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
This PR updates the `etcd-druid` dependency version in go.mod

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
None
```

### CODE REVIEW

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Review by acumino — COMMENTED** [review]
/approve

**Pull request merged**
