### PR TITLE
Sync cluster resource to seed at start of migration

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind enhancement

**What this PR does / why we need it**:
The `Cluster` resource will now be synced to the source seed at the start of a migration operation. With this when a shoot is changed from a Failed to a non-Failed state the change will be reflected in the `Cluster` resource in the source seed during migration. Without this, extension controllers were not able to migrate (or restore if necessary - check #4584) the extension resources.

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
This was previously part of #4584 but since that PR can get delayed a bit more i've added the changes specific to syncing the cluster in this PR.

**Release note**:

```other operator
The `Cluster` resource is now synced at the start of a migrate operation, similar to what is done for reconciliation and deletion operations.
```

### CODE REVIEW

**Review by stoyanr — DISMISSED** [review]
/lgtm

**Comment by plkokanov** [comment]
@stoyanr @kris94 I rebased the PR

**Review by stoyanr — APPROVED** [review]
/lgtm

**Pull request merged**
