### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.10.0->v0.11.1]

### PR DESCRIPTION
**Pull request by aaronfern**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Upgrade etcd-druid image from `v0.10.0` to `v0.11.1`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

``` other operator github.com/gardener/etcd-druid #357 @ishan16696
livenessProbe of etcd container has been updated to `ETCDCTL_API=3 etcdctl get foo --consistency=s` making the consistency `serializable`.
```
``` other operator github.com/gardener/etcd-druid #357 @ishan16696
failureThreshold has been updated to `5` for both livenessProbe and readinessProbe of etcd.
```
``` other operator github.com/gardener/etcd-druid #360 @dimityrmirchev
The `etcd-druid` now uses `distroless` instead of `alpine` as a base image.
```
``` other operator github.com/gardener/etcd-druid #366 @aaronfern
`etcd-druid` will now also add statefulset permissions to the etcd role
```
``` other operator github.com/gardener/etcd-druid #367 @timuthy
Published docker images for Etcd-Druid are now multi-arch ready. They support `linux/amd64` and `linux/arm64`.
```
``` other operator github.com/gardener/etcd-druid #271 @aaronfern
Added a new condition `BackupReady` to the etcd status
```
``` noteworthy operator github.com/gardener/etcd-backup-restore #499 @timuthy
Published docker images for Etcd-Backup-Restore are now multi-arch ready. They support `linux/amd64` and `linux/arm64`.
```
``` noteworthy operator github.com/gardener/etcd-backup-restore #499 @timuthy
The Etcd-Backup-Restore image has been updated to `Alpine 3.15.4`.
```
``` action developer github.com/gardener/etcd-backup-restore #403 @aaronfern
Added new package `membergarbagecollector` to remove superfluous members from the ETCD cluster. Due to this, etcd-backup-restore now needs permissions to list `pods` and `statefulsets`.
```
``` improvement operator github.com/gardener/etcd-backup-restore #403 @aaronfern
Added new package `membergarbagecollector` to remove superfluous members from the ETCD cluster.
```
``` noteworthy operator github.com/gardener/etcd-backup-restore #487 @aaronfern
Etcd can now scale up itself from a single member cluster to a multi member cluster
```
``` other operator github.com/gardener/etcd-custom-image #19 @timuthy
Published docker images for Etcd-Custom-Image are now multi-arch ready. They support linux/amd64 and linux/arm64.
```
``` other operator github.com/gardener/etcd-druid #372 @aaronfern
Added pod permission in etcd_role that now enable `etcd-backup-restore` to get/list/watch pods
```
``` improvement operator github.com/gardener/etcd-backup-restore #504 @aaronfern
Fixed a bug where etcd calls related to multi node operation were used in single node operation
```
``` bugfix operator github.com/gardener/etcd-backup-restore #501 @ishan16696
Temp fix: skip the single member restoration if data-dir found to be invalid.
```
``` bugfix operator github.com/gardener/etcd-backup-restore #501 @ishan16696
Fixed a bug in Scaleup feature in func: `IsMemberInCluster()` which can cause Scaleup feature to get fail.
```
``` improvement operator github.com/gardener/etcd-backup-restore #505 @ishan16696
Assigned the correct Peer address to the Etcd after it restores from backup-bucket.
```
``` improvement operator github.com/gardener/etcd-backup-restore #506 @aaronfern
No attempt is made to update member Peer URL when trying to promote a member
```

### CODE REVIEW

**Review by timuthy — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
FYI @aaronfern @timuthy , the release notes of this PR are quite broken.

They now look like 
```
other operator [github.com/gardener/etcd-druid](http://github.com/gardener/etcd-druid) #357 @ishan16696
```

while they should look like

```
other operator github.com/gardener/etcd-druid #357 @ishan16696
```

This is also causing the whole `create_draft_release_notes` step in the CI/CD to fail.

I am now working on fixing them.

**Comment by timuthy** [comment]
Thanks for noticing and fixing @ialidzhikov ❤️

**Comment by aaronfern** [comment]
Thanks for fixing it @ialidzhikov

**Pull request merged**
