### PR TITLE
Install logging stack when seed is garden

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind bug

**What this PR does / why we need it**:
Currently, when the Seed is Garden cluster the installation of the logging stack is left to the gardener operator which does not support logging installation. This results in a seed without a logging stack.
This PR fixes this issue.

Also, the deletion of the fluent-operator CRD waits until there are no controller installations(which could have their fluent custom resources) and the deletion of the fluent-operator custom resources is done.

**Which issue(s) this PR fixes**:
Part of #7016

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
The logging stack is installed when the seed is a garden cluster managed by the gardener operator.
```
```bugfix operator
Fluent-operator CRDs are deleted after the deletions of the ControllerInstallation and the fluent-bit DaemonSet.
```

### CODE REVIEW

**Review by rfranzke — CHANGES_REQUESTED** [review]
Please take a look at how other components are managed that might exist in both garden and seed. It should be the other way round:
- `gardener-operator` deploys logging stack by default (unconditionally)
- `gardenlet` deploys logging stack only when its seed is not the garden cluster at the same time

/hold

**Comment by vlvasilev** [comment]
> `gardener-operator` deploys logging stack by default (unconditionally)
> `gardenlet` deploys logging stack only when its seed is not the garden cluster at the same time

Gardener-operator does not install a logging stack.
I have tried but ended up not working fluent-bit.
This is because in the gardener runtime, we don't have Cluster resource and in our fluent-bit, we have Cluster informer. And on top of that the fluent-bit native Loki output can't be used since we switched to Vali.

I should have to make separate Vali for the Garden runtime with a separate output plugin.
And when Seed in Garden we will have two Central Vali. One for the seed and one for the garden.

**Comment by rfranzke** [comment]
> > `gardener-operator` deploys logging stack by default (unconditionally)
> > `gardenlet` deploys logging stack only when its seed is not the garden cluster at the same time
> 
> Gardener-operator does not install a logging stack. I have tried but ended up not working fluent-bit. This is because in the gardener runtime, we don't have Cluster resource and in our fluent-bit, we have Cluster informer. And on top of that the fluent-bit native Loki output can't be used since we switched to Vali.
> 
> I should have to make separate Vali for the Garden runtime with a separate output plugin. And when Seed in Garden we will have two Central Vali. One for the seed and one for the garden.

Well, then I guess `fluent-bit` needs to be changed to not depend on the `Cluster` resource. This PR won't help to bring the logging stack to the garden cluster since there is no `gardenlet` running in the garden clusters of productive Gardener installations (besides from the fact that it is conceptionally wrong).

**Comment by rfranzke** [comment]
I guess we can close this one in favor of #8240

**Pull request closed without merging**
