### PR TITLE
No longer grant dashboard the cluster-admin role

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**: The dashboard supports authentication since v1.7. As it didn't work properly back then we have granted the `cluster-admin` role to it, i.e., the dashboard currently has full admin access without the necessity of logging in.
Now, with Dashboard v1.10.0, we revisited the authentication part and it works fine. Users can now login with the basic authentication credentials provided in the handed out kubeconfigs. By default, the dashboard has only the minimal required permissions to run.

More information:
- https://github.com/kubernetes/dashboard/wiki/Access-control
- https://github.com/helm/charts/tree/master/stable/kubernetes-dashboard

**Release note**:

```noteworthy user
The Kubernetes dashboard does no longer have `cluster-admin` privileges, i.e., users need now to login with the basic authentication credentials before the dashboard can be used. These credentials can be found in the provided shoot kubeconfig. By default (i.e., without being logged in), the dashboard only has minimal privileges to run properly.
```

### CODE REVIEW

**Review by timuthy — CHANGES_REQUESTED** [review]
Could you also adjust the `Ingress` settings in https://github.com/gardener/gardener/blob/master/charts/shoot-addons/charts/kubernetes-dashboard/README.md?

**Comment by rfranzke** [comment]
@timuthy I deleted the file, it's not needed.

**Review by timuthy — APPROVED** [review]
Thx :)

**Review by marwinski — COMMENTED** [review]
looks ok to me

**Pull request merged**
