### PR TITLE
Switch from loki to logging service - stage 2

### LINKED ISSUE #7585: ☂️ Upgrade observability apps in Gardener
/area logging
/area monitoring
/kind enhancement

Update older Grafana and Loki applications to the updated alternatives Plutono and Vali

# Motivation

Currently we use old Apache-2 licensed versions of Loki and Grafana and we would like to move towards Plutono and Vali forks. Plutono (fork of Grafana) -> https://github.com/credativ/plutono/releases/tag/v7.5.19 Vali (fork of Loki) -> https://github.com/credativ/vali/releases/tag/v2.2.3 Both forks feature an updated golang (1.19) fixing numerous public CVEs.

## Migration strategy for seed/shoots Logs
The proposed change includes updating current helm charts, runtime deployments, log shippers configurations, documentation and a migration strategy particularly for the current loki stateful sets.

Here is a list of viable options for the migration strategy of the stateful sets.

### Option I
In this option we
- introduce new Vali stateful sets with new PVs.
- preserve old Loki stateful sets with old Loki PVs to allow searches in a case of troubleshooting scenarios
- scale down Loki stateful set to avoid resource consumption on current production landscapes

Pros:
- Allows operators and users to still access the old logs in case of an emergency.
- Preserves current resource consumption

Cons:
- Require manual steps from the operators to increase the replica counts on Lokis if they want access to the old indexed logs.

### Option II
In this option we
- introduce new Vali stateful sets with new PVs.
- delete completely the existing Loki stateful sets

Pros:
- Preserves current resource consumption
- Simplest possible scenario

Cons:
- Older logs in Loki are not available

### Option III
In this option we
- introduce new Vali stateful sets with new PVs.
- copy Loki indices from old PVs to the new ones.

Pros:
- Older logs are still available in the new Vali instances
Cons:
- Copy operations just takes too much time with corresponding downtime. In addition this options puts pressure on the log shippers.

### Option IV
In this option we
- delete loki but preserve it's PVs
  - set `reclaimPolicy`  to `Retain`
  - clean up `claimRef`
- Introduce Vali and claim now `available` Loki PVs

The best option is **Option IV**

Option IV was initially though to be non valid but was proven by @istvanballok and @rickardsjp 

## Migration plan
The entire transition setup requires 4 consecutive Gardener releases

observability-migration

### Gardener release 1.X
(gardener/gardener)
1. Decouple `fluent-bits` from the targets backend by introducing a dedicated `logging.<shoot-namespace>` service https://github.com/gardener/gardener/pull/7623

### Gardener release 1.X+1
(gardener/gardener)
1. Switch `fluent-bits` to target `logging.<shoot-namespace>`
https://github.com/gardener/gardener/pull/7731

At this stage we will have all `fluent-bits` using an unified  `logging` service.

### Gardener release 1.X+2 
(gardener/logging)
1. Adjust fluent-bit output plugin https://github.com/gardener/logging/pull/186
`v0.53.0-dev` tag is the current testing build of (1) aka 

> ```yaml
> - name: fluent-bit-plugin-installer
>     repository: eu.gcr.io/gardener-project/gardener/fluent-bit-to-vali
>     tag: "v0.53.0-dev"
> ```

(2) needs to reference the images from (1) in the charts/images.yaml

(gardener/gardener)
2. Migrate `loki` and `grafana` references in g/g  https://github.com/gardener/gardener/pull/7318

At this stage `gardener/dashboard` still shows Grafana URLs to accommodate the case where we can have both shoots in migrated and non-migrated state. Since `fluent-bits` sends logs to a unified `logging.<shoot-namespace>` service it can ships logs to both migrated and non-migrated clusters. 

### Gardener release 1.X+3
(gardener/dashboards)
1. Adjust `grafana`  URLs in `gardener/dashboard` https://github.com/gardener/dashboard/pull/1409

### PR DESCRIPTION
**Pull request by nickytd**
- switch fluent-bit outputs from loki to logging service
- switch grafana loki data source from loki http endpoint to logging http endpoint
- switch loki prometheus scrape targets from loki to logging

**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:

This is the second stage in resolving #7585 where we switch the fluent-bits and prometheus scrapers configs from using loki service to the previously introduced logging service.
The logging service is available since gardener/v1.67. And at the time of this PR, the logging service is already part of the seeds and shoots logging stacks.
After this PR the fluent-bits target both loki and vali instances on shoots, because the target backends (vali or loki) are covered by the same logging service. The target is to allow in the next PRs, in stage 3 of the loki to vali migration, to have non-disruptive logs delivery regardless of the state of the shoot. Hence on any seed we may have both reconciled shoots (with vali) and non reconciled shoots (with loki) both being target by the cluster fluent-bits.

**Which issue(s) this PR fixes**:
Fixes #7585

**Special notes for your reviewer**:

**Release note**:

```other operator
Now the `fluent-bit`'s output plugin targets the `logging` service instead of the previously used `loki` service.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/approve

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
/hold
until @Kristian-ZH or @vlvasilev have provided feedback

**Review by Kristian-ZH — APPROVED** [review]
/lgtm

**Comment by istvanballok** [comment]
> switch grafana loki data source from loki http endpoint to logging http endpoint
> switch loki prometheus scrape targets from loki to logging

Just for the record and to verify my understanding: IMHO, these changes are not "strictly" required but also do not do any harm.

The aggregate prometheus in the garden namespace scrapes the loki endpoints in the garden namespace. Both are in the garden namespace, so they are reconciled together by the gardenlet. It would be an issue if a Prometheus in the garden namespace would scrape a loki in the control plane namespace, because the garden namespace and the control plane namespace are not reconciled at the same time. However, we do not have such a problematic combination here. The same reasoning is true for the grafana data source definition, which connects Grafana with loki in the control plane namespace, and they are reconciled at the same time.

> switch fluent-bit outputs from loki to logging service

this part is required on the other hand, because the fluent-bit daemon set is in the garden namespace, and it forwards logs to the loki in the control plane namespaces, and they (garden vs. control plane) are not reconciled at the same time. The shoot control planes are reconciled in their maintenance time window which can be several hours after the reconciliation of the garden namespace.

cc @rickardsjp

**Pull request merged**
