### PR TITLE
[ci:component:github.com/gardener/ext-authz-server:0.2.0->0.3.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-2**
**Release Notes**:
``` feature user github.com/gardener/ext-authz-server #4 @DockToFuture
Update alpine image to version `3.15.3` and update dependencies.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/cc @ScheererJ @DockToFuture

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
