### PR TITLE
Increase resource requests for fluent-bit

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area logging
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Increase resource requests for fluent-bit

On large landscapes with large seed nodes the fluent bit is handling a lot more logs. With this change its requests are closer to the real usage so it can have more guaranteed resources.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/invite @vlvasilev @Kristian-ZH 
/assign @vlvasilev @Kristian-ZH 

**Release note**:

```improvement operator
The resource requests for the `fluent-bit` DaemonSet running in the seed clusters have been increased.
```

### CODE REVIEW

**Review by Kristian-ZH — DISMISSED** [review]
On my setup it is even 200m CPU and 200Mi memory but it is also OK

**Review by vlvasilev — DISMISSED** [review]
/lgtm

**Review by rfranzke — DISMISSED** [review]

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
