### PR TITLE
Vendor k-sigs/controller-runtime@v0.5.10

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area open-source
/kind task
/priority normal

**What this PR does / why we need it**:
Vendor k-sigs/controller-runtime@v0.5.10, which contains [several bug fixes](https://github.com/kubernetes-sigs/controller-runtime/compare/v0.5.5...v0.5.10).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
v0.6 will be vendored as part of #2489, see @timuthy's [progress](https://github.com/timuthy/gardener/blob/maintenance.vendor/go.mod).

**Release note**:

```improvement operator
`extensions/pkg/predicate.Or` has been deprecated in favor of `sigs.k8s.io/controller-runtime/pkg/predicate.Or`.
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
Thank you for this PR!

I see that with https://github.com/kubernetes-sigs/controller-runtime/pull/1061 there is already an `Or` predicate. I guess we can now remove our custom or predicate (https://github.com/gardener/gardener/blob/v1.9.0/extensions/pkg/predicate/predicate.go#L92-L123) and use the one from upstream, right?

**Comment by timebertt** [comment]
Yes, indeed. Originally I wanted to do it seperately, but now that you also mentioned it, I just did it in this PR.

Rather than removing our `predicate.Or` I deprecated it with a note that it will be removed with g/g@v1.12.

**Comment by ialidzhikov** [comment]
> Rather than removing our predicate.Or I deprecated it with a note that it will be removed with g/g@v1.12.

Makes sense. Thanks.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
