### PR TITLE
Set lower vpa cpu requests for vpn-shoot pod to 100m

### PR DESCRIPTION
**Pull request by DockToFuture**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Set the min allowed vpa cpu requests for the vpn-shoot pod to `100m`. This will set it to the same value as it is when vpa is disabled and will led to fewer cases where we see cpu throttling in cases of short cpu spikes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Min allowed vpa cpu requests for the vpn-shoot pod are set to `100m`.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
I guess there is a typo in the commit message - it should be `higher` (instead of `lower`), right? Can you please correct this?
Can you please explain how you came up with the above value of `100m`?

**Comment by DockToFuture** [comment]
No its right, its the lower cpu request value/bound for the vpa. In the deployment we also use 100m cpu when the vpa is disabled. From there we took the 100m.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
