### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.15.0->v0.15.1]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` other operator github.com/gardener/etcd-druid #489 @shreyas-s-rao
Fix `make manifests` target.
```

### CODE REVIEW

**Comment by timuthy** [comment]
/assign @shreyas-s-rao 
for checking permissions changed in https://github.com/gardener/etcd-druid/commit/7efbeaf5c89af74e3a5f80b861e1ec89a4787bc0 and should potentially be adapted [here](https://github.com/gardener/gardener/blob/315f0b945f1b26f98faf2017c39e82f8f8c700a4/pkg/operation/botanist/component/etcd/bootstrap.go#L131)

**Comment by timuthy** [comment]
@shreyas-s-rao asked me to take over. The `ClusterRole` has been updated via 8a1654b226a36934807fb84939e5dec7100715f2.

**Comment by ishan16696** [comment]
We are going to have another patch release of etcd-druid. Please refer to this PR: https://github.com/gardener/etcd-druid/pull/485. I think we can close this PR then ?

**Comment by ishan16696** [comment]
> We are going to have another patch release of etcd-druid. Please refer to this PR: https://github.com/gardener/etcd-druid/pull/485. I think we can close this PR then ?

as this PR contains the `ClusterRole ` changes then we can go ahead with this PR.

**Comment by timuthy** [comment]
No worries, I can add this commit also to the new upgrade PR.
/close

**Pull request closed without merging**
