### PR TITLE
Allow VPA downscaling for HA etcd-{main,events}

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area etcd
/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Currently, we don't ever scale down etcd-main for clusters with `purpose: production` and `purpose: infrastructure`, not even when they have an HA configuration. This can lead to situations of resource waste, where a short-term load blows up the resource requests and they never get scaled down again.

This PR allows VPA to evict etcd Pods for downscaling and saving resources, when we don't expect a disruption from this. Eviction for scaling down is still not allowed for singleton etcds.

**Special notes for your reviewer**:
Similar to what we did with https://github.com/gardener/gardener/pull/10235 with the `safe-to-evict` annotation for Cluster Autoscaler.

**Release note**:

```other operator
Allow VPA to evict HA etcd-main and etcd-events for downscaling.
```

### CODE REVIEW

**Comment by dguendisch** [comment]
Does the potential downscaling then apply anytime or only during maintenance windows?

**Comment by voelzmo** [comment]
> Does the potential downscaling then apply anytime or only during maintenance windows?

This is not limited to maintenance windows but can happen anytime.

**Comment by rfranzke** [comment]
> > Does the potential downscaling then apply anytime or only during maintenance windows?
> 
> This is not limited to maintenance windows but can happen anytime.

Yes, but it shouldn't matter for HA clusters anyways, since the PDB prevents evictions of more than 1 member at the same time. I guess that's fine.

**Comment by rfranzke** [comment]
@voelzmo Should we consider a similar change for the ETCD of the virtual garden ([ref](https://github.com/gardener/gardener/blob/855785c7543e88f71674321de787f082da515709/pkg/operator/controller/garden/garden/components.go#L443-L527))?

**Comment by voelzmo** [comment]
> @voelzmo Should we consider a similar change for the ETCD of the virtual garden ([ref](https://github.com/gardener/gardener/blob/855785c7543e88f71674321de787f082da515709/pkg/operator/controller/garden/garden/components.go#L443-L527))?

Oh, that's a good point, I'll add a commit changing this as well!

**Comment by dguendisch** [comment]
> Yes, but it shouldn't matter for HA clusters anyways, since the PDB prevents evictions of more than 1 member at the same time. I guess that's fine.

Yes sure, theoretically it should work anytime. Then I guess only time & experience will tell whether customers will be fine with it or not (I recall that we had cases e.g. with increased latency when one member of a three-member etcd cluster setup was down and customers asked for an RCA...).
Would we have an option (e.g. configuration) to disable downscaling should the need arise?

**Comment by unmarshall** [comment]
VPA controlled evictions are proven to be problematic for quorum based workloads. We already have seen on many instances in the past when evictions caused loss of quorum also for HA clusters. So now when we add more such evictions due to scale down recommendations then possibility for quorum loss theoretically only increases. Therefore i would recommend that you do this initially only for `etcd-events` and make an experience and only then move to `etcd-main`.

**Pull request closed without merging**
