### PR TITLE
Add "Do not edit" description to all Shoot artifacts

### PR DESCRIPTION
**Pull request by mvladev**
**What this PR does / why we need it**:

it adds the following annotation to all resources managed by `resource-manager`
```yaml
metadata:
  annotations:
    gardener.cloud/description: |
      DO NOT EDIT - This resource is managed by Gardener.
      Any modifications are discarded and the resource is returned to the original state.
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
All resources managed by `resource-manager` now have `gardener.cloud/description` annotation with `DO NOT EDIT` warning.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Thanks @mvladev - nice idea. Though, wouldn't it make more sense to let GRM add the annotation itself instead of manually adding it to every single resource?

**Comment by mvladev** [comment]
> Though, wouldn't it make more sense to let GRM add the annotation itself instead of manually adding it to every single resource?

I thought about it, but Some resources already [have this annotation](https://github.com/gardener/gardener/pull/2133/files#diff-e1f39896c426bda625f992d220ce4629L6-R9). Merging both would be a problem.

As an alternative, GRM could use different annotation.

**Comment by rfranzke** [comment]
Yeah, maybe GRM can use `resource-manager.gardener.cloud/description` is something else prefixed with `resource-manager.gardener.cloud/` ?

**Comment by mvladev** [comment]
Closing in favor of gardener/gardener-resource-manager#46

**Pull request closed without merging**
