### PR TITLE
Revert "Add alert if backup sidecar metrics are not scarraped"

### LINKED ISSUE #2208: prometheus-0 is in CrashLoopBackOff
**What happened**:
prometheus-0 is in `CrashLoopBackOff`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot.

2. Ensure the prometheus-0 Pod is in CrashLoopBackOff

```
$ k -n shoot--foo--bar get po prometheus-0
NAME           READY   STATUS             RESTARTS   AGE
prometheus-0   3/4     CrashLoopBackOff   7          14m
```

```
$ k -n shoot--foo--bar logs prometheus-0 prometheus

level=info ts=2020-04-21T09:45:06.994Z caller=manager.go:815 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-04-21T09:45:06.994Z caller=manager.go:821 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-04-21T09:45:06.995Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2020-04-21T09:45:06.995Z caller=main.go:724 msg="Notifier manager stopped"
level=info ts=2020-04-21T09:45:06.995Z caller=main.go:553 msg="Scrape manager stopped"
level=error ts=2020-04-21T09:45:07.004Z caller=main.go:733 err="error loading config from \"/etc/prometheus/config/prometheus.yaml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config/prometheus.yaml\")"
```
**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`): v1.18.2
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
This reverts commit b69d2d5f18f5bbfc879e3429d1723894fade626b.

**Which issue(s) this PR fixes**:
Fixes gardener/gardener#2208

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by wyb1 — APPROVED** [review]
/lgtm

**Comment by wyb1** [comment]
It might make sense to have a more generic alert if we are not getting any b&r metrics.
```
  - alert: KubeEtcdBackupMetricsDown
    expr: absent({job="kube-etcd3-backup-restore"})
    for: 15m
    labels:
      service: etcd
      severity: warning
      type: seed
      visibility: operator
    annotations:
      description: Backup sidecar for Etcd3 cluster {{ $labels.role }} is unavailable or cannot be scraped.
      summary: Etcd3 {{ $labels.role }} backup sidecar cannot be scrapped.

**Comment by swapnilgm** [comment]
> It might make sense to have a more generic alert if we are not getting any b&r metrics.
> 
I agree behind your intension to make it generic. But the motivation for introducing that alert was, to alert if snapshot specific metrics data points are absent for long. Generic approach won't work, cause some metrics are not relevant to snapshot but exposed by etcd-backup-restore regularly irrespective of snapshotter thread is running or not. So, generic alert doesn't makes sense here.

If this alert is having issue with prometheus, i'm fine with reverting for now. We could rework on getting getting those alert without any side-effect to other components.
cc @shreyas-s-rao

**Comment by rfranzke** [comment]
Can you please help getting this PR in and and open a proper replacement PR? Currently, the `master` branch is broken.

**Comment by swapnilgm** [comment]
/LGTM.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
