### PR TITLE
Explicitly enable IPv4 forwarding

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area os
/kind technical-debt

**What this PR does / why we need it**:

Currently, gardener implicitly expects the selected OS image for shoot workers to enable IPv4 forwarding by default.
Make this explicit by configuring worker nodes with `net.ipv4.conf.{all,default}.forwarding = 1`.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

/cc @ScheererJ @MrBatschner

**Release note**:

```other operator
Gardener explicitly configures the shoot worker nodes' kernels with `net.ipv4.conf.{all,default}.forwarding = 1`.
```

### CODE REVIEW

**Comment by ScheererJ** [comment]
@timebertt Thanks for making it explicit. Is there a reason why you did not include IPv6 directly here as well? Do you want to do it separately?

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Review by ScheererJ — APPROVED** [review]
/approve

**Comment by timebertt** [comment]
> Is there a reason why you did not include IPv6 directly here as well? Do you want to do it separately?

Yes, a corresponding change for IPv6 can be performed when the upcoming GEP is implemented :)

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Pull request merged**
