### PR TITLE
Update various tools

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
Update various tools used in gardener.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/retest
/lgtm
/approve

**Review by ary1992 — COMMENTED** [review]
/lgtm

**Pull request merged**
