### PR TITLE
Drop internal version of `extensions/pkg/apis/config` API

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:

This PR drops the internal version of the `extensions/pkg/apis/config` API.
There wasn't even any conversion code and we only used the internal version. So get rid of the duplication to prevent confusion and reduce development/maintenance efforts.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/11043

**Special notes for your reviewer**:

**Release note**:

```breaking dependency
The package `github.com/gardener/gardener/extensions/pkg/apis/config` has been dropped. Use the versioned variant of the package instead: `github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1`.
```

### CODE REVIEW

**Review by ary1992 — COMMENTED** [review]
Thanks!
/lgtm

**Review by marc1404 — APPROVED** [review]
/lgtm
/approve

From the PR description: It was probably meant to say that we're only using the external version, right?
> This PR drops the internal version of the extensions/pkg/apis/config API.
There wasn't even any conversion code and we only used the ~internal~ external version.

**Comment by timebertt** [comment]
> From the PR description: It was probably meant to say that we're only using the external version, right?
> 
> > This PR drops the internal version of the extensions/pkg/apis/config API.
> > There wasn't even any conversion code and we only used the ~internal~ external version.

We always used the internal version before this change. From now on, there is only the external version and we switch all usages to the external version.

**Pull request merged**
