### PR TITLE
Fix image vector overwrite description

### PR DESCRIPTION
**Pull request by MSSedusch**
**What this PR does / why we need it**:
mount path should point to the directory

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Fix image vector overwrite description
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]

**Comment by rfranzke** [comment]
It should probably be something like `/charts_overwrite` instead of `/charts` (this dir already exists in the image)

**Comment by rfranzke** [comment]
Thanks! Please squash the commits into a single one.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
