### PR TITLE
Drop Kubernetes version support timeline docs

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area documentation
/kind cleanup

**What this PR does / why we need it**:
Due to too many boundary conditions, the support timeline docs for Kubernetes versions have been dropped.

**Special notes for your reviewer**:
/cc @dguendisch @ialidzhikov 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by dguendisch** [comment]
Unfortunately I have no better proposal for a formal/predictable removal policy, hence
/lgtm

**Review by ialidzhikov — COMMENTED** [review]
/approve

**Comment by majst01** [comment]
This information was helpful, at least some information which kubernetes version for a shoot can be provided with which gardener version would be nice, must not be called kubernetes support if this is the problem

**Pull request merged**
