### PR TITLE
clean up io/ioutil deprecation

### LINKED ISSUE #4020: [good first issue] Follow-up on `io/ioutil` deprecation
/exp beginner
/needs help

From https://golang.org/doc/go1.16#ioutil:

> The [io/ioutil](https://golang.org/pkg/io/ioutil/) package has turned out to be a poorly defined and hard to understand collection of things. All functionality provided by the package has been moved to other packages. The io/ioutil package remains and will continue to work as before, but we encourage new code to use the new definitions in the [io](https://golang.org/pkg/io/) and [os](https://golang.org/pkg/os/) packages. Here is a list of the new locations of the names exported by `io/ioutil`:
>
> - [Discard](https://golang.org/pkg/io/ioutil/#Discard) => [io.Discard](https://golang.org/pkg/io/#Discard)
> - [NopCloser](https://golang.org/pkg/io/ioutil/#NopCloser) => [io.NopCloser](https://golang.org/pkg/io/#NopCloser)
> - [ReadAll](https://golang.org/pkg/io/ioutil/#ReadAll) => [io.ReadAll](https://golang.org/pkg/io/#ReadAll)
> - [ReadDir](https://golang.org/pkg/io/ioutil/#ReadDir) => [os.ReadDir](https://golang.org/pkg/os/#ReadDir) (note: returns a slice of [os.DirEntry](https://golang.org/pkg/os/#DirEntry) rather than a slice of [fs.FileInfo](https://golang.org/pkg/io/fs/#FileInfo))
> - [ReadFile](https://golang.org/pkg/io/ioutil/#ReadFile) => [os.ReadFile](https://golang.org/pkg/os/#ReadFile)
> - [TempDir](https://golang.org/pkg/io/ioutil/#TempDir) => [os.MkdirTemp](https://golang.org/pkg/os/#MkdirTemp)
> - [TempFile](https://golang.org/pkg/io/ioutil/#TempFile) => [os.CreateTemp](https://golang.org/pkg/os/#CreateTemp)
> - [WriteFile](https://golang.org/pkg/io/ioutil/#WriteFile) => [os.WriteFile](https://golang.org/pkg/os/#WriteFile)

Use [this Github search](https://github.com/gardener/gardener/search?p=1&q=io%2Fioutil) to list the usages of `io/ioutil` for github.com/gardener/gardener.

### PR DESCRIPTION
**Pull request by hzliangbin**
**How to categorize this PR?**

/kind cleanup 

**What this PR does / why we need it**:
clean up io/ioutil deprecation

**Which issue(s) this PR fixes**:
Fixes #4020 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @hzliangbin for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by hzliangbin** [comment]
@ialidzhikov PTAL

**Comment by timebertt** [comment]
```
> Check
Executing golangci-lint
Executing go vet
Executing gofmt/goimports
Unformatted files detected:
extensions/test/tm/generator/helper.go
plugin/pkg/shoot/tolerationrestriction/config.go
make: *** [Makefile:181: check] Error 1
```

**Comment by rfranzke** [comment]
Hi @hzliangbin, thanks for the PR! 🎉

**Comment by ialidzhikov** [comment]
@hzliangbin, thank you for the PR!

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
