### PR TITLE
Generate junit reports in prow

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:

Generate machine-readable reports for unit and integration test jobs, so that they are nicely summarized in prow (like we already have it for the e2e test job).

Example from https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5784/pull-gardener-unit/1513454017429114880
Screen Shot 2022-04-11 at 12 15 23

### CODE REVIEW

**Comment by timebertt** [comment]
Both `pull-gardener-integration` jobs got `OOMKilled`.
It seems, that executing tests with `ginkgo` instead of `go test` temporarily consumes more memory while compiling (`ginkgo` probably just doesn't have as sophisticated resource management as `go tests`).

I increased the memory limits accordingly: https://github.com/gardener/ci-infra/pull/184

**Comment by timebertt** [comment]
After some back and forth and a bit of trial and error, I settled on the following approach:
- continue to use `go test` for test execution
- pass `--ginkgo.junit-report=junit.xml` to report results in a test file per suite
- collect junit reports after test execution to prow artifact directory

I tried to use `ginkgo` for test execution because it can automatically handle the junit reporting. However, this resulted in the following disadvantages:
- resource management doesn't seem to be as good as `go test`
- no (or not so good) parallel test execution by default
- no symmetry with local test execution
- tests were a bit unstable in CI (partly because of ginkgo's parallel execution)
- test jobs took longer than before (2 or 5 minutes added)

(You can checkout the [PR test history](https://prow.gardener.cloud/pr-history/?org=gardener&repo=gardener&pr=5784) for details)

Thus, I settled on the mentioned approach, which only has the disadvantage of a few lines of bash hacks but none of the other disadvantages.
This is ready for review now :)

**Review by rfranzke — COMMENTED** [review]
Nice!

/lgtm
/approve

**Comment by timebertt** [comment]
/hold

I noticed just now, that my approach with separate report files breaks deck: e.g. https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5784/pull-gardener-unit/1513502166390673408 can't load the results.
It seems, deck can't handle so many report files and we need to merge them into a single file.

**Comment by timebertt** [comment]
> It seems, deck can't handle so many report files and we need to merge them into a single file.

Ok, I think I found a pretty neat solution for this problem. 

I added a small tool (~70 lines) that reuses ginkgo's code for merging report files so that we can benefit from both performant parallel execution via `go test` and automated report collection via `ginkgo`.

Tell me, if you like it! :) 
/hold cancel

**Comment by timebertt** [comment]
Approach works well, now the unit test job page can load the results again: https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5784/pull-gardener-unit/1513538870392655872
Screen Shot 2022-04-11 at 17 37 43

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Pull request merged**
