### PR TITLE
add kubelet cGroupDriver settings to Cloudprofile

### PR DESCRIPTION
**Pull request by dergeberl**
**How to categorize this PR?**
/area os
/kind enhancement

**What this PR does / why we need it**:

We needed a possibility to run the newest Flatcar version with the kubelet setting `cgroupdriver` `systemd`. This is our idea to fix it. We saw that you changed it in one version and reverted it. We thought it might be a good idea to add this setting to the `Cloudprofile`. So it can be set for each `MachineImage` individually.

If it is fine this way let us know, so we can provide also the documentation for this feature.

**Which issue(s) this PR fixes**:
Related https://github.com/gardener/gardener-extension-os-coreos/issues/35

**Special notes for your reviewer**:

**Release note**:
```other operator

```

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @dergeberl for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by voelzmo** [comment]
Hey @dergeberl thanks for your contribution! Sorry for the delay – I've only now been able to look at this PR in a bit more detail.

I do understand your need to run a Flatcar version >=2969.0.0 and that this requires the usage of `cgroups v2`, which in turn is only possible when using `systemd` as your `cgroup driver`. You correctly observed that we initially wanted to introduce `systemd` as the overall default `cgroup driver` when switching to k8s 1.22 and then reverted the changes as we were missing necessary changes for the `containerd` configuration. It seems this work hasn't been picked up yet or described in more detail, unfortunately.

I'm kind of hesitant to merge this change for a number of conceptual reasons:
* Given that we want to switch the default for the `cgroup driver` uniformly to `systemd` and we're not aware of a reason for users to keep using `cgroupfs` on newer k8s version instead, I'm not sure that increasing the API surface here is necessary. I'd therefore like to not make this optional, but rather switch the cgroup driver default entirely
* Doing this on the level of `MachineImageVersion` also feels incorrect, given that the switch to `systemd` shouldn't require any OS level changes – for Flatcar users it seems vice versa that starting from a certain version you'd _have to_ use `systemd` otherwise it stops working, because of cgroups v2. Switching to `systemd` works also with cgroups v1, so this should be an independent change
* We didn't want to allow users to re-configure the cgroup driver and instead tie it to updating to a new k8s version to simplify the implications on node rollout, [given that you shouldn't be doing this operation without triggering a node rollout](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers)

I'm aware that this is a disappointing answer for you because it means you have to wait for a longer period of time with switching to the newer Flatcar versions. Hopefully this makes sense to you from a global perspective. I'll try to create a summary issue with the necessary bits and pieces – maybe that also makes it more feasible to contribute towards the solution we're imagining here.

**Comment by voelzmo** [comment]
Let's use the existing issue #5325 to track the necessary work.

**Pull request closed without merging**
