### PR TITLE
Rolling update of the worker pool on kubeReserved change

### PR DESCRIPTION
**Pull request by MichaelEischer**
**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:

**The PR is not yet completely finished, in particular, the tests still need work. But I'd like to get some feedback on the general approach before wrapping up the test implementation**

Implement rolling update of the worker pools when kubeReserved changes (see #2590). The change essentially consists of three parts:
- The operating system config key now also depends on the kubeReserved value. This ensures that only new workers pick up the changed resource reservations.
- The `WorkerPoolHash` now depends on the kubeReserved value. This triggers the node roll and ensures that the new nodes pick up the new OSC key.
- Nodes are now labeled with a key `worker.gardener.cloud/cloud-config-key` that refers to the corresponding operating system config. This is required for the botanist check `OperatingSystemConfigUpdatedForAllWorkerPools`, which previously calculated the key name itself. However, with additional information becoming relevant for the operating system config key, the old approach is no longer feasible.
- The `evictionThreshold` is not yet included, but should be easy to add if the overall approach is fine.

Open questions:

- [ ] The PR currently triggers an unconditional node roll when using the updated `WorkerPoolHash` in the provider-extensions. Is that acceptable or should the PR try to avoid a node roll when the default kubeReserved values are in use?
- [ ] I'm not entirely happy how my changes in `pkg/component/extensions/worker/worker.go` calculate the oscKey again. Passing that in from the OSC would probably be more elegant?
- [ ] Is the general approach sound?

**Which issue(s) this PR fixes**:
Implements part of "Rolling update of the worker pool when critical kubelet configuration changed" of #2590

**Special notes for your reviewer**:
See open questions above. The tests are still WIP.

**Release note**:
-> I'll add one, once the approach has been sorted out.

```other operator

```

### CODE REVIEW

**Comment by MichaelEischer** [comment]
@rfranzke Can you provide feedback whether you think the high-level approach of the PR is sound? I'd also be interested in comments on the other "open questions" in the PR description.

**Comment by rfranzke** [comment]
I will try, but I cannot promise it since this week is quite busy. If I will not make it, I'll come back by next week.

**Comment by MichaelEischer** [comment]
@rfranzke Any idea when you'll be able to take a look at the approach of this PR?

**Comment by rfranzke** [comment]
> * Nodes are now labeled with a key `worker.gardener.cloud/cloud-config-key` that refers to the corresponding operating system config. This is required for the botanist check `OperatingSystemConfigUpdatedForAllWorkerPools`, which previously calculated the key name itself. However, with additional information becoming relevant for the operating system config key, the old approach is no longer feasible.

I read the commit and also the message there, but I haven't fully understood why this is suddenly necessary. Isn't all this already a "problem" today when e.g. the Kubernetes version of a shoot changes (which also causes node rollout)?
Generally, I think it's fine to no longer check the "old" nodes in this health check because they are about to be removed/replaced very soon anyways. Maybe I'm missing something here.
 
> Open questions:
> 
> * [ ]  The PR currently triggers an unconditional node roll when using the updated `WorkerPoolHash` in the provider-extensions. Is that acceptable or should the PR try to avoid a node roll when the default kubeReserved values are in use?

Unacceptable, sorry. Think of installations with thousands of clusters, even tens of thousands of VMs. We can absolutely not cause the replacement of such many VMs just because we rollout a new provider extension to the landscape.

> * [ ]  I'm not entirely happy how my changes in `pkg/component/extensions/worker/worker.go` calculate the oscKey again. Passing that in from the OSC would probably be more elegant?

WDYM, which alternatives do you have in mind?

> * [ ]  Is the general approach sound?

Yes, looks correct in general.

**Comment by rfranzke** [comment]
> So, in essence the new annotation is there to keep the current behavior of ignoring nodes that use an old OSCKey, but extends it to properly handle kubeReserved. Does that clarify the change?

OK, got it now, thanks for the detailed explanation. This makes perfect sense. I agree that adding the values as annotation to the node is weird. For Kubernetes version and CRI name, they are added as labels also because workload might want to use them for node selectors, but adding the kubeReserved values would be really strange.

> There is already `SetWorkerNameToOperatingSystemConfigsMap()` in `pkg/component/extensions/worker/worker.go` which is also used inside `func (w *worker) deploy(...)`. Instead of just passing the content of the OSCs, it could also include their names. Then the worker code no longer needs to call `operatingsystemconfig.KeyFromWorker(&workerPool, w.values.KubernetesVersion, w.values.KubeletConfig)`. Together with the new annotation mentioned above, that would completely centralize the OSCKey calculations into the `operatingsystemconfig` package (and the corresponding botanist part).

Thanks, also this makes perfect sense. The `operatingsystemconfig.Data` struct already contains the `Object`, see https://github.com/gardener/gardener/blob/84f525624b9aff02e8b3dcd6102f1584f89d87b2/pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go#L185-L204
Can't the `Object.Name` be used?

**Comment by MichaelEischer** [comment]
> Can't the `Object.Name` be used?

You're right, I've completely missed that field. I'll switch to using that field.

**Pull request closed without merging**
