### PR TITLE
local setup: Drop registry caches for `eu.gcr.io` and `ghcr.io`

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
After the switch from eu.gcr.io to AR (europe-docker.pkg.dev) we don't have anymore reference of eu.gcr.io images in Gardener or in extensions.
ghcr.io is also unused after we started copying ghcr.io images to europe-docker.pkg.dev (ref https://github.com/gardener/ci-infra/pull/982) because ghcr.io does not support IPv6 natively. The only ghcr.io image that could be used in local setup is https://github.com/gardener/gardener/blob/238408f14a53af6af9eb4e1d8144eb4f14a002b0/hack/kind-up.sh#L208 but by default the kind cluster is created without the `--with-lpp-resize-support` flag.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```other developer
local setup: Registry caches for `eu.gcr.io` and `ghcr.io` are now removed as there are no images from these upstream registries.
```

### CODE REVIEW

**Review by dimitar-kostadinov — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
The `test pull-gardener-unit` failure: https://github.com/gardener/gardener/issues/10189

---

/test pull-gardener-unit

**Comment by ialidzhikov** [comment]
The `pull-gardener-integration` failure:
```
Will run [1m5[0m of [1m5[0m specs
W0724 07:25:51.850468   33641 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W0724 07:25:51.850531   33641 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
[38;5;10m•[0mW0724 07:25:52.510670   33641 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W0724 07:25:52.510736   33641 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
[38;5;10m•[0mW0724 07:25:52.977329   33641 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
W0724 07:25:52.977461   33641 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
[38;5;10m•[0mpanic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d3f586]

goroutine 493 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x30040a0?, 0x4b426c0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/gardener/gardener/pkg/nodeagent/controller/operatingsystemconfig.(*Reconciler).Reconcile(0xc00059ad20, {0x37673b8, 0xc000ae4780}, {{{0xc000c0c210?, 0x5?}, {0xc000c0c200?, 0xc000c65d10?}}})
	/home/prow/go/src/github.com/gardener/gardener/pkg/nodeagent/controller/operatingsystemconfig/reconciler.go:145 +0xea6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x376ce50?, {0x37673b8?, 0xc000ae4780?}, {{{0xc000c0c210?, 0xb?}, {0xc000c0c200?, 0x0?}}})
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00059adc0, {0x37673f0, 0xc00037ed70}, {0x30ff480, 0xc0008522e0})
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/internal/controller/controller.go:316 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00059adc0, {0x37673f0, 0xc00037ed70})
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/internal/controller/controller.go:266 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 366
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.5/pkg/internal/controller/controller.go:223 +0x50c
```

This should be fixed by https://github.com/gardener/gardener/pull/10188 (cc @timuthy).

---

/test pull-gardener-integration

**Comment by ialidzhikov** [comment]
The `pull-gardener-e2e-kind-ha-single-zone-upgrade` failure:

```
  [38;5;9m[FAILED] Expected success, but got an error:
      <*retry.Error | 0xc00011c700>: 
      retry failed with context deadline exceeded, last error: shoot "e2e-upgrade" was not successfully reconciled
      {
          ctxError: <context.deadlineExceededError>{},
          err: <*errors.errorString | 0xc0001103a0>{
              s: "shoot \"e2e-upgrade\" was not successfully reconciled",
          },
      }[0m
  [38;5;9mIn [1m[It][0m[38;5;9m at: [1m/home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/upgrade/upgrade.go:61[0m [38;5;243m@ 07/24/24 08:01:37.954[0m
```

---

/test pull-gardener-e2e-kind-ha-single-zone-upgrade

**Review by oliver-goetz — CHANGES_REQUESTED** [review]
Thanks for your PR 🙂 

`ghcr.io` and `eu.gcr.io` are also part of the registry cache config for prow ([ref](https://github.com/gardener/gardener/blob/master/example/gardener-local/registry-prow/kustomization.yaml)). Please remove it from here too.

**Comment by ialidzhikov** [comment]
> `ghcr.io` and `eu.gcr.io` are also part of the registry cache config for prow ([ref](https://github.com/gardener/gardener/blob/master/example/gardener-local/registry-prow/kustomization.yaml)). Please remove it from here too.

Yep, I just found the same thing while looking into other things. Thanks!

**Review by oliver-goetz — APPROVED** [review]
/lgtm

**Comment by shafeeqes** [comment]
/hold
to unblock tide

**Comment by ialidzhikov** [comment]
For the `pull-gardener-e2e-kind-upgrade` failure I opened https://github.com/gardener/gardener/issues/10193.

**Pull request merged**
