### PR TITLE
Upgrade github.com/gardener/autoscaler from v0.10.0 to v0.12.0

### PR DESCRIPTION
**Pull request by hardikdr**
**How to categorize this PR?**

/priority normal

**What this PR does / why we need it**: Bump the Autoscaler version to v0.12.0 .

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
MCM provider now also returns unregistered nodes to Autoscaler. This change enables autoscaler to pick up an alternate worker-pool if the chosen one can't be scaled-up. 
```
```improvement operator
Autoscaler avoids scaling down the machines which are already being terminated.
```

### CODE REVIEW

**Comment by hardikdr** [comment]
With autoscaler moving to the `pkg/operations/controlplane` from the charts, hope this remains the way to make the 2 different versions of autoscaler deploy for `< k8s 1.16` and `>=k8s 1.16`.

**Comment by hardikdr** [comment]
I anyways tested it quickly, works fine.

**Review by prashanth26 — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
