### PR TITLE
Upgrade plutono version

### PR DESCRIPTION
**Pull request by istvanballok**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Upgrade plutono version to https://github.com/credativ/plutono/releases/tag/v7.5.24

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @rickardsjp 

**Release note**:

```other operator
The Plutono version has been updated from `v7.5.23` to `v7.5.24`.
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/approve

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Review by rickardsjp — APPROVED** [review]
/lgtm

**Pull request merged**
