### PR TITLE
Upgrade to ginkgo v2

### LINKED ISSUE #5311: Upgrade to ginkgo v2
**How to categorize this issue?**

/area testing dev-productivity
/kind enhancement

**What would you like to be added**:

Upgrade our ginkgo dependency to [v2](https://github.com/onsi/ginkgo/releases/tag/v2.0.0).
There is a [migration guide](https://onsi.github.io/ginkgo/MIGRATING_TO_V2) available describing all the new features and breaking changes.

**Why is this needed**:

- with the release of v2, ginkgo v1 is officially out of maintenance
- v2 brings a lot of new features and improved behavior that we can benefit from (especially in e2e and testmachinery tests)
- in the context of https://github.com/gardener/gardener/issues/5310, we would like to make use of the improved ginkgo CLI in v2 (simplified parallel test execution, generating machine-readable reports out of the box, etc.)

**What needs to be done**:

In the upgrade PR:

- [x] upgrade the dependency itself
- [x] adapt import paths `s|import "github.com/onsi/ginkgo|import "github.com/onsi/ginkgo/v2|g`
- [x] drop imports of `github.com/onsi/ginkgo/extensions/table`, see [Changed: First-class Support for Table Testing](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-first-class-support-for-table-testing) 
- [x] replace deprecated `done` channel, see [Removed: Async Testing](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-async-testing)
- [x] adapt the test framework's custom reporter for testmachinery, see [Removed: Custom Reporters](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-custom-reporters)
  - see [here](https://github.com/gardener/gardener/blob/3b548efd49086264eb4bed5aff2c62cd1cc9e4ee/test/suites/shoot/run_suite_test.go#L65-L71) for an example on how to adapt extensions that are using framework's custom reporter
- [x] `ginkgo.{AfterSuite,BeforeSuite}` don't accept timeout parameters anymore
- [x] switch from deprecated `CurrentGinkgoTestDescription()` to `CurrentSpecReport()`, see [Changed: CurrentGinkgoTestDescription()](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-currentginkgotestdescription)
- [x] fix test suites that were not calling `gomock.Controller.Finish()` before and are now suddenly failing because of missing/unexpected calls. Support in `GinkgoT()` was extended and now `Finish` doesn't have to be called anymore to verify calls, see [DeferCleanup](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#defercleanup)
- [x] verify that we don't break anything in the testmachinery tests

After that:

- upgrade the ginkgo dependency and follow the same steps in extensions and other repositories vendoring g/g as well
- start making use of the new features, e.g.:
  - [Spec Decorators](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#spec-decorators), e.g. `Focus`, `Serial`, `Ordered`, `FlakeAttempts`
  - [Spec Labels](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#spec-labels)
  - [DeferCleanup](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#defercleanup)
  - [EntryDescription](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#new-table-level-entry-descriptions)
  - start using machine-readable reports in CI (prow, concourse doesn't support it, I assume), see [Improved: Reporting Infrastructure](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#improved-reporting-infrastructure)

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area testing dev-productivity
/kind enhancement

**What this PR does / why we need it**:

Performs the steps listed in https://github.com/gardener/gardener/issues/5311

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/5311

**Special notes for your reviewer**:

I verified that we don't break anything in the testmachinery tests by running some of our dev tests against this version of the test framework.

/squash
cc @hendrikKahl for 3b548efd49086264eb4bed5aff2c62cd1cc9e4ee

**Release note**:

```breaking dependency
The `ginkgo` dependency has been upgraded to `v2.1.0` (major version upgrade). You can consult [gardener/gardener#5311](https://github.com/gardener/gardener/issues/5311) and the [migration guide](https://onsi.github.io/ginkgo/MIGRATING_TO_V2) for the steps required by this.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

Well-structured, thank you! Looking forward to this :)

**Comment by timebertt** [comment]
> I verified that we don't break anything in the testmachinery tests by running some of our dev tests against this version of the test framework.

/ready

**Comment by vpnachev** [comment]
I just observed one failure from yesterday evening 
```
2022-01-27 17:47:32	=== RUN   TestCPMigrationApplications
2022-01-27 17:47:32	Ginkgo detected an issue with your spec structure
2022-01-27 17:47:32	ginkgo.BeforeSuite(contextify(body, timeout))
2022-01-27 17:47:32	/src/test/framework/gingko_utils.go:46
2022-01-27 17:47:32	  It looks like you are trying to add a [BeforeSuite] node within a container
2022-01-27 17:47:32	  node.
2022-01-27 17:47:32	
2022-01-27 17:47:32	  BeforeSuite can only be called at the top level.
2022-01-27 17:47:32	
2022-01-27 17:47:32	  Learn more at:
2022-01-27 17:47:32	  http://onsi.github.io/ginkgo/#suite-setup-and-cleanup-beforesuite-and-aftersuite
2022-01-27 17:47:32	
2022-01-27 17:47:32	FAIL	github.com/gardener/gardener/test/system/shoot_cp_migration	0.136s
2022-01-27 17:47:32	FAIL
2022-01-27 17:47:33	=== RUN   TestCPMigrationApplications
2022-01-27 17:47:33	Ginkgo detected an issue with your spec structure
2022-01-27 17:47:33	ginkgo.BeforeSuite(contextify(body, timeout))
2022-01-27 17:47:33	/src/test/framework/gingko_utils.go:46
2022-01-27 17:47:33	  It looks like you are trying to add a [BeforeSuite] node within a container
2022-01-27 17:47:33	  node.
2022-01-27 17:47:33	
2022-01-27 17:47:33	  BeforeSuite can only be called at the top level.
2022-01-27 17:47:33	
2022-01-27 17:47:33	  Learn more at:
2022-01-27 17:47:33	  http://onsi.github.io/ginkgo/#suite-setup-and-cleanup-beforesuite-and-aftersuite
2022-01-27 17:47:33	
2022-01-27 17:47:33	FAIL	github.com/gardener/gardener/test/system/shoot_cp_migration	0.146s
2022-01-27 17:47:33	FAIL
```

As only this PR has recently changed something in https://github.com/gardener/gardener/tree/master/test/system/shoot_cp_migration, I guess it could be the reason. Could you please check?

**Pull request merged**
