### PR TITLE
Improve when to delete kube-apiserver HPA during hibernation

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
Delete kube-apiserver HPA only after scaling down kube-apiserver. Previously, we deleted the HPA before applying the chart which led to a recreation of the HPA although we wanted to shoot to get hibernated/scaled down to zero.
We have seen cases where the HPA scaled up the kube-apiserver of shoots again although we didn't desire this, bringing the control plane into an inconsistent state and consuming needless resources.

/cc @MartinWeindel 

**Release note**:

```improvement operator
The HPA for the shoot's kube-apiserver is now deleted only after the control plane gets scaled down when the shoot shall be hibernated, preventing that it accidentally scales up the kube-apiserver deployment again (although the shoot should be hibernated).
```

### CODE REVIEW

**Comment by vlerenc** [comment]
FYI: We have also seen cases where the cluster cannot wakeup anymore if it's a large one. The control plane wakes up with initial sizing, but with lots of resources, some pods. When the machines get back and the pods get scheduled and the kubelets try to create all of them, the control plane keeps crashing for quite long. We are, essentially, not capable to resize fast enough.

**Comment by rfranzke** [comment]
Isn't this rather a vertical scaling issue that should be solved automatically once we introduce mechanism for scaling etcd/kube-apiserver vertically? We want/need to have fast/proper scaling of these two components anyways, so when waking up a hibernated shoot the same mechanism should (fast) scale up both (although, they wake up with initial/standard sizing)?

**Comment by vlerenc** [comment]
I doubt, it will work this way. In the performance tests we have seen problems, prolonged instabilities, slowness in scale-out/up. I guess, but I don't know, that's also the reason why the CERN folks said, they couldn't put their Higgs Boson re-discovery into a single GKE cluster of 700 nodes. They had to break it down into multiple clusters. I expect/assume, GKE clusters can run 700 nodes, but I guess not scale up/out fast enough during a 20m keynote. ;-)

**Review by timuthy — APPROVED** [review]
/lgtm

**Pull request merged**
