### PR TITLE
Upgrade `k8s.io/*` to `v0.26.2`, `sigs.k8s.io/controller-runtime` to `v0.14.5`

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
Upgrade dependencies
- k8s.io/* to v0.26.2
- sigs.k8s.io/controller-runtime to v0.14.5

This PR also adds dashboards related to the newly added metrics in https://github.com/kubernetes-sigs/controller-runtime/pull/2217

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```other developer
The following dependencies are updated:
- `k8s.io/*` : `v0.26.1` -> `v0.26.2`
- `sigs.k8s.io/controller-runtime`: `v0.14.4` -> `v0.14.5`
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve

**Pull request merged**
