### PR TITLE
Update github templates with priority label changes

### PR DESCRIPTION
**Pull request by ialidzhikov**
/priority 4

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timebertt** [comment]
Alternative consideration: we could also drop the default priority label in the templates (or at least for PRs).
I never found them useful because rarely no one changes them and so they just contribute to the large noise of our labels.
If someone wants to express an elevated priority they can explicitly label the issue/PR accordingly.
WDYT?

**Comment by ialidzhikov** [comment]
> Alternative consideration: we could also drop the default priority label in the templates (or at least for PRs).
> I never found them useful because rarely no one changes them and so they just contribute to the large noise of our labels.
> If someone wants to express an elevated priority they can explicitly label the issue/PR accordingly.
> WDYT?

I now removed the priority label from the PR template. @gardener/gardener-maintainers , let me know if there is a strong opinion that the priority label should be present by default in the PR template.

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Should we then also remove the priority label from the issue templates?

**Comment by timebertt** [comment]
Merging now, to include it in the release. 

> Should we then also remove the priority label from the issue templates?

Can still be done later :)

**Pull request merged**
