### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.12.0->v0.12.1]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` bugfix user github.com/gardener/etcd-druid #401 @shreyas-s-rao
Fix statefulset volumeClaimTemplate `StorageClassName` value population if etcd storageClass is an empty string.
```

### CODE REVIEW

**Review by shreyas-s-rao — APPROVED** [review]

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
