### PR TITLE
Allow deletion and migration of never-created clusters with dynamic node network

### LINKED ISSUE #11035: Shoot cannot be deleted or migrated if dynamic node network allocation fails
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:

On some infrastructures, the provider extension dynamically allocates the shoot node network range, see [docs](https://github.com/gardener/gardener/blob/master/docs/extensions/resources/infrastructure.md#dynamic-nodes-network-for-shoot-clusters). I.e., `Shoot.spec.networking.nodes` is empty at creation time, but is filled once the provider extension has populated `Infrastructure.status.nodesCIDR`.

If the shoot creation fails, because the `Infrastructure` creation has never succeeded, gardenlet refuses to delete the shoot with:
```
Shoot's node cidr is empty Operation will be retried.
```

**What you expected to happen**:

gardenlet should delete shoots for which the infrastructure has never been created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a local shoot without `Shoot.spec.network.nodes`:
```bash
yq 'del(.spec.networking.nodes)' example/provider-local/shoot.yaml | k apply -f
```

2. The local `Infrastructure` creation fails with the following error. provider-local doesn't support the dynamic node network allocation.
```bash
$ k -n shoot--local--local get infra local -oyaml | yq .status.lastOperation
description: 'Error reconciling infrastructure: shoot specification does not contain node network CIDR required for VPN tunnel'
lastUpdateTime: "2024-12-13T13:30:10Z"
progress: 50
state: Error
type: Create
```

3. Hence, the shoot creation never succeeds and gardenlet doesn't publish `Shoot.spec.networking.nodes` accordingly:
```bash
$ k -n garden-local get shoot local -oyaml | yq .status.lastErrors
- description: 'task "Waiting until shoot infrastructure has been reconciled" failed: Error while waiting for Infrastructure shoot--local--local/local to become ready: error during reconciliation: Error reconciling infrastructure: shoot specification does not contain node network CIDR required for VPN tunnel'
  lastUpdateTime: "2024-12-13T13:31:53Z"
  taskID: Waiting until shoot infrastructure has been reconciled

$ k -n garden-local get shoot local -oyaml | yq .spec.networking
ipFamilies:
  - IPv4
pods: 10.3.0.0/16
services: 10.4.0.0/16
type: calico
```

4. Delete the shoot:
```bash
$ ./hack/usage/delete shoot local garden-local
shoot.core.gardener.cloud/local annotated
shoot.core.gardener.cloud "local" deleted
```

5. The shoot deletion fails and is stuck forever:
```bash
$ k -n garden-local get shoot local -oyaml | yq .status.lastOperation
description: Shoot's node cidr is empty Operation will be retried.
lastUpdateTime: "2024-12-13T13:35:58Z"
progress: 0
state: Error
type: Delete
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.106.2
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area usability
/kind bug

**What this PR does / why we need it**:

This PR ensures that gardenlet can delete and migrate shoots that use dynamic node network allocation, even if the infrastructure creation has never been successfully completed.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/11035

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Gardener can now delete and migrate shoots that use dynamic node network allocation, even if the infrastructure creation has never been successfully completed.
```

### CODE REVIEW

**Review by marc1404 — COMMENTED** [review]
/lgtm

Thanks for the quick turnaround on the bug! 🐞 :)

**Review by rfranzke — COMMENTED** [review]
/approve

**Pull request merged**
