### PR TITLE
Remove etcd and etcd-backup-restore images

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
After the introduction of `etcd-druid` we decided that it does not make sense to let Gardener control the versions of the `etcd` and `etcd-backup-restore` images as their manifests/configuration are controlled by `etcd-druid`. It is necessary for a successful deployment that the version works well with the manifests/configuration.
Consequently, `etcd-druid` was meanwhile made capable of controlling these versions using the image vector concept (see gardener/etcd-druid#23 and gardener/etcd-druid#24).
Gardener already supports overwriting the image vector for components it deploys, see #2036 and https://github.com/gardener/gardener/blob/master/docs/deployment/image_vector.md#image-vectors-for-dependent-components.
This PR now removes the `etcd` and `etcd-backup-restore` images from Gardener so that `etcd-druid` can take over.

**Special notes for your reviewer**:
/cc @shreyas-s-rao @swapnilgm @georgekuruvillak - once this PR is merged you need to release a new version of etcd-druid when you want Gardener to use a newer/different version of etcd or etcd-backup-restore. There won't be PRs such as #2260 anymore to this repository. Instead, they should be opened to the [gardener/etcd-druid](https://github.com/gardener/etcd-druid) repository. I opened gardener/etcd-druid#50 to track this.

ℹ️Softly depends on #2263

**Release note**:

```noteworthy operator
Gardener's image vector does no longer contain `etcd` and `etcd-backup-restore`. If you want to overwrite these versions you must do it via the `etcd-druid`. Please consult [this document](https://github.com/gardener/gardener/blob/master/docs/deployment/image_vector.md#image-vectors-for-dependent-components) for more information.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Important note: The version of `etcd-druid` that Gardener is using is still referencing `etcd-backup-restore:0.8.0`. Hence, merging this PR without a new `etcd-druid` release would result in Gardener not deploying the `v0.9.0` version.

@shreyas-s-rao @georgekuruvillak @swapnilgm can you please release a new druid version now that https://github.com/gardener/etcd-druid/pull/51 is merged?

**Comment by rfranzke** [comment]
Thanks!

**Review by swapnilgm — CHANGES_REQUESTED** [review]
Simply removing injection won't work right? Since it won't remove the configured etcd image from existing etcd resource. Since druid will see that for exsiting shoot etcd/backup image is already confgirued in CRD, so if won't apply it from the imagevctor.  We will have to delete and recreate old etcd's with image injection.

**Comment by rfranzke** [comment]
What do you mean? I have removed the `image` field of the `Etcd` resource, it's part of the PR, so after shoot reconciliation this field will be omitted and the version of druid will be taken.

> Since druid will see that for exsiting shoot etcd/backup image is already confgirued in CRD, so if won't apply it from the imagevctor. We will have to delete and recreate old etcd's with image injection.

I don't understand - can you explain what you mean? Did you test it locally? In my tests, I was reconciling a shoot and it didn't restart (as expected, because I didn't specify an imagevector overwrite for druid). Then I added such an imagevector overwrite and I saw druid being restarted. In the subsequent shoot reconciliation also the etcds got restarted.

**Comment by swapnilgm** [comment]
ok Ignore it. I had misunderstanding about how gardener applies the charts/templates.

**Review by swapnilgm — APPROVED** [review]
lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
