### PR TITLE
Rework and merge CoreDNS and Node Local DNS dashboards

### PR DESCRIPTION
**Pull request by vicwicker**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

This PR merges the CoreDNS and Node Local DNS dashboards into a single improved DNS dashboard. The motivation that triggered this change was that with the CoreDNS version 1.11, the [forward](https://coredns.io/plugins/forward/) plugin deprecated some of the metrics used in the DNS upstream panels and hence those panels showed no data. Node Local DNS is a thin wrapper around CoreDNS and it still uses CoreDNS 1.10 internally. Hence, only the CoreDNS dashboard needed to be fixed. The first commits in the history fix the broken DNS upstream panels of the CoreDNS dashboard:

1. They adapt the shoot Prometheus scrape configuration to stop scraping the old deprecated metrics in favour of the new ones,
2. Fix the CoreDNS upstream dashboards to query the new metrics, and 
3. Revisit the wording used in the `NodeLocalDNS` dashboard, which referenced `CoreDNS` terminology.

The remaining commits in the history merge the CoreDNS and Node Local DNS dashboards into a single improved DNS dashboard.

While working on this we noticed that many of the panels could be improved. For instance, some of the old queries used the type label from the CoreDNS metrics although [`honor_labels`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) (default false) is not set for the CoreDNS scrape configuration. This means that this label collides with the Gardener type label (i.e., that has values shoot or seed) and the original CoreDNS type label is renamed to exported_type. Other queries used counter values without the rate function: they calculated the difference between the current value and the value $__interval minutes ago. Calculating the aforementioned difference returns bogus values when the counter is reset and the rate function should be used instead, which properly handles counter resets.

The CoreDNS and Node Local DNS dashboard are merged into one dashboard to ease fixing duplicated bugs. They share most of the panels and, when not, the panels in the new single dashboard clearly indicate so. An additional benefit of having a single dashboard is also the unified view of all DNS activity within a shoot, regardless of CoreDNS or Node Local DNS. We introduced a drop-down button to choose specific DNS jobs.

This PR also introduces a new hack utility to iterate over dashboard changes. We used it here to achieve minimal commits that can be easy to review: we do a small change in the Plutono UI, save the dashboard and export it into the codebase using this tool.

Finally, the following screenshots compare the status of the previous and new dashboards:

<details><summary>Previous CoreDNS dashboard</summary>

Screenshot 2024-07-03 at 10-29-18 CoreDNS - Plutono

</details>

<details><summary>Previous Node Local DNS dashboard</summary>

Screenshot 2024-07-03 at 10-30-37 NodeLocalDNS - Plutono

</details>

<details><summary>New DNS dashboard</summary>

Screenshot 2024-07-05 at 15-15-05 DNS - Plutono

</details>

**Special notes for your reviewer**:

/cc @istvanballok @rickardsjp 
/fyi @adenitiu @etiennnr 

**Release note**:

```bugfix operator
Merge the CoreDNS and Node Local DNS dashboards into a single improved DNS dashboard
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
Thanks a lot for the change. It looks good from my perspective.

/lgtm

As node-local-dns does not use coredns 1.11, yet, its dashboards need to stay as is, but eventually it will need to be adapted in the same way. How should we proceed in this regard? Do you want to track it via an issue, a `TODO` or do you have something else in mind?

**Comment by ScheererJ** [comment]
> > How should we proceed in this regard? Do you want to track it via an issue, a `TODO` or do you have something else in mind?
> 
> I think the easiest would be a TODO directly in the imagevector similar to [this comment](https://github.com/gardener/gardener/blob/master/imagevector/images.yaml#L380), so that the reminder is as visible as possible when the node-local-dns version changes. If that's okay with you, I can include it as part of this PR.

That is absolutely fine with me.

> Also, @istvanballok and I discussed today that some of the panels in these dashboards are not that meaningful and / or their queries have bugs. For instance, they do not tolerate counter restarts correctly, which might lead to negative results if the query performs a subtraction. We agreed on using this PR to improve this so there will be some additional commits on top.

+1

**Review by istvanballok — APPROVED** [review]
/lgtm

**Pull request merged**
