### PR TITLE
Update github.com/kubernetes-csi/external-snapshotter

### LINKED ISSUE #7750: gardenlet: VolumeSnapshot cleanup mechanism does no longer work
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
https://github.com/gardener/gardener/pull/5104 introduced deletion of VolumeSnapshots and VolumeSnapshotContents explicitly in gardenlet.
Currently this mechanism does no longer work as the provider-extension upgraded to external-snapshotter@v6 and the VolumeSnapshot and VolumeSnapshotContent resource are no longer served by in `v1beta1`. They are no served in `v1` only. Ref https://github.com/gardener/gardener-extension-provider-aws/pull/666

```
 % k get volumesnapshots.v1.snapshot.storage.k8s.io
No resources found in default namespace.
% k get volumesnapshots.v1beta1.snapshot.storage.k8s.io
error: the server doesn't have a resource type "volumesnapshots"
```

**What you expected to happen**:
gardenlet to clean up VolumeSnapshots in `v1`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an aws Shoot

2. Create a VolumeSnapshot

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: gardener-extension-admission-aws
  namespace: default
  annotations:
  labels:
    app.kubernetes.io/name: gardener-extension-admission-aws
    app.kubernetes.io/instance: release-name
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gardener-extension-admission-aws
    app.kubernetes.io/instance: release-name
  ports:
  - port: 443
    protocol: TCP
    targetPort: 10250
```

3. Make sure the VolumeSnapshot won't be deleted by gardenlet

In https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/utils/kubernetes/client/client.go#L394-L399 if you remove `meta.IsNoMatchError(err) || `, then you will see that gardenlet is failing with

```yaml
lastErrors:
  - description: "task \"Cleaning Kubernetes resources\" failed: 2 errors occurred:\n\t*
      no matches for kind \"VolumeSnapshot\" in version \"snapshot.storage.k8s.io/v1beta1\"\n\t*
      no matches for kind \"VolumeSnapshotContent\" in version \"snapshot.storage.k8s.io/v1beta1\"\n\n"
    lastUpdateTime: "2023-04-04T15:15:23Z"
    taskID: Cleaning Kubernetes resources
```

Hence, currently gardenlet cannot delete VolumeSnapshots and as the no match error is ignored, it is failing silently.

**Anything else we need to know?**:
We should update our code to use `v1` to delete the VolumeSnapshots.

**Environment**:

- Gardener version: v1.67.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
See  https://github.com/gardener/gardener/issues/7750

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7750

**Special notes for your reviewer**:
The `v1` API is served starting `external-snapshotter@v4`.
provider extensions maintained in the gardener org already use a higher external-snapshotter versions. Some versions (for example external-snapshotter@v6.2.1)  do not serve `v1beta1`:
- provider-aws uses external-snapshotter@v6.2.1 - [ref](https://github.com/gardener/gardener-extension-provider-aws/blob/e12c20f1ff0c56cbaaf8526fbc8cfae64262c6de/charts/images.yaml#L223)
- provider-gcp uses external-snapshotter@v6.2.1 - [ref](https://github.com/gardener/gardener-extension-provider-gcp/blob/322bf7fd181cb29e33884a074227ee0295da6225/charts/images.yaml#L213)
- provider-azure uses external-snapshotter@v6.2.1 - [ref](https://github.com/gardener/gardener-extension-provider-azure/blob/ec4c20cfe43c0942fa63a297c58afa5533dea90b/charts/images.yaml#L254)
- provider-openstack uses external-snapshotter@v6.2.1 - [ref](https://github.com/gardener/gardener-extension-provider-openstack/blob/588ccbeb572c739d376445fdb746218dedc0aa1d/charts/images.yaml#L299)
- provider-alicloud uses external-snapshotter@v4.2.1 - [ref](https://github.com/gardener/gardener-extension-provider-alicloud/blob/bff5cb198bea26cb51d5abd9da1a7ad055d328ac/charts/images.yaml#L79)
- provider-vsphere uses external-snapshotter@v6.2.1 - [ref](https://github.com/gardener/gardener-extension-provider-vsphere/blob/a67eee41e3ce73ade3832f1c42ba0cf0accea978/charts/images.yaml#L58)

**Release note**:

```breaking operator
gardenlet now cleans up VolumeSnapshot and VolumeSnapshotContent resources from the `v1` API of the `snapshot.storage.k8s.io` group. `v1` is served starting `external-snapshotter@v4`. Before upgrading to this version of Gardener make sure that provider extension install at least `external-snapshotter@v4` and do not install any lower version.
```

```
An issue causing gardenlet to fail to clean up VolumeSnapshot and VolumeSnapshotContent resources in environments with provider extensions using latest versions of external-snapshotter is now fixed. gardenlet now lists and deletes VolumeSnapshot and VolumeSnapshotContent resources from the v1 API of the `snapshot.storage.k8s.io` group.
```

### CODE REVIEW

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
It seems that `make generate` failed:
```
Generating deepcopy funcs
F0405 15:44:50.290491    6013 deepcopy.go:698] Hit an unsupported type github.com/gardener/gardener/pkg/apis/authentication/v1alpha1.AddToScheme.
make[1]: *** [/home/prow/go/src/github.com/gardener/gardener/Makefile:238: generate] Error 255
make[1]: Leaving directory '/home/prow/go/src/github.com/gardener/gardener'
make: *** [Makefile:214: check-generate] Error 1
```

/hold

**Comment by ialidzhikov** [comment]
I downgraded to github.com/kubernetes-csi/external-snapshotter@v4. github.com/kubernetes-csi/external-snapshotter@v6 updates other transitive dependencies (k8s.io/gengo, github.com/google/gnostic and others).

**Pull request merged**
