### PR TITLE
Remove netpol e2e test generator

### LINKED ISSUE #4581: Consider removing/reworking SeedNetworkPoliciesTest integration test
**How to categorize this issue?**
/area testing
/kind bug
/priority 3

**What happened**:
Since longtime we have the following issues opened:
- https://github.com/gardener/gardener-extension-provider-aws/issues/20
- https://github.com/gardener/gardener-extension-provider-gcp/issues/20
- https://github.com/gardener/gardener-extension-provider-azure/issues/23
- https://github.com/gardener/gardener-extension-provider-openstack/issues/18
- https://github.com/gardener/gardener-extension-provider-alicloud/issues/14

We should rather remove or rework this test as:
- IIUC the test currently is not executed in presubmit or in any cron manner by the test machinery -> does not bring any value as we don't understand whether we have a regression or not
- The test seems to always fail
- The test is quite unmaintained - relies on Logging feature to be always enabled; does not handle the case where the ReversedVPN feature gate is enabled; etc.
- The test is quite complex as it is generated by a huge string with golang code -> see `extensions/test/e2e/framework/networkpolicies/generators/networkpolicies.go`

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area testing
/kind cleanup

**What this PR does / why we need it**:

This PR removes the netpol e2e tests for the following reasons:
- Repetition in the extensions ([example configured CP components](https://github.com/gardener/gardener-extension-provider-gcp/blob/5413e44e0df06337fda102626adb99704268f5d5/test/e2e/netpol-gen/app/gcp.go#L43-L63))
- Double maintenance in gardener/gardener ([example labels](https://github.com/gardener/gardener/blob/7dd736f30c280354a29a362d29b53e81eb179fa5/extensions/test/e2e/framework/networkpolicies/agnostic.go#L38-L46))
- Used code generation for this test is intricate, no documentation exists, only maintainable with increased effort
- Tests are designed in a provider-dependend way although most of the netpols (in many cases all netpols) come from Gardener and aren't modified by extensions.
- Tests have been having issues and have been skipped for a longer period of time (see #4581 for more reasons and linked issues)

**Which issue(s) this PR fixes**:
Fixes #4581

**Special notes for your reviewer**:
Today, we already unit test netpolds in `gardener/gardener` and also added a lot of unit tests for involved components, i.e. we make sure they get necessary labels.
In the future, we are still open to add netpol integration tests to Gardener in a more readable and maintainable fashion. Imho, there is too much technical debt to continue with the current test implementation. I think about recycling some of the generated e2e test ([example](https://github.com/gardener/gardener-extension-provider-gcp/blob/master/test/e2e/networkpolicies/networkpolicy_test.go)) and add them to `gardener/gardener` in the near future.

**Release note**:

```breaking developer
The e2e test network policy generator has been removed from `gardener/gardener` because it has been out of maintenance for a longer period of time. Please remove any references to `github.com/gardener/gardener/extensions/test/e2e/framework/networkpolicies/generators`.
```

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
/lgtm

**Comment by rfranzke** [comment]
```
> Generate / Vendor Check
>> make generate
>> make revendor
make revendor needs to be run:
 M go.mod
make: *** [Makefile:193: check-generate] Error 1
```

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
