### PR TITLE
Update k8s.io/helm

### PR DESCRIPTION
**Pull request by friedrichwilken**
This PR upgrades the version of the used version of `k8s.io/helm` from `v2.13.1` to `v2.16.1` in the `replace` of `go.mod` to prevent possible security issues.

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by timebertt** [comment]
Oops, overlooked the failing unit test. 
@FriedrichWilken can you check https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5804/pull-gardener-unit/1514494781344976896?
/lgtm cancel
/approve cancel

**Comment by friedrichwilken** [comment]
@timebertt will do.

**Comment by rfranzke** [comment]
@FriedrichWilken Do you still plan to pursue this PR? If yes, can you fix the checks so that we can proceed with it, please?

**Comment by friedrichwilken** [comment]
@rfranzke @timebertt I finally fixed this; all tests green. Will squash now.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
