### PR TITLE
Deactivate GitHub Action "Commit Message Check"

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
Prow is now checking for invalid commit messages, thus we don't need the GitHub action anymore.

**Special notes for your reviewer**:
This PR also checks if the prow plugin really works 😄 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
Test successful 😃

**Review by timebertt — APPROVED** [review]
Awesome, thank you!
/lgtm

**Comment by oliver-goetz** [comment]
~You might have to merge manually, because afaik bots are not allowed to merge changes which affect GitHub workflows, but let's see first.~

I was wrong, he did it.

**Pull request merged**
