### PR TITLE
[ci:component:github.com/gardener/vpn2:0.7.0->0.8.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` noteworthy operator github.com/gardener/vpn2 #12 @ScheererJ
VPN shoot client can now be run with a privileged init container and a non-privileged runtime container
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@ScheererJ @DockToFuture just to confirm: can this PR be merged separately from https://github.com/gardener/gardener/pull/6352?

**Comment by ScheererJ** [comment]
@ialidzhikov Yes, this pull request is a prerequisite for #6352, but should run just fine, i.e. without any behavioural change, on its own.

**Review by ialidzhikov — APPROVED** [review]
/approve

**Pull request merged**
