### PR TITLE
Validate network overlapping of shoot and seed

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Add validation for network overlapping between shoot and seed, in case the seed is explicitly set in the shoot manifest. Also, I rename `haveDisjointedNetworks` to  `hasDisjointedNetworks`
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
It looks like the check was missing, so nice contribution. I guess you could also and unit tests for the validation that you introduce.

**Comment by rfranzke** [comment]
Nice, thank you! As @ialidzhikov suggested: Please add some unit tests before we merge this one.

**Comment by vpnachev** [comment]
Thanks for the review!
I have added a unit test.

Also a bug fix in the unit tests is added, otherwise the change of the shoot spec in my test makes other tests to fail.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by adracus** [comment]
\lgtm

**Review by adracus — APPROVED** [review]

**Pull request merged**
