### PR TITLE
resize prometheus pvc size to 20Gi

### PR DESCRIPTION
**Pull request by knightXun**
resize prometheus pvc size to 20Gi, because the minimum pvc size of alicloud is 20Gi.

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @knightXun for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by rfranzke** [comment]
Can you rather configure your alicloud `Seed` object appropriately (https://github.com/gardener/gardener/blob/master/example/50-seed.yaml#L59)? If you set it to `20Gi` then this value will be taken into account. This way we keep the gardener/gardener source code free from provider-specifics.
/hold
/status author-action

**Comment by rfranzke** [comment]
@knightXun does it work? :) Does it make sense to close the PR then?

**Pull request closed without merging**
