### PR TITLE
Remove landscaper code

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

**What this PR does / why we need it**:

Landscaper integration for Gardener in the current approach is canceled.

- Revert "make component-cli parameters configurable (#4515)"
- Revert "remove component descriptor os workaround"
- Revert "add Gardener landscaper blueprints to component descriptor (#3999)"
- delete landscaper code and imports

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```breaking developer
Remove all landscaper related code.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
When I search for the string "landscaper" I still find quite a lot of occurrences. Can you please check?
Also, can you please update the pipeline definition so that the images are no longer built?

**Comment by danielfoehrKn** [comment]
> Also, can you please update the pipeline definition so that the images are no longer built?

Yes, but not in this PR as this has to be done on the "special" branch. I'll do that tomorrow so that the image no longer appear here

**Comment by BeckerMax** [comment]
What about the tests in: https://github.com/gardener/gardener/blob/master/landscaper/pkg/gardenlet/chart/gardenlet_chart_test.go
Do we want to keep them?
Pro: We don't have other tests for the gardenlet chart and the configuration values.
Con: Those tests are forgotten when people do changes in the gardenlet config. They already don't test all branches of the gardenlet config. Also with the introduction of unique secret names in [PR](https://github.com/gardener/gardener/pull/5038) every change in the config needs adaption in the tests as the name changes. 
What is your opinion?

**Comment by danielfoehrKn** [comment]
I am in contact with @AndreasBurger to get the landscaper OCI images removed

**Comment by ialidzhikov** [comment]
Do we also have to drop the landscaper components for
- provider-aws - https://github.com/gardener/gardener-extension-provider-aws/pull/200
- networking-calico - https://github.com/gardener/gardener-extension-networking-calico/pull/83
- os-gardenlinux - https://github.com/gardener/gardener-extension-os-gardenlinux/pull/31
?

cc @gardener/landscaper-maintainers

**Comment by robertgraeff** [comment]
Hi  @ialidzhikov ,
the components networking-calico, os-gardenlinux, and dns-external are currently still deployed by the landscaper. As long as their deploy scripts are not changed back to a deployment without landscaper, the components are still needed. 
There is [this backlog item ](https://github.tools.sap/kubernetes/k8s-lifecycle-management/issues/47) for the change.

**Comment by achimweigel** [comment]
@ialidzhikov , @robertgraeff I think we could get rid of of most of this, but we should still maintain the chart entry in the resources.yaml. This adds the chart to the component descriptor and we could access it in lss without the need to clone the repo anymore. This would resolve a huge problem for fenced landscapes like China. (cc @ccwienk)

**Comment by BeckerMax** [comment]
Regarding:
> What about the tests in: https://github.com/gardener/gardener/blob/master/landscaper/pkg/gardenlet/chart/gardenlet_chart_test.go
Do we want to keep them?

We decided to keep those tests for now and move them to the manageedSeed Actuator tests, see https://github.com/gardener/gardener/pull/5038#discussion_r818056155

Can we do this in this PR? cc @danielfoehrKn

**Comment by rfranzke** [comment]
@danielfoehrKn Please check the failing  `verify` step

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
