### PR TITLE
Fix journal log collection

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
The PR fixes the journal log gathering from the nodes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @KristianZH @vlvasilev 

**Release note**:

```improvement operator
Kubelet and docker logs (for seed clusters) are now accessible from EFK.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
> Kubelet and docker logs (for garden and seed clusters) are now accessible from EFK.

I don't get the release note - why do we now suddenly have logs of the garden cluster in EFK?

**Comment by ialidzhikov** [comment]
> > Kubelet and docker logs (for garden and seed clusters) are now accessible from EFK.
> 
> I don't get the release note - why do we now suddenly have logs of the garden cluster in EFK?

You are right- its only for seed clusters. It's my misunderstanding.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Pull request merged**
