### PR TITLE
Update v1.26 conformance test coverage

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
Ref https://github.com/kubernetes/test-infra/pull/29024

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6773

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Why is the badge for OpenStack "orange"?

**Comment by ialidzhikov** [comment]
> Why is the badge for OpenStack "orange"?

@dguendisch @hendrikKahl is this an issue on our side?

**Comment by ialidzhikov** [comment]
> Why is the badge for OpenStack "orange"?

After a short chat with the colleagues, I understood the following: it means that we don't have yet successful run of of the `conformance-testgrid`. 1.26 for openstack was enabled recently and the single execution so far failed/flaked. But we already have successful runs of `conformance-testgrid-parallel` (compare to `conformance-testgrid` the difference is that `conformance-testgrid-parallel` runs with higher flakeAttempts and is more likely to pass). I will keep an eye on the next runs of `conformance-testgrid` for openstack/1.26 to see whether it will pass or not.

**Comment by ialidzhikov** [comment]
We now have a successful run of `conformance-testgrid` for openstack/1.26. Hence, the badge is green.

**Review by rfranzke — COMMENTED** [review]
That's great, thanks @ialidzhikov!

/lgtm
/approve

**Pull request merged**
