### PR TITLE
Remove SAP news from documentation

### PR DESCRIPTION
**Pull request by Yusuf-Uzun**
**How to categorize this PR?**
/area documentation
/kind cleanup

**What this PR does / why we need it**:
Adjusting a link inside the ReadMe which leads to a 404 page. This was a news from SAP about Gardener which apparently got removed.

**Release note**:
NONE

### CODE REVIEW

**Review by shafeeqes — APPROVED** [review]
Thanks!
/ok-to-test
/lgtm

**Comment by acumino** [comment]
@yusizn Can you please sign the CLA?

**Comment by yusizn** [comment]
@acumino done.

**Pull request merged**
