### PR TITLE
docs: import "Architecture" chapter from the wiki

### PR DESCRIPTION
**Pull request by berendt**
source: https://github.com/gardener/documentation/wiki/Architecture

Signed-off-by: Christian Berendt <berendt@23technologies.cloud>

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @berendt for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by berendt** [comment]
https://github.com/gardener/documentation/wiki/Architecture can be deleted after the merge of this PR.

**Comment by rfranzke** [comment]
Yeah, I guess this makes sense, the wiki is quite hidden. Can you please also add the document to the index (https://github.com/gardener/gardener/blob/master/docs/README.md)?

**Review by rfranzke — APPROVED** [review]
/lgtm
/reviewed ok-to-test

**Pull request merged**
