### PR TITLE
Update envoy proxy to v1.21.4

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Update envoy proxy to v1.21.4.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
Update envoy proxy to v1.21.4 (used in reversed vpn and apiserver-proxy)
```

### CODE REVIEW

**Comment by vpnachev** [comment]
/uncc

@ScheererJ for this repo /invite is disabled, you have to use /cc command.

/cc @DockToFuture

**Comment by ScheererJ** [comment]
@vpnachev Thanks for the hint.

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by acumino — APPROVED** [review]
/approve

**Pull request merged**
