### PR TITLE
tests: Drop no longer used repositories.yaml file

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
https://github.com/gardener/gardener/pull/8540/commits/48970c6aca3be95b5c725d9c71b43da3a266862c adapts the guestbook test to do not download the redis chart from `https://storage.googleapis.com/gardener-public/integrationtests-charts` but copies the redis chart locally under `test/framework/applications/charts/redis`.
Hence, the `test/framework/resources/repository/repositories.yaml` config is no longer used anywhere.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
/approve

**Review by acumino — COMMENTED** [review]
Not related to this PR but can you apply below diff to fix the structure - 

```diff
diff --git a/docs/development/testmachinery_tests.md b/docs/development/testmachinery_tests.md
index 485cb9a02..0919f68d8 100644
--- a/docs/development/testmachinery_tests.md
+++ b/docs/development/testmachinery_tests.md
@@ -27,14 +33,17 @@ The `test` directory is structured as follows:
 ```console
 test
 ├── e2e           # end-to-end tests (using provider-local)
-│  └── shoot
+│  ├── gardener
+│  │  ├── seed
+│  │  ├── shoot
+|  |  └── ...
+|  └──operator
 ├── framework     # helper code shared across integration, e2e and testmachinery tests
 ├── integration   # integration tests (envtests)
 │  ├── controllermanager
 │  ├── envtest
 │  ├── resourcemanager
 │  ├── scheduler
-│  ├── shootmaintenance
 │  └── ...
 └── testmachinery # test machinery tests
    ├── gardener   # actual test cases imported by suites/gardener

```

**Comment by acumino** [comment]
@ialidzhikov Will you adapt https://github.com/gardener/gardener/pull/8934#pullrequestreview-1788217200 change in this PR? or I can also do it in a separate PR.

**Review by acumino — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
