### PR TITLE
Enhance documentation for the Gardenlet's /healthz endpoint

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/kind bug
/priority normal
/area documentation

**What this PR does / why we need it**:
Based on #2925 but uses direct clients instead of listers.

The health manager changes the gardenlets  /healthz endpoint to DOWN if it cannot renew the lease in the Garden cluster. 
However, this does not cover the case when the Gardener Extended API Server is down.

The problem is, that Seeds can be queried from the lister even though the Gardener Extended API Server is down. This can be prevented by using a direct client. 

Advantage: 
  - Gardenlet fails when Gardener Extended API Server is down. I think this is the correct behaviour, as the Gardenlet cannot work without it.

Disadvantage: 
  - more network traffic (one request per 10 s)
  - I propose to decrease the ping interval from 10s -> 20s to save network traffic.

UPDATE: THis PR now only includes enhanced documentation for the Gardenlet's /healthz endpoint.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc operator
Enhance documentation for Gardenlet's /healthz endpoint.
```

### CODE REVIEW

**Comment by timuthy** [comment]
> However, this does not cover the case when the Gardener Extended API Server is down.

I'm generally not objecting but curious if you experienced any particular problems leaving the Gardenlet up and running while the API server was down? So far I was quite confident that a component like Gardenlet can deal with such intermittent issues.

**Comment by rfranzke** [comment]
I'm still struggling a bit with this with respect to the advantages we get compared with the network I/O?

**Comment by timebertt** [comment]
If network I/O is a big concern, we might wait for https://github.com/gardener/gardener/issues/3109 and use the metadata only client. This should be enough for this scenario, as we don't need the spec and saves network traffic.

**Comment by rfranzke** [comment]
Yeah, maybe. I'm still in the phase of understanding the motivation for this change and if we experienced any particular problem with it (or if we foresee problems if we don't introduce this now).

**Comment by timebertt** [comment]
Alternatively, we could also keep the watch but use some event handlers for delete events instead of using the lister.
Though, this would make the logic event-driven instead of level-driven, which might lead to issues, when we miss events.

**Comment by danielfoehrKn** [comment]
> I'm generally not objecting but curious if you experienced any particular problems leaving the Gardenlet up and running while the API server was down?

No, I did not. 
My main motivation was that I "expected" it to fail because I thought that the `/healthz`endpoint should always indicate whether the Gardenlet is healthy / can work. 

Thinking about it again,  we might be better off just documenting the behaviour - the `/healthz`endpoint only  states that Gardenlet has a lease with the Garden cluster.

**Comment by rfranzke** [comment]
Yeah, @danielfoehrKn, maybe that's a good first step to clarify on what can be expected.

**Comment by timebertt** [comment]
I guess, we should generally improve our health checks and do a clean separation between liveness and readiness (ref https://github.com/gardener/gardener-resource-manager/pull/102#discussion_r553790882).
Then we can report an unready state, when caches haven't been synced for a minute or so. This would also cover the stale lease/seed case addressed here.

**Comment by danielfoehrKn** [comment]
> I guess, we should generally improve our health checks and do a clean separation between liveness and readiness (ref gardener/gardener-resource-manager#102 (comment)).
Then we can report an unready state, when caches haven't been synced for a minute or so. This would also cover the stale lease/seed case addressed here.

Maybe you can open an issue for this describing this in more detail?
For this PR, I would only include the documentation - if that is fine with you.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by timuthy — APPROVED** [review]

**Pull request merged**
