### PR TITLE
Update API Core version in docs to core.gardener.cloud/v1beta1

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
Updates Gardener API Core version in docs to `core.gardener.cloud/v1beta1`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve

**Review by rfranzke — COMMENTED** [review]
~~I don't think we need this PR. We don't maintain the content of GEPs once implemented as the details evolve. We rather have dedicated documentation for new features which is maintained.~~

~~/close~~

**Comment by rfranzke** [comment]
Sorry, my bad, I just saw the title of https://github.com/gardener/gardener/blob/master/docs/proposals/04-new-core-gardener-cloud-apis.md is also containing `v1beta1`. In this light, this PR makes sense, of course :)

/reopen

**Pull request merged**
