### PR TITLE
Fixes scaling for the kube-controller-manager during shoot restoration

### LINKED ISSUE #4773: The kube-controller-manager can get stuck with 0 replicas after control plane migration
**How to categorize this issue?**

/area control-plane-migration
/kind bug
/priority 3

**What happened**:
Triggered control plane migration for an azure cluster, which seemed to finish successfully, but then I noticed that the VPN tunnel pod in the shoot never comes up. The reason for that is that the kube-controller-manager in the shoot's control plane had 0 replicas.

The issue seems to come during the `restore` operation and from this code: https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/pkg/operation/botanist/kubecontrollermanager.go#L99-L106
It will check that the operation is not `create`, and that the shoot isn't being hibernated or woken up and return the already existing replicas count for the kube-controller-manager deployment. Since it is a `restore` procedure and the kube-controller-manager has not yet been created in the new control plane, the replicas are 0.
The reason that we have not seen this issue before is that something else seems to be waking up the kube-controller-manager after it is initially created with 0 replicas.

**What you expected to happen**:
The kube-controller-manager to be created with 1 replicas when the shoot is being restored and is not hibernated.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster and migrate it. Observe that during the restore phase the kube-controller-manager is initially created with 0 replicas and later on scaled to 1.

**Anything else we need to know?**:

**Environment**:

- Gardener version: latest master version
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: GCP
- Others:

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
During the restore phase of control plane migration the kube-controller-manager will now be properly created with 1 replica if the shoot is not hibernated.

**Which issue(s) this PR fixes**:
Fixes #4773 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
During the restore phase of control plane migration, the kube-controller-manager deployment will be properly created with 1 replica if the shoot is not hibernated.
```

### CODE REVIEW

**Comment by plkokanov** [comment]
/invite @stoyanr 
although this isn't as critical it would be good to get it in the new release
/milestone v1.33

**Review by stoyanr — COMMENTED** [review]
/lgtm
I tested several different shoot restoration scenarios (with the dependency-watchdog disabled):
* normal migrate / restore
* migrate / restore + hibernate
* migrate / restore + wake-up

**Comment by plkokanov** [comment]
@stoyanr noticed that with the new logic when the shoot is being restored and hibernated at the same time the KCM would be created with 0 replicas. 
The restoration finishes successfully, but there is actually a different problem (not related to the one fixed in this PR) with the mentioned scenario (hibernation + restoration at the same time). 

Since in the new seed the kube-apiserver is not scaled up (it's deployment doesn't exist from a previous reconciliation and the etcd is also not scaled) the shootClient will not get initialised here: https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/pkg/operation/operation.go#L358-L367
which means that later all of the checks will be skipped in this code: 
https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/pkg/operation/botanist/controlplane.go#L137-L172

This basically means that there will be leftover machines with actually running pods for a shoot that is flagged as hibernated.


I could tackle this problem in a different PR later on, as it would also require additional changes to his function: https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/pkg/operation/botanist/kubeapiserver.go#L350 
which is already modified by #4779 and most likely other places in the reconciliation flow that would require special handling for hibernation + restoration.

As an alternative we could disable the hibernation of a shoot cluster while it is being migrated, similar to what we did for deletion. However, the shoot hibernation can be triggered prior to restoration in which case we could first restore the cluster and then perform the hibernation.

**Review by stoyanr — DISMISSED** [review]

**Review by stoyanr — APPROVED** [review]
/lgtm

**Comment by voelzmo** [comment]
@plkokanov do we need to cherry-pick this also to `release-1.33`?

**Comment by plkokanov** [comment]
@voelzmo yep I'll do the cherry pick in a few mins

**Pull request merged**
