### PR TITLE
Update golangci-lint to v1.51.2 to support go 1.20

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Update golangci-lint to v1.51.2 to support go 1.20
The older versions fails with go 1.20, more info in https://github.com/golangci/golangci-lint/issues/3586.

**Which issue(s) this PR fixes**:
Part of #7449 

**Special notes for your reviewer**:

**Release note**:

```other developer
`golangci-lint` has been updated to v1.51.2.
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Comment by vpnachev** [comment]
/cc @timuthy 
to decide whether to include or not this change in v1.65 release.

**Pull request merged**
