### PR TITLE
Move shoot-specific `vpn-seed-server` monitoring config into component package

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
Move shoot-specific `vpn-seed-server` monitoring config into component package.

**Which issue(s) this PR fixes**:
Part of #2754
Left-over of #5055

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Review by timebertt — COMMENTED** [review]
/approve

**Review by timebertt — COMMENTED** [review]
/lgtm

**Pull request merged**
