### PR TITLE
fix gardenlet not copying the bastion ingress status when reconciling

### PR DESCRIPTION
**Pull request by xrstf**
**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:
The new controller for reconciling Bastions wrongly assumed that `extensions.WaitUntilExtensionObjectReady()` would update the object given to it. But in reality, that function operates on deep copy clones of the object. This meant that once the Wait function is done, the `extBastion` is left _untouched_ and did not get updated with the new `status.ingress`. So in the end, the Bastion resource in the garden cluster would get the `BastionReady` condition without the ingress.

The fix is simply to fetch the current state of the object after it became ready.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/invite @timebertt

**Review by timebertt — CHANGES_REQUESTED** [review]
> The new controller for reconciling Bastions wrongly assumed that extensions.WaitUntilExtensionObjectReady() would update the object given to it. But in reality, that function operates on deep copy clones of the object

That doesn't sound right. `WaitUntilExtensionObjectReady` is supposed to update the in-memory object given to it.
How do you come to the conclusion that it doesn't do so?

I think, there's rather something off with `TryPatchStatus`. I already replaced it in https://github.com/timebertt/gardener/commits/cleanup/directclient-7. Maybe this will already fix your problem.

**Comment by timebertt** [comment]
Ok, I dropped the WIP part of https://github.com/timebertt/gardener/commits/cleanup/directclient-7 and opened https://github.com/gardener/gardener/pull/4179.
Can you take a look at the `Bastion` controller part and test if this fixes your problem?

**Comment by xrstf** [comment]
> That doesn't sound right. WaitUntilExtensionObjectReady is supposed to update the in-memory object given to it.
How do you come to the conclusion that it doesn't do so?

I looked at the implementation, saw the calls to `CreateResetObjectFunc` and it doing `resetObj` all the time. Then I tested my code by adding some print statements and saw that while the bastion got ready, my variable still didn't contain the new `status.ingress` I was expecting. This happened consistently over 5+ tries with different Bastions.

**Comment by timebertt** [comment]
Hmm, I checked the implementation again and attached my debugger to the infra component and it works exactly like it is supposed to (including the resets and so on), the passed object is always filled with the latest state.

So I don't think that there's something wrong with `WaitUntilExtensionObjectReady`.
Maybe we should have a joint debug session

**Comment by xrstf** [comment]
Yeah for some reason I cannot reproduce it anymore. I tried #4179 and then went back to master and in both cases it worked as expected.

Maybe the bug only occurs at night when I'm sleepy.

**Pull request closed without merging**
