### PR TITLE
Prevent volume usage alerts

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
`KubePersistentVolumeUsageCritical` is filed when pv free disk space goes below 5%. The PR sets elasticsearch curator disk space threshold also to 5% (1.5Gi for shoot cp, and 5Gi for garden ns) to prevent the alert.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@wyb1 , @mvladev 

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by wyb1 — DISMISSED** [review]
/lgtm hopefully this will also prevent `KubePersistentVolumeFullInFourDays` from firing. If we still have problems in the future we can also tune the alerts.

**Comment by ialidzhikov** [comment]
/hold

Let me check.

**Comment by ialidzhikov** [comment]
/hold cancel

Updated `KubePersistentVolumeFullInFourDays` to ignore elastic pvc, curator should clean up when free disk space is < 5%.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
