### PR TITLE
Adapt the `kube-apiserver` and `kube-controller-manager` to use the appropriate `PriorityClasses`

### PR DESCRIPTION
**Pull request by krgostev**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR adapts  he kube-apiserver and kube-controller-manager to use PriorityClasses`gardener-system-500` and  `gardener-system-300` as part of #5634
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Can you please fix the release note?

**Comment by krgostev** [comment]
> Can you please fix the release note?

The whole description was wrong as I have messed up and submitted it early.

**Comment by rfranzke** [comment]
I removed the release notes, IMO they are not needed

**Pull request merged**
