### PR TITLE
Increase the kube-rback-proxy and telegraf resources in Loki pod

### LINKED ISSUE #4735: loki/kube-rbac-proxy is OOMKilled
**How to categorize this issue?**

/area auto-scaling logging
/kind bug

**What happened**:

`kube-rbac-proxy` sidecar in the loki container got OOMKilled:
```
Controlled By:  StatefulSet/loki
Containers:
  kube-rbac-proxy:
...
    Args:
      --insecure-listen-address=0.0.0.0:8080
      --upstream=http://127.0.0.1:3100/
      --kubeconfig=/kubeconfig/kubeconfig
      --logtostderr=true
      --v=6
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 28 Sep 2021 08:44:30 +0200
      Finished:     Tue, 28 Sep 2021 08:46:44 +0200
    Ready:          False
    Restart Count:  443
    Limits:
      cpu:     20m
      memory:  30Mi
    Requests:
      cpu:        5m
      memory:     15Mi
```

But HVPA wasn't scaling it up, as it's disabled for this container.

**What you expected to happen**:

It should be autoscaled.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
Increase the kube-rback-proxy and telegraf resources in Loki pod

**Which issue(s) this PR fixes**:
Fixes #4735

**Special notes for your reviewer**:

**Release note**:

```other operator
Increased the `kube-rback-proxy` and `telegraf` container resources in Loki pod to withstand higher resource usage spikes.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by Kristian-ZH** [comment]
In my opinion, this will affect Loki stability. It will cause more restarts. Also scaleDownStabilization and scaleUpStabilization were made for Loki. I am not sure if their values are relevant for all of the containers.
I think that if you use static resources for these containers will be much better. But if you still want to dynamically scale them with VPA, then I will suggest to extract these containers to another pod and then scale it with VPA.

As @vlvasilev is the only maintainer of the logging now, I will leave this choice to him. If he thinks that the risk is acceptable with this change then he has my /lgtm .

**Comment by vpnachev** [comment]
With such a narrow range between min and max allowed, does it make sense to enable autoscalling for these containers?
Isn't the risk of restarting the entire loki pod too high just to change cpu with 2m or the memory with 10Mi for some of these containers? This said, I agree with @Kristian-ZH it is better to run these 2 containers with static resources and a bit higher limits.

**Comment by vpnachev** [comment]
Together with @vlvasilev we took a look and decided to not enable vertical scaling for those containers, but just to slightly increase the limits to handle the spikes or higher usage on much larger clusters. 

/hold 

until the PR is updated.

**Review by rfranzke — APPROVED** [review]
/lgtm
/unhold

**Review by vpnachev — APPROVED** [review]
/lgtm

Thanks!

**Comment by timuthy** [comment]
Can we cherry-pick this PR @vlvasilev @vpnachev? (/cc @voelzmo)

**Comment by vpnachev** [comment]
It does not look so critical (i.e. to trigger also a release), but no objections to be cherry-picked and included in the next round of patch releases, if any :wink:

**Comment by timebertt** [comment]
There's also https://github.com/gardener/gardener/pull/4760 waiting to be released on `release-v1.32`, so +1 for cherry-picking this one and releasing them together.

**Comment by vpnachev** [comment]
Done:
- #4769 
- #4770 
- #4771

**Pull request merged**
