### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.15.2->v0.15.3]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` other dependency github.com/gardener/etcd-druid #450 @AleksandarSavchev
Dependency `github.com/gardener/gardener` is updated `v1.36.0` -> `v1.57.1`
```

``` other dependency github.com/gardener/etcd-druid #450 @AleksandarSavchev
Dependency `github.com/onsi/ginkgo` is upgraded to `github.com/onsi/ginkgo/v2`
```

``` other dependency github.com/gardener/etcd-druid #493 @shafeeqes
The dependency of `sigs.k8s.io/controller-runtime/pkg/envtest/printer` package in `etcd-druid` is removed.
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
/approve
/assign @aaronfern @shreyas-s-rao @ishan16696 
for lgtm

**Review by aaronfern — APPROVED** [review]
/lgtm

**Pull request merged**
