### PR TITLE
Update several dependencies

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR updates several dependencies.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Nice, thank you!

/lgtm
/approve

**Comment by rfranzke** [comment]
Integration test fails with:

>   {"level":"error","ts":"2023-09-20T14:28:55.461Z","msg":"Failed to maintain Shoot kubernetes version","controller":"shoot-maintenance","controllerGroup":"core.gardener.cloud","controllerKind":"Shoot","Shoot":{"name":"test-hvpnf","namespace":"garden-srnwn"},"namespace":"garden-srnwn","name":"test-hvpnf","reconcileID":"07750cb4-4e9a-4212-b421-d717b1bc8a90","error":"cannot perform minor Kubernetes version update for expired Kubernetes version \"0.0.5\". No suitable version found in CloudProfile - this is most likely a misconfiguration of the CloudProfile","stacktrace":"github.com/gardener/gardener/pkg/controllermanager/controller/shoot/maintenance.(*Reconciler).reconcile\n\t/home/prow/go/src/github.com/gardener/gardener/pkg/controllermanager/controller/shoot/maintenance/reconciler.go:133\ngithub.com/gardener/gardener/pkg/controllermanager/controller/shoot/maintenance.(*Reconciler).Reconcile\n\t/home/prow/go/src/github.com/gardener/gardener/pkg/controllermanager/controller/shoot/maintenance/reconciler.go:84\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/prow/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/prow/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/prow/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/prow/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}

Seems related to the change 👀

**Comment by acumino** [comment]
> Seems related to the change 👀

Yes, `^` operator behaviour has changed, adapted it in https://github.com/gardener/gardener/pull/8513/commits/4de140927add7fe38e11c5d858785108dfc1cbc1

**Comment by oliver-goetz** [comment]
thanks 😄 

/lgtm

**Comment by oliver-goetz** [comment]
/hold
wait until #8515 is merged

**Review by ary1992 — COMMENTED** [review]
/lgtm

**Pull request merged**
