### PR TITLE
Upgrade to golang 1.20.13-bookworm and 1.21.6-bookworm

### PR DESCRIPTION
**Pull request by robinschneider**
**How to categorize this PR?**

/area testing
/kind enhancement

**What this PR does / why we need it**:
This PR updates Go versions of golang-test image to the recent patch versions 1.21.6 and 1.20.13.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
You are faster than dependabot 🚀 
Thanks 😄 

/ok-to-test
/lgtm
/approve

**Comment by robinschneider** [comment]
@oliver-goetz I couldn't find any build with the new go version.
`crane ls eu.gcr.io/gardener-project/ci-infra/golang-test` only shows images from 2022 and 2023.
```
v20231219-92940f4-1.20
v20231219-92940f4-1.21
```
I am probably to late to find anything in prow, at least I couldn't see anything.

**Pull request merged**
