### PR TITLE
Fixed links

### PR DESCRIPTION
**Pull request by n-boshnakov**

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @n-boshnakov for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by ialidzhikov** [comment]
Thanks!

I guess there are more references that needs to be adapted. Can you check and apply the following patch?

<details>

```diff
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index de0e2412b..89271a2fe 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -1 +1 @@
-Please refer to the [Gardener contributor guide](https://gardener.cloud/documentation/contribute/).
+Please refer to the [Gardener contributor guide](https://gardener.cloud/docs/contribute/).
diff --git a/docs/proposals/README.md b/docs/proposals/README.md
index 833bde5e0..6b871b8db 100644
--- a/docs/proposals/README.md
+++ b/docs/proposals/README.md
@@ -19,7 +19,7 @@ We encourage you to take a look at already merged [GEPs]( https://github.com/gar
 ## Before creating a GEP
 
 Before starting your work and creating a GEP, please take some time to familiarize yourself with our
-general [Gardener Contribution Guidelines](https://gardener.cloud/documentation/contribute/).
+general [Gardener Contribution Guidelines](https://gardener.cloud/docs/contribute/).
 
 It is recommended to discuss and outline the motivation of your prospective GEP as a draft with the community before you take the investment of creating the actual GEP. This early briefing supports the understanding for the broad community and leads to a fast feedback for your proposal from the respective experts in the community.
 An appropriate format for this may be the regular [Gardener community meeting](https://github.com/gardener/documentation/blob/master/CONTRIBUTING.md#weekly-meeting).
@@ -38,7 +38,7 @@ the enhancement.
 
 Apart from general metadata, the GEP should name at least one "main reviewer".
 You can find a main reviewer for your GEP either when discussing the proposal in the community meeting, by asking in our
-[Slack Channel](https://gardener.cloud/documentation/contribute/#slack-channel) or at latest during the GEP PR review.
+[Slack Channel](https://gardener.cloud/docs/contribute/#slack-channel) or at latest during the GEP PR review.
 New GEPs should only be accepted once at least one main reviewer is nominated/assigned. 
 
 The main reviewers are charged with the following tasks:
diff --git a/docs/usage/shoot_status.md b/docs/usage/shoot_status.md
index 3fe0a4b6e..b5b64f9fa 100644
--- a/docs/usage/shoot_status.md
+++ b/docs/usage/shoot_status.md
@@ -1,10 +1,10 @@
 # Shoot Status
 
-This document provides an overview of the [ShootStatus](https://gardener.cloud/documentation/references/core/#core.gardener.cloud/v1beta1.ShootStatus).
+This document provides an overview of the [ShootStatus](https://gardener.cloud/docs/references/core/#core.gardener.cloud/v1beta1.ShootStatus).
 
 ## Conditions
 
-The Shoot status consists of a set of conditions. A [Condition](https://gardener.cloud/documentation/references/core/#core.gardener.cloud/v1beta1.Condition) has the following fields:
+The Shoot status consists of a set of conditions. A [Condition](https://gardener.cloud/docs/references/core/#core.gardener.cloud/v1beta1.Condition) has the following fields:
 
 | Field name           | Description                                                                                                        |
 | -------------------- | ------------------------------------------------------------------------------------------------------------------ |
@@ -89,7 +89,7 @@ The Shoot status holds information about the last operation that is performed on
 
 ### Last Errors
 
-The Shoot status also contains information about the last occurred error(s) (if any) during an operation. A [LastError](https://gardener.cloud/documentation/references/core/#core.gardener.cloud/v1beta1.LastError) consists of identifier of the task returned error, human-readable message of the error and error codes (if any) associated with the error.
+The Shoot status also contains information about the last occurred error(s) (if any) during an operation. A [LastError](https://gardener.cloud/docs/references/core/#core.gardener.cloud/v1beta1.LastError) consists of identifier of the task returned error, human-readable message of the error and error codes (if any) associated with the error.
 
 ### Error Codes
 

```

</details>

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
