### PR TITLE
Enable kube_node_spec_taint metric

### PR DESCRIPTION
**Pull request by adenitiu**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
Make `kube_node_spec_taint` available in `kube-state-metrics` to help filter out nodes that have been tainted by the CA, during K8S version upgrade or node image version rollout. 

**Which issue(s) this PR fixes**:
Enables users to use the query

`(kube_node_spec_taint{job="kube-state-metrics",key="node.kubernetes.io/unreachable",effect="NoSchedule"} unless ignoring(key,value) kube_node_spec_taint{job="kube-state-metrics",key=~"ToBeDeletedByClusterAutoscaler"}) == 1`

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rickardsjp — APPROVED** [review]
/lgtm

**Comment by adenitiu** [comment]
Ok, I am not really sure that my changes are currently breaking the e2e tests mentioned above. I merged also the latest main / master branch into my fork. Would appreciate any inputs on what can I do next to get the PR tests green.

**Review by rickardsjp — APPROVED** [review]
/lgtm
(repeat due to the rebase)

**Pull request merged**
