### PR TITLE
Upgrade github.com/gardener/autoscaler

### PR DESCRIPTION
**Pull request by himanshu-kun**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**Special notes for your reviewer**:
- gardener/cluster-autoscaler@v0.19.0 is no longer used
- gardener/cluster-autoscaler@v1.20.1 K8s <= 1.20. This is done because both v0.19.0 and v1.20.0 sync kubernetes/cluster-autoscaler 1.20 only.

**Release note**:

```other operator
The following images are updated:
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler:` `v0.19.0` -> `v1.20.1` (for Kubernetes `< 1.20`)
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler:` `v1.20.0` -> `v1.20.1` (for Kubernetes `1.20`)
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler:` `v1.21.0` -> `v1.21.1 `(for Kubernetes `1.21`)
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler`: `v1.21.0` -> `v1.22.1` (for Kubernetes `>= 1.22`)
```

### CODE REVIEW

**Comment by himanshu-kun** [comment]
I'll be creating patch release for 1.20 , 1.21 and 1.22 and will update this PR. So requesting not to merge
cc @ialidzhikov

**Comment by ialidzhikov** [comment]
/hold
we agreed that @himanshu-kun will incorporate also new patch releases for autoscaler needed for https://github.com/gardener/gardener/issues/5064 as part of this PR

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
