### PR TITLE
Drop `.spec.dns.{ingressDomain,provider.domains,provider.zones}` fields in the Seed API

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
The usage in controllers for the fields `.spec.dns.{ingressDomain,provider.domains,provider.zones}`  were removed in #7529.
Now these fields are removed from the Seed API.

**Which issue(s) this PR fixes**:
Part of #7519 

**Special notes for your reviewer**:
/hold until gardener v1.66 is released

**Release note**:

```breaking operator
The deprecated fields `seed.spec.dns.ingressDomain`, `seed.spec.dns.provider.domains`, `seed.spec.dns.provider.zones` has been removed from the Seed API. Please check your `Seed` manifests and remove any usage before upgrading to this Gardener version.
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
> @shafeeqes: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-e2e-kind-ha-multi-zone-upgrade	[dd3ab6f](https://github.com/gardener/gardener/commit/dd3ab6f68e546de47a92b6ad5a54b1f8ef363223)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7602/pull-gardener-e2e-kind-ha-multi-zone-upgrade/1633402144629460992)	false	`/test pull-gardener-e2e-kind-ha-multi-zone-upgrade`
> pull-gardener-unit	[0e8a82f](https://github.com/gardener/gardener/commit/0e8a82fc33bf2094f2b234decfef0747391beb4d)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7602/pull-gardener-unit/1633419385961975808)	true	`/test pull-gardener-unit`
> pull-gardener-apidiff	[e430f6e](https://github.com/gardener/gardener/commit/e430f6ec657053d7be94c9a76ba39315474d2a89)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7602/pull-gardener-apidiff/1633421719509143552)	false	`/test pull-gardener-apidiff`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7602). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Ran `make generate` inside a go container.

**Comment by shafeeqes** [comment]
/unhold
gardener `v1.66` is released.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Comment by shafeeqes** [comment]
> @shafeeqes: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-apidiff	[e430f6e](https://github.com/gardener/gardener/commit/e430f6ec657053d7be94c9a76ba39315474d2a89)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7602/pull-gardener-apidiff/1635127483936280576)	false	`/test pull-gardener-apidiff`
> pull-gardener-integration	[e430f6e](https://github.com/gardener/gardener/commit/e430f6ec657053d7be94c9a76ba39315474d2a89)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7602/pull-gardener-integration/1635206188452810752)	unknown	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7602). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ashafeeqes). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

I will open a separate PR for this flake.
/test pull-gardener-integration

**Pull request merged**
