### PR TITLE
Bump VPA to 0.13.0

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Bump VPA to 0.13.0 to get newest fixes. Includes a [fix for Pods being stuck in OOMKill CrashLoopBackoff](https://github.com/kubernetes/autoscaler/pull/5326).

See entire release notes: https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.13.0

**Release note**:

```other operator
Update vertical-pod-autoscaler to v0.13.0. This deprecates `autoscaling.k8s.io/v1beta2` API, switch to `autoscaling.k8s.io/v1` instead.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/approve

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
Can you update the VPA CRDs in https://github.com/gardener/gardener/tree/c2df49e4b1e5611a35c645c35692d4b4206cc5b7/pkg/operation/botanist/component/vpa/templates?

**Comment by voelzmo** [comment]
> Can you update the VPA CRDs in https://github.com/gardener/gardener/tree/c2df49e4b1e5611a35c645c35692d4b4206cc5b7/pkg/operation/botanist/component/vpa/templates?

Done, thanks for the reminder! I've added a template task to our backlog, so we remember to do this on every update in the future.

**Comment by ialidzhikov** [comment]
@voelzmo , please adapt the unit tests as well.

**Comment by voelzmo** [comment]
> @voelzmo , please adapt the unit tests as well.

Thanks for the ping, I was already on it – fiddling with the backticks in raw strings proved more finnicky than I hoped for ;(
Maybe this would be a good point in time to think about the value of these tests? Are we testing that our managed resources does really contain the files we put into the 'templates' section? Should we maybe only test for the stuff we care about, like the gardener-specific labels and the vpa version?

**Review by andrerun — APPROVED** [review]

**Pull request merged**
