### PR TITLE
[ci:component:github.com/gardener/hvpa-controller:v0.4.0->v0.5.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` improvement operator github.com/gardener/hvpa-controller #93 @stoyanr
The HVPA controller now respects `controlledResources` and `controlledValues` parameters that have been newly introduced in `autoscaling.k8s.io/v1`.
```

``` improvement operator github.com/gardener/hvpa-controller #91 @stoyanr
`autoscaling.k8s.io/v1` is now being used instead of `autoscaling.k8s.io/v1beta2` in HVPA resources. This enables using `controlledValues: RequestsOnly` in `spec.vpa.template.spec.resourcePolicy`
```

### CODE REVIEW

**Comment by stoyanr** [comment]
I added a new commit that vendors `hvpa-controller` 0.5.0, adopts `autoscaling.k8s.io/v1`, and adds `controlledValues` to some Hvpa resources. This PR should be mergeable now.

**Review by rfranzke — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Pull request merged**
