### PR TITLE
Make QPS/burst settings for VPA configurable

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
When there are a lot of VPA objects and corresponding VPACheckpoints to take care of, the VPA needs to be able to do more than just 5 qps to kube-api. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This allows configuring the VPA recommender 

**Release note**:

```feature operator
You can now specify QPS and burst limits for the VPA recommender when contacting the kube-apiserver.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Do we really need to expose this in the `Shoot`? For other components we simply set such values to a higher number (e.g. https://github.com/gardener/gardener/blob/8abb827821db42806a828c66b93995e1a54c693c/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/configcodec_test.go#L86-L87). Wouldn't this work here as well?

**Comment by voelzmo** [comment]
> Do we really need to expose this in the `Shoot`? For other components we simply set such values to a higher number (e.g.
> 
> https://github.com/gardener/gardener/blob/8abb827821db42806a828c66b93995e1a54c693c/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/configcodec_test.go#L86-L87
> 
> ). Wouldn't this work here as well?

I think currently we would need to do some experimentation to find a good value here, which will most likely require some back-and-forth. In order to allow for iterating on this without having to create a new release, I opted for exposing this. At the same time, I share your concern with unnecessarily increasing the API surface, but wasn't sure how to allow for iterating without exposing it. Is there a different way?

**Comment by rfranzke** [comment]
If this is just for testing/experimentation, probably a webhook-based approach makes more sense. Generally, I don't see much difference compared to what we do with the kubelet's settings, so I would be fine with setting qps=burst=50 for VPA as well. However, if you think this is too risky and prefer to first find "good values" then I vote for waiting with any changes in `gardener/gardener` and work with webhooks to manipulate the deployment.

**Comment by voelzmo** [comment]
Alright, let's close this for now and I'll start experimenting with the webhook-based approach. Thanks!

**Pull request closed without merging**
