### PR TITLE
Cleanup more usages of DirectClient

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area dev-productivity scalability
/kind cleanup
/priority normal

**What this PR does / why we need it**:

This PR cleans up more usages of the `DirectClient` in order to eventually get rid of it.

It tackles usages in 
- gardenlet bootstrap code
- gardener-controller-manager project controller
- gardener-controller-manager plant controller (switches to strategic merge patches for updating the status)

**Which issue(s) this PR fixes**:
Part of #2822

**Special notes for your reviewer**:
/squash

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by timebertt** [comment]
/hold
until the `v1.19.0` release is cut.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
