### PR TITLE
Improve error code mapping for quota issues

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
Improve error code mapping for quota issues

**Release note**:

```other operator
The error code mapping has been extended such that more quota-related issues are properly detected.
```

### CODE REVIEW

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
It is not anything outstanding, but I guess we can cherry-pick this one to the existing `release-v*` branches so that it will be included in eventual next patch releases. WDYT?

**Comment by rfranzke** [comment]
Sure, we could, I can open some PRs later today

**Comment by vpnachev** [comment]
Thanks!
/needs cherry-pick

**Pull request merged**
