### PR TITLE
Fix ingress class handling

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind bug
/needs cherry-pick

**What this PR does / why we need it**:
This PR improves the handling for rendered Ingress resource which are deployed to seed clusters.
Seeds can be non Gardener managed clusters and might contain a custom version suffix (`v1.19.12-some-suffix`).
With such a version, the version switches in the Helm charts did not work reliably.

**Special notes for your reviewer**:
/cc @mliepold @dguendisch 

**Release note**:

```bugfix operator
A bug has been fixed that did not add the required ingress class in some seed clusters that are not Gardener managed.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm
/milestone v1.32

**Pull request merged**
