### PR TITLE
Disable etcd backup compaction by default

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR disables the etcd backup compaction feature by default. It should consciously be enabled by operators because the feature comes with certain cost implications (e.g. network traffic) and requires machines with a rather large root disk. 

**Release note**:

```breaking operator
The etcd backup compaction feature has been disabled by default. It can by enabled anytime via the `etcdConfig` section in the Gardenlet-Componentconfig.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]

**Comment by rfranzke** [comment]
@timuthy Can you please fix the failing tests?

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timuthy** [comment]
Through #5147 another problem has drawn my attention: We set very low worker values in the Helm chart which become the "new" default when applying Gardenlet via this chart. For instance, if an operator applied Gardenlet earlier, the `etcdController` worker count was `50` (hard coded). With the Helm chart values, this count becomes only `3` if operators do not deliberately set another value. Hence, I added another commit 1b8f5c5.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by shreyas-s-rao — APPROVED** [review]

**Pull request merged**
