### PR TITLE
Fix flaky `BackupBucket` Controller test

### LINKED ISSUE #6904: [Flaky Test] Extensions Controller BackupBucket Integration Test Suite
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`BackupBucket should successfully create and delete a BackupBucket (respecting operation annotation)`

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6902/pull-gardener-integration/1585137129640431616#1:build-log.txt%3A131-219

**Reason for failure**:
The test never observes the BackupBucket object to transition to `status.lastOperation.state=Error` but instead sees `Processing`.
This could be caused by the exponential backoff (the requested error causes the controller to retry).

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
This PR fixes the flaky BackupBucket Controller integration test by slowing down reconciliations in case of errors.

<details> 
<summary>Test results:</summary>
<pre>
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 1 runs so far, 0 failures
20s: 1 runs so far, 0 failures
25s: 2 runs so far, 0 failures
30s: 2 runs so far, 0 failures
35s: 3 runs so far, 0 failures
40s: 3 runs so far, 0 failures
45s: 4 runs so far, 0 failures
50s: 4 runs so far, 0 failures
55s: 4 runs so far, 0 failures
1m0s: 5 runs so far, 0 failures
1m5s: 5 runs so far, 0 failures
1m10s: 6 runs so far, 0 failures
1m15s: 6 runs so far, 0 failures
1m20s: 7 runs so far, 0 failures
1m25s: 7 runs so far, 0 failures
1m30s: 8 runs so far, 0 failures
1m35s: 8 runs so far, 0 failures
1m40s: 9 runs so far, 0 failures
1m45s: 9 runs so far, 0 failures
1m50s: 9 runs so far, 0 failures
1m55s: 10 runs so far, 0 failures
2m0s: 10 runs so far, 0 failures
2m5s: 11 runs so far, 0 failures
2m10s: 11 runs so far, 0 failures
2m15s: 12 runs so far, 0 failures
2m20s: 12 runs so far, 0 failures
2m25s: 13 runs so far, 0 failures
2m30s: 13 runs so far, 0 failures
2m35s: 14 runs so far, 0 failures
2m40s: 14 runs so far, 0 failures
2m45s: 14 runs so far, 0 failures
2m50s: 15 runs so far, 0 failures
2m55s: 15 runs so far, 0 failures
3m0s: 16 runs so far, 0 failures
3m5s: 16 runs so far, 0 failures
3m10s: 17 runs so far, 0 failures
3m15s: 17 runs so far, 0 failures
3m20s: 18 runs so far, 0 failures
3m25s: 18 runs so far, 0 failures
3m30s: 19 runs so far, 0 failures
3m35s: 19 runs so far, 0 failures
3m40s: 19 runs so far, 0 failures
3m45s: 20 runs so far, 0 failures
3m50s: 20 runs so far, 0 failures
3m55s: 21 runs so far, 0 failures
4m0s: 21 runs so far, 0 failures
4m5s: 22 runs so far, 0 failures
4m10s: 22 runs so far, 0 failures
4m15s: 23 runs so far, 0 failures
4m20s: 23 runs so far, 0 failures
4m25s: 23 runs so far, 0 failures
4m30s: 24 runs so far, 0 failures
4m35s: 24 runs so far, 0 failures
4m40s: 25 runs so far, 0 failures
4m45s: 25 runs so far, 0 failures
4m50s: 26 runs so far, 0 failures
4m55s: 26 runs so far, 0 failures
5m0s: 27 runs so far, 0 failures
5m5s: 27 runs so far, 0 failures
5m10s: 28 runs so far, 0 failures
5m15s: 28 runs so far, 0 failures
5m20s: 28 runs so far, 0 failures
5m25s: 29 runs so far, 0 failures
5m30s: 29 runs so far, 0 failures
5m35s: 30 runs so far, 0 failures
5m40s: 30 runs so far, 0 failures
5m45s: 31 runs so far, 0 failures
5m50s: 31 runs so far, 0 failures
5m55s: 32 runs so far, 0 failures
6m0s: 32 runs so far, 0 failures
6m5s: 33 runs so far, 0 failures
6m10s: 33 runs so far, 0 failures
6m15s: 33 runs so far, 0 failures
6m20s: 34 runs so far, 0 failures
6m25s: 34 runs so far, 0 failures
6m30s: 35 runs so far, 0 failures
6m35s: 35 runs so far, 0 failures
6m40s: 36 runs so far, 0 failures
6m45s: 36 runs so far, 0 failures
6m50s: 37 runs so far, 0 failures
6m55s: 37 runs so far, 0 failures
7m0s: 38 runs so far, 0 failures
7m5s: 38 runs so far, 0 failures
7m10s: 38 runs so far, 0 failures
7m15s: 39 runs so far, 0 failures
7m20s: 39 runs so far, 0 failures
7m25s: 40 runs so far, 0 failures
7m30s: 40 runs so far, 0 failures
7m35s: 41 runs so far, 0 failures
7m40s: 41 runs so far, 0 failures
7m45s: 42 runs so far, 0 failures
7m50s: 42 runs so far, 0 failures
7m55s: 43 runs so far, 0 failures
8m0s: 43 runs so far, 0 failures
8m5s: 43 runs so far, 0 failures
8m10s: 44 runs so far, 0 failures
8m15s: 44 runs so far, 0 failures
8m20s: 45 runs so far, 0 failures
8m25s: 45 runs so far, 0 failures
8m30s: 46 runs so far, 0 failures
8m35s: 46 runs so far, 0 failures
8m40s: 47 runs so far, 0 failures
8m45s: 47 runs so far, 0 failures
8m50s: 47 runs so far, 0 failures
8m55s: 48 runs so far, 0 failures
9m0s: 48 runs so far, 0 failures
9m5s: 49 runs so far, 0 failures
9m10s: 49 runs so far, 0 failures
9m15s: 50 runs so far, 0 failures
9m20s: 50 runs so far, 0 failures
9m25s: 51 runs so far, 0 failures
9m30s: 51 runs so far, 0 failures
9m35s: 52 runs so far, 0 failures
9m40s: 52 runs so far, 0 failures
9m45s: 52 runs so far, 0 failures
9m50s: 53 runs so far, 0 failures
9m55s: 53 runs so far, 0 failures
10m0s: 54 runs so far, 0 failures
10m5s: 54 runs so far, 0 failures
10m10s: 55 runs so far, 0 failures
10m15s: 55 runs so far, 0 failures
10m20s: 56 runs so far, 0 failures
10m25s: 56 runs so far, 0 failures
10m30s: 57 runs so far, 0 failures
10m35s: 57 runs so far, 0 failures
10m40s: 57 runs so far, 0 failures
10m45s: 58 runs so far, 0 failures
10m50s: 58 runs so far, 0 failures
10m55s: 59 runs so far, 0 failures
11m0s: 59 runs so far, 0 failures
11m5s: 60 runs so far, 0 failures
11m10s: 60 runs so far, 0 failures
11m15s: 61 runs so far, 0 failures
11m20s: 61 runs so far, 0 failures
11m25s: 62 runs so far, 0 failures
11m30s: 62 runs so far, 0 failures
11m35s: 62 runs so far, 0 failures
11m40s: 63 runs so far, 0 failures
11m45s: 63 runs so far, 0 failures
11m50s: 64 runs so far, 0 failures
11m55s: 64 runs so far, 0 failures
12m0s: 65 runs so far, 0 failures
12m5s: 65 runs so far, 0 failures
12m10s: 66 runs so far, 0 failures
12m15s: 66 runs so far, 0 failures
12m20s: 67 runs so far, 0 failures
12m25s: 67 runs so far, 0 failures
12m30s: 67 runs so far, 0 failures
12m35s: 68 runs so far, 0 failures
12m40s: 68 runs so far, 0 failures
12m45s: 69 runs so far, 0 failures
12m50s: 69 runs so far, 0 failures
12m55s: 70 runs so far, 0 failures
13m0s: 70 runs so far, 0 failures
13m5s: 71 runs so far, 0 failures
13m10s: 71 runs so far, 0 failures
13m15s: 71 runs so far, 0 failures
13m20s: 72 runs so far, 0 failures
13m25s: 72 runs so far, 0 failures
13m30s: 73 runs so far, 0 failures
13m35s: 73 runs so far, 0 failures
13m40s: 74 runs so far, 0 failures
13m45s: 74 runs so far, 0 failures
13m50s: 75 runs so far, 0 failures
13m55s: 75 runs so far, 0 failures
14m0s: 76 runs so far, 0 failures
14m5s: 76 runs so far, 0 failures
14m10s: 76 runs so far, 0 failures
14m15s: 77 runs so far, 0 failures
14m20s: 77 runs so far, 0 failures
14m25s: 78 runs so far, 0 failures
14m30s: 78 runs so far, 0 failures
14m35s: 79 runs so far, 0 failures
14m40s: 79 runs so far, 0 failures
14m45s: 80 runs so far, 0 failures
14m50s: 80 runs so far, 0 failures
14m55s: 81 runs so far, 0 failures
15m0s: 81 runs so far, 0 failures
15m5s: 81 runs so far, 0 failures
15m10s: 82 runs so far, 0 failures
15m15s: 82 runs so far, 0 failures
15m20s: 83 runs so far, 0 failures
15m25s: 83 runs so far, 0 failures
15m30s: 84 runs so far, 0 failures
15m35s: 84 runs so far, 0 failures
15m40s: 85 runs so far, 0 failures
15m45s: 85 runs so far, 0 failures
15m50s: 86 runs so far, 0 failures
15m55s: 86 runs so far, 0 failures
16m0s: 86 runs so far, 0 failures
16m5s: 87 runs so far, 0 failures
16m10s: 87 runs so far, 0 failures
16m15s: 88 runs so far, 0 failures
16m20s: 88 runs so far, 0 failures
16m25s: 89 runs so far, 0 failures
16m30s: 89 runs so far, 0 failures
16m35s: 90 runs so far, 0 failures
16m40s: 90 runs so far, 0 failures
16m45s: 91 runs so far, 0 failures
16m50s: 91 runs so far, 0 failures
16m55s: 91 runs so far, 0 failures
17m0s: 92 runs so far, 0 failures
17m5s: 92 runs so far, 0 failures
17m10s: 93 runs so far, 0 failures
17m15s: 93 runs so far, 0 failures
17m20s: 94 runs so far, 0 failures
17m25s: 94 runs so far, 0 failures
17m30s: 95 runs so far, 0 failures
17m35s: 95 runs so far, 0 failures
17m40s: 96 runs so far, 0 failures
17m45s: 96 runs so far, 0 failures
17m50s: 96 runs so far, 0 failures
17m55s: 97 runs so far, 0 failures
18m0s: 97 runs so far, 0 failures
18m5s: 98 runs so far, 0 failures
18m10s: 98 runs so far, 0 failures
18m15s: 99 runs so far, 0 failures
18m20s: 99 runs so far, 0 failures
18m25s: 100 runs so far, 0 failures
18m30s: 100 runs so far, 0 failures
18m35s: 101 runs so far, 0 failures
18m40s: 101 runs so far, 0 failures
18m45s: 101 runs so far, 0 failures
18m50s: 102 runs so far, 0 failures
18m55s: 102 runs so far, 0 failures
19m0s: 103 runs so far, 0 failures
19m5s: 103 runs so far, 0 failures
19m10s: 104 runs so far, 0 failures
19m15s: 104 runs so far, 0 failures
19m20s: 105 runs so far, 0 failures
19m25s: 105 runs so far, 0 failures
19m30s: 105 runs so far, 0 failures
19m35s: 106 runs so far, 0 failures
19m40s: 106 runs so far, 0 failures
19m45s: 107 runs so far, 0 failures
19m50s: 107 runs so far, 0 failures
19m55s: 108 runs so far, 0 failures
20m0s: 108 runs so far, 0 failures
</pre>
</details>

**Which issue(s) this PR fixes**:
Fixes #6904

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by timuthy** [comment]
FYI, tests failed because of unhealthy MCM pods:
```
10m         Warning   Failed                         pod/machine-controller-manager-855d4b4d5d-5phsn    Failed to pull image "ghcr.io/gardener/machine-controller-manager-provider-local:sha-1c148ce": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/gardener/machine-controller-manager-provider-local:sha-1c148ce": failed to resolve reference "ghcr.io/gardener/machine-controller-manager-provider-local:sha-1c148ce": failed to authorize: failed to fetch anonymous token: unexpected status: 503 Service Unavailable
```

I will retry later.

**Review by timebertt — APPROVED** [review]
Thank you!
/lgtm

**Comment by rfranzke** [comment]
Nice!

**Pull request merged**
