### PR TITLE
Allow garden prometheus to scrape extensions outside of garden namespace

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Allow garden prometheus to scrape extensions outside of garden namespace.

Previously, garden prometheus was only configured to scrape resources in garden namespace. Now, extensions can be labeled to be scraped even outside of garden namespace.

Services of extensions would need to labeled like the following:

```
annotations:
  networking.resources.gardener.cloud/from-all-garden-scrape-targets-allowed-ports: '[{"port":<server-port-on-pod>,"protocol":"<protocol, typically TCP>"}]'
  networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
  networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Allow extensions to be scraped in garden runtime cluster even outside garden namespace
```

/cc @rfranzke @marwinski

### CODE REVIEW

**Review by rfranzke — CHANGES_REQUESTED** [review]
Can you document this for extensions so that they know what needs to be done to get scraped by `prometheus-garden`?

**Comment by ScheererJ** [comment]
> Can you document this for extensions so that they know what needs to be done to get scraped by `prometheus-garden`?

I added documentation in https://github.com/gardener/gardener/pull/10720/commits/cc0127c67ef127d26f06521c4e24f759fab28120.

@rfranzke Is this what you had in mind?

**Review by rfranzke — COMMENTED** [review]
I was actually thinking more about https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#monitoring since this is usually only relevant for extensions (i.e., components not deployed via Gardener), right?

**Comment by ScheererJ** [comment]
> I was actually thinking more about https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#monitoring since this is usually only relevant for extensions (i.e., components not deployed via Gardener), right?

In https://github.com/gardener/gardener/blob/master/docs/operations/network_policies.md#logging--monitoring we already have some information relevant for extension developers. Therefore, it felt more natural to add it there to the `Garden` section.

I first also looked into https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md#monitoring, but there is no mention of network policy labels at all. Should I replicate/move parts of the documentation there or add corresponding links?

WDYT?

**Comment by rfranzke** [comment]
OK, then I'm fine. Maybe just add a link to the `operations/network_policies.md` document within the extensions document, so that people can easily find it.

**Comment by ScheererJ** [comment]
Added links and a tip to the extension documentation.

PTAL.

**Review by timebertt — COMMENTED** [review]
/lgtm

**Pull request merged**
