### PR TITLE
Update etcd-druid dependency

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR updates the `github.com/gardener/etcd-druid` dependency.

**Special notes for your reviewer**:
/cc @timebertt @PavelPavlov46 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
Thanks!
/lgtm

Any chance we can backport this? Because v1.34.0 is somewhat "broken to vendor"...

**Comment by timuthy** [comment]
> Thanks! /lgtm
> 
> Any chance we can backport this? Because v1.34.0 is somewhat "broken to vendor"...

https://github.com/gardener/gardener/pull/4892

**Pull request merged**
