### PR TITLE
[operator] Fix virtual-etcd dashboards

### PR DESCRIPTION
**Pull request by rickardsjp**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
Now that the virtual-etcd is managed by the gardener-operator, the Prometheus scrape jobs were adjusted in an internal repository. The corresponding dashboards for Plutono are adjusted in this PR.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @istvanballok @acumino 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by istvanballok — COMMENTED** [review]
/lgtm

**Review by acumino — COMMENTED** [review]
Thanks
/approve

**Pull request merged**
