### PR TITLE
Fixes for release validation v1.22

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**
Including fixes:

* Remove validating the removal of the use-as-seed annotation (see https://github.com/gardener/gardener/pull/3978)
* Adapt resource names for Gardener component's RBAC

/area open-source
/kind regression
/priority 2

**What this PR does / why we need it**:
With #3901, we have introduced dedicated `ClusterRole`s for the `gardener-apiserver` and `gardener-controller-manager` components. However, we missed that the `roleRef` is immutable in the respective `ClusterRoleBinding`s:

```
ClusterRoleBinding.rbac.authorization.k8s.io "gardener.cloud:controller-manager:admin" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"gardener.cloud:system:gardener-controller-manager"}: cannot change roleRef
```

As we want to keep the dedicated `ClusterRole`s (to potentially further restrict the permissions in the future), let's now use the opportunity to properly adapt and streamline the resource names. This will result in new `ClusterRoleBinding` objects, i.e., they won't conflict with the existing ones in the system, however, operators have to make sure to cleanup the old roles after applying the Helm chart (see release note).

**Special notes for your reviewer**:
/invite @BeckerMax 

**Release note**:

```action operator
There are now dedicated `ClusterRole`s for the `gardener-apiserver` and `gardener-controller-manager`. As the `roleRef` fields of the binding `ClusterRoleBinding`s are immutable, also the names of the `ClusterRoleBinding`s have been changed. When you apply this version of Gardener then you have to make sure to cleanup the old resources that will be still left in your system be running the following command:
`kubectl delete clusterrolebinding/gardener.cloud:apiserver:admin clusterrolebinding/gardener.cloud:controller-manager:admin clusterrole/gardener.cloud:system:gardener-scheduler clusterrolebinding/gardener.cloud:system:gardener-scheduler --ignore-not-found --wait=false`
```

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
/lgtm

Regarding the release note:
Why does it explicitly list `clusterrole/gardener.cloud:system:gardener-scheduler` as a resource to be deleted but not `clusterroles` of the other components?

**Comment by rfranzke** [comment]
@timebertt because only the scheduler's ClusterRole was renamed

**Comment by timebertt** [comment]
I'm confused: here https://github.com/gardener/gardener/pull/3975/files#diff-e8eb4fd11ff0014712dca08c362a3ee0d534274ee404c9bc184cef9297353957R6 the clusterrole of the apiserver was also renamed. Same for the controller-manager.

**Comment by timebertt** [comment]
@stoyanr I assume you pushed your commit to this branch by accident, right?

**Comment by BeckerMax** [comment]
@timebertt  This is another commit that is needed for release validation. That is why I suggested the commit to be pushed to the `rc` branch. I need an image with both changes to test whether the deploy to dev runs through.

**Comment by timebertt** [comment]
Ah ok, so should we close https://github.com/gardener/gardener/pull/3978 in favor of this one then?

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
> https://github.com/gardener/gardener/pull/3975/files#diff-e8eb4fd11ff0014712dca08c362a3ee0d534274ee404c9bc184cef9297353957R6

Yes, but those `ClusterRole`s were never released yet (I just introduced them in #3901), so there is no necessity for a release note.

**Comment by timebertt** [comment]
> > https://github.com/gardener/gardener/pull/3975/files#diff-e8eb4fd11ff0014712dca08c362a3ee0d534274ee404c9bc184cef9297353957R6
> 
> Yes, but those `ClusterRole`s were never released yet (I just introduced them in #3901), so there is no necessity for a release note.

Ah thanks, now I got it :)

**Comment by timebertt** [comment]
We can merge this PR FMPOV :)

**Pull request merged**
