### PR TITLE
Update the go.mod version to go1.17

### LINKED ISSUE #4843: Update the go.mod version to go1.17
**How to categorize this issue?**

/area open-source
/kind enhancement
/priority 4

**What would you like to be added**:

From https://github.com/gardener/gardener/pull/4822#issue-755237424:

> I didn't update the go version of the module (the one in go.mod) because to be honest I am not able to completely follow the changes to the [module graph pruning](https://golang.org/ref/mod#graph-pruning). go1.17 should be able to work with go1.16 module. This is actually also how kubernetes/kubernetes upgraded to go1.17 - the go runtime version is go1.17 but the module version is still go1.16 - ref https://github.com/kubernetes/kubernetes/pull/103692. So it should not be a problem if we delay to module version update to another PR.

**Why is this needed**:
To keep the module version up-to-date

### PR DESCRIPTION
**Pull request by ialidzhikov**
/area open-source
/kind enhancement

This PR consists of:
1. Updating the version in the go.mod file.
   ```diff
   -go 1.16
   +go 1.17
   ```

2. Running `make revendor` afterwards.

Fixes #4843

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Thanks!

Can you explain why the concerns in https://github.com/gardener/gardener/pull/4822#issue-755237424 are no longer relevant?

> I didn't update the go version of the module (the one in go.mod) because to be honest I am not able to completely follow the changes to the [module graph pruning](https://golang.org/ref/mod#graph-pruning). go1.17 should be able to work with go1.16 module. This is actually also how kubernetes/kubernetes upgraded to go1.17 - the go runtime version is go1.17 but the module version is still go1.16 - ref https://github.com/kubernetes/kubernetes/pull/103692. So it should not be a problem if we delay to module version update to another PR.

**Comment by ialidzhikov** [comment]
> Can you explain why the concerns in https://github.com/gardener/gardener/pull/4822#issue-755237424 are no longer relevant?

I see that the raised concern in https://github.com/kubernetes/kubernetes/pull/103692 was related to [depstat](https://github.com/kubernetes-sigs/depstat) and it is not something that we use in gardener/gardener - ref https://github.com/kubernetes/kubernetes/pull/103692#issuecomment-896905016.

**Review by rfranzke — APPROVED** [review]
/lgtm
/milestone v1.43

**Pull request merged**
