### PR TITLE
Enable server side encryption of oss buckets on Alicloud

### PR DESCRIPTION
**Pull request by minchaow**
**What this PR does / why we need it**:
This PR is to enable server side encryption of oss buckets on Alicloud.
**Which issue(s) this PR fixes**:
Fixes #
None
**Special notes for your reviewer**:
It will trigger a 'terraform apply' job on existed buckets. It will not affect snapshots already stored in buckets, but for snapshots uploaded after the change, they will be encrypted on server side.

```noteworthy operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
We'll merge it now, but this Terraform script will soon be deleted in favour of #1128 and the provider-specific extension controllers. Please file a similar PR to https://github.com/gardener/gardener-extensions/blob/master/controllers/provider-alicloud/pkg/alicloud/client/client.go#L105

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by minchaow** [comment]
sure, will file one soon

**Comment by rfranzke** [comment]
great, thanks

**Pull request merged**
