### PR TITLE
Add qps and burst for the vpa-recommender for Shoots and Seeds

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
The default values for qps and burst (5/10) for the vpa-recommender are too low for large Seed clusters. 
For Seed clusters with 250 Shoots and > 3800 vpa resource, we can observe an execution latency (until Vpa recommendations are provided) of 1.17min (down from 30 minutes).

The new settings cause around 80 queries/second on the API server (up from 10 qps). To have a little buffer, a qps of 100 seems reasonable.
The increase in the request rate to the API Server of 70 qps did not seem to negatively affect the API Server.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Increase the QPS and burst values for `kube-apiserver` requests for the `vpa-recommender` of Seed and Shoot clusters to better cope with large cluster sizes.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Does it make sense to set the flags also for the other VPA components?

/cc @stoyanr

**Comment by voelzmo** [comment]
> Does it make sense to set the flags also for the other VPA components?

We can also set this for e.g. the vpa-updater, although we haven't seen this become a bottleneck so far. When looking at its control loop on our busiest seeds, it was still operating very comfortably with the default values. As long as we don't see a reason to change the values, I'd say we stick to the defaults?

**Comment by rfranzke** [comment]
Sure, your call, I just wanted to bring this up since I thought about it when looking at the changes

/approve

**Review by voelzmo — COMMENTED** [review]
/lgtm

**Review by voelzmo — APPROVED** [review]

**Pull request merged**
