### PR TITLE
Add the mcm_machine_set_failed_machines metric

### PR DESCRIPTION
**Pull request by jguipi**
How to categorize this PR?
/area monitoring
/kind enhancement

What this PR does / why we need it:
Add a new metric that will allow Prometheus to scrape the stale machine count.

Which issue(s) this PR fixes:
Fixes # 

Special notes for your reviewer:
- This PR will need to wait for another MCM PR to get merge (https://github.com/gardener/machine-controller-manager/pull/808) 
- This PR will probably need to be merge at the same time as those PR: 
	- https://github.com/gardener/gardener-extension-provider-aws/pull/740
	- https://github.com/gardener/gardener-extension-provider-gcp/pull/586
	- https://github.com/gardener/gardener-extension-provider-azure/pull/677
	- https://github.com/gardener/gardener-extension-provider-alicloud/pull/596
	- https://github.com/gardener/gardener-extension-provider-vsphere/pull/402 
	- https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/257
	- https://github.com/gardener/gardener-extension-provider-openstack/pull/612
	- https://github.com/gardener/gardener/pull/7794

Release note:
```
NONE
```

### CODE REVIEW

**Comment by jguipi** [comment]
cc.: @dmahmalatsap @istvanballok @rickardsjp

**Review by rfranzke — CHANGES_REQUESTED** [review]
Please also adapt https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/machinecontrollermanager/monitoring.go

Also, I think you have to open PRs for all the provider extensions with the same change (MCM is not yet managed centrally by Gardener).

**Comment by jguipi** [comment]
> Please also adapt https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/machinecontrollermanager/monitoring.go
> 
> Also, I think you have to open PRs for all the provider extensions with the same change (MCM is not yet managed centrally by Gardener).

Just to be sure, when you talk about `provider extensions` are you making reference to all those repositories: 

- https://github.com/gardener/machine-controller-manager-provider-azure
- https://github.com/gardener/machine-controller-manager-provider-local
- https://github.com/gardener/machine-controller-manager-provider-openstack
- https://github.com/gardener/machine-controller-manager-provider-aws
- https://github.com/gardener/machine-controller-manager-provider-gcp
- https://github.com/gardener/machine-controller-manager-provider-alicloud
- https://github.com/gardener/machine-controller-manager-provider-vsphere
- https://github.com/gardener/machine-controller-manager-provider-yandex
- https://github.com/gardener/machine-controller-manager-provider-equinix-metal
- https://github.com/gardener/machine-controller-manager-provider-kubevirt

Or in the Gardener case, we only need to focus on the major cloud provider : 
- aws
- Azure
- gcp
- Alicloud
- Openstack

cc.: @rfranzke

**Comment by ScheererJ** [comment]
@jguipi https://github.com/gardener/gardener-extension-provider-aws/blob/4b402bd01068b6bbd0a31b188bc2d16cd2b91d19/charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml#L46 is the example for provider-aws @rfranzke was referring to. You most likely do not need to change the machine controller manager provider extensions, but the provider extensions.

This change does the job for provider-local in https://github.com/gardener/gardener/pull/7794/files#diff-feb6651c4decec47755c42467f4feb3f1e66076cc7bfa24147cd3b0b6e8e7a7d. The change in `monitoring.go` is valid for all infrastructures.

**Comment by ScheererJ** [comment]
Do you also want to add the metric to a dashboard or is this planned for a later change?

**Comment by jguipi** [comment]
> Do you also want to add the metric to a dashboard or is this planned for a later change?

This is plan for a later change !

**Comment by jguipi** [comment]
> You most likely do not need to change the machine controller manager provider extensions, but the provider extensions.

Ok, that makes more sense to me! I've pushed those PRs.

**Comment by rfranzke** [comment]
Please adapt https://github.com/gardener/gardener/blob/8e32b191699dfeaf5c72b110fb473ee50d88fcb8/pkg/operation/botanist/component/machinecontrollermanager/monitoring_test.go.
Always run `make verify` before pushing to be sure :)

**Comment by dmahmalatsap** [comment]
Tests are passing !
@rfranzke just checking if the review at https://github.com/gardener/gardener/pull/7794#pullrequestreview-1389447480 is still relevant.

Let us know if there's anything else to change !

cc. @jguipi

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
