### PR TITLE
[release-v1.34] Calculate component descriptor

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area delivery
/kind bug

**What this PR does / why we need it**:
This is an empty commit which is necessary for the `v1.34.2` release to fix the broken component descriptor in release `v1.34.1`. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Requested by @AndreasBurger @enrico-kaack-comp 

**Release note**:

```bugfix operator
The component descriptor has been fixed.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Why is this needed? Can't you just click the release button?

**Comment by timuthy** [comment]
> Why is this needed? Can't you just click the release button?

I wanted to have a release note to let the community know what the release is about. I guess an empty commit doesn't hurt? 👀

**Review by rfranzke — APPROVED** [review]

**Comment by timuthy** [comment]
Waiting for a final go from @AndreasBurger 
/hold

**Comment by timuthy** [comment]
/close
Hotfix is not needed because `v1.35.0` was released in time.

**Pull request closed without merging**
