### PR TITLE
Fix control plane monitoring and logging PriorityClasses

### LINKED ISSUE #6464: PriorityClasses for control plane monitoring and logging components are wrong
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
After https://github.com/gardener/gardener/pull/6257:
```
$ k -n shoot--foo--bar get po -o json | jq -r '.items[] | "\(.metadata.name) \(.spec.priorityClassName)"'
cloud-controller-manager-dcbb87568-fprtx gardener-system-300
csi-driver-controller-8446c7484b-8zvht gardener-system-300
csi-snapshot-controller-f585959ff-dmz8l gardener-system-200
csi-snapshot-validation-5d79596897-72mws gardener-system-200
etcd-events-0 gardener-shoot-controlplane
etcd-main-0 gardener-shoot-controlplane
gardener-resource-manager-7f6869994c-7x9ft null
gardener-resource-manager-7f6869994c-fs9sb null
gardener-resource-manager-7f6869994c-qwdq9 null
grafana-operators-68d4c7db75-9l85j gardener-system-600
grafana-users-bdfcdf4cb-fc5wk gardener-system-600
kube-apiserver-7849f46694-7cxdk gardener-system-500
kube-controller-manager-9fcccb99f-lghqf gardener-system-300
kube-scheduler-6456488487-dvlnd null
kube-state-metrics-7bfdcfdb6c-srww6 gardener-system-100
loki-0 gardener-system-600
machine-controller-manager-565678bc44-4nrt6 gardener-system-300
prometheus-0 gardener-system-600
vpa-admission-controller-8598f5597c-pwq9s gardener-system-200
vpa-recommender-6f8b96c88-czx6p gardener-system-200
vpa-updater-5c864c76b-vh9xb gardener-system-200
vpn-seed-server-699cbcb78d-znk7k gardener-shoot-controlplane
```

`prometheus`, `loki`, `grafana-operators`, `grafana-users` wrongly use `gardener-system-600`. 
According to https://github.com/gardener/gardener/blob/master/docs/development/priority-classes.md `gardener-system-600` is a Seed system PriorityClass and should be used only by Seed system components. The control plane components from above should rather use `gardener-system-100`. Only the components in the garden namespace should use `gardener-system-600`.

**What you expected to happen**:
See above.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 99b5f7bbdb1be1b7e7e57d97792180b0be2655cd
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
See a detailed explanation/motivation in https://github.com/gardener/gardener/issues/6464.
This PR also cleans up the `logging.loki.garden.priority` field that is obsolete after https://github.com/gardener/gardener/pull/6257.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6464

**Release note**:

```breaking operator
The `logging.loki.garden.priority` field is removed from gardenlet's component config as it is no longer used after the [new concept for PriorityClasses in Gardener](https://github.com/gardener/gardener/blob/v1.52.2/docs/development/priority-classes.md).
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
After https://github.com/gardener/gardener/pull/6257,
https://github.com/gardener/gardener/blob/b7e6d8691ccc9421a4cee73286497a1f004d5612/test/testmachinery/shoots/logging/seed_logging_stack.go#L115 still uses the old fluent-bit name, running the tm tests give me

```
  Unexpected error:
      <*errors.StatusError | 0xc000e126e0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "priorityclasses.scheduling.k8s.io \"fluent-bit\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "fluent-bit",
                  Group: "scheduling.k8s.io",
                  Kind: "priorityclasses",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      priorityclasses.scheduling.k8s.io "fluent-bit" not found
  occurred
  In [BeforeEach] at: /Users/i545724/go/src/github.com/gardener/gardener/test/testmachinery/shoots/logging/seed_logging_stack.go:116
```
Can you please adapt it similar to https://github.com/gardener/gardener/blob/b7e6d8691ccc9421a4cee73286497a1f004d5612/test/testmachinery/shoots/logging/seed_logging_stack.go#L120?

**Comment by shafeeqes** [comment]
Thanks!

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Review by krgostev — COMMENTED** [review]
We have looked into the PR with @timebertt and it looks good. Thanks for the quick fix!

**Review by krgostev — APPROVED** [review]
/lgtm

**Pull request merged**
