### PR TITLE
[renovate] Add release notes for docker and github-releases

### LINKED ISSUE #1734: Renovate should include Gardener release note with link to GitHub release
/kind enhancement

**What would you like to be added**:
When Renovate updates an image in `gardener/gardener` ([example](https://github.com/gardener/gardener/pull/9759)) then it should include a link to the GitHub release of the updated component, e.g. like this:

<code>
```other dependency
The `gardener/dashboard` image has been updated to `v1.75.0`. [Release Notes](https://github.com/gardener/dashboard/releases/tag/1.75.0)
```
</code>

**Why is this needed**:
Traceability

/cc @oliver-goetz 
Can we achieve this relatively simple?

### PR DESCRIPTION
**Pull request by petersutter**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
This PR updates the Renovate configuration to include a PR footer with release notes for `docker` datasource and release notes with links for `github-releases` datasource.

Thanks @timebertt for the [suggestion](https://github.com/gardener/ci-infra/issues/1734#issuecomment-2124429769)

Example PR:
Screenshot 2024-05-23 at 14 34 42

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/ci-infra/issues/1734

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
Can you extend the PR tu support adding the release notes for all updates from GitHub releases, not only those two repositories?

**Review by rfranzke — COMMENTED** [review]
Thanks! I don't know whether this really works in the end, but technically it looks good.
/lgtm
/cc @oliver-goetz @timebertt

**Review by oliver-goetz — CHANGES_REQUESTED** [review]
Nice 🚀 

We have a couple of updates based on docker releases. Adding release notes might not work in this case, but we can still mention them with an additional rule like this.

```
    {
      // Add PR footer for docker releases.
      "matchDatasources": ["docker"],
      "matchFileNames": ["imagevector/**"],
      "prFooter": "```other dependency\nThe `{{depName}}` image has been updated to `{{newVersion}}`.\n```"
    }
```

**Review by timebertt — COMMENTED** [review]
Nice!
/lgtm

**Review by oliver-goetz — APPROVED** [review]

**Pull request merged**
