### PR TITLE
Allow gardener admission controller to read configmaps

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/kind bug

**What this PR does / why we need it**:
Add missing get configmap permissions to the Gardener Admission Controller required here https://github.com/gardener/gardener/blob/d5a42254fc20c654d19bdda9ef3934e83d4ea417/pkg/admissioncontroller/webhooks/admission/auditpolicy/admission.go#L138

**Which issue(s) this PR fixes**:
Follow-up on https://github.com/gardener/gardener/pull/3720

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
NONE
```

### CODE REVIEW

**Comment by BeckerMax** [comment]
Thanks! I guess we do not need a release note as the original change was not released yet, or?

**Review by rfranzke — APPROVED** [review]
/lgtm

Yep @BeckerMax, nice!

**Pull request merged**
