### PR TITLE
Streamline `WithServiceAccountIssuerHostname`

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Streamline `WithServiceAccountIssuerHostname`

/cc @dimityrmirchev 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by dimityrmirchev** [comment]
Thanks, this looks better

/lgtm

**Review by acumino — COMMENTED** [review]
/approve

**Pull request merged**
