### PR TITLE
provide ability to fix chart namespace

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:

When passing charts to [genericactuator.NewActuator](https://pkg.go.dev/github.com/gardener/gardener@v1.32.1/extensions/pkg/controller/controlplane/genericactuator#NewActuator), it always passes in the `kube-system` namespace or blank. However, this may not work for many charts. Many expect the user to provide the equivalent of `helm install --namespace some-namespace`. The charts may not even work in the generic namespace, and _must_ have a provided namespace. A good example is the rook-ceph chart (which is what brought me to this).

This PR provides an ability to create the [Chart](https://pkg.go.dev/github.com/gardener/gardener@v1.32.1/pkg/utils/chart#Chart) with a `Namespace` override. If the `c.Namespace` is set, then the `Apply()`/`Render()`/`Delete()` will ignore the passed namespace and use the override.

I did look at putting it into the actuator, but there isn't a clean and easy way to get it in there, whereas the pattern of calling `genericactuator.NewActuator()` and passing it lots of charts in the args is an easy place to do it.

I have't quite figured out how to _create_ that namespace, but this is a step in the right direction.

**Special notes for your reviewer**:

As an example of how I might use this, look at the aws extension where [it creates the `controlPlaneShootChart` in `valuesprovider.go`](https://github.com/gardener/gardener-extension-provider-aws/blob/443b16a2f12e0a3ddc2756575e9169147fb763dc/pkg/controller/controlplane/valuesprovider.go#L248-L256):

```go
		SubCharts: []*chart.Chart{
			{
				Name: "cloud-controller-manager",
				Path: filepath.Join(aws.InternalChartsPath, "cloud-controller-manager"),
				Objects: []*chart.Object{
					{Type: &rbacv1.ClusterRole{}, Name: "system:controller:cloud-node-controller"},
					{Type: &rbacv1.ClusterRoleBinding{}, Name: "system:controller:cloud-node-controller"},
				},
			},
```

If the CCM were supposed to be in a specific namespace, say `aws-ccm`, we currently could not support it. With this PR, it remains optional, but we could do:

```go
		SubCharts: []*chart.Chart{
			{
				Name: "cloud-controller-manager",
				Namespace: "aws-ccm",
				Path: filepath.Join(aws.InternalChartsPath, "cloud-controller-manager"),
				Objects: []*chart.Object{
					{Type: &rbacv1.ClusterRole{}, Name: "system:controller:cloud-node-controller"},
					{Type: &rbacv1.ClusterRoleBinding{}, Name: "system:controller:cloud-node-controller"},
				},
			},
```

This isn't a perfect example, as AWS is likely to put the namespace in the chart itself, obviating the need for it here, but it gets the idea across.

Rook is the primary example right now.

**Release note**:

```feature developer
Support Chart namespace override
```

### CODE REVIEW

**Comment by deitch** [comment]
BTW, if there _is_ a better and cleaner way to do this, I am open to it.

**Comment by deitch** [comment]
Thanks @rfranzke

**Comment by deitch** [comment]
One thing I did not cover here was the equivalent of `--create-namespace`, i.e.

```
helm install --create-namespace --namespace <namespace>
```

Does `chart.Chart()` take care of ensuring the namespace exists when passed to `Chart.Apply()`? Or is that something I would need to include here?

**Comment by stoyanr** [comment]
@deitch I am afraid I don't fully understand the idea of this PR. You write that:

> When passing charts to `genericactuator.NewActuator`, it always passes in the `kube-system` namespace or blank.

But in fact, this is not the case. The generic controlplane actuator always passes the namespace of the controlplane resource, see e.g. https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L301-L303.

The namespace is not specified in the `Chart` because the implicit idea is that it can't be known in advance, at least not in the use case for which this type was created. Currently the only place I am aware of where this `Chart` type is used is the generic controlplane actuator you mentioned, and from our perspective everything that is part of a shoot'c control plane **must** go to the same namespace, the one that contains the shoot's control plane.

You also write that: 
> This is the equivalent of passing "helm install --namespace" to the Applier.

However, the `Apply` function already has a `namespace` parameter that would be from my perspective the equivalent of the  `--namespace` command line argument. I am not sure why would we need a second way to provide a namespace. Also, overriding a parameter with a field from the type (and not vice versa) is rather strange from my perspective, if this is needed at all I would propose to design it the other way around.

Could you describe the exact problem with `rook-ceph` that you are trying to solve, perhaps a link to the problematic chart and if possible the code on your side that attempts to use `Chart` and fails?

At the moment (without knowing more details about your use case) I am inclined to say that any chart that attempts to install something outside of the controlplane namespace should not be installed by the generic controlplane actuator. Could you perhaps solve your problem by installing / removing this chart as part of a different flow than reconciling the `Controlplane` resource? I am only vaguely familiar with `rook-ceph` but it seems to me more like something that an `Infrastructure` reconciliation could take care of?

**Comment by deitch** [comment]
> The namespace is not specified in the Chart because the implicit idea is that it can't be known in advance, at least not in the use case for which this type was created. 

Agreed.

> Currently the only place I am aware of where this Chart type is used is the generic controlplane actuator you mentioned, and from our perspective everything that is part of a shoot's control plane must go to the same namespace, the one that contains the shoot's control plane.

Does it? What if I am deploying resources to the shoot itself? For example, a CCM or a storage mesh (which is my use case). Granted, CCM almost always lives in `kube-system`, but it need not.

> However, the Apply function already has a namespace parameter that would be from my perspective the equivalent of the --namespace command line argument.

Agreed. My issue is not with _can_ I pass a namespace, but how do I _override_ the default namespace that Gardener passes, i.e. `kube-system`. There are charts for system components which are expected to be installed not in an application namespace or in `kube-system`, but in a dedicated one. rook-ceph is our example at hand (which brought this to me), but I can think of others.

> I am not sure why would we need a second way to provide a namespace. Also, overriding a parameter with a field from the type (and not vice versa) is rather strange from my perspective, if this is needed at all I would propose to design it the other way around.
>
> Could you describe the exact problem with rook-ceph that you are trying to solve, perhaps a link to the problematic chart and if possible the code on your side that attempts to use Chart and fails?

Certainly. If there is a different way to do this, I am all for it. I just want to make it work.

[Here are the install instructions](https://rook.io/docs/rook/v1.7/helm-ceph-cluster.html#release) for rook-ceph. Essentially:

```
helm repo add rook-release https://charts.rook.io/release
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster \
   --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f values-override.yaml
```

It is fully expected that you:

* install it in a specific dedicated namespace
* create that namespace
* pass it as part of the values

The namespace itself appears nowhere in the chart; it is entirely parametrized via either templates in the chart (`--set ...`) or the `--namespace rook-ceph` which sets the default.

It shouldn't go in `kube-system` or `default`. 

What I have been trying to do via [this PR](https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/136) - and led me to this - is put the plain vanilla off-the-shelf rook chart into ` charts/internal/shoot-system-components/charts/rook-ceph/`, added the storage class into the right place, of course, and then modified `valuesprovider.go` to include it as part of `controlPlaneShootChart` that gets passed to `AddManager` (which calls `genericactuator.NewActuator()`).

The storage needs to be in place for the shoot to function as anything with storage - e.g. a shooted seed - because storage via CSI is a prerequisite. 

Given the above - it needs to be installed (as an option) when deploying a shoot; we want to keep the plain vanilla chart without modifications (upkeep/maintenance costs); we need to deploy it to a specific namespace and create that namespace - is there a better way to go about doing this? I am all for whatever works.

**Comment by stoyanr** [comment]
@deitch Thanks, it's much more clearer now.

> Does it? What if I am deploying resources to the shoot itself? 

You are right, there are charts that go to the shoot, I did not realize `rook-ceph` may be such a chart. These charts are not applied directly, but rendered and applied later by GRM via a `ManagedResource`. The namespace Gardener passes is always `kube-system`. The relevant code is https://github.com/gardener/gardener/blob/b12f41152e867e6c0678311c9a82400ea7f0e5e6/extensions/pkg/controller/controlplane/genericactuator/actuator.go#L317-L319. 

Still, rather than modifying the `Chart` type in the proposed way, I would consider the following approach:

* Create the namespace via a separate chart / managed resource. As you mentioned, the namespace should also be created, and there is no other really good way to do it except via the GRM. You would need to add yet another chart to the list of charts passed, e.g. `controlPlaneShootNamespaceChart`.
* If `controlPlaneShootNamespaceChart` is non-nil, pass the relevant namespace (instead of `kube-system`) to the call to `managedresources.RenderChartAndCreate` mentioned above.

This would however not work if, in addition to deploying `rook-ceph` to its own namespace, you would also like to deploy stuff to `kube-system` namespace, e.g. CCM RBAC resources, CSI node controller, etc. For this reason, I would also propose that you consider instead of modifying the generic actuator:
* Create your own actuator (the generic actuator is there really only for convenience, you can very well replace it with your own)
* Embed the generic actuator into your own to avoid duplicating code and delegate to the generic actuator `Reconcile` and `Delete` methods.
* Extract `rook-ceph` to its own chart, and also create the namespace chart mentioned above
* Apply these charts in your actuator's `Reconcile` method after calling `Reconcile` on the generic actuator (via managed resources). 
* Delete these charts in your actuator's `Delete` methods before calling `Delete` on the generic actuator (via managed resources).
 
As an example how a similar non-generic actuator can be implemented, you could take a look at https://github.com/gardener/gardener-extension-provider-azure/blob/master/pkg/controller/controlplane/actuator.go.

The one thing that I am not entirely sure is that since there is no way to specify that the rook-ceph managed resource depends on the namespace managed resource (and so should be applied after and deleted before the other one), GRM will try to apply / delete them in parallel, which would result in failures. Still I think it should probably work, since GRM would automatically retry after such a failure. No one has tried this however, so I can't be sure. Perhaps you could give it a try and if you encounter issues, we can discuss how to solve them (e.g. via a fix in GRM).

**Comment by deitch** [comment]
I get what you are saying, that this cannot simply go into the same "space" (for lack of a better term, encompassing chart location and actuator, etc.) with the kube-system namespaced things (CSI, CPEM, etc.). It would be convenient if there were a structure to handle these as well, but there isn't.

So you are proposing that instead of modifying the `genericactuator.Actuator`, I create my own in `pkg/controller/controlplane/` (like the link above), which modifies the behaviour that I want. 

I then call that actuator in `add.go` to pass to `controlplane.add()` rather than the generic one. 

That part I get.

The part I am unsure of is this.

* I think you are saying that this would be a completely different argument to my `NewActuator()`. In addition to passing it the genericactuator with all of its usual arguments, I also pass it a "to apply to shoot when done chart" argument. This is an entirely new var, similar to, say, `controlPlaneShootChart` or `controlPlaneChart` that I already am passing to the `genericactuator.NewActuator()`. Except here it is being passed to my actuator.
* The chart itself would live in a new separate path under `charts/internal/shoot-components/` or similar

So it would look something sort of like this.

`valuesprovider.go`:

```go
var shootLateDeployChart = &chart.Chart{
	Name: "shoot-later-components",
	Path: filepath.Join(equinixmetal.InternalChartsPath, "shoot-later-components"),
	SubCharts: []*chart.Chart{
		{
			Name: "rook-ceph",
			Images: []string{
				equinixmetal.RookCephImageName,
			},
		},
	},
}
```

`add.go`:

```go
func AddToManagerWithOptions(mgr manager.Manager, opts AddOptions) error {
	var (
		exposureSecrets           secretutil.Interface
		configChart               chart.Interface
		controlPlaneExposureChart chart.Interface
		configName                string
	)

	return controlplane.Add(mgr, controlplane.AddArgs{
		Actuator: NewActuator(
                        genericactuator.NewActuator(
                              equinixmetal.Name, controlPlaneSecrets, exposureSecrets, configChart,
 			     controlPlaneChart, controlPlaneShootChart, nil, storageClassChart, controlPlaneExposureChart,
			     NewValuesProvider(logger), extensionscontroller.ChartRendererFactoryFunc(util.NewChartRendererForShoot),
			     imagevector.ImageVector(), configName, opts.ShootWebhooks, mgr.GetWebhookServer().Port, logger
                        ),
                        shootLateDeployChart),
		ControllerOptions: opts.Controller,
		Predicates:        controlplane.DefaultPredicates(opts.IgnoreOperationAnnotation),
		Type:              equinixmetal.Type,
	})
}
```

And my `Reconcile` (and `Delete`) would look more or less:

`actuator.go`:

```go
(a *Actuator) Reconcile(ctx context.Context, cal *extensionsv1alpha1.ControlPlane, cl *extensionscontroller.Cluster) (bool, error) {
    // do something in here to apply the given chart to the given cluster
}
```

First, did I understand you correctly?
Second, is the dedicated path where the charts should live, as I understood them?
Third, I am not sure what goes in the `Reconcile` and `Delete`.

**Comment by stoyanr** [comment]
> First, did I understand you correctly?

Yes, this is more or less what I had in mind.

> Second, is the dedicated path where the charts should live, as I understood them?

Yes.

> Third, I am not sure what goes in the Reconcile and Delete.

E.g for `Reconcile`:

```go
func (a *actuator) Reconcile(
	ctx context.Context,
	cp *extensionsv1alpha1.ControlPlane,
	cluster *extensionscontroller.Cluster,
) (bool, error) {
	// Call Reconcile on the composed Actuator
	if _, err := a.Actuator.Reconcile(ctx, cp, cluster); err != nil {
		return false, err
	}

	// Get shoot later components chart values
	values, err = a.getShootLaterComponentsChartValues(ctx, cp, cluster)
	if err != nil {
		return false, err
	}

	// Render the shoot later components chart and create a managed resource
	if err := managedresources.RenderChartAndCreate(ctx, cp.Namespace, shootLaterComponentsChartResourceName, false, a.client, chartRenderer, a.shootLaterComponentsChart, values, a.imageVector, shootLaterComponentsNamespace, version, true, false); err != nil {
		return false, err
	}

	// Something similar to above for the namespace chart
}
```

You can take a look at the generic actuator implementation for how to get `a.client` properly injected, and how to build `chartRenderer` and `version`. `a.imageVector` is probably best passed via the constructor (together with the charts). The rest are constants. The most interesting part is building the values, but you should have already implemented this logic in your current PR as part of your custom `ValuesProvider`. You would now need to move it to your custom `Actuator`.

For `Delete`, you first delete your managed resources and then delegate to `a.Actuator.Delete`. Again you can take a look at the generic actuator implementation for how to do this properly.

**Comment by deitch** [comment]
OK, good.

Let's close this PR, but I will come back here when I have further questions, until I get the other PR truly ready.

Thanks @stoyanr

**Comment by stoyanr** [comment]
@deitch You are welcome!

**Comment by deitch** [comment]
@stoyanr still struggling with a few things.

First, creating the namespaces. I looked at creating a "namespaces" chart, and at just putting it in the `internal/shoot-later-components/values.yaml` as a list and having the actuator just create them. Both had challenges. 

* For a separate chart, I ran into issues with how to handle ordering. It isn't too bad when creating (doesn't hurt to apply a `Namespace` yaml twice), but it creates issues when deleting. I could remove it from the list of `Chart.Subcharts`, but it becomes messy.
* For the straight list, I wasn't sure how to get those. I would need to read the actual `values.yaml` somewhere, either in `valuesprovider` or `actuator`.

In both circumstances, do you have any idea how I should indicate "use this namespace for this chart"? I thought about putting it in `values.yaml` as part of the sub-charts values, but then I need the actuator (or valuesprovider) to extract that value and pass it on. I wasn't sure how to handle that either.

**Comment by deitch** [comment]
@stoyanr I am going to move the conversation over to the actual PR, so you can comment on the direction in the implementation.

**Pull request closed without merging**
