### PR TITLE
Remove alpine based envoy image

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
We will move to distroless envoy image once multi arch image for it is available.

/cc @ScheererJ 

**Release note**:

```other operator

```

### CODE REVIEW

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by ScheererJ — CHANGES_REQUESTED** [review]
Why do we switch from `envoy-alpine` to `envoy`? I would understand switching to `envoy-distroless`, but `envoy` is nearly twice in compressed size compared to `envoy-alpine`.

Do you have any idea when `envoy-distroless` will support `arm64` or if this is planned at all?

**Comment by acumino** [comment]
> Do you have any idea when `envoy-distroless` will support `arm64` or if this is planned at all?

By the next release which is planned on 15th Aug 2022. The PR to build mulit arch distroless envoy image is already merged https://github.com/envoyproxy/envoy/pull/21134

**Comment by ScheererJ** [comment]
> > Do you have any idea when `envoy-distroless` will support `arm64` or if this is planned at all?
> 
> By the next release which is planned on 15th Aug 2022. The PR to build mulit arch distroless envoy image is already merged [envoyproxy/envoy#21134](https://github.com/envoyproxy/envoy/pull/21134)

This would mean that we can have `envoy-distroless` when we switch to `envoy` >= v1.23.

What is the benefit of switching now from `envoy-alpine` to `envoy` and later to `envoy-distroless` compared to just switching to `envoy-distroless` once we move to v1.23? It feels like unnecessary effort, a higher network/memory footprint and a bigger attack surface.

**Comment by acumino** [comment]
> What is the benefit of switching now from `envoy-alpine` to `envoy` and later to `envoy-distroless` compared to just switching to `envoy-distroless` once we move to v1.23? It feels like unnecessary effort, a higher network/memory footprint and a bigger attack surface.

Multi arch image is required for arm64 arch shoots. There is no other motivation to switch to `envoy` from `envoy-alpine`. As of now, only envoy is multi arch image.

**Comment by ScheererJ** [comment]
> > What is the benefit of switching now from `envoy-alpine` to `envoy` and later to `envoy-distroless` compared to just switching to `envoy-distroless` once we move to v1.23? It feels like unnecessary effort, a higher network/memory footprint and a bigger attack surface.
> 
> Multi arch image is required for arm64 arch shoots. There is no other motivation to switch to `envoy` from `envoy-alpine`. As of now, only envoy is multi arch image.

Please create an issue for switching to `envoy-distroless` when possible so that we can keep track of this.

**Review by ScheererJ — APPROVED** [review]
Thanks for explaining your reasoning.
/lgtm

**Comment by plkokanov** [comment]
@acumino should we include this in v1.49?

**Comment by acumino** [comment]
> Please create an issue for switching to `envoy-distroless` when possible so that we can keep track of this.

Switching to `envoy-distroless` is tracked in this issue https://github.com/gardener/gardener/issues/6127.

**Pull request merged**
