### PR TITLE
Allow MCM to delete VolumeAttachments

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind bug

**What this PR does / why we need it**:
After https://github.com/gardener/machine-controller-manager/pull/839 MCM provider extensions need to delete VolumeAttachments. See the PR description for more details.

Steps to reproduce:
1. Create a Shoot
2. Create a PVC
3. Delete the Shoot
4. Make sure that MCM provider-aws fails to delete the Node with reason:
```
E1108 13:18:46.014810       1 machine_util.go:1199] (deleteNodeVolAttachments) Error deleting volume attachments for node "ip-10-250-18-49.eu-west-1.compute.internal", machine "shoot--foo--bar-worker-1-z1-dd4b9-rm9zm": volumeattachments.storage.k8s.io "csi-6d9353d0a5734f4c3b1c3643da399da1c91c0a2d6a570e36a88da54be9829b0d" is forbidden: User "system:serviceaccount:kube-system:machine-controller-manager" cannot delete resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
```

**Which issue(s) this PR fixes**:
See above

**Special notes for your reviewer**:
N/A

**Release note**:

```bugfix operator
machine-controller-manager RBAC in the Shoot cluster does now allow MCM to delete volumeattachments. MCM provider extensions vendoring machine-controller-manager >= v0.50.0 (ref https://github.com/gardener/machine-controller-manager/pull/839) need to delete volumeattachments.
```

### CODE REVIEW

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/approve

**Pull request merged**
