### PR TITLE
Removed duplicate word (inside)

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area documentation
/kind cleanup
/priority normal

**What this PR does / why we need it**:
It removes a redundant word and fixes the documentation to be more easy to read/understand.

**Which issue(s) this PR fixes**:
Fixes #
The PR does not fix a bug, but the documentation.

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @ScheererJ for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by timebertt — APPROVED** [review]
/ok-to-test
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm
/reviewed ok-to-test

**Comment by rfranzke** [comment]
CLA needs to be signed. 👀 
/author-action

**Pull request merged**
