### PR TITLE
[release-v1.5] Fix deletion case for extension predicates

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR fixes the deletion of shoots or their extension resources in the seed once shoots were in a `Failed` state.

**Special notes for your reviewer**:

**Release note**:

```improvement operator
An issue has been fixed which caused failed shoot clusters to not be deleted successfully after a retry had been triggered.
```

### CODE REVIEW

**Review by danielfoehrKn — APPROVED** [review]

**Comment by rfranzke** [comment]
Maybe I missed it, but why isn't it a 1:1 backport of #2435? This is a different commit now?

**Comment by danielfoehrKn** [comment]
@rfranzke I think this is  the "safer" version (only adding a predicate to make the deletion case working) [from there](https://github.com/gardener/gardener/pull/2435#issuecomment-641920158).
Though I am not sure, thinking about it, if it would not be better to backport the exact same commit.

**Comment by timuthy** [comment]
Well, that's exactly what we discussed [here](https://github.com/gardener/gardener/pull/2435#issuecomment-641920158) after the suggestion from @ialidzhikov and [your response](https://github.com/gardener/gardener/pull/2435#issuecomment-641971043).

**Comment by rfranzke** [comment]
I see, probably I missed this point, sorry. I'm fine with this PR if you think it makes more sense, but why can't we simply take the same fix that we did for the `master` branch?

**Review by rfranzke — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by timuthy** [comment]
@rfranzke I have no strong opinion but know it was confusing to apply a different fix as a back port because it looked differently. Now, I applied the exact same changes we had applied to the `master` branch.

**Comment by rfranzke** [comment]
Thanks Tim!

**Pull request merged**
