### PR TITLE
Add missing test suite for `plugin/pkg` and some general improvements

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Add missing test suite for `plugin/pkg`.

**Special notes for your reviewer**:
Introduced with https://github.com/gardener/gardener/pull/8234
/cc @rfranzke 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Thanks for cleaning this up! :)

/lgtm
/approve

BTW: How do you find the duplicate imports? Is there perhaps a linter that we could simply enable? See also #8462

**Comment by shafeeqes** [comment]
> BTW: How do you find the duplicate imports?

I just fixed those which were suggested by my IDE 😅 

> Is there perhaps a linter that we could simply enable?

We could check, yes.

**Comment by shafeeqes** [comment]
Here it is, https://github.com/gardener/gardener/pull/8503

**Pull request merged**
