### PR TITLE
Scrape logs from pods in the shoot kube-system which have the resources.gardener.cloud/managed-by:gardener label:value

### PR DESCRIPTION
**Pull request by vlvasilev**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
With this PR the logs of pods in the shoot's `kube-system` namespace which got the `resources.gardener.cloud/managed-by:gardener` `label:value` will be scraped from `Promtail` and stored in Loki. Thus, for example, the logs from `csi-driver-node` pods that have neither `gardener.cloud/role` nor `origin` labels will be scraped and stored, too. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Logs from pods managed by `garden-resource-manager` will be scraped and stored in the shoot's Loki.
```

### CODE REVIEW

**Comment by plkokanov** [comment]
Just a note that this will also add logs for: `network-problem-detector-*`, `cloud-node-manager`, ` calico-node-vertical-autoscaler`, `cilium`, `node-local-dns` pods. Will this be ok wrt load?

**Comment by vlvasilev** [comment]
> Just a note that this will also add logs for: `network-problem-detector-*`, `cloud-node-manager`, ` calico-node-vertical-autoscaler`, `cilium`, `node-local-dns` pods. Will this be ok wrt load?

No problem at all. Just a little bit of network cost but we need all logs for debugging purposes.

**Pull request merged**
