### PR TITLE
Add system-component label to calico-kube-controllers deployment

### PR DESCRIPTION
**Pull request by schrodit**
**What this PR does / why we need it**:
Add the gardener system-components label `garden.sapcloud.io/role: system-component` to the calico-kube-controllers deployment
**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Nice, thanks. Please also add it here: https://github.com/gardener/gardener/pull/1129/files#diff-d94b3dbcb86230702865c94d0741db59L410

**Comment by schrodit** [comment]
also added the label to the template labels

**Review by ialidzhikov — APPROVED** [review]
/approve

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
