### PR TITLE
Fix SANs of etcd client service cert

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind bug
/priority 1

**What this PR does / why we need it**:
This PR fixes a bug which caused a failure when initializing defragmentation for etcd in the `backup-restore` side-car (see https://github.com/gardener/etcd-backup-restore/issues/494).

Since Etcd-Druid `v0.9.0` the `advertise-client-urls` configuration has changed to the pod domain name(s) to support multi-node clusters, e.g. `etcd-main-0.etcd-main-peer.shoot--local--local.svc`.
However, the SANs of etcd's server certificate have not been adjusted to this change, i.e. to include a wildcard entry like `*.etcd-main-peer.shoot--local--local.svc`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Thanks for your input @ishan16696, @aaronfern and @abdasgupta.

**Release note**:

```bugfix operator
A bug has been fixed which prevented the etcd defragmentation from running properly. This fix will cause a restart of all etcd instances during the next maintenance time window.
```

### CODE REVIEW

**Review by aaronfern — APPROVED** [review]
Thanks for the PR @timuthy!

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Pull request merged**
