### PR TITLE
Add alert for not ready pods

### PR DESCRIPTION
**Pull request by mvladev**
Also filter for pods with `origin=gardener`

### CODE REVIEW

**Comment by rfranzke** [comment]
Add a better description please, when exactly will this alert be triggered? As far as I can understand we'll get alerts for any non-ready pod in the Shoot cluster (including customer/user pods), true?

**Comment by mvladev** [comment]
Those metrics are only limited to the `kube-system` namespace in the Shoot cluster - https://github.com/gardener/gardener/blob/06044cdfb92a258ac462d305916a011939ebb260/charts/seed-monitoring/charts/kube-state-metrics-shoot/templates/kube-state-metrics.yaml#L54

**Comment by rfranzke** [comment]
OK. Can we add a label filter? The Gardener labels all the pods it deploys into `kube-system` with `origin=gardener`, and we basically only care about them (we do not want to have alerts for customer pods deployed into `kube-system` that are not ready for whatever reason).

**Comment by mvladev** [comment]
@rfranzke done

**Review by rfranzke — APPROVED** [review]
Great, thanks!

**Pull request merged**
