### PR TITLE
Drop deprecated `imagePullProgressDeadline` field from the Shoot API

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
Drop deprecated `imagePullProgressDeadline` field from the Shoot API.
Follow-up of #9106 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — CHANGES_REQUESTED** [review]
Remove it from https://github.com/gardener/gardener/blob/f8a98afa335f16edab2d0cf6feeb9da0f2135348/example/90-shoot.yaml#L90 and https://github.com/gardener/gardener/blob/f8a98afa335f16edab2d0cf6feeb9da0f2135348/example/90-shoot.yaml#L253

**Comment by rfranzke** [comment]
> /hold until gardener v1.88 is released.

The https://github.com/gardener/gardener/tree/release-v1.88 branch already exists, so I guess we can continue with the PR and merge it into `master`?

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Comment by shafeeqes** [comment]
> > /hold until gardener v1.88 is released.
> 
> The https://github.com/gardener/gardener/tree/release-v1.88 branch already exists, so I guess we can continue with the PR and merge it into `master`?

Yes. I just put it on hold because I added a commit removing the TODO introduced with https://github.com/gardener/gardener/pull/9143, but since we did not merge it to master, we can go ahead with this one.

**Pull request merged**
