### PR TITLE
adjust shoot validation to support min-0 worker pools

### PR DESCRIPTION
**Pull request by elankath**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Adjust shoot validation to support minimum Zero Worker Pools, so such shoots are accepted. This is first step in supporting dynamic distribution of worker pools.

**Which issue(s) this PR fixes**:
Addresses Stage-1 of #7857 

**Special notes for your reviewer**:

**Release note**:

```other
Adjust shoot validation to support worker pools with Autoscaler Min specified as Zero. 
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Is this already supported by `cluster-autoscaler`, i.e., don't we need more changes (e.g., as explained in https://github.com/gardener/gardener/issues/7857#issuecomment-1721146719) before we really can allow this? Or does it already work today?

**Comment by elankath** [comment]
> Is this already supported by `cluster-autoscaler`, i.e., don't we need more changes (e.g., as explained in [#7857 (comment)](https://github.com/gardener/gardener/issues/7857#issuecomment-1721146719)) before we really can allow this? Or does it already work today?

CA already supports scale from zero for a node group today. With this change, we are attempting to support this even for the first node group (which currently needs min > 0). The other stages mentioned in the comment are for achieving dynamic node distribution in a node group as opposed to the computed static distribution today. But that is a far greater change, requires a design proposal, review and prototype and will not go in at the current time.

**Comment by rfranzke** [comment]
OK, thanks.
/approve
/cc @himanshu-kun @rishabh-11

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Comment by elankath** [comment]
unit tests, integration tests and manual testing complete and successful. Shoot with minimum zero worker triggers autoscaler scale-up for node with system components as can be seen below

```yaml
      workers:
      - machine:
          image:
            name: gardenlinux
            version: 934.10.0 
          type: m5.large
        maxSurge: 1
        maxUnavailable: 0
        maximum: 2
        minimum: 0
```
Autoscaler is deployed during shoot reconcile. Scale up is triggered by autoscaler. 
```
I0919 13:18:23.949577       1 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 18.73µs
I0919 13:18:33.950866       1 mcm_manager.go:699] Generating node template only using nodeTemplate from MachineClass shoot--local--i034796l-a-ash-shoot-z1-ca3ca: template resources-> cpu: 2,memory: 8Gi
W0919 13:18:33.951262       1 clusterstate.go:444] AcceptableRanges have not been populated yet. Skip checking
I0919 13:18:33.951905       1 klogx.go:87] Pod kube-system/metrics-server-f8556c48c-mp85r is unschedulable
I0919 13:18:33.951924       1 klogx.go:87] Pod kube-system/blackbox-exporter-7fbdd886dc-5qgwl is unschedulable
I0919 13:18:33.951930       1 klogx.go:87] Pod kube-system/calico-node-vertical-autoscaler-68fc8fb447-twt98 is unschedulable
I0919 13:18:33.951939       1 klogx.go:87] Pod kube-system/coredns-76bdbc4d85-xrnk4 is unschedulable
I0919 13:18:33.951946       1 klogx.go:87] Pod kube-system/blackbox-exporter-7fbdd886dc-4bvlr is unschedulable
I0919 13:18:33.951954       1 klogx.go:87] Pod kube-system/calico-typha-deploy-6b8c5f9747-9wzq4 is unschedulable
I0919 13:18:33.952105       1 klogx.go:87] Pod kube-system/coredns-76bdbc4d85-5snxs is unschedulable
I0919 13:18:33.952120       1 klogx.go:87] Pod kube-system/metrics-server-f8556c48c-272gr is unschedulable
I0919 13:18:33.952126       1 klogx.go:87] Pod kube-system/vpn-shoot-6d6bd68cfb-69jwc is unschedulable
I0919 13:18:33.952135       1 klogx.go:87] Pod kube-system/calico-typha-horizontal-autoscaler-7b8d6759cf-mfd86 is unschedulable
I0919 13:18:33.952142       1 klogx.go:87] Pod kube-system/calico-typha-vertical-autoscaler-657dfb847c-wcrjc is unschedulable
I0919 13:18:33.953312       1 waste.go:55] Expanding Node Group shoot--local--i034796l-a-ash-shoot-z1 would waste 72.50% CPU, 93.29% Memory, 82.89% Blended
I0919 13:18:33.953342       1 orchestrator.go:193] Best option to resize: shoot--local--i034796l-a-ash-shoot-z1
I0919 13:18:33.953356       1 orchestrator.go:197] Estimated 1 nodes needed in shoot--local--i034796l-a-ash-shoot-z1
I0919 13:18:33.953388       1 orchestrator.go:310] Final scale-up plan: [{shoot--local--i034796l-a-ash-shoot-z1 0->1 (max: 2)}]
I0919 13:18:33.953416       1 orchestrator.go:582] Scale-up: setting group shoot--local--i034796l-a-ash-shoot-z1 size to 1
I0919 13:18:43.973264       1 mcm_manager.go:699] Generating node template only using nodeTemplate from MachineClass shoot--local--i034796l-a-ash-shoot-z1-ca3ca: template resources-> cpu: 2,memory: 8Gi
```
Shoot reconcile succeeds
```
k get shoot -A                                                                                            git:min-zero-wp*
NAMESPACE      NAME         CLOUDPROFILE   PROVIDER   REGION      K8S VERSION   HIBERNATION   LAST OPERATION            STATUS    AGE
garden-local   i034796l-a   aws            aws        eu-west-1   1.27.4        Awake         Create Succeeded (100%)   healthy   63m
```
alll systems components deployed and running

```
gardenctl target --garden kind-extensions --project local --shoot i034796l-a
k get po -A
NAMESPACE     NAME                                                  READY   STATUS    RESTARTS   AGE
kube-system   apiserver-proxy-h92x7                                 2/2     Running   0          9m18s
kube-system   blackbox-exporter-7fbdd886dc-4bvlr                    1/1     Running   0          11m
kube-system   blackbox-exporter-7fbdd886dc-sgpcm                    1/1     Running   0          118s
kube-system   calico-node-rh46x                                     2/2     Running   0          9m18s
kube-system   calico-node-vertical-autoscaler-68fc8fb447-twt98      1/1     Running   0          10m
kube-system   calico-typha-deploy-5ccb95cbf4-wh82l                  1/1     Running   0          8m25s
kube-system   calico-typha-horizontal-autoscaler-7b8d6759cf-mfd86   1/1     Running   0          11m
kube-system   calico-typha-vertical-autoscaler-657dfb847c-wcrjc     1/1     Running   0          11m
kube-system   coredns-76bdbc4d85-5snxs                              1/1     Running   0          11m
kube-system   coredns-76bdbc4d85-xrnk4                              1/1     Running   0          11m
kube-system   csi-driver-node-mqtvp                                 3/3     Running   0          9m18s
kube-system   egress-filter-applier-6rdgs                           1/1     Running   0          9m18s
kube-system   kube-proxy-ash-shoot-v1.27.4-nxq2n                    2/2     Running   0          7m57s
kube-system   metrics-server-f8556c48c-272gr                        1/1     Running   0          11m
kube-system   metrics-server-f8556c48c-mp85r                        1/1     Running   0          11m
kube-system   network-problem-detector-host-hcgv8                   1/1     Running   0          9m18s
kube-system   network-problem-detector-pod-sf6mk                    1/1     Running   0          9m18s
kube-system   node-exporter-hnfjf                                   1/1     Running   0          2m57s
kube-system   node-local-dns-m785j                                  1/1     Running   0          9m18s
kube-system   node-problem-detector-52x8k                           1/1     Running   0          117s
kube-system   vpn-shoot-6d6bd68cfb-wtf2s                            1/1     Running   0          118s
```

**Pull request merged**
