### PR TITLE
Use hooks instead of build command for mcm-provider-local

### PR DESCRIPTION
**Pull request by rrhubenov**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Hooks can now be used to generate the needed patch file for imageVectorOverwrite.
This removes the need to call ko outside of skaffold.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by Kostov6 — COMMENTED** [review]
Thanks for the PR! Just a small nit: aren't local variables supposed to be lowercase and only env vars uppercase?

**Comment by rrhubenov** [comment]
> Thanks for the PR! Just a small nit: aren't local variables supposed to be lowercase and only env vars uppercase?

I've made a habit of naming all bash variables with full uppercase, but what you're saying does make sense and avoids some possible collisions with env vars. It's important for us to be consistent so I'll follow this naming convention, thanks!

**Review by oliver-goetz — COMMENTED** [review]
Thanks, I like solution with the hook 🚀 

You could remove the `$(KO)` dependencies from [Makefile](https://github.com/gardener/gardener/pull/9782/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) and [tools.mk](https://github.com/gardener/gardener/pull/9782/files#diff-5356a0e0b4bde62f01a4e49f3b51d5cf35997c75e095948e80aabc4b0574a330) too.
They have been introduced in #9782 for the build command.

**Review by rfranzke — COMMENTED** [review]
Nice!
/approve

**Pull request merged**
