### PR TITLE
[WIP] Change retention period to 14 days

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #653 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
The log retention period for ElasticSearch has been changed to `14d`.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
OK, but this does not fix #653. What about the Docker logs?

**Comment by marwinski** [comment]
No it does not fix #653 but the "other" problem where we keep the logs in elastic search.

**Comment by rfranzke** [comment]
@ialidzhikov will you work on the Docker part as part of this PR or will you open a separate one?

**Comment by ThormaehlenFred** [comment]
Docker Part would be even more important

**Comment by mvladev** [comment]
Docker log rotation (by age) would require an additional container to run in the cluster. Better to split it in a separate PR.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by marwinski** [comment]
Just clarified: it should generally be 14 days and not 30 days.

**Pull request merged**
