### PR TITLE
Update `github.com/gardener/etcd-druid` and `github.com/gardener/dependency-watchdog`

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
For extension using dependabot (see https://github.com/gardener/gardener/issues/6328), after vendoring of `gardener/gardener@v1.76` and removal of the replace directive for `k8s.io/client-go` , dependabot when trying to update (or check for updates) fails with:
```
Dependabot encountered the following error:

panic: internal error: can't find reason for requirement on k8s.io/client-go@v0.26.3
```

I suspect that it might be related to the exclude directives for `k8s.io/client-go` that we had to put in `gardener/dependency-watchdog` and `gardener/etcd-druid` when tackling https://github.com/gardener/gardener/issues/6807.
This PR vendors `gardener/dependency-watchdog` and `gardener/etcd-druid` versions that don't have the exclude directives anymore. I hope that this helps with the above dependabot issue.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6807

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Review by acumino — COMMENTED** [review]
/approve

**Pull request merged**
