### PR TITLE
Prepare next Dev Cycle v1.103.0-dev

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
Prepare next Dev Cycle v1.103.0-dev

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by plkokanov** [comment]
/hold
As it turned out that https://github.com/gardener/gardener/pull/10244 introduced a new field in`v1beta1.Shoot` which is also present with a different type  in `v1alpha1.Shoot`: 
https://github.com/gardener/gardener/blob/a9d81c0dc2c2ae5c9ca3e3919b5af8f1c218106f/pkg/apis/core/v1beta1/types_shoot.go#L826-L829
https://github.com/gardener/gardener/blob/a9d81c0dc2c2ae5c9ca3e3919b5af8f1c218106f/pkg/apis/operator/v1alpha1/types_garden.go#L344-L346

**Comment by plkokanov** [comment]
/unhold
(again) so that we don't get any extra PRs in the new release. Once the fix around https://github.com/gardener/gardener/pull/10244 is done, I will merge it in the release branch.

**Pull request merged**
