### PR TITLE
Fix TopologySpreadConstraints for existing clusters

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area high-availability
/kind bug regression

**What this PR does / why we need it**:
This PR fixes an issue with wrongly calculated `TopologySpreadConstraints` for existing shoot clusters. Earlier, when 'non-HA' or 'Node' shoots were scheduled to multi-zonal seeds, the pods could have scheduled to different zones. These cluster will have more than one zone listed in their control-plane namespace, so the webhook must not add a spread over zones. This can lead to un-schedulable pods.

For example:

**t0** - before Gardener `v1.60.0`:
```
etcd-0 -- zone-0
etcd-1 -- zone-0
etcd-2 -- zone-0
kube-apiserver -- zone-1
```

**t1** - with Gardener `v1.60.0`:

```
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - zone-0
            - zone1
...
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        name: etcd
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
  - labelSelector:
      matchLabels:
        name: etcd
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
```

```
etcd-0 -- zone-0
etcd-1 -- zone-0
etcd-2 -- # `Pending` - due to TopologySpreadConstraint, this pod is supposed to be scheduled to `zone-1`
kube-apiserver -- zone-1
```

**Special notes for your reviewer**:
/cc @rfranzke @ialidzhikov 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
Sorry for joining late, the changes make sense. Thank you!

**Pull request merged**
