### PR TITLE
Move content of `kuberbacproxy` into `vali` component

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind cleanup

**What this PR does / why we need it**:
`kube-rbac-proxy` and also `valitail` actually belong to the `vali` component since `kube-rbac-proxy` is actually a sidecar container in the `vali` `StatefulSet` and no separate/dedicated deployment. Back then (when `kuberbacproxy` component was introduced) the Vali deployment was still managed via Helm charts, but since recently this has been refactored to Golang (ref #8061), so we can finally move the code now.

**Special notes for your reviewer**:
/cc @shafeeqes @acumino

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Review by acumino — APPROVED** [review]
/lgtm

**Pull request merged**
