### PR TITLE
Updating CRD for DNSEntries to allow specifying routing policy

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
The dns-controller-manager will support weighted routing policy with the next release.
The `CustomResourceDefinition` for `dnsentries.dns.gardener.cloud` are still managed by the Gardenlet on the seeds, so it needs to be updated.

**Special notes for your reviewer**:
See PR https://github.com/gardener/external-dns-management/pull/270

**Release note**:

```other operator
Updating CRD for `DNSEntries` to allow specifying routing policy
```

### CODE REVIEW

**Comment by MartinWeindel** [comment]
@acumino Can you add this PR to v1.52 please?

**Comment by acumino** [comment]
> @acumino Can you add this PR to v1.52 please?

Done.
/milestone v1.52

**Pull request merged**
