### PR TITLE
Revert "The blackbox-exporter need not tolerate the NoSchedule/NoExecute taints"

### PR DESCRIPTION
**Pull request by istvanballok**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Reverts gardener/gardener#7002.

The blackbox-exporter should tolerate the NoSchedule/NoExecute taints.

Shoot owners can taint their nodes to control scheduling and execution of the workload. If the system components did not tolerate these taints, it can happen that they can not be scheduled at all.

Note that there is a `systemComponents.allow=true` configuration option on the worker pools which can be used to prevent scheduling system components to specific worker pools. (See #2480)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @rickardsjp @hendrikKahl @rfranzke 

**Release note**:

```other operator
The blackbox-exporter tolerates the NoSchedule/NoExecute taints
```

### CODE REVIEW

**Review by rickardsjp — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Let's go ahead with this for now until we have a better solution for explicitly tolerating the taints of the worker pools allowing system components to run.

/approve

**Pull request merged**
