### PR TITLE
Deflake kubeconfig rotation assertions in `ManagedSeed` e2e test

### LINKED ISSUE #6618: [Flaky Test] E2E Test: Gardenlet Kubeconfig Rotation Tests
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
https://github.com/gardener/gardener/blob/833e5f89b48079922d39ac43f60a3d853e802f43/test/e2e/managedseed/create_rotate_delete.go#L58

**CI link**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6570/pull-gardener-e2e-kind/1565631458054246400

**Reason for failure**:
```
 Expected success, but got an error:
      <*errors.errorString | 0xc000156750>: {
          s: "kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-09-02 09:46:40.027848693 +0000 UTC, newClientCertificateIssuedAt: 2022-09-02 09:46:40 +0000 UTC",
      }
      kubeconfig secret has not yet been renewed, timeBeforeRotation: 2022-09-02 09:46:40.027848693 +0000 UTC, newClientCertificateIssuedAt: 2022-09-02 09:46:40 +0000 UTC
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/managedseed/create_rotate_delete.go:398
```

**Anything else we need to know**:
Introduced with https://github.com/gardener/gardener/pull/6568

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
This PR deflakes the kubeconfig rotation assertions in `ManagedSeed` e2e test:

The `newClientCertificateIssuedAt` time does not contain any nanoseconds, however the `v.timeBeforeRotation` does.

This was leading to failing tests in case the new client certificate was issued at the very same second like the `v.timeBeforeRotation`, e.g. `timeBeforeRotation: 2022-09-02 20:12:24.058418988 +0000 UTC`, `newClientCertificateIssuedAt: 2022-09-02 20:12:24 +0000 UTC`. Hence, let's round the times down to the second.

As a consequence, we now also consider the rotation successful when `newClientCertificateIssuedAt >= timeBeforeRotation` (before it was only `>`).

**Which issue(s) this PR fixes**:
Fixes #6618

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by plkokanov** [comment]
Is there any chance that there could be a false positive if the `newClientCertificateIssuedAt` is issued at `2022-09-02 20:12:24 +0000 UTC` but `timeBeforeRotation` is almost 1 second after that - 022-09-02 20:12:24.999999999 +0000 UTC?

**Comment by rfranzke** [comment]
> Is there any chance that there could be a false positive if the `newClientCertificateIssuedAt` is issued at `2022-09-02 20:12:24 +0000 UTC` but `timeBeforeRotation` is almost 1 second after that - `2022-09-02 20:12:24.999999999 +0000 UTC`?

The `Truncate()` call would still round `2022-09-02 20:12:24.999999999 +0000 UTC` down to the nearest second, i.e. down to `2022-09-02 20:12:24 +0000 UTC`. Then it's equal to the `newClientCertificateIssuedAt` and the test should pass.

**Comment by plkokanov** [comment]
I think I didn't explain it too well. I was wondering if there's a possibility for the following scenario:
1. The kubeconfig certificate that is created before the rotation is triggered has a `NotBefore` timestamp of `2022-09-02 20:12:24 +0000 UTC`
2. The rotation gets triggered very soon after the kubeconfig certificate creation and `timeBeforeRotation` is set to `2022-09-02 20:12:24.999999999 +0000 UTC` (but could even be a value closer to `2022-09-02 20:12:24 +0000 UTC`
3. The kubeconfig certificate does not get regenerated for w/e reason.
4. `newClientCertificateIssuedAt` gets assigned to the `NotBefore` timestamp of `2022-09-02 20:12:24 +0000 UTC`
5. Then due to the `Truncate()` call, the test would pass (`newClientCertificateIssuedAt` will be equal to `timeBeforeRotation`), but we wouldn't want it to pass if the certificate didn't get regenerated.

**Comment by rfranzke** [comment]
Aha, quite interesting @plkokanov, good question! Theoretically this can happen, but practically there are quite some pod restarts involved in all rotations, so it's almost impossible (gardenlet redeployment, leader election, CSR creation and auto-approval will take more than `1s` in sum).

Even if we tried to address this, I wouldn't have a good idea. We could read the kubeconfig before triggering the rotation and comparing it to the one after the rotation, however then we only know that "something changed" but we cannot properly assert the timing expectations.

I suggest keeping it as is for now, that's very likely good enough :)

**Comment by plkokanov** [comment]
One more idea would be to wait for `1s` before triggering the rotation, but I guess you're right that the chance for the scenario I described to happen is slim.
/lgtm

**Pull request merged**
