### PR TITLE
Split kube-state-metrics charts into separate manifests

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
According to https://helm.sh/docs/topics/chart_best_practices/templates/.:
> - Each resource definition should be in its own template file.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by amshuman-kr — DISMISSED** [review]
LGTM

But I copied this from the [seed-monitoring](https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/templates/kube-state-metrics.yaml). So this needs to be fixed there as well.

**Comment by ialidzhikov** [comment]
> LGTM
> 
> But I copied this from the [seed-monitoring](https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/core/charts/kube-state-metrics-seed/templates/kube-state-metrics.yaml). So this needs to be fixed there as well.

Adapted also in `seed-monitoring` chart.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
