### PR TITLE
Use multi-arch image of `nginx`, `curl`, `alpine`, `busybox` and `k8s-example-web-app` for tests

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
This PR updates the test images (except the redis image) to use multi-arch image.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/backlog/issues/19

**Special notes for your reviewer**:
~~Depends on https://github.wdf.sap.corp/kubernetes/guestbook/pull/3~~

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Comment by ialidzhikov** [comment]
/hold

I don't see the redis image adapted - ref https://github.com/gardener/gardener/blob/c840b5b50d6cad209d2f34a28b771bd514b93a4d/test/framework/applications/guestbooktest.go#L137-L138

**Review by ialidzhikov — COMMENTED** [review]
There is some issue with the redis image.

Running the guestbook test the redis StatefulSet cannot get ready:
```
$ k -n gardener-e2e-nxgtl get po
NAME             READY   STATUS             RESTARTS   AGE
redis-master-0   0/1     CrashLoopBackOff   2          57s
```

**Comment by ialidzhikov** [comment]
I am also fine if you revert 70e87d96e9ed86bc6b7c0505fb55ec8a5ac50097 and follow-up with the redis image in another PR.

**Review by ialidzhikov — COMMENTED** [review]
As you reverted the redis commit, I assume you want to tackle it with another PR.

/hold cancel
/lgtm

**Pull request merged**
