### PR TITLE
Cleanup leftovers from the logging migration

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**How to categorize this PR?**

/area logging
/kind cleanup
/priority normal

**What this PR does / why we need it**:
Since the gardener was released with the new logging stack successfully, this code is not needed anymore.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@vpnachev @vlvasilev 

**Release note**:

```improvement operator
None
```

### CODE REVIEW

**Review by vpnachev — DISMISSED** [review]
/lgtm
/invite @vlvasilev

**Comment by vpnachev** [comment]
Please, resolve the conflicts.
/author-action

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
