### PR TITLE
Run tests with race detector enabled

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area testing
/kind enhancement

**What this PR does / why we need it**:
Changes test to run with `-race` flag.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/invite @timebertt 

@acumino Thanks, can you update the PR description with information what the motivation for this change is? Thanks!

**Review by timebertt — CHANGES_REQUESTED** [review]
The race the detector was consciously disabled for the integration tests.
We run the gardener-apiserver in process and the race detector permanently detected races in the apiserver library.
ref https://github.com/gardener/gardener/pull/4265

Hence, let's close this PR.

**Comment by acumino** [comment]
> The race the detector was consciously disabled for the integration tests. We run the gardener-apiserver in process and the race detector permanently detected races in the apiserver library. ref #4265
> 
> Hence, let's close this PR.

I tried running it multiple times It works fine. Maybe it could have been the case with old api versions. But if it's a regular issue I can close the PR.

**Comment by timebertt** [comment]
> I tried running it multiple times It works fine. Maybe it could have been the case with old api versions. But if it's a regular issue I can close the PR.

I assume, the flaky integration tests were mainly in concourse pipelines and not locally. I'm not sure if you can reproduce it locally.
I pretty much expect, that the flakes will occur again once the race detector is enabled again.

I'm open to try it out, but I expect, we will eventually need to revert it again.

**Comment by rfranzke** [comment]
Any suggestion how to proceed folks? :)
/remove needs/ok-to-test

**Comment by timebertt** [comment]
@acumino what was your motivation for enabling the race detector after all? Do you have a concrete race in mind that would only have been caught in integration tests?

**Comment by BeckerMax** [comment]
@acumino What is your motivation for running the race detector? Is it coming from  https://github.com/gardener/gardener/issues/2965 ?

In https://github.com/gardener/gardener/issues/2965#issuecomment-1014315219 the next step is described as:
> Next step is to run Gardener locally with the -race flag. Create a few Shoots and then look at the findings. Compile the findings of the race detector and see wether they are actionable. Post the findings into this issue.

Did you already do that? I found a few races back then. Can you confirm that you found no races when doing that?

**Comment by acumino** [comment]
> @acumino what was your motivation for enabling the race detector after all? Do you have a concrete race in mind that would only have been caught in integration tests?

For possible data races. I need to look for a scenario for Gardener.

**Comment by acumino** [comment]
> @acumino What is your motivation for running the race detector? Is it coming from #2965 ?
> 
> In [#2965 (comment)](https://github.com/gardener/gardener/issues/2965#issuecomment-1014315219) the next step is described as:
> 
> > Next step is to run Gardener locally with the -race flag. Create a few Shoots and then look at the findings. Compile the findings of the race detector and see wether they are actionable. Post the findings into this issue.
> 
> Did you already do that? I found a few races back then. Can you confirm that you found no races when doing that?

I am running the api-server from last week using `-race` flag, didn't hit any issue. Haven't done for others.
But as @timebertt explained it, we mostly hit issues in concourse pipelines, probably I should close this PR for now and reopen it later when I am assured with all. WDYT?

**Comment by timebertt** [comment]
Yes, sounds good. Let's close this PR for now.
/close

**Pull request closed without merging**
