### PR TITLE
Allow easy IPv6-only prow tests

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/area dev-productivity
/area quality
/area robustness
/area testing
/kind enhancement

**What this PR does / why we need it**:
Allow easy IPv6-only prow tests.

To ensure that support for IPv6-only clusters does not break it would be helpful if a CI test would check the functionality. This pull request should include the required changes to make this happen.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7051

**Special notes for your reviewer**:
This change is used to run special IPv6-only prow jobs, which are manually triggered. Until those jobs work this should not be merged.

/hold

**Release note**:

```other operator
e2e-kind tests can now run successfully in an IPv4-only environment
```

### CODE REVIEW

**Comment by ScheererJ** [comment]
IPv6 tests seem to succeed consistently.

/unhold

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Comment by ScheererJ** [comment]
https://github.com/gardener/ci-infra/pull/1623 will enable ipv6 tests on gardener/gardener.

**Review by oliver-goetz — APPROVED** [review]
awesome 🚀

**Pull request merged**
