### PR TITLE
fix labels on grafana netpol to match nginx-ingress

### LINKED ISSUE #4108: Grafana NetworkPolicy does not match Ingress controller in kube-system
**How to categorize this issue?**

/area monitoring
/area security
/kind bug
/priority 2

**What happened**:

The shoot's Grafana deploys a NetworkPolicy which does not match the Nginx Ingress Controller in `kube-system`. Hence it's not accessable:

The NetworkPolicy
```yaml
Name:         allow-grafana
Namespace:    shoot--garden--hm4vihjqoz
Created on:   2021-05-25 13:02:05 +0200 CEST
Labels:       <none>
Annotations:  gardener.cloud/description: Allows Ingress to the Grafana from the nginx controller and Egress to Prometheus.
Spec:
  PodSelector:     component=grafana,garden.sapcloud.io/role=monitoring
  Allowing ingress traffic:
    To Port: 3000/TCP
    From:
      NamespaceSelector: role=garden
      PodSelector: app=nginx-ingress,component=controller
    From:
      NamespaceSelector: role=kube-system
      PodSelector: app=nginx-ingress,component=controller
  Allowing egress traffic:
    To Port: 9090/TCP
    To:
      PodSelector: app=prometheus,garden.sapcloud.io/role=monitoring,role=monitoring
  Policy Types: Egress, Ingress 

```

The nginx-ingress controller:
```yaml
Name:                 nginx-ingress-controller-dbb74974-bdsl5
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Start Time:           Sat, 22 May 2021 16:49:17 +0200
Labels:               app.kubernetes.io/component=controller
                           app.kubernetes.io/instance=nginx-ingress
                           app.kubernetes.io/name=ingress-nginx
                           pod-template-hash=dbb74974e
```

as can be seen the labels don't match the label selectors

**What you expected to happen**:

Labels matching the selectors and traffic being allowed.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Gardener 1.23.1 to GCP and create a shoot. Then try to access the Grafana Dashbaord of that Shoot

**Environment**:

- Gardener version: 1.23.1
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: GCP

### PR DESCRIPTION
**Pull request by christianhuening**
**How to categorize this PR?**

/area monitoring
/kind bug

**What this PR does / why we need it**:

adjusts the labels for the allow-grafana network policy so that it matches the nginx controller deployed to kube-system

**Which issue(s) this PR fixes**:
Fixes #4108 

**Release note**:

```bugfix user
Fix the Shoot Grafana Network Policies to match the Nginx-Ingress controller in kube-system
```

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @christianhuening for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by rfranzke — COMMENTED** [review]
I'm confused, the only `nginx-ingress` controller deployed into `kube-system` is the one which can be enabled as addon via the `Shoot` spec, and this one has the correct labels for the network policy:

https://github.com/gardener/gardener/blob/09bc83682353f0b2f049a8a22d77a33fe8c2867b/charts/shoot-addons/charts/nginx-ingress/templates/controller-deployment.yaml#L34-L35

Can you elaborate what you are trying to fix here?

**Comment by christianhuening** [comment]
I am using `garden-setup` which deploys an nginx-ingress controller into the `kube-system` namespace in the Base/Seed cluster: https://github.com/gardener/garden-setup/blob/master/components/ingress-controller/deployment.yaml#L35 

And that nginx-ingress is what is being used to reach the grafana instance running in the shoot's namespace and that's also what has the wrong labels. 

Maybe I am totally on the wrong path here and the utter presence of that nginx-ingress is wrong?

**Comment by rfranzke** [comment]
In this case, shouldn't it rather be the labels of the nginx-ingress controller deployment in garden-setup which should be adapted?

**Comment by christianhuening** [comment]
I don't know :) https://kubernetes.slack.com/archives/CB57N0BFG/p1621956761076800

**Comment by rfranzke** [comment]
IMO, g/g is the wrong place, it does not know anything about g/garden-setup and should not be "coupled" to it.

**Comment by christianhuening** [comment]
but apparently the `app` and `component` labels are not the default for the nginx-ingress in garden-setup either 🤔 
Now I am confused since you wrote: 

> the only nginx-ingress controller deployed into kube-system is the one which can be enabled as addon via the Shoot spec

does this mean the nginx-ingress in the `kube-system` ns is not even "correct"? I already wondered why the grafana rule would expect an ingress in the `garden` ns

**Comment by rfranzke** [comment]
The network policy in g/g is to enable the managed seed/shooted seed case, i.e., when a shoot is registered as seed later on. Every seed needs an ingress controller, and if the shoot's `.spec.addons.nginxIngress.enabled=true` then the nginx-ingress controller deployed into the shoot's `kube-system` namespace will be used.

I don't know what g/garden-setup is doing with nginx, probably @Diaphteiros can clarify this.

**Comment by christianhuening** [comment]
ok, i've opened another MR for this in garden-setup: https://github.com/gardener/garden-setup/pull/502 
if you think that's more appropriate, then let's close this one here @Diaphteiros @rfranzke

**Comment by christianhuening** [comment]
closed since the garden-setup PR was merged

**Pull request closed without merging**
