### PR TITLE
[GEP-18] Adapt VPN-related secrets to new secrets manager

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
This PR adapts the VPN-related secrets (`vpn-shoot-client`, `vpn-seed-server`, `vpn-seed-server-tlsauth`, `vpn-shoot`, `vpn-seed`, `vpn-seed-tlsauth`) to the new secrets manager.

Note that the `kube-apiserver-http-proxy` secret (used only when `ReversedVPN` is enabled) will be handled as part of #5671.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3292#issuecomment-1036058890

/invite @timebertt @BeckerMax 
/invite @ScheererJ @DockToFuture 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
/label needs-rebase

Otherwise tide won't be able to merge because this PR still contains the old GitHub Workflow configuration

**Comment by stoyanr** [comment]
I tested this locally by reconciling an existing shoots. This is what happened to secrets (with `ReversedVPN` enabled):

**seed:**
vpn-seed-server-a6f44feb => vpn-seed-server-e53848dd
vpn-seed-server-tlsauth-52d3d443 => vpn-seed-server-tlsauth-a1d0aa00
vpn-shoot-client => vpn-shoot-client-4ea5b47b

**shoot:**
=> vpn-shoot-ca-ef6c6542
vpn-shoot-6a9cbc37 => vpn-shoot-client-bb5dd759
vpn-shoot-tlsauth-52d3d443 => vpn-shoot-tlsauth-e4fb6d26

The new secrets were correctly mounted and had the secrets manager labels (in the seed). The old secrets in the seed were not deleted, but I assume this is ok (they will be garbage collected).

**Comment by rfranzke** [comment]
Thanks again @stoyanr! Now also rebased to latest `master`.

**Comment by stoyanr** [comment]
With `ReversedVPN` disabled:

**shoot:**
=> vpn-shoot-ca-f6d5d3e8
vpn-shoot-66af1993 => vpn-shoot-server-b6080e0a
vpn-shoot-tlsauth-9e792d46 => vpn-shoot-tlsauth-68369fae

**seed:**
vpn-seed => vpn-seed-62e29204
vpn-seed-tlsauth => vpn-seed-tlsauth-de1d12a3
vpn-shoot => vpn-shoot-server-197c0a57

Again, the new secrets were correctly mounted and had the secrets manager labels (in the seed). This time the old secrets in the shoot were not deleted, but I assume this is ok (they will be garbage collected).

All in all, it seems to me this PR behaves as expected.

/lgtm

**Pull request merged**
