### PR TITLE
Upgrade logging stack versions

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
Upgrade logging stack versions

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@wyb1 

**Release note**:

```other user
Grafana is upgraded to version `7.5.4`
```
```other operator
Loki is upgraded to version `2.2.1` and Fluent-bit to `1.7.3`
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/invite @vlvasilev @wyb1 @istvanballok

**Comment by vpnachev** [comment]
Please, reflect in the release note that also fluent-bit and loki are upgraded.

**Review by wyb1 — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
