### PR TITLE
Deflake nodeagent health check integration test

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
Deflakes Node Agent Healthcheck controller tests.
We don't need to wait for the `node.Status.Addresses` to be empty, we are patching it to be empty. We just need to wait for it to be eventually re-populated.

Before:
```
❯ stress -p 32 ./test/integration/nodeagent/healthcheck/healthcheck.test --ginkgo.progress --ginkgo.show-node-events
...
30s: 39 runs so far, 4 failures (10.26%)
35s: 57 runs so far, 4 failures (7.02%)
```
After:
```
❯ stress -p 64 ./test/integration/nodeagent/healthcheck/healthcheck.test --ginkgo.progress --ginkgo.show-node-events
...
9m5s: 1829 runs so far, 0 failures
9m10s: 1851 runs so far, 0 failures
9m15s: 1868 runs so far, 0 failures
```

**Which issue(s) this PR fixes**:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8989/pull-gardener-integration/1739169070156091392
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8989/pull-gardener-integration/1739148641521635328
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8976/pull-gardener-integration/1738459207314706432
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8989/pull-gardener-integration/1738130025422524416
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8979/pull-gardener-integration/1738106648322379776

**Special notes for your reviewer**:
Introduced with https://github.com/gardener/gardener/pull/8786
/cc @majst01 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ary1992 — COMMENTED** [review]
Thanks for fixing :)
/lgtm

**Comment by shafeeqes** [comment]
The flake is too frequent. Let's get this in.
/approve

**Comment by oliver-goetz** [comment]
Thanks @shafeeqes 😄

**Pull request merged**
