### PR TITLE
Do not deny updates for old shoots with invalid domains

### PR DESCRIPTION
**Pull request by plkokanov**
**How to categorize this PR?**

/area ops-productivity security
/kind bug

**What this PR does / why we need it**:
#5974 introduced a validation for shoot default domains that is performed on every shoot operation. This caused an issue for very old shoot clusters that already specified an incorrect domain, but are currently used so deleting the shoot to create a new one with a valid domain is not an option.
This PR moves the check whether a shoot's domain is valid or not so that it is only performed in the following cases:
- On shoot creation, if the `shoot.spec.dns.domain` is set in the `shoot.yaml`.
- On shoot updates, if the `soot.spec.dns.domain` was not defined, and it is set with the current update operation
- On shoot updates, If a very old shoot had specified an invalid domain but was never assigned to a seed and is getting assigned to a seed for the first time with the current update operation.

/cc @rfranzke @ialidzhikov @acumino 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix user
Allow updates of old shoot clusters that were already created with an invalid default domain before the validation was introduced.
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
