### PR TITLE
Remove or adjust memory limits for shoot components

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/kind enhancements

**What this PR does / why we need it**:

Removes or adjusts memory limits according to measured usage for shoot control plane and system components to prevent OOMKills due to reaching the limits.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
* Based on #5627, should only be merged after that one is merged.

**Release note**:

```noteworthy operator
Memory limits of all shoot control plane or system components have been removed or adjusted according to measured usage to prevent OOMKills due to reaching the limits.
```

### CODE REVIEW

**Comment by stoyanr** [comment]
/hold until #5627 is merged and this PR is properly rebased.

/invite @rfranzke @vlerenc @ScheererJ @vlvasilev 

/cc @ScheererJ Please double check the networking components.
/cc @vlvasilev Please double check logging stack components (loki)

All reviewers, please only look at the second commit, the first commit is part of #5627. I am inviting for review now instead of  after this PR has been properly rebased to make sure we would be able to merge this PR and #5627 in time for the next gardener release.

**Review by ScheererJ — DISMISSED** [review]
Looks good for networking components
/lgtm

**Comment by vlerenc** [comment]
cc @istvanballok @wyb1 also for the Prometheus stack and whether memory limit removal is OK or a problem for Prometheus (is it a memory hog or properly dealing with memory)

@DockToFuture @ScheererJ Shouldn't apiserver-proxy-daemonset be free of limits as it's an essential component or is this the theoretical maximum from your PoV? And CoreDNS?

cc @marwinski in addition on VPN (seed/shoot).

Cluster-autoscaler has limits @himanshu-kun. Do we want that? To me, it's on the same level of MCM and other control plane controllers. We can survive when they are down for a few minutes, but not long. They are more important than the observability stacks and less important than API servers and ETCD.

**Comment by ScheererJ** [comment]
@vlerenc apiserver-proxy is not essential for all clusters as it is only useful if `kubernetes.default.svc.cluster.local` is used. There are a lot of components/stakeholders using rather kube-apiserver's internet routable DNS name instead. Still, it is likely essential for a number of clusters/components.
From my perspective, the (envoy) limit is far higher than we would want it to grow. Therefore, I would keep it. If you would rather like to err on the side of caution we can also remove it, but I guess having envoy consume more than a gigabyte of memory will cause other issues, e.g. pressure on the node.

**Comment by vlerenc** [comment]
> @vlerenc apiserver-proxy is not essential for all clusters as it is only useful if kubernetes.default.svc.cluster.local is used. There are a lot of components/stakeholders using rather kube-apiserver's internet routable DNS name instead. Still, it is likely essential for a number of clusters/components.

Yes, that's what I meant. For those, this daemonset is essential.

> From my perspective, the (envoy) limit is far higher than we would want it to grow. Therefore, I would keep it. If you would rather like to err on the side of caution we can also remove it, but I guess having envoy consume more than a gigabyte of memory will cause other issues, e.g. pressure on the node.

OK.

**Comment by himanshu-kun** [comment]
> Cluster-autoscaler has limits @himanshu-kun. Do we want that? To me, it's on the same level of MCM and other control plane controllers. We can survive when they are down for a few minutes, but not long. They are more important than the observability stacks and less important than API servers and ETCD.

Yes @vlerenc , removing the limits from CA would be beneficial.

**Comment by stoyanr** [comment]
@ScheererJ @himanshu-kun As a follow-up on the above discussion, I will remove the limits from `apiserver-proxy` and `cluster-autoscaler`. I will wait for some more feedback before changing the PR to avoid doing it multiple times.

Edit: Actually, when reading carefully the comments above it seems that the recommendation is to rather not remove the `apiserver-proxy` limit, esp. for envoy container, so I will not do it. Sorry for the misunderstanding.

**Review by wyb1 — COMMENTED** [review]
>cc @istvanballok @wyb1 also for the Prometheus stack and whether memory limit removal is OK or a problem for Prometheus (is it a memory hog or properly dealing with memory)

@vlerenc regarding the Prometheus stack, we (me and @istvanballok) believe that removing the CPU limits is not an issue and in some cases can even help. For example with large queries if Prometheus has access to more CPU it can process these queries faster and will need less memory. The memory usage for Prometheus is not bounded and could in theory keep growing depending on the number of targets, metrics, and queries being executed. This hasn't been an issue in the past so no reason to block this for Prometheus.

/lgtm

**Comment by stoyanr** [comment]
@vlerenc @rfranzke After merging #5627 (thanks!), I rebased this PR on master, removed the TODOs, adapted it to the latest feedback from component owners above, and tested the latest changes. From my perspective it's ready to be merged now as well.

/unhold

**Pull request merged**
