### PR TITLE
Incorrect Azure Profile

### PR DESCRIPTION
**Pull request by tuxgoose**
**What this PR does / why we need it**:
Example for azure is incorrect, profile should be az
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
No, see #1259

**Comment by tuxgoose** [comment]
https://github.com/gardener/gardener/issues/1348

**Comment by tuxgoose** [comment]
➜  gardener_shoot_nursery git:(master) ✗ kubectl apply -f azure-no.yaml
Error from server (Forbidden): error when creating "azure-no.yaml": shoots.garden.sapcloud.io "ev-1067" is forbidden: cloudprofile.garden.sapcloud.io "azure" not found

**Comment by tuxgoose** [comment]
kubectl get cloudprofiles
NAME           CLOUD PROVIDER   AGE
  1 apiVersion: garden.sapcloud.io/v1beta1
az             azure            511d

**Pull request closed without merging**
