### PR TITLE
[ci:component:github.com/gardener/dependency-watchdog:v0.7.2->v0.8.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
``` bugfix operator github.com/gardener/dependency-watchdog #41 @ashwani2k
A bug is fixed which allowed dependency-watchdog to not ignore scaling operations on deployment which are not enabled/deployed in a given cluster
A bug with uploading of a rotated dependency-watchdog-probe secrets is now fixed by refreshing the clients with updated secrets.
```

``` improvement operator github.com/gardener/dependency-watchdog #44 @ary1992
Switch default leader election resource lock for `dependency-watchdog` from `endpointsleases` to `leases`.
```

``` noteworthy operator github.com/gardener/dependency-watchdog #48 @himanshu-kun
A dependent's scaling up/down can be ignored by DWD now by adding the annotation `dependency-watchdog.gardener.cloud/ignore-scaling` to the deployment
```

``` improvement operator github.com/gardener/dependency-watchdog #57 @timuthy
Published docker images for Dependency-Watchdog are now multi-arch ready. They support `linux/amd64` and `linux/arm64`.
```

``` noteworthy operator github.com/gardener/dependency-watchdog #59 @dimityrmirchev
The `dependency-watchdog` now uses `distroless` instead of `alpine` as a base image.
```

``` improvement operator github.com/gardener/dependency-watchdog #62 @unmarshall
DWD client shall no longer use long running TCP connections when attempting to probe Kube ApiServer via internal endpoint.
```

### CODE REVIEW

**Review by unmarshall — APPROVED** [review]
/lgtm

**Review by ialidzhikov — COMMENTED** [review]
What about https://github.com/gardener/dependency-watchdog/pull/44 - can we now drop the RBAC rules for endpoints or are then still needed for something?

**Comment by unmarshall** [comment]
>What about https://github.com/gardener/dependency-watchdog/pull/44 - can we now drop the RBAC rules for endpoints or are then still needed for something?

We do not need this for `dependency-watchdog-probe` but it is still needed for `dependency-watchdog-endpoint` as it watches service endpoints. I see that [cluster role rules](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/dependencywatchdog/bootstrap.go#L334-L390) does not have endpoints resource listed for `RoleProbe` and that is correct. For `RoleEndpoint` it is required and what is currently configured should not be changed.

**Comment by ialidzhikov** [comment]
> We do not need this for `dependency-watchdog-probe` but it is still needed for `dependency-watchdog-endpoint` as it watches service endpoints. I see that [cluster role rules](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/dependencywatchdog/bootstrap.go#L334-L390) does not have endpoints resource listed for `RoleProbe` and that is correct. For `RoleEndpoint` it is required and what is currently configured should not be changed.

Can you prepare a follow-up PR to drop the endpoint rules that are no longer required?

**Comment by unmarshall** [comment]
>Can you prepare a follow-up PR to drop the endpoint rules that are no longer required?

Do you talk about [role-binding](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/dependencywatchdog/bootstrap.go#L168-L180)?
I also checked the existing role for dependency-watchdog-probe and you are right it has an additional role for endpoints which is no longer required. I will create a follow-up PR for this soon.

**Comment by ialidzhikov** [comment]
> Do you talk about [role-binding](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/dependencywatchdog/bootstrap.go#L168-L180)?
> I also checked the existing role for dependency-watchdog-probe and you are right it has an additional role for endpoints which is no longer required. I will create a follow-up PR for this soon.

Ok, please do so. Thanks!

**Comment by ialidzhikov** [comment]
I also believe that rules for leases ([ref](https://github.com/gardener/gardener/blob/3530a75708fc000b8b8256cf59c8f4652c8c1657/pkg/operation/botanist/component/dependencywatchdog/bootstrap.go#L348-L358) and [ref](https://github.com/gardener/gardener/blob/3530a75708fc000b8b8256cf59c8f4652c8c1657/pkg/operation/botanist/component/dependencywatchdog/bootstrap.go#L378-L388)) can be moved from the ClusterRoles to the Roles.

**Review by ialidzhikov — APPROVED** [review]
/lgtm
/approve

**Comment by ialidzhikov** [comment]
ping @unmarshall for https://github.com/gardener/gardener/pull/6436#issuecomment-1207681032 and https://github.com/gardener/gardener/pull/6436#issuecomment-1207684345. Are you looking into it?

**Comment by unmarshall** [comment]
Yes i will start working on the PR tomorrow.

**Pull request merged**
