### PR TITLE
Add missing files from gardener/gardener-extensions@v1.6.1

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
A few files were missing in #2141, sorry, this PR adds them.

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
/lgtm

**Review by ialidzhikov — DISMISSED** [review]
/lgtm

**Comment by rfranzke** [comment]
GitHub pages are currently down, see https://www.githubstatus.com/, hence, https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-pull-request-job/builds/55 failed (as `golangci-lint` cannot be installed). `make verify` succeeds locally, generation check passed in CI. --> Merging now.

**Review by vlerenc — COMMENTED** [review]
test review as non-tem member

**Pull request merged**
