### PR TITLE
Remove minAllowed.CPU from all components

### PR DESCRIPTION
**Pull request by voelzmo**
**How to categorize this PR?**

/area auto-scaling
/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Remove all `minAllowed.cpu` values from (H)VPA objects. Our tests didn't show harmful side effects of removing these and in many cases VPA did recommend values lower than the minAllowed. Therefore, we start saving resources if we switch to the VPA recommendation for CPU.

We don't do this for memory, as it is not compressible and would lead to more/faster OOMKills.

**Which issue(s) this PR fixes**:
Fixes #

**Release note**:

```other operator
Removed `minAllowed.cpu` from all VPA objects
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Just to close the loop/verify my understanding/document this: IIRC, the motivation for introducing `minAllowed` values for CPU back then was that we saw that VPA sometimes scaled down components too aggressively. For example, there were controllers which weren't quite active after initialization and only consumed very little CPU (~`1m` or so?), but they indeed need some CPUs at start-up time to start their watches, sync their caches, etc. This is no longer relevant now since we removed CPU limits everywhere, hence, even if VPA recommends only a few CPU, such controllers should be able to bootstrap successfully?

**Comment by voelzmo** [comment]
> even if VPA recommends only a few CPU, such controllers should be able to bootstrap successfully

This is an accurate summary of our findings and reasoning, yes. That also ties back to us not removing the `minAllowed` for memory.

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
