### PR TITLE
Ask contributor to open cherry-pick PR if needed

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area dev-productivity open-source
/kind enhancement

**What this PR does / why we need it**:
Add a note in the PR template and dev process that the contributor should open cherry-pick PRs for bug fixes and major improvements.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Thanks for the PR. The change in `docs/development/process.md` lgtm, but I would vote to drop the note in `.github/pull_request_template.md`. The PR template is already long and quite a lot of similar notes can be added there, for example:
- if you are contributing a new feature, make sure that you contribute docs about it as well
- make sure that the knowledge is distributed
- etc.

As I said, I would vote to keep the PR template short and simple without such notes. WDYT?

**Comment by vpnachev** [comment]
I added it to the pr template because I doubt everyone reads docs/development/process.md regularly.
But you are right, the template is overloaded even today and I am open to remove it.
Let's keep this PR open as it is now to collect more feedback from @gardener/gardener-maintainers.

**Comment by BeckerMax** [comment]
Thanks!

Can we specify what 
> still supported versions

means exactly? The latest three releases?

I think we should not maintain the same information in the PR template and the process.md. But we could link from the PR template to
- the process page
- the PR checklist
as a mandatory resource to follow. Then we would also have a link to the information @ialidzhikov  pointed out above, like adding documentation.

**Comment by vpnachev** [comment]
> Can we specify what
> 
> > still supported versions
> 
> means exactly? The latest three releases?

This is already done, see https://github.com/gardener/gardener/blame/master/docs/development/process.md#L30

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by rfranzke** [comment]
It seems there is no further feedback, shall we merge it?

**Comment by ialidzhikov** [comment]
> It seems there is no further feedback, shall we merge it?

I mean in the above communication, I and @BeckerMax clearly stated that we would like to keep the PR template clean and maintain similar notes only in `docs/development/process.md`. So no need from the change in `.github/pull_request_template.md` IMO.

**Comment by vpnachev** [comment]
I have removed the change in the PR template.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
