### PR TITLE
Make the linter fail on missing or wrong doc comments

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area quality, dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Makes the linter fail on missing or wrong doc comments and a few other common style errors, and fixes all such issues that already exist.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Making the linter fail on missing or wrong doc comments and a few other common style errors consists of enabling `revive` in the `golangci-lint` configuration and excluding certain `revive` errors that we are perhaps not interested in. 

I have fixed the following `revive` errors (as regexes that could be included in the `golangci-lint` configuration if desired):
```
- "exported: comment on exported (var|const|type|method|function) .* should be of the form "
- "exported: exported (var|const|type|method|function) .* should have comment or be unexported"
- receiver-naming # receiver name .* should be consistent with previous receiver name .* for .*
- error-strings # error strings should not be capitalized or end with punctuation or a newline
- increment-decrement # should replace .* \+= 1 with .*\+\+
- if-return # redundant if \.\.\.; err != nil check, just return error instead
```

I have disabled the following `revive` errors via the `golangci-lint` configuration:
```
- var-naming # ((var|const|struct field|func) .* should be .*
- dot-imports # should not use dot imports
- package-comments # package comment should be of the form
- unexported-return # exported func .* returns unexported type .*, which can be annoying to use
- indent-error-flow # if block ends with a return statement, so drop this else and outdent its block
- "exported: (type|func) name will be used as .* by other packages, and that stutters;"
```

See also https://github.com/gardener/gardener-extension-provider-gcp/pull/319.
  
**Release note**:

```other developer
Missing or wrong doc comments and a few other common style errors will now be reported by the linter.
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm
Thanks a lot!

**Comment by rfranzke** [comment]
@stoyanr Can you check the `verify` step?

```
Executing golangci-lint
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
extensions/pkg/controller/worker/machines.go:121:6: func name will be used as worker.WorkerPoolHash by other packages, and that stutters; consider calling this PoolHash (golint)
func WorkerPoolHash(pool extensionsv1alpha1.WorkerPool, cluster *extensionscontroller.Cluster, additionalData ...string) (string, error) {

```

**Comment by stoyanr** [comment]
> @stoyanr Can you check the verify step?

Hm, interesting, I didn't get these messages for whatever reason, I guess `golangci-lint` was recently updated but I haven't run `make install-requirements` meanwhile. Will take a look!

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
