### PR TITLE
Release responsible schedule for v1.88 until v1.93

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
Extends the docs with a proposal for the release responsible schedule for v1.88 until v1.93

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/cc @shafeeqes @ScheererJ @ary1992 @timuthy @oliver-goetz 

Can you please check if this works for you and `/lgtm` accordingly or propose a change?

**Comment by rfranzke** [comment]
/hold
until 20.11.2023

**Review by timuthy — COMMENTED** [review]
/lgtm

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Review by ary1992 — COMMENTED** [review]
/lgtm

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Pull request merged**
