### PR TITLE
Add script which checks the docforge manifest

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
Add script which checks if the manifest in the repo can be processed by the docforge.

The script will call `docforge` only if there is a PR with a change in `.docforge` or `docs` directories, otherwise the script will exit with status code 0.

This script will be added in the `pipeline_definition` as a PR step.

After 1-2weeks experimental period we can also make it as a required step.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@dimitar-kostadinov @Kostov6 

**Release note**:

```doc developer
A new `check-manifest` step will be triggered on each PR which will check if the manifest file can be processed by docforge
```

### CODE REVIEW

**Comment by rfranzke** [comment]
I have several questions:

1. Why do we need this? Do we expect such frequent changes on this manifest? I would rather say no, but I'm also far away from docforge.
2. If being integrated, this should probably be part of the `verify-extended` rule instead of a separate CI step.
3. Why is a GitHub token needed to perform a validation of this manifest?

**Comment by timebertt** [comment]
+1
To add to the list of questions:
- this script seems strongly related to docforge itself and not specific to any repo. Hence, why is it added here and not place somewhere else where it can be reused from? g/g seems like the wrong place to maintain such a script.

**Comment by Kristian-ZH** [comment]
>Why do we need this? Do we expect such frequent changes on this manifest? I would rather say no, but I'm also far away from docforge.

Frequent changes - No. But also it checks the documentation markdowns linked in the docforge. So if something is introduced (broken frontmatters in the document or idk...), we will catch the issue directly from the PR, not during the website update.
Also in the script is used `dry-run` flag which will allow us to see the file structure which will be builded from this manifest on each PR which changes the `/docs` directory.

>If being integrated, this should probably be part of the verify-extended rule instead of a separate CI step.

Okay

> Why is a GitHub token needed to perform a validation of this manifest?

Docforge needs a token for Github authentication/authorisation.


> this script seems strongly related to docforge itself and not specific to any repo. Hence, why is it added here and not place somewhere else where it can be reused from? g/g seems like the wrong place to maintain such a script.

Our Idea was to add such a script in each repo which has .docforge manifest (exposed in the website).
If we keep the script in a central place, e.g. gardener/docforge or gardener/website-generator  repo, I am not sure if it will be possible for the script to access the manifest or the docs structure directly from the PR as it currently does.

**Comment by rfranzke** [comment]
> > Why is a GitHub token needed to perform a validation of this manifest?
> 
> Docforge needs a token for Github authentication/authorisation.

This doesn't quite answer it. Why? What is it doing and how is GitHub involved?

> > this script seems strongly related to docforge itself and not specific to any repo. Hence, why is it added here and not place somewhere else where it can be reused from? g/g seems like the wrong place to maintain such a script.
> 
> Our Idea was to add such a script in each repo which has .docforge manifest (exposed in the website). If we keep the script in a central place, e.g. gardener/docforge or gardener/website-generator repo, I am not sure if it will be possible for the script to access the manifest or the docs structure directly from the PR as it currently does.

I think @timebertt's point was to not duplicate this script to each repository and it is a valid one since there are no repository-specifics parts in it. 
Please think about this and come back.

Additionally, I would like to run this script from my local machine when making changes to this manifest instead of filing the PR and waiting for the check to fail. This should work out-of-the-box when running `make verify-extended` and not require me to specify any environment variables.

**Comment by Kristian-ZH** [comment]
> This doesn't quite answer it. Why? What is it doing and how is GitHub involved?

Because git/github APIs use it for authorised read access to github. Without it it could also work (I am not sure), but the rate limit of the calls to github will be `60` instead of `5000` as now.
Currently docforge has no option to skip this flag.

**Comment by rfranzke** [comment]
What is `docforge` reading from GitHub such that it needs to authenticate itself? In my ideal imagination, we run something like `docforge validate -f <manifest>` which performs whatever validation to make sure that docforge can process/use this manifest.

**Comment by Kristian-ZH** [comment]
This script actually does not make calls for github as we have here `resourceMapping` but unfortunately the docforge is written to require this token (maybe because no one thought it would be used just for a such a small  one-repo manifest or IDK). 
We will think about some refactoring then and will try to remove this depencency.

About @timebertt's question. I can move this script to gardener/website-generator repo and then to vendor this repo from here and to call the script.

> In my ideal imagination, we run something like docforge validate -f <manifest> which performs whatever validation to make sure that docforge can process/use this manifest.

Docforge validates not only the manifest but the file documents linked in it. This means that it will catch also issues like this one: https://github.com/gardener/gardener/pull/4915. So it will catch each issue in the Markdown documents under /docs directory also.
The only difference makes `--dry-run` flag which means that it will not save the builded file tree on the disk, but will print it in the output.

Finally. I will close this PR for now. When we remove the GIT_TOKEN dependency from docforge I will open another PR which vendors g/website-generator and adds this check to verify-extended

**Comment by rfranzke** [comment]
OK, great, thank you @Kristian-ZH

**Comment by timebertt** [comment]
> I will open another PR which vendors g/website-generator and adds this check to verify-extended

Please don't vendor `g/website-generator` in `g/g`. Instead please add a target to https://github.com/gardener/gardener/blob/master/hack/tools.mk, which download the script / tool via `curl` or some other easy mechanism so that it can be executed later on in another make target.

**Pull request closed without merging**
