### PR TITLE
Fix Shoot reconcilation when APIServerSNI was not enbled at all

### LINKED ISSUE #2492: Cannot bootstrap Seed when all gardenlet feature gates are false
**How to categorize this issue?**

/kind bug
/kind regression
/priority normal

**What happened**:
Cannot bootstrap Seed when all gardenlet feature gates are false.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. `make start-gardenlet` on the master branch

2. Ensure that a Seed cannot be bootstrapped.
```
$ k describe seed seed-local-aws

    Message:               failed to delete manifests: 3 errors occurred: [could not delete object of kind "EnvoyFilter" "istio-ingress/proxy-protocol": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3", could not delete object of kind "Gateway" "istio-ingress/proxy-protocol": no matches for kind "Gateway" in version "networking.istio.io/v1beta1", could not delete object of kind "VirtualService" "istio-ingress/proxy-protocol-blackhole": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"]
    Reason:                BootstrappingFailed
    Status:                False
    Type:                  Bootstrapped
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/kind bug
/kind regression
/priority normal

**What this PR does / why we need it**:

It breaks reconcilation with 

```
time="2020-06-24T08:53:11+02:00" level=error msg="Failed to reconcile Shoot \"local-aws\": flow \"Shoot cluster reconciliation\" encountered task errors: [task \"Deploying Kubernetes API server\" failed: retry failed with context deadline exceeded, last error: failed to apply manifests: 1 error occurred: could not apply object of kind \"NetworkPolicy\" \"shoot--foo--local-aws/allow-to-shoot-apiserver\": context deadline exceeded task \"Deploying Kubernetes API server service SNI settings in the Seed cluster\" failed: retry failed with context deadline exceeded, last error: failed to delete manifests: 4 errors occurred: [could not delete object of kind \"DestinationRule\" \"shoot--foo--local-aws/kube-apiserver\": no matches for kind \"DestinationRule\" in version \"networking.istio.io/v1beta1\", could not delete object of kind \"EnvoyFilter\" \"istio-ingress/shoot--foo--local-aws\": no matches for kind \"EnvoyFilter\" in version \"networking.istio.io/v1alpha3\", could not delete object of kind \"Gateway\" \"shoot--foo--local-aws/kube-apiserver\": no matches for kind \"Gateway\" in version \"networking.istio.io/v1beta1\", could not delete object of kind \"VirtualService\" \"shoot--foo--local-aws/kube-apiserver\": no matches for kind \"VirtualService\" in version \"networking.istio.io/v1beta1\"]]" operation=reconcile shoot=garden-foo/local-aws
```

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/2492#issuecomment-648328778

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/invite @tim-ebert

**Comment by timebertt** [comment]
/assign
Currently testing...

**Comment by ialidzhikov** [comment]
I tested it, shoot reconcile now should be fine.

**Review by timebertt — APPROVED** [review]
> I tested it, shoot reconcile now should be fine.

Yep, I also verified that successfully.
Thanks for fixing @mvladev!
/lgtm

**Pull request merged**
