### PR TITLE
Support configuration of rate limits for external and additional DNSProviders

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Provider specific rate limits have been introduced with PR https://github.com/gardener/external-dns-management/pull/229.
This PR adds the optional configuration both in the default domain secrets for the default external `DNSProvider` and in the shoot manifest for custom primary and additional providers.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
Support configuration of rate limits for external and additional DNSProviders
```

### CODE REVIEW

**Review by rfranzke — CHANGES_REQUESTED** [review]
Sorry, but shouldn't we rather remove all these `DNSProvider` specifics from the Gardener API? With the introduction of the `UseDNSRecords` feature gate, everything related to `dns.gardener.cloud` should move to `gardener-extension-shoot-dns-service`. Can we rather focus on this instead of building new stuff on top? 👀

**Comment by MartinWeindel** [comment]
@rfranzke
This PR is only a minor enhancement of the existing implementation. I don't know why it should be connected to the migration of the `DNSProvider` to the `gardener-extension-shoot-dns-service`. First a concept for the migration needs be worked out and I'm not sure if there are resources on Gardener core side at the moment to help with all the complications it will need.

**Comment by mandelsoft** [comment]
@rfranzke 
Basically we have two dns solutions now. This was already a bad idea from the very beginning. But we should at least avoid to push this implementation detail to the shoot configuration. If we introduce a separate dns configuration for the shoot dns service (which is basically an integral part of our k8s solution. Even if it is theoretically optional, it is always active), we would force the shoot maintainer to configure two dns configurations, which must also be supported by the gui and the secret management.

This really shows that the initial approach of introducing two separate solutions is not only a bad idea, it is a very bad idea.

**Comment by rfranzke** [comment]
@MartinWeindel I understand, however, with this line of argumentation it will never be done and we will just continue to build things on top... While I'm happy to provide feedback/help in an issue, meeting, GEP PR, or whatever, I think the responsibility for driving this should be with the `gardener-extension-shoot-dns-service` maintainers (since it is mainly in their interest to eliminate this detour to `gardener/gardener` to  implement improvements like this rate limit stuff, for example).

@mandelsoft While the `.spec.dns` section should probably remain (though, trimmed down to the bare minimum required for `extensions.gardener.cloud/v1alpha1.DNSRecord`s only), all "advanced" configuration should move into the `providerConfig` for extensions (https://github.com/gardener/gardener/blob/ce9d741798eac2df8c470190ab483aa4c5818ebf/example/90-shoot.yaml#L281-L287), similar to how it's done for all other extensions. The `gardener-extension-shoot-dns-service` can look at both `.spec.dns` and this `providerConfig` to get the required configuration, i.e., there is probably no need to configure the same information twice.

> This really shows that the initial approach of introducing two separate solutions is not only a bad idea, it is a very bad idea.

I still don't agree and I don't see how it's related. Please, let's not reiterate on that.

**Comment by timuthy** [comment]
@MartinWeindel shall we close this PR and continue with the plan described in #5270?

**Pull request closed without merging**
