### PR TITLE
Fixed broken links 01.2022

### PR DESCRIPTION
**Pull request by n-boshnakov**
**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR fixes broken links in the Gardener website.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

### CODE REVIEW

**Review by rfranzke — CHANGES_REQUESTED** [review]
Changing this doesn't improve it since the `CloudBotanist` interface is gone from this file. It's probably better to refer to a commit in which this interface was still present.

**Comment by n-boshnakov** [comment]
> Changing this doesn't improve it since the `CloudBotanist` interface is gone from this file. It's probably better to refer to a commit in which this interface was still present.

The text surrounding the link explains that the interface is slated for removal. If that has already happened, wouldn't it be better to remove that part of the file along with the link?

**Comment by rfranzke** [comment]
The document is an enhancement proposal from some years back. I think it's valueable to keep them and also the initial proposal details.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
