### PR TITLE
Calculate the monthly average resource usage of the shoot control planes

### PR DESCRIPTION
**Pull request by istvanballok**
**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Calculate the monthly average resource usage of the shoot control planes.

The monthly average resource (CPU, Memory, Network and Disk) usage and requests
of the shoot control planes that are hosted in this seed are calculated by an
elaborate set of recording rules in the "cache" Prometheus.

The cadvisor metrics about the CPU, Memory and Network usage:

```
- container_cpu_usage_seconds_total
    
- container_memory_usage_bytes
- container_memory_working_set_bytes
    
- container_network_receive_bytes_total
- container_network_transmit_bytes_total
```

the kube-state-metrics metrics about the CPU, Memory and Disk requests:

```
- kube_pod_container_resource_requests (for both CPU and memory)
- kube_persistentvolumeclaim_resource_requests_storage_bytes
```

and the kubelet metrics about the Disk usage:

```
- kubelet_volume_stats_used_bytes
```

are aggregated

- by namespace
- by namespace and owner (and container, if applicable).

The average usage and time ratio of the cluster lifetime is also calculated for the current month. The metrics for the short lived clusters are retained to enable fast queries about all the clusters that existed during the month.

Dashboards are added to the Grafana in the garden namespace to show the resource usage of the shoot control planes (and the other garden components).

image
image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

Please see the commit messages for more details.

/cc @rickardsjp 

**Release note**:

```other operator
Calculate the monthly average resource usage of the shoot control planes
Add recording rules to the "cache" Prometheus in the garden namespace of the seed and dashboards to the Grafana in the garden namespace to calculate and show the resource usage of the shoot control planes
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/approve

**Comment by istvanballok** [comment]
/hold (we are about to add one more tiny feature)
thank you for the review, @rfranzke! :)

**Comment by istvanballok** [comment]
/unhold
/lgtm
@rickardsjp and I improved this PR and the commit messages.

**Review by rickardsjp — APPROVED** [review]
/lgtm

**Pull request merged**
