### PR TITLE
[ci:component:github.com/gardener/vpn2:0.10.0->0.11.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
``` noteworthy operator github.com/gardener/vpn2 #18 @ScheererJ
Updated base image of vpn seed server and vpn shoot client to alpine 3.16.2
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Comment by rfranzke** [comment]
@ScheererJ It seems there is a problem with this `vpn2` image:

```
2022-09-19T08:13:10.888236928Z stdout F 2022-09-19 08:13:10 library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
2022-09-19T08:13:10.891502284Z stdout F 2022-09-19 08:13:10 TCP/UDP: Preserving recently used remote address: [AF_INET]10.2.197.45:8132
2022-09-19T08:13:10.891556877Z stdout F 2022-09-19 08:13:10 Attempting to establish TCP connection with [AF_INET]10.2.197.45:8132 [nonblock]
2022-09-19T08:13:10.891582666Z stdout F 2022-09-19 08:13:10 TCP connection established with [AF_INET]10.2.197.45:8132
2022-09-19T08:13:12.897038324Z stdout F 2022-09-19 08:13:12 TCP_CLIENT link local: (not bound)
2022-09-19T08:13:12.897097381Z stdout F 2022-09-19 08:13:12 TCP_CLIENT link remote: [AF_INET]10.2.197.45:8132
2022-09-19T08:13:12.911037182Z stdout F 2022-09-19 08:13:12 [vpn-seed-server] Peer Connection Initiated with [AF_INET]10.2.197.45:8132
2022-09-19T08:13:12.912449701Z stdout F 2022-09-19 08:13:12 TUN/TAP device tun0 opened
2022-09-19T08:13:12.912514768Z stdout F 2022-09-19 08:13:12 /sbin/ip link set dev tun0 up mtu 1500
2022-09-19T08:13:12.915702058Z stdout F 2022-09-19 08:13:12 /sbin/ip link set dev tun0 up
2022-09-19T08:13:12.916995309Z stdout F 2022-09-19 08:13:12 /sbin/ip addr add dev tun0 192.168.123.2/24
2022-09-19T08:13:12.918390669Z stdout F 2022-09-19 08:13:12 Initialization Sequence Completed
2022-09-19T08:17:59.552278733Z stdout F 2022-09-19 08:17:59 Connection reset, restarting [0]
2022-09-19T08:17:59.552644782Z stdout F 2022-09-19 08:17:59 /sbin/ip addr del dev tun0 192.168.123.2/24
2022-09-19T08:17:59.644812274Z stdout F 2022-09-19 08:17:59 SIGTERM[soft,connection-reset] received, process exiting
2022-09-19T08:17:59.646837797Z stderr F /network-connection.sh: line 140: sleep: command not found
```

ref https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/6692/pull-gardener-e2e-kind/1571767536716877824/artifacts/shoot--local--e2e-unpriv/machine-shoot--local--e2e-unpriv-local-78c49-wltmz/pods/kube-system_vpn-shoot-57cfbbb989-fhtm6_40e8e22f-7da3-4576-8925-c2b03c3d084e/vpn-shoot/2.log

/approve cancel

**Comment by ScheererJ** [comment]
> @ScheererJ It seems there is a problem with this `vpn2` image:

Good catch by the test. My local tests finished the race differently, i.e. `vpn-seed-server` was available before `vpn-shoot`. It seems like the end-to-end test has different timings.

I will create a new hotfix release of the vpn2 images once the ci pipeline works again...

**Comment by ScheererJ** [comment]
Closed in favour of https://github.com/gardener/gardener/pull/6705.
/close

**Pull request closed without merging**
