### PR TITLE
Update go-apidiff to fix failing api-diff test

### LINKED ISSUE #6168: `pull-gardener-apidiff` fails silently
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:

`pull-gardener-apidiff` permanently fails silently with the following error:
```
2022/06/21 16:04:22 internal error: package "time" without types was imported from "github.com/gardener/gardener/pkg/utils/time"
```
e.g. https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6113/pull-gardener-apidiff/1539277751167488000#1:build-log.txt%3A23

Note however, that the job is not marked as failed, prow doesn't comment on the PR about the failure and hence nobody has noticed this problem.

**What you expected to happen**:

1. running `apidiff` should not fail with the mentioned error
2. if `apidiff` fails, the job should be marked as failed

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #6168

**Special notes for your reviewer**:
/cc @timebertt 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by timebertt — COMMENTED** [review]
Does this also fix the mentioned second problem?

> if apidiff fails, the job should be marked as failed

**Comment by acumino** [comment]
> Does this also fix the mentioned second problem?
> 
> > if apidiff fails, the job should be marked as failed

Locally I have tested it works fine.

**Comment by acumino** [comment]
>https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/6169/pull-gardener-apidiff/1539890998807629824/build-log.txt

@timebertt it works as expected.

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
