### PR TITLE
Remove `check-manifest` and docforge binary

### PR DESCRIPTION
**Pull request by Kostov6**
**How to categorize this PR?**

/area documentation
/kind cleanup

**What this PR does / why we need it**:
Removes `check-manifest` and docforge binary that are part of https://github.com/gardener/documentation/issues/431

**Special notes for your reviewer**:

**Release note**:

```breaking dependency
The `hack/check-docforge.sh` script is now removed. The repo based manifest are removed in favor of a centrally managed manifests. See https://github.com/gardener/documentation/issues/431. The manifests are now maintained centrally in https://github.com/gardener/documentation/tree/master/.docforge.
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by dimitar-kostadinov — COMMENTED** [review]
/lgtm

**Comment by oliver-goetz** [comment]
`check-docforge` make target needs to be removed from [unit-test prow jobs](https://github.com/gardener/ci-infra/blob/master/config/jobs/gardener/gardener-unit-tests.yaml) too.

**Pull request merged**
