### PR TITLE
Deploy istio-ingress in all namespace when ExposureClass is used

### LINKED ISSUE #6270: #5946 broke ability to update istio if ExposureClasses are used
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
Updating istio does no longer work after https://github.com/gardener/gardener/pull/5946 if `ExposureClasses` are used. There is only one managed resource for the istio resources, but the `istio-ingress` resources should be deployed into several namespaces, one for each exposure class.
Looking into the managed resource, you can see that only one set of `istio-ingress` resources are included. Hence, the other exposure class namespaces are not updated properly.

**What you expected to happen**:
If istio is updated this should be reflected in all exposure class namespaces.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an exposure class, e.g. by adding the following to your gardenlet config:

```
exposureClassHandlers:
  - name: internet-config
    loadBalancerService:
      annotations:
        loadbalancer/network: internet
  - name: internal-config
    loadBalancerService:
      annotations:
        loadbalancer/network: internal
    sni:
      ingress:
        namespace: ingress-internal
        labels:
          network: internal
```

2. Afterwards, simply update istio, e.g. by incrementing the minor version in `charts/images.yaml`.
3. Watch only one `istio-ingress` gateway being updated.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

/cc @dkistner @acumino @rfranzke

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
When chart is rendered it save values as Manifests:
```
// Manifest represents a manifest file, which has a name and some content.
type Manifest struct {
	Name    string
	Content string
	Head    *releaseutil.SimpleHead
}
```
So rendering the same charts for different namespaces gives different manifest `content` but the manifest `name` is the same as it is generated based on the file path from where the chart is imported.
https://github.com/gardener/gardener/blob/4e2d28f2af7093eb94819652a6f4709b5fbfaf06/pkg/operation/botanist/component/istio/ingress_gateway.go#L60-L84

Later all the rendered charts are appended to be deployed as one managed resource.
https://github.com/gardener/gardener/blob/4e2d28f2af7093eb94819652a6f4709b5fbfaf06/pkg/operation/botanist/component/istio/ingress_gateway.go#L82-L83. 

But to deploy charts as MR we use `AsSecretData` function to create secrets for managed resource from rendered charts.
https://github.com/gardener/gardener/blob/4e2d28f2af7093eb94819652a6f4709b5fbfaf06/pkg/operation/botanist/component/istio/istiod.go#L145

Here first chart are stored in map, because of this rendered charts with same name are deployed only once, causing the issue, istio-ingress deployment and other resource to get deployed only in one namespace.
https://github.com/gardener/gardener/blob/4e2d28f2af7093eb94819652a6f4709b5fbfaf06/pkg/chartrenderer/default.go#L203-L211

**Which issue(s) this PR fixes**:
Fixes #6270

**Special notes for your reviewer**:
/cc @rfranzke @ScheererJ 

**Release note**:

```bug operator
A bug causing istio-ingress to not get deployed in every namespace for each exposure class has been fixed.
```

### CODE REVIEW

**Comment by acumino** [comment]
@ScheererJ Can you please test if things work properly on your side?

**Review by ScheererJ — APPROVED** [review]
/lgtm

Seems to work in my scenario with multiple exposure classes.

**Review by rfranzke — COMMENTED** [review]
/approve

**Comment by rfranzke** [comment]
Please add a bugfix release note and cherry-pick this to `release-v1.50`?

**Pull request merged**
