### PR TITLE
Bump up logging images

### PR DESCRIPTION
**Pull request by nickytd**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
This PR bump ups following logging container images:
1. fluent-bit                     1.9.3 -> 1.9.6
2. fluent-bit-to-loki        v0.40.0 -> v0.41.0
3. loki-curator                v0.40.0 -> v0.41.0
4. kube-rbac-proxy       v0.12.0 -> v0.13.0
5. telegraf                       v0.40.0 -> v0.41.0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other  operator
The following images are updated:
- `fluent/fluent-bit`: `1.9.3` -> `1.9.6`
- `eu.gcr.io/gardener-project/gardener/fluent-bit-to-loki`: `v0.40.0` -> `v0.41.1`
- `eu.gcr.io/gardener-project/gardener/loki-curator`: `v0.40.0` -> `v0.41.0`
- `quay.io/brancz/kube-rbac-proxy`: `v0.12.0` -> `v0.13.0`
- `eu.gcr.io/gardener-project/gardener/telegraf-iptables`: `v0.40.0` -> `v0.41.0`
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@nickytd can you sign the CLA?

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Comment by nickytd** [comment]
/hold 
Fluent-Bit is currently in release of 1.9.7, will include it if released in time

**Comment by ialidzhikov** [comment]
Can we proceed with this PR? When fluent-bit@1.9.7 is out you can create a new PR for it? Why we have to hold all of the 4 other version bumps because of fluent-bit?

**Comment by nickytd** [comment]
Now we can. [1.9.6](https://fluentbit.io/announcements/) just has been released.

**Comment by ialidzhikov** [comment]
Ok, than can I ask you to
1. Sign the CLA
2. Unhold

**Comment by nickytd** [comment]
/unhold

CLA has been signed

**Comment by ialidzhikov** [comment]
> CLA has been signed

Maybe you also have to add your email (`git config user.email`) to your github account to allow the CLA check to figure that it is you.

**Review by ialidzhikov — APPROVED** [review]
/approve

**Pull request merged**
