### PR TITLE
Improve WebhookConstraintMatchers for namespaces

### LINKED ISSUE #5956: Mis-functioning of detection webhooks that are potentially problematic for maintenance activities
**How to categorize this issue?**
/area ops-productivity
/kind bug
/priority normal

**What happened**:
In a shoot although shoot owner already configed validatingwebhook to excluded `kube-system` namespace, in dashboard there's still some warning indicating 

```
Maintenance precondition check failed. It may not be safe to start maintenance for your cluster due to the following reason: ValidatingWebhookConfiguration "xxx" is problematic: webhook "xxx" with failurePolicy "Fail" and 3s timeout might prevent worker nodes from properly joining the shoot cluster
```

**What you expected to happen**:

this warning message should not show

**How to reproduce it (as minimally and precisely as possible)**:

1) create a shoot
2) apply a validatingwebhook with following content
```
failurePolicy: Fail
  matchPolicy: Exact
  name: xxx.sh
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
```
3) check the alerts in dashboard
image

**Anything else we need to know?**:
I assume it's related to https://github.com/gardener/gardener/issues/3122

**Environment**:

- Gardener version: 1.55.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
/area ops-productivity
/kind enhancement

Currently a webhook for namespaces that properly ignores the `kube-system` namespace is still considered as problematic webhook:

```yaml
  failurePolicy: Fail
  matchPolicy: Exact
  name: check-ignore-label.gatekeeper.sh
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
```

This PR adapts the constraints to do not consider any webhook for namespace as problematic but only webhooks for namespace selecting the `kube-system` namespace.

Fixes #5956

**Release note**:

```other operator
A corner case in gardenlet's logic about detection of misconfigured webhook is addressed. Previously a webhook for namespaces that properly ignores the kube-system namespace was wrongly considered as "problematic". 
```

### CODE REVIEW

**Review by plkokanov — COMMENTED** [review]
Thanks for the PR! Just one question. I saw in #5956 for the mentioned webhook that the `namespaceSelector` should be replaced by `objectSelector` since `Namespace`s are cluster scoped. But the, `namespaceSelector` when the object is a `Namespace`, behaves as an `objectSelector`. At least from what I understand from the k8s docs:

> The namespaceSelector decides whether to run the webhook on a request for a namespaced resource (or a Namespace object), based on whether the namespace's labels match the selector. If the object itself is a namespace, the matching is performed on object.metadata.labels. If the object is a cluster scoped resource other than a Namespace, namespaceSelector has no effect.

So shouldn't we also not add constraints due to webhooks that have a proper `namespaceSelector`?
I tested the PR with a webhook that has a proper `objectSelector` and a constraint was not added. But a constraint is still added, if the webhook uses a proper `namespaceSelector`.

**Comment by ialidzhikov** [comment]
Thanks for letting me know! I was not aware of this handling. I now added a new commit which should cover this case as well.

**Comment by rfranzke** [comment]
Nice!
/approve

**Comment by plkokanov** [comment]
Coolio! lgtm from my side as well.
/approve

**Pull request merged**
