### PR TITLE
[ci:component:github.com/gardener/autoscaler:v1.24.0->v1.25.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
``` other operator github.com/gardener/autoscaler #157 @rishabh-11
Synced the changes till v1.25.0 of upstream autoscaler
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
/milestone v1.62
/approve

/cc @himanshu-kun
Please check

**Comment by himanshu-kun** [comment]
@rishabh-11 would be raising a seperate PR for updating the charts ~this PR should be closed at that time.
why 1.62 milestone ? we will need a hotfix for this in 1.61 right?~
got the reason from @shafeeqes

**Comment by ialidzhikov** [comment]
/close
as cluster-autoscaler@1.25 should be used only for K8s >= 1.25 Shoots

**Pull request closed without merging**
