### PR TITLE
Upgrade gomega version

### PR DESCRIPTION
**Pull request by mvladev**
**How to categorize this PR?**

/area testing
/kind bug
/priority normal

**What this PR does / why we need it**:

This version includes the https://github.com/onsi/gomega/pull/402 fix that stops causing panics when `DeepDepriveEqual` fails to match.

**Which issue(s) this PR fixes**:

n/a 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by timuthy** [comment]
@mvladev can you please rebase, so that the verify step will succeed?

**Comment by mvladev** [comment]
@timuthy PR was rebased.

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
