### PR TITLE
Enable annotation validation for ingress-nginx 

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
Nginx ingress controller v1.9.0 added support for annotation validation. This will be enabled by default in future releases. As sanitization and validation of such annotations is relevant to security, let's enable it now.

https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.9.0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
`nginx-ingress-controller` now enables annotation validation.
```
```other dependency
`nginx-ingress-controller` image is updated to `v1.9.1`.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/cc @shafeeqes

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by shafeeqes** [comment]
Thanks!
/approve

**Comment by vpnachev** [comment]
v1.79 and v1.80 are on older nginx ingress version that does not have the flag `--enable-annotation-validation`, therefore it does not make sense to cherry-pick.

**Pull request merged**
