### PR TITLE
Add APIServer Network Policy to Blackbox Exporter

### LINKED ISSUE #5185: Blackbox Reporter missing network policy label to be able to communicate with APIServer when Cilium is used
**How to categorize this issue?**

/area monitoring
/area control-plane
/kind bug

**What happened**:
We have Cilium active as CNI in all our clusters. When enabling alerting via alertmanager we received a lot of alerts from shoots indicating they wouldn't be able to reach the api-server. It turned out that the blackbox-reporter pod was missing a network policy label to be allowed to talk to the apiserver 

**What you expected to happen**:
blackbox reporter correctly being labelled with network policy label

**How to reproduce it (as minimally and precisely as possible)**:
deploy shoot with reversevpn and enable alerting

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.33.1
- Kubernetes version (use `kubectl version`): 1.20.12
- Cloud provider or hardware configuration: GCP + AWS
- Others:

### PR DESCRIPTION
**Pull request by christianhuening**
This fixes https://github.com/gardener/gardener/issues/5185

**How to categorize this PR?**

/area monitoring
/kind bug

**What this PR does / why we need it**:
Adds the label to match the network policy for api server communication to the blackbox exporter
**Which issue(s) this PR fixes**:
Fixes #5185 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Adds network policy label to blackbox reporter so it can talk to the K8s APIServer
```

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @christianhuening for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by istvanballok** [comment]
Hi @christianhuening,

thank you for the PR. Generally, it looks good to me - I don't see any drawbacks of adding the `networking.gardener.cloud/to-apiserver: allowed` label to apply the respective network policy for the blackbox exporter. The [gardener.cloud--allow-to-apiserver](https://github.com/gardener/gardener/blob/77e09dd522d7bfb682cc35d0be437201b606061b/charts/shoot-core/components/charts/network-policies/templates/allow-to-api-server.yaml) network policy allows (any) egress traffic on the TCP port 443, which is just fine. (As far as I can tell, "any", because stricter restrictions to the api server were not implemented, hence the network policy is actually more permissive than its name suggests.)

On the other hand, I couldn't reproduce the issue https://github.com/gardener/gardener/issues/5185 and I'm curious to understand what I'm missing.
First I thought that maybe the blackbox exporter's egress is not "isolated" (doesn't have any matching network policies, see https://kubernetes.io/docs/concepts/services-networking/network-policies/#the-two-sorts-of-pod-isolation) but that wouldn't explain why it works for us.
Then I found that the [gardener.cloud--allow-to-public-networks](https://github.com/gardener/gardener/blob/77e09dd522d7bfb682cc35d0be437201b606061b/charts/shoot-core/components/charts/network-policies/templates/allow-to-public-networks.yaml) network policy matches based on the `networking.gardener.cloud/to-public-networks: allowed` label, which is already [present](https://github.com/gardener/gardener/blob/d03684381df819d8eb726f484458d709f3756e6e/charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml#L32) on the blackbox exporter, hence the blackbox exporter is already allowed to perform any egress traffic (any IP, no port restriction). Nevertheless, regarding the semantics of the network policies, it is fine with me to add the label `to-apiserver`, because indeed, the blackbox exporter is expected to talk to the api server.

This explains why we haven't faced the issue that you reported, and I'm curious to understand the difference to your setup.

**Comment by christianhuening** [comment]
@istvanballok hm as far as i can see the policies are only different in their port and that the public networks one allows for connecting to to a CIDR of `0.0.0.0` where the apiserver policy basically allows "any".

```yaml
Spec:
  PodSelector:     networking.gardener.cloud/to-public-networks=allowed
  Not affecting ingress traffic
  Allowing egress traffic:
    To Port: <any> (traffic allowed to all ports)
    To:
      IPBlock:
        CIDR: 0.0.0.0/0
        Except:
```

```yaml
Spec:
  PodSelector:     networking.gardener.cloud/to-apiserver=allowed
  Not affecting ingress traffic
  Allowing egress traffic:
    To Port: 443/TCP
    To: <any> (traffic not restricted by destination)
  Policy Types: Egress
```

Reading the docs i am wondering what exactly happens here, since the only difference is that the apiserver policy specifies a port and does not care about a destination whereas the public networks policy defines the quad zero notation. So I am assuming that maybe the CNI implemention is doing something weird here? We're using Calico on Seeds and Cilium on Shoots.

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by istvanballok** [comment]
@christianhuening thank you for your insights!
In one of our (few) shoots with cilium, the blackbox exporter can not reach the API server as you reported. Just for the record, you could update the title and the description of the issue #5185, because it seems that it is not related to the reversed VPN setup.

> We're using Calico on Seeds and Cilium on Shoots.

I'd expect that the blackbox exporter in the seed is working fine.

I found this cilium issue: https://github.com/cilium/cilium/issues/16147#issuecomment-843611823
I'm not sure if it is the same, it is reported to be fixed in an older version than what we use.
https://github.com/gardener/gardener-extension-networking-cilium/blob/v1.7.1/charts/images.yaml

Regarding this PR, it looks good to me, too. :) Thank you.

**Comment by christianhuening** [comment]
i updated the original issue ticket with some information pointing to cilium

**Comment by rfranzke** [comment]
@christianhuening Could you rebase, please?

**Comment by rfranzke** [comment]
@christianhuening Something is wrong with this PR (56 commits, +12,838 −3,877 changes). Please check again.

**Comment by christianhuening** [comment]
@rfranzke yeah `rebase` and I had an argument and it seems I lost ;-)

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
