### PR TITLE
Add new collector configs to node exporter

### PR DESCRIPTION
**Pull request by teturou8001**
Request to add a few more collectors to have information for /proc/stat and /proc/pressure/.

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

We would want to know the exact boot time of nodes and some internal pressure details, which will help to understand some situations like OOMKilled.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**: 

```other operator
Add new collector configs to node exporter
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @teturou8001 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by rfranzke — APPROVED** [review]
/lgtm

@wyb1 @istvanballok Any concerns/comments?
/second-opinion

**Review by wyb1 — APPROVED** [review]
Is this change intended for shoot owners or Gardener operators? In general for shoot owners it is better to deploy their own node exporter since we don't have a guarantee that the node exporter will always have the same configuration, version, etc.

The number of metrics that get exposed with these collectors is relatively small (no unbounded variables like volume mounts) so from that perspective /lgtm

**Comment by teturou8001** [comment]
> Is this change intended for shoot owners or Gardener operators? In general for shoot owners it is better to deploy their own node exporter since we don't have a guarantee that the node exporter will always have the same configuration, version, etc.
> 

Thanks for your suggestion, @wyb1. I think this would be required in both cases when the Gardner provided node exporter is used.

Thanks for your review and merge. I believe this will bring more insights when nodes were actually restarted.

**Pull request merged**
