### PR TITLE
Support single node seed clusters by adding seed-admission-controller deployment configuration

### PR DESCRIPTION
**Pull request by Gerrit91**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
In our test setup we can only have a single node seed cluster. However, the seed-admission-controller is deployed with strong pod anti affinity into the seed's garden namespace with a static amount of 3 replicas. This causes the managed resource for this controller to go unhealthy (the desired replica count cannot be reached).

We deal with this problem by manually adding a HPA that reduces the replica count to 1 after every seed reconciliation. This PR aims for a cleaner solution by offering a seed configuration setting to reduce the amount of replicas of the seed-admission-controller deployment.

**Which issue(s) this PR fixes**:
~

**Special notes for your reviewer**:
~

**Release note**:

```feature operator
Seed clusters with less than three nodes are now supported. In order for this to work, it is required to reduce the number of seed-admission-controller replicas through the new seed configuration for seed-admission-controller.
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @Gerrit91 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by rfranzke** [comment]
Hey @Gerrit91, thanks for the pro-active PR!
I'm wondering whether we can get rid of the "configuration complexity" for now by letting the gardenlet determine the number of replicas it should deploy for GSAC by checking the number of nodes available in the cluster?

**Comment by Gerrit91** [comment]
Hey @rfranzke,

thanks for taking a look so quickly. Well, your suggestion sounds much simpler plus it's easier for the operator. I will take a look and see if I am able to make it. :)

**Comment by Gerrit91** [comment]
Closing in favor of https://github.com/gardener/gardener/pull/3811.

**Pull request closed without merging**
