### PR TITLE
Promote gardenlet feature gate `ReversedVPN` to beta.

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind api-change

**What this PR does / why we need it**:
Promote gardenlet feature gate `ReversedVPN` to beta.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
Promote gardenlet feature gate `ReversedVPN` to beta.
```

### CODE REVIEW

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]

**Comment by dguendisch** [comment]
https://github.com/gardener/gardener/blob/dea47981d402dfc6e99390d7742e3dc507afcac1/docs/usage/reversed-vpn-tunnel.md#how-to-configure refers to the annotation `alpha.featuregates.shoot.gardener.cloud/reversed-vpn`, does that stay or is it then rather a `beta...` annotation?

**Comment by ScheererJ** [comment]
> https://github.com/gardener/gardener/blob/dea47981d402dfc6e99390d7742e3dc507afcac1/docs/usage/reversed-vpn-tunnel.md#how-to-configure refers to the annotation `alpha.featuregates.shoot.gardener.cloud/reversed-vpn`, does that stay or is it then rather a `beta...` annotation?

I would prefer to keep it as is to not break/change existing clusters.

**Review by dguendisch — COMMENTED** [review]
/lgtm

**Pull request merged**
