### PR TITLE
Support etcd scale down enhancement

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>

**How to categorize this PR?**

/area cost
/area storage
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PR enhances etcd crd and druid role to support https://github.com/gardener/etcd-druid/pull/59, which allows druid to take full snapshot of etcd data and delete the etcd data volume on etcd scale down during shoot hibernation.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This PR must go in before next druid release (which will contain https://github.com/gardener/etcd-druid/pull/59)

**Release note**:

```improvement operator
Add `volumeRetentionPolicy` field to etcd crd which will be respected by etcd-druid on etcd scale down and etcd deletion. Default policy is `Delete`.
```

### CODE REVIEW

**Comment by swapnilgm** [comment]
Thanks for the PR. But as you described it makes sense with next release of druid. So, maybe we can close it for now and reopen later. WDYS?

**Comment by rfranzke** [comment]
I'm also okay to merge it now as it doesn't change any behaviour and just prepares for the future changes. Though, I agree that it generally is better/easier followable for reviewers when the changes are submitted together.
Anyways, @shreyas-s-rao, do you want this PR to be merged now or rather closed and reopened later?

**Comment by shreyas-s-rao** [comment]
I'm ok with reopening this PR later, so that review becomes easy. Closing it for the timebeing.

**Pull request closed without merging**
