### PR TITLE
[ci:component:github.com/gardener/autoscaler:v1.28.0->v1.28.1]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
```other operator github.com/gardener/autoscaler #301 @rishabh-11
Add logging for mcm cloud-provider methods for better traceability 
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/kind enhancement
/cc @rishabh-11 
/approve

**Comment by rishabh-11** [comment]
Can we have a patch for this @rfranzke? This is needed for better debugging of CA issues on landscapes.

**Comment by rfranzke** [comment]
@rishabh-11 We can cherry-pick this and include it in the next hotfix release, though, we typically don't create hotfixes just to improve logs (unless there are very severe issues that make it indispensable). Hence, feel free to write `/cherry-pick <branch-name>` comments to this PR to get automatic cherry-pick PRs, but if following above strategy, it would only be released with the next minor version, or when there are other patches/bug fixes to be hotfixed.

**Pull request merged**
