### PR TITLE
Move shoot status label updates to GCM

### LINKED ISSUE #4286: Label shoot as progressing if gardenlet stopped sending heartbeats
**How to categorize this issue?**

/area robustness ops-productivity
/kind enhancement

**What would you like to be added**:

When gardener-controller-manager detects that a gardenlet stopped sending heartbeats, it sets all conditions for all shoots on the respective seed to unknown: https://github.com/gardener/gardener/blob/677eaffc5acdf78d19f09566945f4e91d97da742/pkg/controllermanager/controller/seed/seed_lifecycle_reconcile.go#L161
Though, the shoot status label (`shoot.gardener.cloud/status`) is not changed, so shoots stay marked as healthy, although health checks are not executed anymore.

So I propose to label shoots as `progressing` in `setShootStatusToUnknown`.
Labelling them as `unhealthy` is probably a bit too harsh. We could also introduce a new status value `unknown` which would be more fitting.

Looking for more opinions.

**Why is this needed**:

The label is used by different components to determine the overall health of a shoot (e.g. dashboard, managedseedset controller, tableconverter for `kubectl get shoot` (status column)), so it should also correctly reflect that the status is not actually known, if the gardenlet stopped sending heartbeats.

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Moves shoot status label (`shoot.gardener.cloud/status`) updates to GCM, as suggested in #4286. 

**Which issue(s) this PR fixes**:
Fixes #4286

**Special notes for your reviewer**:
* This PR doesn't change the treatment of conditions with `Unknown` status. This means that if there are such conditions, including under the circumstances described in #4286, the shoot will be marked as `unhealthy`. There is also #5041 that introduces a new `unknown` status label value. Initially this was part of this PR but has been intentionally separated to a different PR since it seems to need a separate discussion.

**Release note**:

```feature operator
Updating the shoot status label has been moved to GCM.
```

### CODE REVIEW

**Comment by holgerkoser** [comment]
It is unclear to me what this new status means. Should we consider the cluster healthy or unhealthy, if it goes from `healthy` to `unknown` or if it goes from `unhealthy` to `unknown`. I have the impression that we mix orthogonal status information into one property. Cluster is `Healthy` or `Unhealthy`. Create or Reconcile is `Progressing` or has finished `Successful` or `Failed`. And now the information: If the Shoot Status is `Fresh` or `Stale`. Cloud you provide a State Diagram for `shoot.gardener.cloud/status`?

**Comment by stoyanr** [comment]
> I have the impression that we mix orthogonal status information into one property.

Conditions could have status `Unknown` since a long time, and we can't really help it. So far we have avoided properly updating the label for shoots with `Unknown` conditions, but this has been at the expense of accuracy, and sometimes this has unwanted consequences as described in the original issue. We could perhaps pretend that shoots with `Unknown` conditions are something else than `unknown`, e.g. `progressing` or `unhealthy`, but in my opinion, and as also proposed by @timebertt, it would be great if we could correctly label them as `unknown` from now on.

> Cloud you provide a State Diagram for shoot.gardener.cloud/status

It's a diagram in which every status is reachable from every other one, basically a rectangle with all sides and diagonals drawn. Even if we draw it, I doubt it would be that useful.

**Comment by holgerkoser** [comment]
Thank you @stoyanr. I think we will support it in the dashboard like we already do it for [`progressing`](https://github.com/gardener/dashboard/blob/master/frontend/src/utils/index.js#L337-L339) clusters. 


However I still do not understand why someone is not interested if a cluster has been `healthy` or `unhealthy` before it entered the `unknown` state.

**Comment by stoyanr** [comment]
> However I still do not understand why someone is not interested if a cluster has been healthy or unhealthy before it entered the unknown state.

@timebertt @holgerkoser I am not really sure how to answer here but I wouldn't like to make this discussion a stopper for this PR (as it also addresses a different issue that's a bit more urgent). Therefore, I would propose to move the introduction of the `unknown` status label (and its ranking as "worst of all" or "slightly better than unhealthy") to a different PR, and continue the discussion, and subsequent changes if needed, there.

In this way, only the actual move of the logic from `gardenlet` to GCM will remain in this PR. Conditions with `Unknown` status will lead to the shoot being labeled as `unhealthy` (this is how it's implemented currently), which is I believe good enough for now. Any objections?

**Comment by stoyanr** [comment]
I did as proposed above, so this PR no longer introduces a new status label value. This has been moved to #5041. Let's continue the discussion about it there.

**Comment by stoyanr** [comment]
@timebertt I rebased this on master after #5013 got merged and removed `Draft` so it's now ready for review.

**Review by timebertt — APPROVED** [review]
Thank you, looks great!
/lgtm

**Review by rfranzke — APPROVED** [review]
/lgtm
Very nice!

**Pull request merged**
