### PR TITLE
Remove GA-ed `DisableDNSProviderManagement` feature gate

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
The `DisableDNSProviderManagement` feature gate is locked to default and no-op since v1.52. I believe we can clean it up now.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/5270

**Release note**:

```other operator
The GA-ed `DisableDNSProviderManagement` feature gate is now removed.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/hold
until 1.59 is released

/cc @MartinWeindel

**Review by MartinWeindel — APPROVED** [review]
Thanks

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Comment by rfranzke** [comment]
Opened #6959 instead.

**Pull request closed without merging**
