### PR TITLE
feat: add WatchBuilder to extension controller

### PR DESCRIPTION
**Pull request by domdom82**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:

The [extension lib for controllers](https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/extension/controller.go) currently does not support adding `Watches` for generic extensions. We do support them e.g. for the [infra extension](https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/infrastructure/controller.go#L47) via the `WatchBuilder`.

This PR adds the same capability for generic extensions and should allow them to watch other resources if needed.

**Release note**:

```feature developer
The extension library now supports adding watches via `WatchBuilder` for other resources in the generic extension controller.
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Comment by domdom82** [comment]
@plkokanov ping for approval

**Review by plkokanov — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
