### PR TITLE
Add graphics to document GRM projected service account tokens

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

The images themselves are hosted in [this dedicated Github issue](https://github.com/gardener/gardener/issues/5158).

Reason:

> Some images can become very large (a couple of MB).
A lot of automation pulls the whole Gardener repository to checkout some helm charts etc. Hence, we do not want to
dramatically increase the repository size by adding pictures.
By letting Github "host" those images, we get a publicly reachable URL that we can use in documentation.

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
Thanks for spending some time on drawing these things up! Well done!

While I like the images, I don't like the approach of hosting them in a GitHub issue. This is non-intuitive and feels weird to me.

> A lot of automation pulls the whole Gardener repository to checkout some helm charts etc.

Well, this is a smell anyways and should rather be tackled by e.g. following up on #4123, but it should not influence how we maintain the project artefacts. 

So, I'd vote for adding them as regular images to repository structure.

**Comment by danielfoehrKn** [comment]
> So, I'd vote for adding them as regular images to repository structure.

Okay, I'll also try to compress the images a bit to reduce the size.

**Comment by danielfoehrKn** [comment]
Also moved the images for the concept section into a dedicated directory `images` to adhere to the same layout as other sections.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
