### PR TITLE
upgrade gardener-resource-manager to v0.13.1

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area quality
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Upgrade gardener-resource-manager to v0.13.0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/invite @gardener/hvpa-controller-maintainers 
While revendoring I got API type changes from hvpa in, can you please check?

**Release note**:

``` improvement operator github.com/gardener/gardener-resource-manager #65 @tim-ebert
Fixed a bug, that caused the deletion of Services to be blocked.
```

``` improvement operator github.com/gardener/gardener-resource-manager #63 @tim-ebert
Fixed a bug, that caused the deletion of RBAC resources to be blocked.
```

``` improvement operator github.com/gardener/gardener-resource-manager #57 @timuthy
A forceful reconciliation for managed resources can now be triggered by the annotation `gardener.cloud/operation: reconcile`.
```

``` improvement operator github.com/gardener/gardener-resource-manager #57 @timuthy
The Gardener-Resource-Manager does now try to recover unhealthy managed resources (condition `ResourcesHealthy`) by reconciling the resource.
```

``` improvement operator github.com/gardener/gardener-resource-manager #54 @tim-ebert
`gardener-resource-manager` now properly removes its finalizer from secrets, that are not referenced by a `ManagedResource` anymore.
```

``` noteworthy operator github.com/gardener/gardener-resource-manager #54 @tim-ebert
Please ensure, that `gardener-resource-manager` has the required permissions to also update secrets now.
```

``` improvement operator github.com/gardener/gardener-resource-manager #51 @tim-ebert
A bug has been fixed, which could lead to a situation, where a `ManagedResource` is falsely indicating a "Ready" state for a short period of time.
```

``` improvement operator github.com/gardener/gardener-resource-manager #50 @tim-ebert
The `ManagedResource` CRD features a new field `.spec.deletePersistentVolumeClaims`. If set to `true`, gardener-resource-manager will delete PVCs belonging to managed StatefulSets, when they are deleted.
```

``` improvement operator github.com/gardener/gardener-resource-manager #49 @tim-ebert
`gardener-resource-manager` now also injects labels specified in `.spec.injectLabels` into the `.spec.volumeClaimTemplates` of new StatefulSets.
```

``` improvement operator github.com/gardener/gardener-resource-manager #48 @tim-ebert
`gardener-resource-manager` now deletes resources with `DeletePropagationForeground` to cascade the deletion to their dependents (e.g. to clean up `Job`s created by a `CronJob`).
```

``` improvement user github.com/gardener/gardener-resource-manager #46 @mvladev
All resources managed by `resource-manager` now have `resource-manager.gardener.cloud/description` annotation with `DO NOT EDIT` warning.
```

``` improvement operator github.com/gardener/gardener-resource-manager #45 @tim-ebert
The logs of `gardener-resource-manager` have been reworked to contain less unnecessary error entries.
```

``` improvement operator github.com/gardener/gardener-resource-manager #44 @tim-ebert
`gardener-resource-manager` now keeps the status of managed objects to prevent overwriting the status of CRs that don't have a `status` subresource.
```

``` improvement operator github.com/gardener/gardener-resource-manager #44 @tim-ebert
`gardener-resource-manager` now keeps the replicas and/or resource requirements of Deployments and StatefulSets if they are scaled horizontally and/or vertically by an HPA or HVPA respectively.
```

``` improvement operator github.com/gardener/gardener-resource-manager #43 @tim-ebert
The `ResourcesApplied` condition of `ManagedResource`s now includes all errors, that occurred while applying/deleting managed objects if there were any.
```

``` improvement operator github.com/gardener/gardener-resource-manager #42 @tim-ebert
A bug has been fixed, which made `gardener-resource-manager` fail to apply all new objects, if there were conflicting changes on those objects, instead of retrying the update request.
```

``` improvement operator github.com/gardener/gardener-resource-manager #41 @tim-ebert
`gardener-resource-manager` now adds finalizers to Secrets referenced in `ManagedResource`s to prevent Secrets from being deleted accidentally.
```

``` improvement operator github.com/gardener/gardener-resource-manager #40 @tim-ebert
`gardener-resource-manager` now makes use of a caching client for talking to the targeted API server, which reduces its network traffic.
```

``` improvement operator github.com/gardener/gardener-resource-manager #37 @ialidzhikov
`gardener-resource-manager` handling for Jobs is now improved.
```

``` improvement operator github.com/gardener/gardener-resource-manager #35 @mvladev
Service merge now handles headless `ClusterIP` services and `ExternalName` services. `.spec.healthCheckNodePort` is only set if the service is of type `LoadBalancer` with  `.spec.externalTrafficPolicy: Local`
```

``` improvement operator github.com/gardener/gardener-resource-manager $276bf6d3fbc265e3dc4a32286a6cc0fdf3dd8280
A bug has been fixed, that caused new Services to get assigned a different ClusterIP than specified.
```

### CODE REVIEW

**Comment by timebertt** [comment]
Do I need to copy over the release notes from the CI upgrade PR or is this done automatically?

**Comment by rfranzke** [comment]
I've added them for you.. :)

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Review by ggaurav10 — DISMISSED** [review]

**Comment by timebertt** [comment]
/hold
I found a bug in grm

**Comment by timebertt** [comment]
Ref https://github.com/gardener/gardener-resource-manager/issues/67

**Comment by timebertt** [comment]
/title Upgrade gardener-resource-manager to v0.13.1
/unhold

Updated the PR to grm@v0.13.1 containing the bug fix.
Tested it again and validated that the fix works now.

**Review by rfranzke — DISMISSED** [review]

**Review by ggaurav10 — DISMISSED** [review]

**Comment by timebertt** [comment]
CI Build fails, but should be unrelated to this PR.
Seems like we have some flaky tests: https://concourse.ci.gardener.cloud/builds/312222#L5ef14d25:182
https://github.com/gardener/gardener/blob/31fcde1257e711ff5db79f639c0f215a037a2983/pkg/healthz/periodic_test.go#L87-L98
@rfranzke Can you take a look at it?

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
