### PR TITLE
Deploy `GardenerAccess` component in shoot deletion flow

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:
Deploy `GardenerAccess` component in shoot deletion flow and optimize task dependencies.

**Special notes for your reviewer**:
/invite @timuthy @ialidzhikov 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Generally looks good to me. I only have the following question for my understanding - what was the impact of not deploying the GardenerAccess in the Shoot deletion flow and not having the GardenerAccess component deployed before the `Initializing connection to Shoot` steps?

**Comment by rfranzke** [comment]
@ialidzhikov In case the reconciliation flow failed to generate the gardener access secrets (for whatever reason) and the shoot is being deleted afterwards it might hang forever since the relevant secrets are missing. Without them, gardenlet is not able to talk to the shoot's API server.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

Thanks for explaining!

**Pull request merged**
