### PR TITLE
Remove calculation of resource allocations for prometheus

### PR DESCRIPTION
**Pull request by ggaurav10**
**What this PR does / why we need it**:
Remove calculation of resource allocations for prometheus since VPA is already deployed for it.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]

**Review by wyb1 — COMMENTED** [review]
Can we remove the template entirely or do other components still rely on this?

**Comment by ggaurav10** [comment]
> Can we remove the template entirely or do other components still rely on this?

EleasticSearch still relies on this. Is it safe to introduce VPA for that too? There might be some downtime when VPA applies scaling.

**Comment by wyb1** [comment]
I'm not sure about elasticsearch. Regardless, we can unlink the _resources.tpl file from all dirs in `seed-monitoring` since it is no longer used. Other than that /lgtm
Thanks for getting this @ggaurav10 
Edit: I guess you can't remove _resources.tpl since it is still being used by elasticsearch.

**Review by wyb1 — APPROVED** [review]

**Comment by rfranzke** [comment]
cc @ialidzhikov

**Comment by ialidzhikov** [comment]
> cc @ialidzhikov

We can open an issue about it. We need to test it and see how it behaves as the issues we had in the past with elasticsearch were mostly scaling, resource requests/limits related.

**Pull request merged**
