### PR TITLE
replace k8s/utils/slices with std impl

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area open-source quality
/kind cleanup

**What this PR does / why we need it**:
Less dependencies to external packages.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
The tests error with:
```
pkg/utils/imagevector/imagevector.go:22:2: package slices is not in GOROOT (/usr/local/go/src/slices)
```
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/8369/pull-gardener-e2e-kind/1692450290982195200#1:build-log.txt%3A185

**Comment by oliver-goetz** [comment]
Unfortunately, the [krte](https://github.com/kubernetes/test-infra/tree/master/images/krte) images do not have a variant for Go 1.21.0 yet. Only for [Go 1.21rc2](https://github.com/kubernetes/test-infra/blob/bd6cac2691cb8f0033ad2bf1dcf667aed1b1da58/images/kubekins-e2e/variants.yaml#L11).
Thus, e2e-tests with Go 1.21 will fail now.

**Comment by oliver-goetz** [comment]
We have our own `krte` with Go 1.21 now. Let's see if it works 🤞 

/retest

**Comment by oliver-goetz** [comment]
next try 🤞 
/retest

**Review by shafeeqes — APPROVED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
