### PR TITLE
tools: drop yaml2json dependency in favour of yq

### PR DESCRIPTION
**Pull request by dnaeon**
**How to categorize this PR?**

/area quality
/kind cleanup

**What this PR does / why we need it**:

Currently there are two different YAML processors being used as part of the tools - `yq` and `yaml2json`.  

This PR drops `yaml2json` in favour of `yq`.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by dnaeon** [comment]
Please hold this one for now. Code was based on [yq](https://github.com/kislyuk/yq) and not [Go's yq](https://github.com/mikefarah/yq) version. Will fix that shortly.

**Comment by dnaeon** [comment]
Should be fixed now.

**Review by ialidzhikov — COMMENTED** [review]
Thanks!

/lgtm

**Comment by dnaeon** [comment]
`/retest`

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
