### PR TITLE
Dump container logs of e2e tests

### PR DESCRIPTION
**Pull request by timebertt**
**How to categorize this PR?**

/area testing developer-productivity
/kind enhancement

**What this PR does / why we need it**:

Dumps all container logs of the kind cluster in e2e tests to improve the debugging experience for failing e2e tests.
Prow picks them up and uploads them to GCS. You can view them by clicking on `Artifacts` and navigating through the file hierarchy.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6016

**Special notes for your reviewer**:

In draft, until I have verified that this works in a test run.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by timebertt** [comment]
Awesome, this works like a charm! 🥳 
You can find the logs from the test run in the artifacts directory: https://gcsweb.gardener.cloud/gcs/gardener-prow/pr-logs/pull/gardener_gardener/6089/pull-gardener-e2e-kind/1534900817759309824/artifacts/

**Comment by oliver-goetz** [comment]
/retest
flaky e2e test, but this time the test offers logs from kind cluster:
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6089/pull-gardener-e2e-kind/1534911068743143424

**Comment by rfranzke** [comment]
While this is a great improvement, it doesn't yet help with cases where `make gardener-up` is failing (e.g. https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6099/pull-gardener-e2e-kind/1539609788265009152).
Do you have an idea how we can always dump the kind logs? Perhaps we need a wrapping script with a trap similar to the one introduced in this PR?

**Comment by timebertt** [comment]
True, I've already added it to https://github.com/gardener/gardener/issues/6016.
My ideas would be
- move the trap to the prowjob definition
- move the [core steps of the prowjob](https://github.com/gardener/ci-infra/blob/d240abc887e88a87a4f4d9e1a312d44f679ce074/config/jobs/gardener/gardener-e2e-kind.yaml#L32-L38) into a script in g/g which also contains the trap (should be called something like `hack/ci-e2e-kind.sh`)

One could even argue, that the trap was added in the wrong place after all because `hack/test-e2e-local.sh` doesn't know anything about the kind cluster (strictly speaking).
It should be in the same place as the `make kind-up` call.

I tend towards option 2 because of less duplication.

**Pull request merged**
