### PR TITLE
Slow down HPA down-scale to once in 24 hours

### PR DESCRIPTION
**Pull request by amshuman-kr**
**What this PR does / why we need it**: As a follow up for [PR#389](https://github.com/gardener/gardener/pull/389), using HPA for kube-apiserver can cause HPA to thrash kube-apiserver replicas in some cases.

For example, if the HPA specifies desired CPU utilisation as 60% and the actual utilisation is around 40%, then a slight change in utilisation can cause the HPA to thrash between replicas 2 and 3.

Since scaling down of kube-apiserver can be disruptive to work-loads, this PR increases the downscale-delay to 24h.

**Release note**:
```noteworthy operator
The horizontal pod autoscaler downscale delay for shooted Seed clusters has been increased to `24h`.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
This would change the value for all Shoots. Maybe we should only set it that way for shooted Seeds?

**Comment by rfranzke** [comment]
Or, even better: As of your recent analysis, what about making this configurable per Shoot? It seems to be too strict if Gardener would hard-code this as the workloads deployed to clusters might differ. WDYT?

**Comment by amshuman-kr** [comment]
Agreed about making it configurable per shoot. Are you proposing a change to Shoot spec?

**Comment by rfranzke** [comment]
Yes, we already have the [`.spec.kubernetes.kubeControllerManager`](https://github.com/gardener/gardener/blob/master/example/90-shoot-aws.yaml#L62) section.

What about

```yaml
...
spec:
  ...
  kubernetes:
    kubeControllerManager:
      featureGates:
        SomeKubernetesFeature: true
      horizontalPodAutoscaling:
        cpuInitializationPeriod: 5m0s 
        downscaleStabilization: 5m0s
        initialReadinessDelay: 30s
        syncPeriod: 15s
        tolerance: 0.1
```

**Comment by amshuman-kr** [comment]
+1 Makes sense.

These parameters are version specific. For example, cpuInitializationPeriod, downscaleStabilization, initialReadinessDelay are in 1.12 whereas downscaleDelay and upscaleDelay seem to be in 1.11.

This this part of  the shoot spec is free-flow, right?

**Comment by rfranzke** [comment]
> These parameters are version specific. For example, cpuInitializationPeriod, downscaleStabilization, initialReadinessDelay are in 1.12 whereas downscaleDelay and upscaleDelay seem to be in 1.11.

The same applies to [some of the OIDC parameters](https://github.com/gardener/gardener/blob/master/example/90-shoot-aws.yaml#L38-L51). We have to validate properly which flags may be used in which version. Right now please do only implement the {1.11,1.10,1.9} flags. We will implement the new ones when doing the Kubernetes 1.12 integration.

> This this part of the shoot spec is free-flow, right?

What do you mean by that?

**Comment by amshuman-kr** [comment]
>> This this part of the shoot spec is free-flow, right?

> What do you mean by that?

What I meant was pretty much what you said earlier about OIDC parameters and validating explicitly. So, all good :-)

**Comment by vlerenc** [comment]
We seem to have a problem here, introduced with the large release this week, that we need to mitigate fast. I would rather **not extend our API in a hurry**. Haste is a bad advisor, that's why I would like to move into the direction where we had less issues and that was before introduction of HPA. If we can smoothen it's behaviour, that would be therefore very welcome.

**Comment by amshuman-kr** [comment]
@vlerenc I agree with your point about gaining control via smaller and more frequent releases. 

But as @rfranzke mentioned, these flags are statically passed to the kube-controller-manager and not dynamically configurable via HPA. And as I mentioned in the mail thread, tweaking tolerance would put limits on the desired values specifiable in the HPA. Since these values are really work-load driven, it becomes hard/impossible to specify good default without the possibility for customers to change it.

But coming back to fixing the problem here, might it be a good idea to take a 2 step approach?

1. Slow the scaledown delay to 24h for all clusters (shoots and seeds). This can address the immediate problem. But this might enhance costs for the time being because scaling down of other workloads using HPA also would slow down (both in seeds and shoots). I think this might acceptable trade-off.

2. Make this configurable in the Shoot spec. This can be a longer term approach which we can take our time and include in a later (even perhaps next?) release.

**Comment by mvladev** [comment]
Changing those values only for the kube API server makes no sense even if it's only for Seeds which are Shoots. In the future we might rely on different components to use HPA and this will affect them. End users might also be affected (not SAP clusters).

Is the CPU the only bottleneck?

**Comment by amshuman-kr** [comment]
Cross posting from the mail-thread.

* The default value of 0.1 for --horizontal-pod-autoscaler-tolerance means that only a spike (either way) of ~6% CPU usage can trigger a scale up or down. With the base level at 60%, we have a lot more buffer than just 6%.
  * For 60%, we can afford tolerance to be 0.2 (tolerance till ~75%) or even 0.3 (tolerance till ~85%).
  * For 75% desired CPU utilization, 0.1 means tolerance till ~83%, 0.2 means tolerance till ~93%).
  * For 85% desired CPU utilization, 0.1 means tolerance till ~94%
  * I think 60% with 0.2 or even 0.3 is suitable. It would trigger a scaling decision only for larger spikes from the desired baseline. 75% with 0.2. might be cutting it too close?
  * But coredns is using 80% threashold, and tolerance or 0.2 would certainly be cutting it close.
  * So a tolerance of 0.2 would be problematic even just for seed clusters.
* The down-scaling interval of 15m is still too short. Especially, because of the low threshold for spikes. Making it 24h certainly makes sense.
* We need to mitigate the side effects during scale down. Requests, connections dropped etc.
* CPU utilization is not a reliable parameter, neither is memory. Response time or requests-per-second might be more reliable metric. But this is beta and would require custom metrics -> https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics

**Comment by rfranzke** [comment]
We decided to set the downscale delay to `24h` for shooted Seeds and keep the `15m` for normal Shoots. Long-term we will think about making it configurable per Shoot as proposed above.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
