### PR TITLE
Fix nil pointer panic

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
An issue causing panic in the health check for extension is fixed.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
An issue causing panic in the health check for extension, when the health check result is empty, is fixed.
```

### CODE REVIEW

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Comment by rfranzke** [comment]
Cherry-pick needed?

**Pull request merged**
