### PR TITLE
[operator] Introduce `gardensystem/virtual` Golang component

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
This PR introduces the Golang component for the `gardensystem/virtual` resources also residing in https://github.com/gardener/gardener/tree/master/charts/gardener/controlplane/charts/application/templates.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7016

**Special notes for your reviewer**:
/cc @oliver-goetz @ScheererJ @timuthy 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
so many roles... 😅
good PR 🚀 
/lgtm

**Review by ScheererJ — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
