### PR TITLE
Renew bootstrap token only once a day

### PR DESCRIPTION
**Pull request by vpnachev**
**How to categorize this PR?**

/area ops-productivity
/kind bug
/priority normal

**What this PR does / why we need it**:
Avoid to regenerate the bootstrap token on each reconciliation by re-using already existing token with the same name. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
A bug that was renewing the bootstrap token secret on each reconciliation has been fixed.
```

### CODE REVIEW

**Review by danielfoehrKn — COMMENTED** [review]
In addition to the changes proposed, I think (& tested) that the computation of the tokenId is not stable. 

> utils.ComputeSHA256Hex([]byte(time.Now().Format("2006-01-02")))[:6]

Computing this can yield a different result every x hours. We are taking the six characters of the SHA that is computed from a unique timestamp with the same format. 
Only because the time format is identical does not mean necessarily that the hex starts with the same characters?

Is there a reason why we would want the TokenID NOT to be stable for each Shoot? 
In my point of view, we can just take the first six characters of the SHA of the Shoot name as a fixed token ID.

**Comment by rfranzke** [comment]
@vpnachev thanks for the PR!

@danielfoehrKn we want to have a whole new token once per day, that's why it is implemented this way.

Also, I cannot really follow what you write.  Shouldn't `time.Now().Format("2006-01-02")` always lead to the same result during the 24h of a day, e.g. 2020-12-18? Then we compute the SHA out of it (again, same result for the same string, or?), and then we take the first 6 characters (again, same result).

If this is true I would still prefer a minimal fix only for now and rather invest time into removal of all the bootstrap token management from g/g and rather use the tokens from MCM.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by prashanth26 — APPROVED** [review]
Thanks for this fix. 

/lgtm

**Review by timuthy — APPROVED** [review]

**Comment by vpnachev** [comment]
I just double checked with 
```golang
package main

import (
	"fmt"
	"time"

	"github.com/gardener/gardener/pkg/utils"
)

func main() {
	hour := time.Hour
	date := time.Now().UTC()
	for i := 0; i < 48; i++ {
		hex := utils.ComputeSHA256Hex([]byte(date.Format("2006-01-02")))[:6]
		fmt.Printf("Date: %v, Hex: %v\n", date, hex)
		date = date.Add(hour)
	}
}

```

The token id is unique per day.
```
Date: 2020-12-18 07:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 08:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 09:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 10:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 11:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 12:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 13:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 14:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 15:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 16:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 17:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 18:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 19:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 20:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 21:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 22:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-18 23:38:42.77261422 +0000 UTC, Hex: c9669d
Date: 2020-12-19 00:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 01:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 02:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 03:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 04:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 05:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 06:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 07:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 08:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 09:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 10:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 11:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 12:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 13:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 14:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 15:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 16:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 17:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 18:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 19:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 20:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 21:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 22:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-19 23:38:42.77261422 +0000 UTC, Hex: 6df9f9
Date: 2020-12-20 00:38:42.77261422 +0000 UTC, Hex: 800c49
Date: 2020-12-20 01:38:42.77261422 +0000 UTC, Hex: 800c49
Date: 2020-12-20 02:38:42.77261422 +0000 UTC, Hex: 800c49
Date: 2020-12-20 03:38:42.77261422 +0000 UTC, Hex: 800c49
Date: 2020-12-20 04:38:42.77261422 +0000 UTC, Hex: 800c49
Date: 2020-12-20 05:38:42.77261422 +0000 UTC, Hex: 800c49
Date: 2020-12-20 06:38:42.77261422 +0000 UTC, Hex: 800c49
```

**Comment by danielfoehrKn** [comment]
> I just double checked with

Thanks, I had a flaw in the testing code.

> we want to have a whole new token once per day, that's why it is implemented this way.

What is the reason why you want that?

**Comment by rfranzke** [comment]
@danielfoehrKn The ideal solution is to have one bootstrap token exclusively per machine which is being invalidated/deleted from the system again once the machine has registered as node. As we don't have this yet we at least rotate the token once per day to not have one and the same token during the whole cluster's lifecycle.
Obviously, that's still no good solution, but it's better than never rotating it.

Now your question is about why we can't keep the token ID stable for a cluster and only rotate the token secret. The answer is: Yes, sure, we could do that, but then the "rotation" implementation is harder because we have to remember when we last rotated the token secret (how? annotation? other means?) and rotate it again if 24h have passed.

So, given that we strive for a dedicated token per machine anyways, let's go ahead with @vpnachev's minimal fix for now and rather invest into the ideal solution 😄

**Comment by vpnachev** [comment]
> > we want to have a whole new token once per day, that's why it is implemented this way.
> 
> What is the reason why you want that?

As a shoot can be reconciled only once a day on some Gardener installations, it is required the token to be valid for 24+ hours so that nodes created by cluster autoscaller can use it to join the cluster.

**Comment by danielfoehrKn** [comment]
> As a shoot can be reconciled only once a day on some Gardener installations, it is required the token to be valid for 24+ hours so that nodes created by cluster autoscaller can use it to join the cluster.

Ok, thanks that makes sense.

**Review by danielfoehrKn — APPROVED** [review]

**Pull request merged**
