### PR TITLE
Fix premature controllerinstallation deletion

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area control-plane
/kind bug
/priority normal

**What this PR does / why we need it**:
This PR fixes a bug which caused the GCM to delete on-demand `ControllerInstallations` prematurely. https://github.com/gardener/gardener/pull/2261 already fixed this issue but the code was accidentally removed by some changes later.

**Special notes for your reviewer**:
Co-authored-by: Rafael Franzke <rafael.franzke@sap.com>

**Release note**:

```improvement operator
An issue has been fixed which caused Gardener to delete on-demand extensions prematurely. 
```

### CODE REVIEW

**Review by rfranzke — DISMISSED** [review]
/lgtm thanks!

**Review by timebertt — DISMISSED** [review]
/lgtm

**Comment by timuthy** [comment]
Hold on! I just noticed that the provider extension is not deleted because of the infrastructure kind even though all shoots were deleted in my local setup.

```
  - lastTransitionTime: "2020-06-26T08:37:58Z"
    lastUpdateTime: "2020-06-26T09:27:58Z"
    message: 'extension objects still exist in the seed: [Infrastructure/gcp]'
    reason: ExtensionObjectsExist
    status: "True"
    type: Required
```

I'm currently checking this.

**Comment by timuthy** [comment]
As I said, I found another issue but I prefer to open an GitHub issue and address it in another PR. It's not really critical except that the extension which reconciles the last removed extension from the seed (today infrastructure) will stay.

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
