### PR TITLE
Fix y axis title of 'System services Memory usage'

### PR DESCRIPTION
**Pull request by gadisn**
Cores -> Memory

**How to categorize this PR?**

/area TODO
/kind TODO
/priority normal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @gadisn for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by wyb1 — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
