### PR TITLE
Prepare for the removal of the `ownerChecks` field

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
**How to categorize this PR?**

/area control-plane-migration
/kind cleanup

**What this PR does / why we need it**:
The `ownerChecks` field is been removed because of the removal of "Bad-case" control plane migration.
For more details, see: https://github.com/gardener/gardener/issues/6302.
The `ownerChecks` field is locked to `false` in https://github.com/gardener/gardener/pull/7909.

Similar to https://github.com/gardener/gardener/pull/7534

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6302

**Special notes for your reviewer**:
N/A

**Release note**:

```breaking operator
The Seed's `.spec.settings.ownerChecks` field is now no-op - the `gardener-apiserver` no longer defaults this field and no longer validates it. The field will be set always to `nil` on CREATE/UPDATE request.
Gardener landscape operators specifying this field should no longer specify it. The field will be removed in a future version of Gardener.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/hold
until 1.73 is released, we target this PR for 1.74.

**Comment by timuthy** [comment]
/unhold
v1.73 is released

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by dimitar-kostadinov** [comment]
**pull-gardener-e2e-kind-migration** fails with:
```

  [FAILED] Expected success, but got an error:
      <*retry.Error | 0xc000a60980>: 
      retry failed with context deadline exceeded, last error: shoot "e2e-migrate" was not successfully reconciled
      {
          ctxError: <context.deadlineExceededError>{},
          err: <*errors.errorString | 0xc000176530>{
              s: "shoot \"e2e-migrate\" was not successfully reconciled",
          },
```

**pull-gardener-e2e-kind-operator**  fails with:
```
  [FAILED] Timed out after 31.052s.
  The function passed to Eventually failed at /home/prow/go/src/github.com/gardener/gardener/test/e2e/operator/garden/create_delete.go:108 with:
  Unexpected error:
      <*fmt.wrapError | 0xc00089e5c0>: 
      error discovering kubernetes version: Get "https://api.virtual-garden.local.gardener.cloud/version": read tcp 127.0.0.1:59518->127.0.0.1:443: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:59512->127.0.0.1:443: read: connection reset by peer
```

/retest-required

**Pull request merged**
