### PR TITLE
Update VPA to vertical-pod-autoscaler-0.9.0

### LINKED ISSUE #2961: Update VPA to vertical-pod-autoscaler-0.9.0
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/priority normal

**What would you like to be added**:
Update VPA to [vertical-pod-autoscaler-0.9.0](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.9.0)

**Why is this needed**:
1. Allow custom timeout value for webhook calls [kubernetes/autoscaler#3549](https://github.com/kubernetes/autoscaler/pull/3549) can help us revert https://github.com/gardener/gardener/pull/2802 while still solving https://github.com/gardener/gardener/issues/2779 by a simple change to the webhook timeout config in the charts.
1. VPA - Always process OOM samples [kubernetes/autoscaler#3079](https://github.com/kubernetes/autoscaler/pull/3079) can address https://github.com/gardener/gardener/issues/2890 by reacting better to oomkills.
1. CLI flags for VPA recommender aggregations config [kubernetes/autoscaler#2905](https://github.com/kubernetes/autoscaler/pull/2905) can help us configure VPA to scale down recommendations faster than `24h` (perhaps as quickly as after `2h`). That was the rationale behind this PR in the first place. But aggressive scale downs will only exacerbate the spike-handling problem we have been increasingly facing with the VPA recommender. Perhaps we should go a bit slow on this one.

cc @wyb1 @ggaurav10 @rfranzke @vlerenc @ialidzhikov @kallurbsk @istvanballok

### PR DESCRIPTION
**Pull request by kallurbsk**
**How to categorize this PR?**

/area auto-scaling
/area control-plane
/kind enhancement

**What this PR does / why we need it**:
The PR updates the release of VPA to vpa-pod-autoscaler-0.9.0.
This is an attempt at a version upgrade from 0.8.0 to tackle the issues mentioned in 

1. Allow custom timeout value for webhook calls kubernetes/autoscaler#3549 can help us revert #2802 while still solving #2779 by a simple change to the webhook timeout config in the charts.
2. VPA - Always process OOM samples kubernetes/autoscaler#3079 can address #2890 by reacting better to oomkills.
3. CLI flags for VPA recommender aggregations config kubernetes/autoscaler#2905 can help us configure VPA to scale down recommendations faster than 24h (perhaps as quickly as after 2h). That was the rationale behind this PR in the first place. But aggressive scale downs will only exacerbate the spike-handling problem we have been increasingly facing with the VPA recommender. Perhaps we should go a bit slow on this one.

**Which issue(s) this PR fixes**:
Fixes #2961

**Special notes for your reviewer**:

**Release note**:

```
Update the VPA pod autoscaler version from 0.8.0 to 0.9.0
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Please update the PR title, description, labels, and, if necessary, the release note.

**Comment by rfranzke** [comment]
Also, please squash the commits and sign the CLA.

**Comment by kallurbsk** [comment]
Hi Rafael,

Tried updating the CLA but the link is dying on me. Updated other details.
I am trying to squash the commits now.

**Pull request closed without merging**
