### PR TITLE
Make ingress domain for Seeds immutable

### LINKED ISSUE #3281: Changing Seed IngressDomain will make Shoot monitoring unavailable until next Shoot Reconcile
/area networking
/kind bug

/priority normal

**What happened**:
After changing the `seed.spec.dns.ingressDomain` the monitoring Ingresses in the Shoot namespaces of the Seed will keep the old ingressDomain until the Shoots get [reconciled](https://github.com/gardener/gardener/blob/6a4526b135da570f567c2fb5bd597bd07e02b915/pkg/gardenlet/controller/shoot/shoot_control_reconcile.go#L386).
If the Shoots are reconciled at a later point in time (for example in a later maintenance window) then Shoot monitoring will be unavailable until then.

**What you expected to happen**:
Changing the ingressDomain in the Seed should not disable Shoot monitoring until the next Shoot reconcile.

**Anything else we need to know?**:
Seeing two options currently:

A) Add migration logic to adapt Ingresses when the Seed is reconciled
B) Making ingressDomain immutable

### PR DESCRIPTION
**Pull request by BeckerMax**
**How to categorize this PR?**

  /area control-plane
  /area robustness
/kind bug
/priority normal

**What this PR does / why we need it**:
Make ingress domain for Seeds immutable

Changing the ingress domain on running Seed clusters can cause
a temporary unavailability of the Shoots monitoring.

We decided to not support the use case of changing the
ingress Domain for Seeds. This is in line with the
Shoot resource where the ingress domain is also immutable.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/3281

**Release note**:
```noteworthy operator
The ingress domain configuration for Seeds is now immutable.
```

### CODE REVIEW

**Comment by BeckerMax** [comment]
Is there some expected documentation about which fields are immutable?

**Comment by danielfoehrKn** [comment]
> Is there some expected documentation about which fields are immutable?

Would be nice to have, but I do not think it exists yet.

**Review by danielfoehrKn — DISMISSED** [review]
/lgtm

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Comment by timuthy** [comment]
> Is there some expected documentation about which fields are immutable?

We could add it to the doc string of the API field, so that it'll be mentioned in the API ref (https://gardener.cloud/documentation/references).

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
