### PR TITLE
Allow to configure image GC thresholds for kubelet configuration in `Shoot` API

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area storage scalability
/kind enhancement

**What this PR does / why we need it**:
Allow to configure image GC thresholds for kubelet configuration in `Shoot` API.
/squash

**Which issue(s) this PR fixes**:
Part of #4281

**Release note**:

```feature user
It's now possible to configure the `imageGC{High,Low}ThresholdPercent` fields for the kubelet configuration (defaults: `50` for the high threshold, `40` for the low threshold) in the `Shoot` API via `.spec.{provider.workers[].}kubernetes.kubelet.imageGC{High,Low}ThresholdPercent`.
```

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
Nice! Thanks for the dedicated commits :)
/lgtm

Do you want to add a link to upstream docs to the release note? https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

**Comment by timebertt** [comment]
@rfranzke  Shall we get this in for `v1.26`?

**Comment by rfranzke** [comment]
@timebertt it can also wait for v1.27, no issues

**Comment by timebertt** [comment]
`BackupBucket` envtest is failing. Can you rebase onto https://github.com/gardener/gardener/pull/4265?

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
