### PR TITLE
Set  kindest/node image and Shoot K8s version to 1.27 for e2e tests

### PR DESCRIPTION
**Pull request by ary1992**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
After the merge of #7883 ,  Gardener now supports seed and shoot clusters with v1.27.

**Which issue(s) this PR fixes**:
Part of #7783 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ary1992** [comment]
Tests are failing as `EnableStaticTokenKubeconfig` is set to true for e2e tests. Working on it to fix it.

**Comment by shafeeqes** [comment]
> @ary1992: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-e2e-kind-ha-multi-zone-upgrade	[f4ba30d](https://github.com/gardener/gardener/commit/f4ba30d64950a20428e602f4318a0ef213399d15)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7970/pull-gardener-e2e-kind-ha-multi-zone-upgrade/1661189739211919360)	false	`/test pull-gardener-e2e-kind-ha-multi-zone-upgrade`
> pull-gardener-e2e-kind-upgrade	[f4ba30d](https://github.com/gardener/gardener/commit/f4ba30d64950a20428e602f4318a0ef213399d15)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7970/pull-gardener-e2e-kind-upgrade/1661189739618766848)	false	`/test pull-gardener-e2e-kind-upgrade`
> pull-gardener-e2e-kind-ha-single-zone-upgrade	[f4ba30d](https://github.com/gardener/gardener/commit/f4ba30d64950a20428e602f4318a0ef213399d15)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/7970/pull-gardener-e2e-kind-ha-single-zone-upgrade/1661189739329359872)	false	`/test pull-gardener-e2e-kind-ha-single-zone-upgrade`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=7970). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aary1992). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Cherry-pick this commit https://github.com/gardener/gardener/pull/7948/commits/7fb1bdeacf0b69753616107d0d27c10de8c6b8f5

**Review by shafeeqes — APPROVED** [review]
/lgtm

**Pull request merged**
