### PR TITLE
Update Istio to v1.21.1

### PR DESCRIPTION
**Pull request by axel7born**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update Istio to v1.21.1
```

### CODE REVIEW

**Review by DockToFuture — CHANGES_REQUESTED** [review]
Thank you for the PR! It looks overall good. :) 
There is a change in the istiod deployment, the `ISTIOD_ADDR` env var was removed.
```
          - name: ISTIOD_ADDR
            value: istiod.istio-system.svc:15012
```
Can you also remove it?

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Comment by oliver-goetz** [comment]
/approve

thanks 😄

**Pull request merged**
