### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.17.0->v0.18.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes**:
``` other developer github.com/gardener/etcd-druid #579 @shreyas-s-rao
Upgrade to go 1.20.3.
```

``` feature developer github.com/gardener/etcd-druid #547 @abdasgupta
Run `make ci-e2e-kind` to run the e2e tests on local machine
```

``` improvement developer github.com/gardener/etcd-druid #581 @shreyas-s-rao
Block public access for S3 buckets created by e2e tests.
```

``` bugfix operator github.com/gardener/etcd-druid #587 @ishan16696
Added check to ensure that the scale up annotation is removed from the etcd statefulset only when scale-up succeeds
```

``` improvement operator github.com/gardener/etcd-backup-restore #612 @aaronfern
Base alpine image upgraded from `3.15.7` to `3.15.8`
```

``` improvement developer github.com/gardener/etcd-backup-restore #613 @shreyas-s-rao
Upgrade to go 1.20.3
```

``` bugfix operator github.com/gardener/etcd-backup-restore #614 @ishan16696
Fixes a bug in backup-restore which falsely detects scale-up scenario incase of rolling update of statefulset.
```

``` improvement developer github.com/gardener/etcd-backup-restore #615 @shreyas-s-rao
Block public access for S3 buckets created by integration tests.
```

``` improvement operator github.com/gardener/etcd-backup-restore #617 @ishan16696
Add a learner with backoff in case of scale-up feature is triggered.
```

``` improvement operator github.com/gardener/etcd-backup-restore #605 @ishan16696
Added a safety check before adding a learner(non-voting) member in etcd cluster.
```

``` feature developer github.com/gardener/etcd-druid #538 @seshachalam-yv
Eliminated `Role` helm charts and converted into Golang component with added unit tests.
```

``` feature developer github.com/gardener/etcd-druid #539 @seshachalam-yv
Eliminated `RoleBinding` helm charts and converted into Golang component with added unit tests.
```

``` other operator github.com/gardener/etcd-druid #575 @aaronfern
etcd-custom-image updates from `v3.4.13-bootstrap-9` to `v3.4.13-bootstrap-10`
```

``` other operator github.com/gardener/etcd-custom-image #32 @aaronfern
Base alpine image for etcd-custom-image upgraded from `3.15.7` to `3.15.8`
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
/kind enhancement
Please check why the HA tests are failing, @aaronfern @ishan16696

**Comment by abdasgupta** [comment]
@shafeeqes looking into it

**Comment by ishan16696** [comment]
From the logs: [https://gcsweb.gardener.cloud/gcs/gardener-prow/pr-logs/pull/gardener_gardener/7893/pul[…]ate-node_etcd-main-0_ecf8f866-18a8-4e98-b3da-800c39d64eda/](https://gcsweb.gardener.cloud/gcs/gardener-prow/pr-logs/pull/gardener_gardener/7893/pull-gardener-e2e-kind-ha-single-zone/1655892913764175872/artifacts/gardener-local-ha-single-zone/gardener-local-ha-single-zone-worker2/pods/shoot--local--e2e-update-node_etcd-main-0_ecf8f866-18a8-4e98-b3da-800c39d64eda/)

I found there is only 1 etcd and backup-restore logs, which means only 1 replica of etcd was deployed.
logs:
```
2023-05-09T11:39:38.415457821Z stderr F time="2023-05-09T11:39:38Z" level=error msg="Failed to connect to etcd KV client: context deadline exceeded" actor=member-add
2023-05-09T11:39:38.415461251Z stderr F time="2023-05-09T11:39:38Z" level=error msg="unable to check presence of member in cluster: context deadline exceeded" actor=member-add
2023-05-09T11:39:38.420178191Z stderr F time="2023-05-09T11:39:38Z" level=info msg="Etcd cluster scale-up is detected" actor=initializer
2023-05-09T11:39:38.842951901Z stderr F time="2023-05-09T11:39:38Z" level=info msg="Responding to status request with: Progress" actor=backup-restore-server
```
Weird thing I found from the logs of backup-restore is it was detecting the scale-up case which implies etcd statefulset had the scale-up annotation which was added by druid.
I think what's happening is this test deploys etcd with `replica=1`  but don't wait for etcd to become ready and then it marked the shoot to become HA after that druid adds scale-up annotation  to etcd statefulset which leads to this error.
But that's my hypothesis it could be wrong as locally all g/g tests are passing as @abdasgupta told me.

Druid adds scale-up annotation using this condition:
```go
func clusterScaledUpToMultiNode(val *Values, sts *appsv1.StatefulSet) bool {
	if sts != nil && sts.Spec.Replicas != nil {
		return (val.Replicas > 1 && *sts.Spec.Replicas == 1) ||
			(metav1.HasAnnotation(sts.ObjectMeta, scaleToMultiNodeAnnotationKey) && sts.Status.UpdatedReplicas < *sts.Spec.Replicas)
	}
	return val.Replicas > 1 && val.StatusReplicas == 1
}
```

I'm unable to find etcd sts yaml but I found etcd.yaml: [https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/7893/pull-ga[…]d-ha-single-zone/1655892913764175872/artifacts/etcds.yaml](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/7893/pull-gardener-e2e-kind-ha-single-zone/1655892913764175872/artifacts/etcds.yaml)
`.spec.replicas`  is set to `3`  with `generation: 2` , so etcd CR was updated.
but etcd status is this
```
  status:
    clusterSize: 1
    conditions:
    - lastTransitionTime: "2023-05-09T11:25:45Z"
      lastUpdateTime: "2023-05-09T11:39:30Z"
      message: At least one member is not ready
      reason: NotAllMembersReady
      status: "False"
      type: AllMembersReady
    - lastTransitionTime: "2023-05-09T11:38:55Z"
      lastUpdateTime: "2023-05-09T11:39:30Z"
      message: Stale snapshot leases. Not renewed in a long time
      reason: BackupFailed
      status: "False"
      type: BackupReady
    - lastTransitionTime: "2023-05-09T11:25:45Z"
      lastUpdateTime: "2023-05-09T11:39:30Z"
      message: The majority of ETCD members is not ready
      reason: QuorumLost
      status: "False"
      type: Ready
    currentReplicas: 1
    etcd:
      apiVersion: apps/v1
      kind: StatefulSet
      name: etcd-main
    members:
    - id: bf97e80bb01e78be
      lastTransitionTime: "2023-05-09T11:25:45Z"
      name: etcd-main-0
      reason: UnknownGracePeriodExceeded
      role: Leader
      status: NotReady
    observedGeneration: 1
    ready: false
    replicas: 1
    serviceName: etcd-main-client
    updatedReplicas: 1
```
so, druid doing it work correctly but I think this is the bug in tests itself or timing issue as we introduce backoff in backup-restore
@seshachalam-yv can you also take a look, check whether my hypothesis is correct or not.

**Comment by rfranzke** [comment]
> so, druid doing it work correctly but I think this is the bug in tests itself or timing issue as we introduce backoff in backup-restore

If so, why didn't we observe these failures earlier?

**Comment by ishan16696** [comment]
> If so, why didn't we observe these failures earlier?

https://github.com/gardener/gardener/issues/7924
https://github.com/gardener/etcd-druid/issues/597

**Comment by ishan16696** [comment]
We will release etcd-druid `v0.18.1` with the fix for the issue: https://github.com/gardener/etcd-druid/issues/597
Hence, closing this PR.
/close

**Pull request closed without merging**
