### PR TITLE
[ci:component:github.com/gardener/apiserver-proxy:v0.6.0->v0.7.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
``` improvement operator github.com/gardener/apiserver-proxy #21 @ScheererJ
Updated base image of apiserver-proxy to alpine 3.16.2
```

### CODE REVIEW

**Review by ScheererJ — APPROVED** [review]
/lgtm
/approve

**Review by ialidzhikov — COMMENTED** [review]
I am not able to find in the logs an error that is directly related to the apiserver-proxy image. I also tested locally and the new image looks fine. For now I guess it was a prow instability that led to the failures.

/retest

**Comment by shafeeqes** [comment]
> @gardener-robot-ci-3: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-integration	[3e45b7f](https://github.com/gardener/gardener/commit/3e45b7fb61ebd85e559a1307fffdd4e7ca0d2e31)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6698/pull-gardener-integration/1572150280986824704)	unknown	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=6698). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agardener-robot-ci-3). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Opened https://github.com/gardener/gardener/issues/6709
/retest

**Comment by shafeeqes** [comment]
> @gardener-robot-ci-3: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-integration	[3e45b7f](https://github.com/gardener/gardener/commit/3e45b7fb61ebd85e559a1307fffdd4e7ca0d2e31)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6698/pull-gardener-integration/1572151823794442240)	true	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=6698). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agardener-robot-ci-3). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Looks like another flake. Opened https://github.com/gardener/gardener/issues/6710
/retest

**Pull request merged**
