### PR TITLE
Shoot migrate flow: Move `ensureResourceManagerScaledUp` in front of `deployGardenerResourceManager`

### LINKED ISSUE #7606: Control-plane migration stuck for shoots hibernated for at least 24 hours
**How to categorize this issue?**
/area control-plane-migration
/kind bug

**What happened**:
When triggering a control-plane migration for shoots that were hibernated for more than 24h, the migration gets stuck at the "Waiting until ManagedResources are deleted" step.

This happens because the token in the `shoot-access-gardener-resource-manager` secret expires after 24h and therefore the `gardener-resource-manager` is unable to communicate with the shoot apiserver.

**What you expected to happen**:
A successful control-plane migration 🙂
**How to reproduce it (as minimally and precisely as possible)**:
1. Hibernate shoot
2. Wait 24h **or** update the `shoot-access-gardener-resource-manager` secret token (to something invalid) and remove the `serviceaccount.resources.gardener.cloud/token-expiration-duration` label
3. Trigger a control-plane migration
4. See the `Migrate` operation being stuck at "Waiting until ManagedResources are deleted"

**Anything else we need to know?**:
In the migration flow the `gardener-resource-manager` deployment is only scaled up: https://github.com/gardener/gardener/blob/2f34cb1422985253aa47eb761bb759d6ae4823e3/pkg/gardenlet/controller/shoot/shoot/reconciler_migrate.go#L175-L179

However, it is necessary to re-run the bootstrap logic for the `gardener-resource-manager` due to the `shoot-access-gardener-resource-manager` secret being expired.

In every reconcile (which includes waking up a hibernated shoot) it is checked if the bootstrap logic must be triggered in the `DeployGardenerResourceManager` func:
https://github.com/gardener/gardener/blob/3f666d244bd497074b40c5e1182fa2f8ddc1e5e2/pkg/operation/botanist/resource_manager.go#L124-L152

I would therefore propose to additionally call `DeployGardenerResourceManager` before the  `ensureResourceManagerScaledUp` task of the migrate flow.
This PR contains the proposed change #7608  

**Environment**:

- Gardener version: 1.62.1
- Kubernetes version: 1.23.16

### PR DESCRIPTION
**Pull request by Kumm-Kai**
**How to categorize this PR?**
/area control-plane-migration
/kind bug

**What this PR does / why we need it**:
After a little more testing I've discovered that the fix in (#7608) works better if the `gardener-resource-manager` is scaled up before calling `deployGardenerResourceManager`.
While testing #7608 I haven't really payed attention and didn't see that the flow fails once and succeeds afterwards. 

**Which issue(s) this PR fixes**:
- Fixes #7606
- Also fixes another bug where after a control-plane migration of a hibernated shoot all `shoot-access-` secrets contain no data

**Release note**:
```other operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Can you explain why/what "works better"?

**Comment by Kumm-Kai** [comment]
> Can you explain why/what "works better"?

If the `gardener-resource-manager` has 0 replicas the `mustBootstrapGardenerResourceManager` func in `botanist.DeployGardenerResourceManager` will return `false` -> `gardener-resource-manager` won't be bootstraped.
After that the `gardener-resource-manager` will be scaled to 1. The shoot `reconciler_migrate` flow will fail at `deleteManagedResources` like in #7606.
At the next run the `deployGardenerResourceManager` task will bootstrap the `gardener-resource-manager` as it is still scaled to 1.

When the `gardener-resource-manager` is scaled up before the `deployGardenerResourceManager` task the flow will succeed directly.

**Comment by rfranzke** [comment]
OK, thanks, sounds reasonable!

/lgtm
/ok-to-test
/approve

**Comment by rfranzke** [comment]
@Kumm-Kai something seems wrong with the e2e-migration test - it continuously fails. Please check

**Comment by rfranzke** [comment]
@Kumm-Kai Do you still plan to look into this issue?

**Comment by Kumm-Kai** [comment]
> @Kumm-Kai Do you still plan to look into this issue?

Yes I do, but I currently don't have much time.

I started looking into it and it seems like the `deployGardenerResourceManager` is scaling down the `grm` again.
I think it would be best to write another function that bootstraps the `grm` if needed and to use it instead.

**Pull request closed without merging**
