### PR TITLE
Update docforge to v0.33.0

### PR DESCRIPTION
**Pull request by oliver-goetz**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR updates `docforge` to `v0.33.0` which includes an  `arm64` build too ([ref](https://github.com/gardener/docforge/releases/tag/v0.33.0))

**Which issue(s) this PR fixes**:
Part of #6258

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
/cc @Kostov6 @Kristian-ZH 
for lgtm

**Review by Kostov6 — APPROVED** [review]
/lgtm

**Pull request merged**
