### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.15.0->v0.15.2]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
``` other operator github.com/gardener/etcd-druid #489 @shreyas-s-rao
Fix `make manifests` target.
```

``` other operator github.com/gardener/etcd-druid #491 @ialidzhikov
The Etcd resource now allows specify etcd client Service labels via the `spec.etcd.clientService.labels` field.
```

### CODE REVIEW

**Comment by ishan16696** [comment]
@timuthy you can add yours `ClusterRole` commit in this PR. thanks

**Comment by timuthy** [comment]
/assign @ishan16696
for having a second look.
/approve

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Pull request merged**
