### PR TITLE
Enable scale down also for kube-apiserver via HVPA

### PR DESCRIPTION
**Pull request by ggaurav10**
**What this PR does / why we need it**:
Enable vertical scale down also for kube-apiserver via HVPA

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Enabled vertical scale down also for kube-apiserver via HVPA
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]

**Comment by rfranzke** [comment]
Can you elaborate a bit about the tests you have run to be confident that this does not cause any problems before we merge this? :)

**Comment by ggaurav10** [comment]
We have mainly done some stress testing, which results in vertical scaling (up) of API server without any downtime. During the no/less load situation, we expect similar or better scaling (down) behaviour. The stabilisation window for scale down is set to 15 minutes, whereas it is set to 3 minutes for scale up.
Further, the `minCpuChange` and `minMemChange` can also be configured separately for scale up and scale down, which is not currently the case. We can consider changing these values to 1 core and 1GB respectively for scale down. Refer: [here](https://github.com/gardener/gardener/blob/master/charts/seed-controlplane/charts/kube-apiserver/values.yaml#L130-L135)
WDYT @amshuman-kr

**Comment by rfranzke** [comment]
Great, thank you!

**Comment by rfranzke** [comment]
Test failed because setup is not yet adapted to gardenlet. Merging.

**Pull request merged**
