### PR TITLE
Upgrade K8s dependencies to v0.24.3

### LINKED ISSUE #6441: `--field-selector` for Shoots does not work as expected
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
While using `--field-selector` we noticed the following discrepancy. On large landscapes `--field-selector spec.cloudProfileName=foo` did not return anything while there were actually results that had to be returned:

```
$ k get shoots -n garden-foo --field-selector=spec.cloudProfileName=foo
# returns 1 entry as expected

$ k get shoots -A --field-selector=spec.cloudProfileName=foo
No resources found
# wrong, should return 1 entry
```

There are also much bigger discrepancies:
```
$ k get shoots -A --field-selector=spec.cloudProfileName=baz --no-headers | wc -l
243
# while the number of Shoots using the baz CloudProfile is 465
```

Using the `--chunk-size=0` flag seem to fix this issue.

This issue looks related to https://github.com/kubernetes/kubernetes/issues/110625. The corresponding PR is backported to 1.24 and present in v0.24.3+ of K8s dependencies (https://github.com/kubernetes/kubernetes/pull/110735).

Credits to @vpnachev for reporting!

**What you expected to happen**:
`--field-selector` to work reliably for Shoots (or any other resources of gardener-apiserver)

**How to reproduce it (as minimally and precisely as possible)**:
See above.

```
# 1. Create 5 Shoots with CloudProfile `azure`
# 2. Create 5 Shoots with CloudProfile `gcp`

# 3. Make sure using  spec.cloudProfileName=azure (or gcp) and--chunk-size=2 only 4 Shoot are returned, not 5
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.51.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
This PR upgrades the K8s dependencies to v0.24.3 to adopt a fix for https://github.com/kubernetes/kubernetes/issues/110625. Currently for the gardener-apiserver requesting resources with the `--selector` / `--field-selector` flags does not always return the expected result. For more details see #6441.

**Which issue(s) this PR fixes**:
Fixes #6441

**Release note**:

```bugfix user
K8s dependencies are upgraded to v0.24.3 to adopt a fix in the `k8s.io/apiserver` module that causes gardener-apiserver to do not always return the expected result when the client requests resources with the `--selector` / `--field-selector` flags.
```

### CODE REVIEW

**Comment by timebertt** [comment]
kicking prow in the butt after it was down:
/area quality
/kind bug
/ok-to-test

**Review by acumino — APPROVED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
