### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.11.1->v0.11.2]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-2**
**Release Notes**:
``` improvement operator github.com/gardener/etcd-backup-restore #510 @timuthy
An issue has been fixed that caused the `Backup-Restore` component to connect to the wrong etcd cluster for initializing and member-add procedures.
```

### CODE REVIEW

**Review by acumino — APPROVED** [review]

**Comment by timuthy** [comment]
/hold
I just had a look at the logs and something seems to be wrong with the CA rotation for the multi-node etcd case. Let me investigate further.

**Comment by acumino** [comment]
@timuthy can this PR make it to v1.52 or should I remove the milestone?

**Comment by timuthy** [comment]
Unfortunately, we found another issue which needs to be fixed and release asap. This new release needs to be part of `v1.52` because otherwise we needed to revert https://github.com/gardener/gardener/pull/6384 as it'll break multi-node clusters.

**Comment by timuthy** [comment]
/close
This version is buggy. A [fix](https://github.com/gardener/etcd-druid/pull/388) will be rolled out with a new Druid Hotfix.

**Pull request closed without merging**
