### PR TITLE
Set default resource lock to leases for extensions

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
CC - @ialidzhikov 

**Release note**:

```breaking dependency
The default leader election of extensions has been changed from `configmapsleases` to `leases`. Please make sure, that you had at least `gardener@v1.17.0` in your go.mod before upgrading to this version so that it has successfully acquired leadership with the hybrid resource lock (`configmapsleases`) at least once.
```

### CODE REVIEW

**Comment by timebertt** [comment]
The release note should be `breaking dependency` and it's not related to any running gardener version, right? This is only affecting the extensions...

**Comment by acumino** [comment]
> The release note should be `breaking dependency` and it's not related to any running gardener version, right? This is only affecting the extensions...

Yes, The idea is anything that imports g/g should have v1.17 at least to upgrade it to the latest.

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
@ialidzhikov Any concerns?

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
