### PR TITLE
Release responsible schedule for v1.64 until v1.78

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
Extends the docs with a proposal for the release responsible schedule for v1.64 until v1.78.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by timuthy — COMMENTED** [review]
I can help with the release as well 🙂

**Comment by rfranzke** [comment]
Oops, sorry @timuthy, forgot to include you 😄 Will push some update.

**Comment by rfranzke** [comment]
OK, incorporated @timuthy now :)
@ary1992 @shafeeqes please check again

**Review by acumino — COMMENTED** [review]
/lgtm

**Review by timuthy — COMMENTED** [review]
/lgtm

**Comment by plkokanov** [comment]
I will be in vacation from 20.03.2023 to 24.03.2023 and there's a high chance that I will be in vacation also from 26.06.2023 to 07.07.2023 so @rfranzke are you ok if we swap for `v1.66` and `v1.67`? And perhaps we could swap with @oliver-goetz for `v1.74` and `v1.76 `?

**Comment by rfranzke** [comment]
@plkokanov Works for me. I incorporated the change proposal, hope that's also fine for @oliver-goetz

**Comment by rfranzke** [comment]
Thanks everybody!
/approve

**Pull request merged**
