### PR TITLE
Include Prometheus tests in verify-extended rule

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:
The Prometheus tests weren't executed as part of the `verify-extended` rule which caused #2439. Let's better include them to detect issues before they get merged.

**Which issue(s) this PR fixes**:
Ref #2439 

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by timebertt — DISMISSED** [review]
/lgtm

**Comment by rfranzke** [comment]
/hold
until #2439 is fixed

**Comment by rfranzke** [comment]
/unhold
as #2439 is fixed

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
