### PR TITLE
[ci:component:github.com/gardener/etcd-druid:v0.19.3->v0.20.0]

### PR DESCRIPTION
**Pull request by ghost**
**Release Notes**:
```noteworthy operator github.com/gardener/etcd-druid #688 @shreyas-s-rao
`custodian-sync-period` value is set to `15s` in the Helm chart for etcd-druid.
```
```noteworthy operator github.com/gardener/etcd-backup-restore #637 @aaronfern
Etcd-backup-restore now uses a distroless image as its base image. It is no longer compatible with [etcd-custom-image](https://github.com/gardener/etcd-custom-image), and must be used with [etcd-wrapper](https://github.com/gardener/etcd-wrapper) instead. 
```
```improvement operator github.com/gardener/etcd-druid #687 @gardener-robot-ci-3
Upgraded `etcd-backup-restore` from `v0.24.3` to `v0.24.6` for `etcd-custom-image`, and from `v0.25.1` to `v0.26.0` for `etcd-wrapper`
```
```noteworthy operator github.com/gardener/etcd-druid #672 @abdasgupta
Etcd snapshot compaction jobs will now be named `<etcd-name>-compactor` for better readability for human operators.
```
```improvement operator github.com/gardener/etcd-backup-restore #638 @shreyas-s-rao
Bump alpine base version for Docker build to `3.18.2`.
```
```improvement operator github.com/gardener/etcd-backup-restore #628 @aaronfern
Backup-restore waits for its etcd to be ready before attempting to update peerUrl
```
```noteworthy operator github.com/gardener/etcd-backup-restore #637 @aaronfern
Etcd-backup-restore now uses the user home directory to create files.
```
```bugfix operator github.com/gardener/etcd-druid #688 @shreyas-s-rao
Custodian controller no longer watches leases owned by the etcd resources, thus reducing frequency of etcd status updates and now honouring `custodian-sync-period` value.
```
```bugfix operator github.com/gardener/etcd-druid #662 @aaronfern
A bug causing incorrect volume mount path for `Etcd`s and `EtcdCopyBackupsTask`s using `Local` snapshot storage provider while using distroless etcd-backup-restore image `v0.25.x` has been resolved.
```
```improvement operator github.com/gardener/etcd-backup-restore #640 @seshachalam-yv
Introduced `delta-snapshot-retention-period` CLI flag to extend the configurable retention period for delta snapshots in `etcd-backup-restore`, enhancing flexibility for backup retention.
```
```bugfix operator github.com/gardener/etcd-druid #662 @aaronfern
A bug causing `EtcdCopyBackupsTask` jobs to fail to create temp snapshot directory while using distroless etcd-backup-restore image `v0.25.x` has been resolved.
```
```improvement operator github.com/gardener/etcd-backup-restore #649 @ishan16696
While scaling up a non-HA etcd cluster to HA skipping the scale-up checks for first member of etcd cluster as first member can never be a part of scale-up scenarios.
```
```doc developer github.com/gardener/etcd-druid #659 @shreyas-s-rao
Introduce DEPs (Druid Enhancement Proposals) for proposing large design changes in etcd-druid.
```
```noteworthy operator github.com/gardener/etcd-custom-image #40 @shreyas-s-rao
Update alpine base image version to 3.18.3.
```
```other operator github.com/gardener/etcd-druid #673 @aaronfern
All default images are now present in `images.yaml`
```
```doc operator github.com/gardener/etcd-druid #658 @shreyas-s-rao
Introduce DEP-04 [EtcdMember Custom Resource](https://github.com/gardener/etcd-druid/blob/master/docs/proposals/04-etcd-member-custom-resource.md).
```
```feature operator github.com/gardener/etcd-druid #651 @seshachalam-yv
Introduce `Spec.Backup.DeltaSnapshotRetentionPeriod` in the `Etcd` resource to allow configuring retention period for delta snapshots.
```
```improvement operator github.com/gardener/etcd-backup-restore #659 @ishan16696
Revendors the bbolt from `v1.3.6` to `v1.3.7`
```
```noteworthy user github.com/gardener/etcd-backup-restore #667 @abdasgupta
Introduce flag `metrics-scrape-wait-duration` to `etcdbrctl compact` command, that specifies a wait duration at the end of a snapshot compaction, to allow Prometheus to scrape metrics related to compaction before the `etcdbrctl` process exits.
```
```improvement developer github.com/gardener/etcd-backup-restore #644 @shreyas-s-rao
Add CVE categorization for etcd-backup-restore.
```
```breaking user github.com/gardener/etcd-druid #656 @shreyas-s-rao
Update etcd-custom-image to `v3.4.26-2`.
```
```feature developer github.com/gardener/etcd-druid #668 @shreyas-s-rao
Add support for `Local` provider for e2e tests.
```
```other operator github.com/gardener/etcd-backup-restore #647 @seshachalam-yv
Upgraded Ginkgo v1 to v2 and updated other dependencies
```
```noteworthy operator github.com/gardener/etcd-druid #686 @abdasgupta
Add new flag `metrics-scrape-wait-duration` for compaction controller to set a wait duration at the end of every compaction job, to allow for metrics to be scraped by a Prometheus instance.
```
```breaking operator github.com/gardener/etcd-druid #681 @aaronfern
Etcd druid will now not support `policy/v1beta1` for `PodDisruptionBudget`s and will only use `policy/v1` for `PodDisruptionBudget`s
```

### CODE REVIEW

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm

**Pull request closed without merging**
