### PR TITLE
Update to Golang 1.18, replace certificates with SHA-1 signature

### LINKED ISSUE #5756: Remove the usages of `SHA1-RSA` certificates
**How to categorize this issue?**

/area usability
/kind enhancement

**Why is this needed**:

Go is deprecating the `SHA1-RSA` in v1.18 https://github.com/golang/go/issues/41682 and will be removed with v1.19. This is causing the provider-local setup to fail. Trying to run provider-local with go v1.18 fails with the following error:
```
W0331 12:34:52.979059    8820 dispatcher.go:153] Failed calling webhook, failing closed seed-restriction-gardener.gardener.cloud: failed calling webhook "seed-restriction-gardener.gardener.cloud": failed to call webhook: Post "https://127.0.0.1:2721/webhooks/admission/seedrestriction?timeout=10s": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "example.net")
```

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR updates to Golang 1.18 and also bumps the `alpine` images.
It also replaces the GAC certificate with SHA-1 signature due to https://github.com/golang/go/issues/41682.

**Which issue(s) this PR fixes**:
Fixes #5756

**Special notes for your reviewer**:
/cc @ialidzhikov @acumino 

**Release note**:

```other developer
The golang version is now updated to `1.18.1`.
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
Unit Tests for Go 1.18 do not run with Go 1.17 and vice versa.
I created PR https://github.com/gardener/ci-infra/pull/231 to update test prow jobs of gardener/gardener to 1.18.

These are our tasks
- merge https://github.com/gardener/ci-infra/pull/231  when this PR is ready
- make unit tests work here and merge this PR
- all open PRs might need a rebase to make unit tests work again

**Comment by rfranzke** [comment]
Thanks!

**Comment by shafeeqes** [comment]
The release note says 1.17.2, Why?

**Comment by rfranzke** [comment]
> The release note says 1.17.2, Why?

copy/paste 😉 fixed now

**Comment by acumino** [comment]
Have you checked the scope of generics feature of go 1.18 in Gardener? It seems promising to me. It can be pursued in separate PR but I feel it's better to at least list here the new feature of 1.18 which can be used.

**Comment by rfranzke** [comment]
> Have you checked the scope of generics feature of go 1.18 in Gardener? It seems promising to me. It can be pursued in separate PR but I feel it's better to at least list here the new feature of 1.18 which can be used.

I don't understand, what do you suggest? There probably is some potential to use generics, but I haven't checked and don't think it's reasonable to actively do it now. Instead, we can rather do it on-demand when we anyways touch code that could use new features.

**Comment by shafeeqes** [comment]
Thanks!

/lgtm
/approve

**Comment by rfranzke** [comment]
Thanks for approving! `/unhold`ing https://github.com/gardener/ci-infra/pull/231 now to make Prow happy

**Comment by oliver-goetz** [comment]
That was too early, the prow config was not updated yet 😅

**Comment by oliver-goetz** [comment]
prow runs the go 1.18 test image now

**Comment by oliver-goetz** [comment]
okay, it should work now. PR is queued for merging
However Tide is very accurate when it comes to testing against the latest stage of the master branch 😄

**Comment by rfranzke** [comment]
Awesome, thanks everybody for your help!

**Pull request merged**
