### PR TITLE
Update to Golang 1.20 also updates several other dependencies

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR updates Golang to v1.20. Along with it, it also updates several dependencies.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7449

**Special notes for your reviewer**:
General dependency is also upgraded as part of this PR.

**Release note**:

```other operator
The golang version is now updated to `1.20.1`.
```
```other operator
The following dependency is updated:
- go.uber.org/automaxprocs: v1.4.0 -> v1.5.1
- golang.org/x/crypto: v0.1.0 -> v0.6.0
- golang.org/x/tools: v0.4.0 -> v0.6.0
- gonum.org/v1/gonum: v0.11.0 -> v0.12.0
- github.com/onsi/ginkgo/v2: v2.6.1 -> v2.8.3
- github.com/onsi/gomega: v1.24.2 -> v1.27.1
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
`eu.gcr.io/gardener-project/3rd/golang:1.20.1` does not exist yet.
Otherwise, lgtm.

**Comment by rfranzke** [comment]
Btw, why are we still using `eu.gcr.io/gardener-project/3rd/golang` in our test definitions? We have switched to upstream repo for the `Dockerfile` https://github.com/gardener/gardener/blob/676ec251d1381932940be9b31f8e9e781aa62534/Dockerfile#L2

Can't we switch to this also for the remaining occurrences? cc @ialidzhikov

**Review by rfranzke — COMMENTED** [review]
lgtm apart from question above

**Comment by acumino** [comment]
> Btw, why are we still using `eu.gcr.io/gardener-project/3rd/golang` in our test definitions? We have switched to upstream repo for the `Dockerfile`
> 
> https://github.com/gardener/gardener/blob/676ec251d1381932940be9b31f8e9e781aa62534/Dockerfile#L2
> 
> Can't we switch to this also for the remaining occurrences? cc @ialidzhikov

If we use upstream golang image, can it not cause docker rate limit issue?

**Comment by ialidzhikov** [comment]
> Btw, why are we still using `eu.gcr.io/gardener-project/3rd/golang` in our test definitions? We have switched to upstream repo for the `Dockerfile`
> 
> https://github.com/gardener/gardener/blob/676ec251d1381932940be9b31f8e9e781aa62534/Dockerfile#L2
> 
> Can't we switch to this also for the remaining occurrences? cc @ialidzhikov

As you noted down, these test definitions are used by the test machinery. I don't have much info for this topic. I only know how things evolved in the past - we had to switch to GCR copies to prevent dockerhub rate limits; we know that rate limit issues are fixed for concourse/cicd but I don't know about test-machinery. Maybe @dguendisch or @hendrikKahl can share if it is safe to switch to dockerhub image again for the golang image in the test definitions.

**Comment by dguendisch** [comment]
> if it is safe to switch to dockerhub image again for the golang image in the test definitions.

Meanwhile we're authenticated dockerhub access with bigger rate limits, though I cannot forecast whether this will be enough.
So I'd think you could give it a try but be prepared to switch back if the rate limits are hit.

**Comment by oliver-goetz** [comment]
👍 
/lgtm

**Review by rfranzke — COMMENTED** [review]
Thanks, then let's try it this way.
/approve

**Comment by dguendisch** [comment]
fwiw: see https://news.ycombinator.com/item?id=35166317 and https://blog.alexellis.io/docker-is-deleting-open-source-images/ respectively
while maybe(?) golang is safe as an "official" image, we should however going forward better stick to our own repositories (specifically dockerhub is an obvious unsafe bet these days)

**Comment by acumino** [comment]
> fwiw: see https://news.ycombinator.com/item?id=35166317 and https://blog.alexellis.io/docker-is-deleting-open-source-images/ respectively while maybe(?) golang is safe as an "official" image, we should however going forward better stick to our own repositories (specifically dockerhub is an obvious unsafe bet these days)

I read about this but maybe these big orgs repo will apply for the docker opensource program to prevent it from getting removed.

**Pull request merged**
