### PR TITLE
Upgrade the version of fluent-bit image to 1.9.7

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**How to categorize this PR?**

/area logging
/kind enhancement

**What this PR does / why we need it**:
Upgrade the version of fluent-bit image to 1.9.7

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@vlvasilev 

**Release note**:

```other operator
The following image is updated:
- fluent/fluent-bit: 1.9.6 -> 1.9.7
```

### CODE REVIEW

**Review by vlvasilev — APPROVED** [review]
/lgtm

**Review by timebertt — COMMENTED** [review]
/approve

**Review by ialidzhikov — APPROVED** [review]
/approve

**Pull request merged**
