### PR TITLE
feat: configure calico admission in extension setup

### PR DESCRIPTION
**Pull request by domdom82**
**How to categorize this PR?**

/area networking
/kind cleanup

**What this PR does / why we need it**:

So far, only providers and cilium admission controllers were deployed in the (local) extensions setup. This PR adds calico admission as well.

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by domdom82** [comment]
@timuthy ping for approval

**Review by timuthy — COMMENTED** [review]
/approve

**Pull request merged**
