### PR TITLE
Add Luca to `OWNER_ALIASES`

### PR DESCRIPTION
**Pull request by timuthy**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR adds @LucaBernstein as reviewer and approver to `gardener/gardener`.
Welcome Luca 🥳 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by oliver-goetz** [comment]
Welcome @LucaBernstein 😄 

/lgtm
/approve

**Comment by timuthy** [comment]
https://github.com/gardener/gardener/pull/9942#issuecomment-2154624060

Can you help @oliver-goetz ? 😄

**Pull request merged**
