### PR TITLE
Evolve Infrastructure component into DeployMigrateWaiter

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity quality robustness
/kind technical-debt test
/priority normal
/topology seed
/platform all
/exp intermediate

**What this PR does / why we need it**:
After #2548, this PR now evolves the component for `Infrastructure` to a `DeployMigrateWaiter`. It also introduces unit tests and adapts the Golang conventions for the `ControlPlane` component along the road.

/invite @plkokanov @swilen-iwanow @kris94 

**Which issue(s) this PR fixes**:
Part of #2754

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by danielfoehrKn — DISMISSED** [review]
nice. lgtm

**Comment by rfranzke** [comment]
Rebased to resolve conflicts

**Review by BeckerMax — DISMISSED** [review]

**Comment by rfranzke** [comment]
Rebased to resolve conflicts

**Review by BeckerMax — APPROVED** [review]

**Pull request merged**
