### PR TITLE
Remove validating the removal of the use-as-seed annotation

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Removes validating the removal of the `use-as-seed` annotation from the shoot validator, in order to be able to remove the `use-as-seed` annotation as part of the migration to `ManagedSeeds`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
It is now possible to remove the `use-as-seed` annotation even if the seed is in use by shoots. This is part of deprecating the `use-as-seed` annotation in favor of using ManagedSeeds directly.
```

### CODE REVIEW

**Review by timebertt — COMMENTED** [review]
Am I right to assume, that if you now remove the `use-as-seed` annotation without removing the `ownerReference` on the `ManagedSeed` first, the `ManagedSeed` will also be deleted?

In that case, should we rather enhance the validation to allow removing the annotation if there is a corresponding `ManagedSeed` without an `ownerReference` instead of completely removing the validation?

**Comment by stoyanr** [comment]
> In that case, should we rather enhance the validation to allow removing the annotation if there is a corresponding `ManagedSeed` without an `ownerReference` instead of completely removing the validation?

I would say no, since we want to deprecate the `use-as-seed` annotation, not just keep it as a "proxy" for managed seeds as today. If we should ever have such a check, it should be on a `ManagedSeed`, not `use-as-seed`.

Right now there is no such check, so it's possible to delete such a managed seed. The deletion will fail though since it will try to delete the seed, which in turn will fail until all shoots are removed. I could perhaps add an admission plugin that forbids the deletion of a used ManagedSeed it you think it makes sense (in a different PR).

**Comment by timebertt** [comment]
Good point, @stoyanr. You're right.

> I could perhaps add an admission plugin that forbids the deletion of a used ManagedSeed it you think it makes sense (in a different PR).

I actually thought, we had this in place already. Can you add it then?

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by BeckerMax** [comment]
closing this one in favor of https://github.com/gardener/gardener/pull/3975

**Pull request closed without merging**
