### PR TITLE
Drop deprecated `.spec.{type,providerConfig}` fields in `ControllerRegistration`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
The `.spec.{type,providerConfig}` fields in `ControllerRegistration`
- were deprecated with https://github.com/gardener/gardener/pull/3995 (since `v1.23`),
- were announced to be finally removed with https://github.com/gardener/gardener/pull/4532 (since `v1.30`),
- are now finally dropped with `v1.34` or `v1.35`.

**Release note**:

```breaking operator
The deprecated `.spec.{type,providerConfig}` fields in the `ControllerRegistration` resource have now been dropped. Make sure to migrate to `ControllerDeployment`s before updating to this Gardener version.
```

### CODE REVIEW

**Review by timebertt — CHANGES_REQUESTED** [review]
Are we sure, we really want to drop these fields in the `v1beta1` API?
If the fields are not used anymore, what's the benefit (besides removing code)?

I'm once again torn on how strictly we actually want to follow the Kubernetes API conventions.
To me it seems like, it would be a good time now to discuss this question and come up with some guideline before we remove fields in `v1beta1`.
(Maybe it's now also time for `core.gardener.cloud/v1` 😉)

**Comment by rfranzke** [comment]
> If the fields are not used anymore, what's the benefit (besides removing code)?

See https://github.com/gardener/gardener/pull/3995, it motivates why we introduced `ControllerDeployment`s and deprecated those fields in the context of the seed authorizer topics.

> To me it seems like, it would be a good time now to discuss this question and come up with some guideline before we remove fields in v1beta1.

I don't see any issues with removing them. They are exposed for operators only, the deprecation and announcement period was long enough.

**Comment by timuthy** [comment]
I'm also not seeing this as a sure thing to remove a field from a beta API.
What makes me not objecting are the points that @rfranzke stated + operators can "easily" switch to the changed API, i.e. `kubectl apply` still works with adjusted resource (even though `"spec":{"deployment":{"providerConfig":null,"type":null}}` is in the patch request) and deleting a very old and forgotten `ControllerRegistration` works as well.

**Review by timuthy — APPROVED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
