### PR TITLE
Add responsible team for nginx-controller & default backend

### PR DESCRIPTION
**Pull request by StenlyTU**
**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:

Add [gardener-landscape-stability](https://github.com/orgs/gardener/teams/gardener-landscape-stability/members) team as responsible of nginx-ingress-controller & ingress-default-backend.

/invite @dguendisch WDYT?

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by dguendisch — APPROVED** [review]

**Comment by timuthy** [comment]
/hold
due to offline discussion

**Pull request closed without merging**
