### PR TITLE
Few code enhancements

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
Fix few linter findings.
- `perfsprint` linter in golanci for `fmt.Sprintf` alternatives
- `wsl` linter in golangci for whitespaces
- `testpackage` linter in golangci to use separate test package
- `redundant-import-alias` linter in revive for removing redundant import aliases

I have not enabled any of these linters since we don't want to force such fine-grained rules.
Also the findings in this PR are not exhaustive, some current implementations are better readable/usable.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by acumino — COMMENTED** [review]
/lgtm
/approve
/retest

**Comment by rfranzke** [comment]
Thanks for the PR! :)

> I have not enabled any of these linters since we don't want to force such fine-grained rules.

Hm, wouldn't it make sense to at least enable `perfsprint` and `redundant-import-alias`? The other two are perhaps a bit picky/have too many exceptions, indeed.

**Comment by shafeeqes** [comment]
`redundant-import-alias`- Sure.
`perfsprint`, Not sure, I felt in some places, the `Sprintf` is better readable than string concatenation.
And for types like int32, we have to do `strconv.FormatUint(uint64(value), 10))` etc.

**Comment by rfranzke** [comment]
OK, fair enough 👍🏻

**Pull request merged**
