### PR TITLE
Updated istio to v1.12.5

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Updated istio to v1.12.5

As part of the process the envoy filters and the cluster roles were cleaned up
to better match the upstream variants.

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Release note**:

```other operator
Updates istio components to v1.12.5
```

### CODE REVIEW

**Comment by DockToFuture** [comment]
The PR looks good but we should also check for:

- https://github.com/gardener/gardener/tree/master/charts/istio/istio-ingress
- https://github.com/gardener/gardener/tree/master/charts/istio/istio-istiod

I see there some slightly differences.

**Comment by dguendisch** [comment]
Let's hold it until https://github.com/gardener/machine-controller-manager/issues/679 is solved

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/unhold
/approve

**Comment by timebertt** [comment]
Merging manually as PR can't be merged by tide (diff between base branch and this PR in github actions)

**Pull request merged**
