### PR TITLE
Increase istio-ingressgateway memory limits

### PR DESCRIPTION
**Pull request by dguendisch**
**How to categorize this PR?**

/area networking
/area scalability

**What this PR does / why we need it**:
Similar to https://github.com/gardener/gardener/pull/3732, increase the max memory settings for the istio-ingressgateway.
On some seeds we still see istio getting killed by OOMKill (all 3 below restarted containers had OOMKill as reason):
```
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-65cd6bd489-4cvv6   1/1     Running   1          37d
istio-ingressgateway-65cd6bd489-8p2gn   1/1     Running   0          24d
istio-ingressgateway-65cd6bd489-n9f6r   1/1     Running   1          37d
istio-ingressgateway-65cd6bd489-np894   1/1     Running   0          22d
istio-ingressgateway-65cd6bd489-z4rmh   1/1     Running   1          36d
```

See also:
image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
istio-ingressgateway memory limit is increased to 2560Mi
```

/invite @mvladev

### CODE REVIEW

**Comment by mvladev** [comment]
I would say to increase it to 3 or 4k

**Comment by dguendisch** [comment]
Also raising the request then to e.g. `512Mi` ? (otherwise we have a huge diff between requests and limits...)

**Comment by mvladev** [comment]
> (otherwise we have a huge diff between requests and limits...)

This is not a problem.

**Comment by dguendisch** [comment]
> This is not a problem.

??
The higher the diff, the higher the risk that a node will not have enough headroom to serve the limits...

**Comment by dguendisch** [comment]
In an out-of-band discussion with @istvanballok we concluded to go with `3072Mi` as new limit and `256Mi` as new requests (basically because the requests of the lowest utilized pods where around `256Mi`).

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
