### PR TITLE
Upgrade github.com/gardener/autoscaler

### PR DESCRIPTION
**Pull request by himanshu-kun**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**Release note**:

```other operator
The following images are updated:
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler`: `v1.20.1` -> `v1.20.2` (for Kubernetes `< 1.21`)
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler`: `v1.21.1` -> `v1.21.2` (for Kubernetes `1.21`)
- `eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler`: `v1.21.1` -> `v1.22.2` (for Kubernetes `>= 1.22`)
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@himanshu-kun can you share why there are no release notes for the new patch releases?

**Comment by himanshu-kun** [comment]
We just updated the golang version in pipeline to deal with some vulnerabilites , that is why we didn't add the release notes @ialidzhikov 
Shall I add them manually ?

**Comment by ialidzhikov** [comment]
> We just updated the golang version in pipeline to deal with some vulnerabilites , that is why we didn't add the release notes

I see release notes added in https://github.com/gardener/autoscaler/pull/137. Can you check why they were not picked by the CI/CD?

> Shall I add them manually ?

I would appreciate if you can pay attention to this in the future. You can update the releases for the cluster-autoscaler and add the release note there. For this PR, I will add a release note that the CA version gets updated. Whoever is interested can check the CA release pages.

**Review by ialidzhikov — COMMENTED** [review]
/lgtm

**Review by ialidzhikov — COMMENTED** [review]
/approve

**Pull request merged**
