### PR TITLE
🛡 Enable `ServiceAccount` token projection and token requestor for `provider-local`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
* When the `provider-local` extension is running on a seed with a gardenlet of at least `v1.37` then
  * `ServiceAccount` token projection is enabled.
  * the `machine-controller-manager` deployed into shoot namespaces
    * uses `ServiceAccount` token projection.
    * uses a token managed by GRM's token requestor instead of a client certificate.

**Which issue(s) this PR fixes**:
Part of gardener/gardener#4659
Part of gardener/gardener#4878

**Special notes for your reviewer**:
✅ ~Depends on https://github.com/gardener/gardener/pull/5162, hence, PR is in draft state.~
✅ ~Depends on #5163, hence PR is in draft state.~

**Release note**:

```noteworthy developer
NONE
```

### CODE REVIEW

**Review by timuthy — APPROVED** [review]
/lgtm
Also tested it, works like a charm 🙂

**Review by timebertt — APPROVED** [review]
Nice, I like it!
/lgtm

**Pull request merged**
