### PR TITLE
Exclude node from worker healthcheck which are not managed by MCM

### LINKED ISSUE #5672: Worker healthcheck to exclude nodes annotated with `node.machine.sapcloud.io/not-managed-by-mcm="1"`
**How to categorize this issue?**

/area ops-productivity 
/kind enhancement

**What would you like to be added**:
The nodes annotated with `node.machine.sapcloud.io/not-managed-by-mcm="1"` to be excluded from the health checks ran by the worker controller.
Ref: https://github.com/gardener/machine-controller-manager/pull/612

**Why is this needed**:
There is a possibility a node not managed by MCM, respectively Gardener, to be joined in a shoot cluster. In such cases, these nodes could be reported that their cloud-config is outdated or that there is other issues with them that are out of scope of Gardener.

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
There is a possibility a node not managed by MCM, respectively Gardener, to be joined in a shoot cluster. This PR excludes nodes annotated with `node.machine.sapcloud.io/not-managed-by-mcm="1"` from the health checks ran by the worker controller.

**Which issue(s) this PR fixes**:
Fixes #5672

**Special notes for your reviewer**:

**Release note**:

```feature operator
The nodes annotated with `node.machine.sapcloud.io/not-managed-by-mcm="1"` are no longer considered in health checks ran by the worker controller.
```

### CODE REVIEW

**Review by himanshu-kun — CHANGES_REQUESTED** [review]
Please add some test case as well. lgtm otherwise

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
