### PR TITLE
Update architecture diagram

### PR DESCRIPTION
**Pull request by vlerenc**
**What this PR does / why we need it**:
- Drop/deprecate Kubernetes dashboard for its security risks
- Insert vertical network segregation line between seed and shoot
- Insert hint about SNI routing that we exclusively do
- Fix poor choice of uppercase letters
- Realign various misaligned lines/boxes/notes

**Which issue(s) this PR fixes**:
Requested by @ThormaehlenFred.

**Special notes for your reviewer**:
/area documentation
/kind cleanup

**Release note**:
```doc user
Architecture diagram was updated discouraging the use of the Kubernetes dashboard (among other hints and cosmetic updates).
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
> @vlerenc: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-gardener-integration	[630de16](https://github.com/gardener/gardener/commit/630de16c861db824564f69a60ae01ccaeeaf8a1f)	[link](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6701/pull-gardener-integration/1572095419582779392)	true	`/test pull-gardener-integration`
> [Full PR test history](https://prow.gardener.cloud/pr-history?org=gardener&repo=gardener&pr=6701). [Your PR dashboard](https://prow.gardener.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Avlerenc). [Command help for this repository](https://prow.gardener.cloud/command-help?repo=gardener%2Fgardener). Please help us cut down on flakes by linking this test failure to an [open flake report](https://github.com/gardener/gardener/issues?q=is:issue+is:open+label:kind/flake) or filing a [new flake report](https://github.com/gardener/gardener/issues/new?template=flaking-test.md&title=%5BFlaky+Test%5D+FLAKING+TEST%2FSUITE) if you can't find an existing one. Also see our [testing guideline](https://github.com/gardener/gardener/blob/master/docs/development/testing.md) for how to avoid and hunt flakes.

Due to https://github.com/gardener/gardener/issues/6671
/retest

**Review by rfranzke — COMMENTED** [review]
/lgtm
/approve

**Comment by vlerenc** [comment]
Thx!

**Pull request merged**
