### PR TITLE
[Test] Update images.yaml for druid

### PR DESCRIPTION
**Pull request by abdasgupta**
**How to categorize this PR?**

/area TODO
/kind TODO

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by rfranzke** [comment]
Why don't you perform these e2e tests in the `etcd-druid` repo directly like other "extensions"?

**Comment by abdasgupta** [comment]
> Why don't you perform these e2e tests in the `etcd-druid` repo directly like other "extensions"?

Okay. Will keep it in mind and it won't happen from the next time. Thank you.

**Pull request closed without merging**
