### PR TITLE
Drop `.spec.settings.ownerChecks` field from Seed API

### PR DESCRIPTION
**Pull request by dimitar-kostadinov**
**How to categorize this PR?**

/area control-plane-migration
/kind api-change
/kind cleanup

**What this PR does / why we need it**:
This PR removes `.spec.settings.ownerChecks` after it has been deprecated in https://github.com/gardener/gardener/pull/7748. For existing Seeds the field was set to nil with https://github.com/gardener/gardener/pull/7951.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6302

**Special notes for your reviewer**:
N/A

**Release note**:

```breaking operator
⚠️ The deprecated field `.spec.settings.ownerChecks` has been removed from the Seed API. Please check your `Seed`s and remove any usage before upgrading to this Gardener version.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
v1.75 has been released, can the draft state be removed now?

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Review by ScheererJ — COMMENTED** [review]
Thanks for the change.

/lgtm

**Pull request merged**
