### PR TITLE
Set execution order for example yaml 

### PR DESCRIPTION
**Pull request by swapnilgm**
Signed-off-by: Swapnil Mhamane <swapnil.mhamane@sap.com>

### CODE REVIEW

**Comment by rfranzke** [comment]
Can we name `60-namespace-garden-dev.yaml` like `00-namespace-garden.yaml`, so `00-namespace-garden-dev.yaml`?

**Comment by swapnilgm** [comment]
Looking from `dev-setup` scripts perspective it looks weird to have 00 from garden namespace and 60 for garden-dev. But thinking, we would only go for project creation once garden cluster is setup with everything till seed creation. 
@rfranzke  What is your opinion about this explanation? Still do you wan't me change it?

**Comment by rfranzke** [comment]
Hmm ok, valid, I understand what you mean, but I'd still prefer to have the two namespaces grouped together. OK?

**Comment by swapnilgm** [comment]
Done

**Review by rfranzke — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
