### PR TITLE
Configure prometheus to scrape CCM and KCM using https

### LINKED ISSUE #476: Prometheus should use HTTPS port for scraping metrics of KCM/CCM for K8S >= 1.12
As of Kubernetes 1.12 the cloud-controller-manager and kube-controller-manager advertise the metrics via a HTTPS server. The old HTTP server is still running as well, however, it will be deprecated and removed in a future Kubernetes version.

Consequently, we should change the Prometheus configuration to use HTTPS for scraping the metrics of KCM/CCM for Kubernetes >= 1.12. See also @mvladev 's comment on the Kubernetes 1.12 integration PR: https://github.com/gardener/gardener/pull/474#issuecomment-432181938

### PR DESCRIPTION
**Pull request by wyb1**
**What this PR does / why we need it**:
Enables Prometheus to scrape CCM and KCM via https. 
**Which issue(s) this PR fixes**:
Fixes #476 

**Special notes for your reviewer**:
CCM and KCM need to be version 1.13+
**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
@wyb1 is this PR ok to be merged? Or why did you ask @zanetworker to add the do-not-merge label?

**Comment by wyb1** [comment]
Should we not wait until 1.13.0+ is supported by gardener? But I suppose it's fine to merge. It won't do anything until the cluster is 1.13.0+

**Comment by rfranzke** [comment]
OK, thank you. IMO it's fine to get it in. We don't break HTTP scraping for clusters <1.13 with that, right?

**Comment by wyb1** [comment]
Clusters with <1.13 will work as usual.

**Comment by rfranzke** [comment]
Nice, thanks!

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
