### PR TITLE
Fix flake of `NamespacedCloudProfile` + `Shoot` creation in e2e tests

### PR DESCRIPTION
**Pull request by LucaBernstein**
**How to categorize this PR?**

/area robustness
/kind test

**What this PR does / why we need it**:
If the `NamespacedCloudProfile` still contains the custom dummy machine image upon `Shoot` creation, it can happen that the test framework picks it for the worker, as the order of the images in the profile is not guaranteed.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by LucaBernstein** [comment]
/hold
the issue occurred again in a ci job.

**Review by timuthy — COMMENTED** [review]
/lgtm

**Review by rfranzke — COMMENTED** [review]
/approve

**Pull request merged**
