### PR TITLE
[`provider-local`] Drop `MachineClass` Helm chart

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR drops `provider-local`'s `MachineClass` Helm chart and instead deploys the resources directly via Golang.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
FYI @kon-angelo @shaoyongfeng @afritzler @majst01 @Gerrit91 @JensAc: Perhaps you'd like to follow a similar approach in the other provider extensions as well.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by afritzler** [comment]
@rfranzke we are already applying the `MachineClass` + `Secret` without using helm: https://github.com/onmetal/gardener-extension-provider-onmetal/blob/main/pkg/controller/worker/machines.go#L54-L73

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Review by shafeeqes — COMMENTED** [review]
/lgtm

**Pull request merged**
