### PR TITLE
replace trivial sort.Func usages with slices.Sort

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**How to categorize this PR?**

/area open-source
/kind cleanup

**What this PR does / why we need it**:
This PR replaces some trivial usages of the `sort` package with `slices.Sort`. As per https://go.dev/blog/go1.21 the `slices` package is generally faster.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ary1992** [comment]
Thanks for the PR.
There are few more places as well where are using `sort.Slice` function https://github.com/gardener/gardener/blob/89debfd7475372a8f40de88804a6fe84c3085c25/pkg/operation/botanist/botanist.go#L55 .
Is this left out or is there any reason to not replace this one as well with `slices.SortFunc` ?

Same for `sort.Strings` function https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/utils/kubernetes/kubernetes.go#L300

**Comment by dimityrmirchev** [comment]
Thanks, @ary1992 ! I somehow missed these two, the next commit should correct this. I deliberately left out occurrences of `sort.Sort` like https://github.com/gardener/gardener/blob/master/pkg/chartrenderer/sorter.go#L120 since changing them is a little more hands on, although these can be refactored as well. My main goal is to promote the usage of the `slices` pkg in this repo.

**Pull request merged**
