### PR TITLE
Regenerate local development certificate for ETCD/GAPI

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
The old client certificate for `gardener-apiserver` to talk to ETCD has expired, see e.g. in https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/7067/pull-gardener-e2e-kind-ha-single-zone/1599666466070728704/artifacts/gardener-local-ha-single-zone-worker2/pods/garden_etcd-0_16e43430-e0f8-4bb9-8037-32016e7a8195/etcd/0.log:

```
2022-12-05T07:34:30.381852537Z stderr F {"level":"warn","ts":"2022-12-05T07:34:30.381Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"10.1.179.130:37212","server-name":"etcd-client.garden.svc","error":"tls: failed to verify client certificate: x509: certificate has expired or is not yet valid: current time 2022-12-05T07:34:30Z is after 2022-12-03T06:11:00Z"}
```

This PR regenerates the certificates with a longer validity (`10y`).

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by dimityrmirchev — APPROVED** [review]
/lgtm

**Review by acumino — APPROVED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
